### ISSUE TITLE
Support separate C++ and Python ITK versions in Remote module CI update script

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#1029]
As discussed in https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/66 by @jhlegarreta , we need to

- The [`UpdateRequiredITKVersionInRemoteModules.sh`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh) script will need to get updated to accommodate for the existence of a separate Python tag.
- The quotes added may require the regular expressions used in the [`UpdateRequiredITKVersionInRemoteModules.sh`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh) script to be revisited so that the variables have them stripped.

**Comment by jhlegarreta** [comment]
Related to this or a pre-condition is #1022.
