### ISSUE TITLE
Using ITK statically on windows in an application, it freezes at the end of the execution in the destructor of the treadPool

### ISSUE THREAD

**Issue by DeswingBE** [InsightSoftwareConsortium/ITK#1038]
### Description

We are using ITK statically in a module (dll) used in an application, this feature will use the threadpool

following the documentation, we are using the itk::ThreadPool::SetDoNotWaitForThreads function to deactivate the wait for the 
    m_Condition.notify_all();
in the destructor of the ThreadPool

But still, our application freezes at the join part :

  for (ThreadIdType i = 0; i < m_Threads.size(); i++)
    {
    m_Threads[i].join();
    }

looking in the stack trace for the trheads , they are all blocked in the threadpool::ThreadExecute function:

 std::unique_lock<std::mutex> mutexHolder( m_PimplGlobals->m_Mutex );
        threadPool->m_Condition.wait( mutexHolder,
          [threadPool]

looking at the thread List we can see 3 threadPool (one for the application and 2 for modules using ITK) thus we have 24 threads all blocked at the same point

It looks like the main thread is locking the mutex for its threadPool's threads

tried then by using ITK dll's instead of .lib , and everything is fine, but we would prefer to use ITK statically :)

any advice?

### Versions

5.0

### Environment

Windows 7 , Visual studio 2017 compiler

**Comment by dzenanz** [comment]
@DeswingBE it would be good if you tested patch from #1052 on a few of your scenarios.
