### ISSUE TITLE
ITK Source Forge project is a little out of date.

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#1043]
### Description
The information on this site is a bit out of date.  A few minutes putting in updated content to redirect to GitHub/discourse would be helpful:

https://sourceforge.net/projects/itk/support

### Expected information
Redirect to new pages.

### Actual information

Old information is there.

**Comment by thewtex** [comment]
There are some great reviews on SourceForge :-).

I could not find out how to update https://sourceforge.net/projects/itk/support but I did find an option to indicate the project has moved. Now there is a big blue button that links to GitHub:

![image](https://user-images.githubusercontent.com/25432/60304662-143f6d80-9908-11e9-83cd-cab5dcc58130.png)

**Comment by dzenanz** [comment]
@thewtex can you add [me](https://sourceforge.net/u/dzenanz/) to [ITK](https://sourceforge.net/p/itk/_members/) on SourceForge?

**Comment by thewtex** [comment]
@dzenanz added. There is nothing left on SourceForge for ITK, though. Long Live GitHub!
