### ISSUE TITLE
Inconsistent outputs on very small images

### ISSUE THREAD

**Issue by maekclena** [InsightSoftwareConsortium/ITK#1055]
### Description

I was looking at #1011 when I came up with the example below. The first execution of the filter returns the expected output but the following executions have some chance of returning an image with artifacts.

I tried different filters but they all behaved the same.

The artifacts quickly become less likely with bigger images. Above 50x50 they rarely appear. 

### Steps to Reproduce

```c++
#include <itkCastImageFilter.h>
#include <itkTestingComparisonImageFilter.h>

using ImageType = itk::Image<float, 2>;
using FilterType = itk::CastImageFilter<ImageType, ImageType>;
using ComparisonType = itk::Testing::ComparisonImageFilter<ImageType, ImageType>;

ImageType::Pointer run()
{
  ImageType::Pointer input = ImageType::New();
  input->SetRegions({10, 10});
  input->Allocate();

  FilterType::Pointer filter = FilterType::New();
  filter->SetInput(input);
  filter->Update();

  return filter->GetOutput();
}

int main()
{
  ImageType::Pointer reference = run();
  ComparisonType::Pointer comparison = ComparisonType::New();
  comparison->SetValidInput(reference);

  for (unsigned int i = 0; i < 5; i++)
  {
    ImageType::Pointer output = run();
    comparison->SetTestInput(output);
    comparison->Update();
    std::cout << comparison->GetNumberOfPixelsWithDifferences() << std::endl;
  }
}
```

### Expected behavior

All outputs should be identical.

### Actual behavior

Some outputs are different.

### Reproducibility

~95% of the time for 10x10 images.
~1% of the time for 50x50 images.

### Versions

master

### Environment

macOS Mojave

**Comment by dzenanz** [comment]
`input->Allocate();` allocates the image with undefined content. With small images, that allocation probably occurs in some region which the program used before. With larger images, a new block is probably requested from the operating system. And the OS zeroes is out to prevent processes from spying on one another.

Using `input->Allocate(true);` makes the test produce the identical result (all zeroes) each time. 

The reported behavior is not a bug.
