### ISSUE TITLE
Add `itk::VectorImage` coverage in itkExpandImageFilterTest

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#1066]
### Description

Explicitly test the use of `itk::VectorImage with `itk::ExpandImageFilter` in `itkExpandImageFilterTest`.

### Expected behavior

The testing coverage of this use case is explicitly tested.

### Actual behavior

It is only implicitly tested by its used in `itk::FEMRegistrationFilter`.

### Additional Information

This issue was identified in #1054

**Comment by blowekamp** [comment]
Usage with Image of Vectors help by #1076.
