### ISSUE TITLE
GetImageFromArray or Similar fuction in ITK C++  (Minor Issue)

### ISSUE THREAD

**Issue by ShibaPrasad** [InsightSoftwareConsortium/ITK#1083]
Hi All,

I am currently using ITK 5 and C++ . Do we have - GetImageFromArray() fuction in ITK C++ ? 
Issue is:
-  output of my computation is a 2d array. After that I need to display or save the image out of it.
Is there anyway i can do it?

**Comment by dzenanz** [comment]
Yes, [ImportImageFilter](https://itk.org/Doxygen/html/classitk_1_1ImportImageFilter.html) does what you want. You will have to specify dimensions and other metadata.

**Comment by ShibaPrasad** [comment]
Thank You

**Comment by ShibaPrasad** [comment]
Hi
I am trying to read the dogImage[] and write the Image to my local directory (In my program). I have provided the dogImage[] output and also code i am trying. Would you please give me some advise here?

**dogImage:**
--------------------
  RTTI typeinfo:   itk::Image<float, 3u>
  Reference Count: 3
  Modified Time: 1239
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (0x55be42550910) 
  Source output name: Primary
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1232
  UpdateMTime: 1240
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [256, 256, 202]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [256, 256, 202]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [256, 256, 202]
  Spacing: [0.664062, 0.664062, 0.5]
  Origin: [0, 0, 0]
  Direction: 
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix: 
0.664062 0 0
0 0.664062 0
0 0 0.5

  PointToIndexMatrix: 
1.50588 0 0
0 1.50588 0
0 0 2

  Inverse Direction: 
1 0 0
0 1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x55be42544440)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, float>
      Reference Count: 1
      Modified Time: 1238
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f3da57f4010
      Container manages memory: true
      Size: 13238272
      Capacity: 13238272
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Below Is the code I am trying:**
---------------------------------------
    char filename[256];
    sprintf(filename, "dog-%d-%d.png", i, j);
    std::cout << filename << std::endl;
    this->writeImage(dogImage[j], filename);                 // https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html#ae67de579bc4b36c11f322af08061f697

    typedef  short InputPixelType;
    typedef  short OutputPixelType;
    const unsigned int Dimension = 3; // or 2

    typedef itk::Image <InputPixelType,  Dimension>  InputImageType;
    typedef itk::Image <OutputPixelType, Dimension>  OutputImageType;

    typedef itk::ImportImageFilter <InputPixelType, Dimension>  ImportFilterType;  // A filter object created and // can try to make a ScaleInvariantFeatureImageFilter

    ImportFilterType::Pointer importFilter = ImportFilterType::New();

    ImportFilterType::SizeType  size;               
    size[0]  = 256;  				                // size along X
    size[1]  = 256;  				                // size along Y
    size[2]  = 256;  				                // size along z

    ImportFilterType::IndexType start;
    start.Fill( 0 );

    ImportFilterType::RegionType region;
    region.SetIndex( start );
    region.SetSize(  size  );
    importFilter->SetRegion( region );

    double origin[Dimension];
    origin[0] = 0.0;                                // X coordinate
    origin[1] = 0.0;                                // Y coordinate
    origin[2] = 0.0;                                // Z coordinate

    importFilter->SetOrigin( origin );              // origin of output image is specified with SetOrigin

    double spacing[Dimension];
    spacing[0] = 1;                                // along X direction
    spacing[1] = 1;                                // along Y direction
    spacing[2] = 1;                                // along z direction

    importFilter->SetSpacing( spacing );

    const unsigned int numberOfPixels =  size[0] * size[1] * size[2];
    std::cout << " Shiba-numberOfPixels" << " ... " << numberOfPixels << std::endl;
    const bool importImageFilterWillOwnTheBuffer = false;                      
    importFilter->SetImportPointer( (InputPixelType *)dogImage, numberOfPixels,importImageFilterWillOwnTheBuffer );

    typedef itk::ImageFileWriter< OutputImageType >  WriterType;
    WriterType::Pointer writer = WriterType::New();

    std::cout << " Shiba-before writer" << " ... " << std::endl;
    writer->SetInput(importFilter->GetOutput());
    writer->SetFileName( "./1DOG.nii" );
    std::cout << " Shiba-after writer" << " ... " << std::endl;
