### ISSUE TITLE
SubjectImplementation::RemoveObserver() is not documented correctly?

### ISSUE THREAD

**Issue by imikejackson** [InsightSoftwareConsortium/ITK#1085]
The description for the method itkObject::RemoveObserver() only states that the observer is _removed_. In looking at the code the Command object is actually deleted. 

The issue is that in some code bases developers might pass in a pointer that is already being managed by a shared_ptr or "smart pointer". This may lead to clean up issues including crashes.

The documentation should explicitly state that the method will in fact *delete* the object.

What would be nice would be to a "RemoveObserver" and a "DeleteObserver" or "TakeObserver" API that unambiguously allows the developer to select the proper API to use.

Adding an API to "TakeObserver" where the Command object is removed from being managed without deleting the object would allow both scenarios of pointer to be used.

**Comment by blowekamp** [comment]
Have you tested your understanding of the code? 

In SimpleITK I am using `Commands` as shared resources and it works OK. The terminology is a little confusing. The user provides a a `Command` in `AddObserver` to observe an event. Internally to the `itk::Object` an `Observer` is created which holds the event, command and a tag. When `RemoveObserver` is called the internal `Observer` is deleted, but user provided command is not.

**Comment by imikejackson** [comment]
void
SubjectImplementation::RemoveObserver(unsigned long tag)
{
  for ( auto i = m_Observers.begin();
        i != m_Observers.end(); ++i )
    {
    if ( ( *i )->m_Tag == tag )
      {
      delete ( *i );
      m_Observers.erase(i);
      m_ListModified = true;
      return;
      }
    }
}

Not sure how it is working for your shared resources (not all "shared pointers" are created equal) but the code above is pretty clear about what happens. Of course I could be misunderstanding the "delete (*i)" line of code as I don't get to code much lately...

**Comment by imikejackson** [comment]
So I just noticed that I am looking at the "SubjectImplementation" class which is in the same file as itkObject. So maybe I am a bit confused about all the interplay of those classes?

The stack trace we got indicated the crash was because of a double delete condition and seemingly pointed to this class.

**Comment by blowekamp** [comment]
I have looked at the code more, and I would need to more time to bring this all back into memory. Last time I update this code I made it near bullet proof with correctly handling exception in delete event, exception in call backs, and recursive events.

The user provided command is a smart pointer... Looking at the documentation for `itk::Object::AddObserver` it looks like it has never been update to reflect this.

**Comment by imikejackson** [comment]
https://github.com/InsightSoftwareConsortium/ITK/blob/9cb1aa6e09a6a108c86b8414321d38b9817c284f/Modules/Core/Common/src/itkObject.cxx#L511

Looking at the actual code it looks like it is a pointer?

**Comment by blowekamp** [comment]
Yup, but [`Command`](https://itk.org/Doxygen/html/classitk_1_1Command.html) is derived from `Object`, and the `SubjectImplementation stores it as a smart pointer:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/src/itkObject.cxx#L52

Inputs to filters are also passed as raw pointers.

**Comment by imikejackson** [comment]
I might be showing my ignorance in modern C++ at this point but let's say that I have a std::shared_ptr<MyCommand> command that I have created. If I then pass that to the AddObserver(command) method, the AddObserver will then de-reference the shared_ptr<> into the raw pointer, hand that down through the stack where eventually it gets put into a vtkSmartPointer<> which, I am going to assume, will take control of the raw pointer? That leaves my std::shared_ptr with a reference to a raw pointer that is going to get cleaned up out from underneath it? or the other way around, just depends on the order of operations.

**Comment by dzenanz** [comment]
Using `shared_ptr<>` might be the problematic part. I think that all ITK classes derived from `itk::Object` need to be managed using `itk::SmartPointer<ClassName>`, aka `ClassName::Pointer`. Trying to assign `ClassName::New()` to a plain pointer causes it to be immediately deallocated. Doesn't the same thing happen with an `std::shared_ptr<ClassName>`?

**Comment by imikejackson** [comment]
So the issue ends up being our implementation of an itk::Command subclass. I reworked our code to use all of the proper ITK macros that are used in ITK Command subclasses and now our code does not crash and does not through warnings from itkLightObject about reference counts. 

Sorry for the noise.
