### ISSUE TITLE
CI currently broken

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#1095]
A compile error sneaked into master, effectively stopping all PRs for passing continuous integration testing.

Example: #1093 fails [CircleCI](https://open.cdash.org/viewBuildError.php?buildid=6005845), due to [CastImageFilterTest](https://github.com/InsightSoftwareConsortium/ITK/blob/fa638adc365cbbb7a400d9f8993610d75250fcd7/Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx#L53).

**Comment by dzenanz** [comment]
@hjmjohnson this does not have much to do with CI infrastructure. It is a compile error which needs fixing. @blowekamp The errors seem to be coming from files you updated recently. Can you see what is the problem?

**Comment by hjmjohnson** [comment]
OK. I am not seeing these errors on my builds.  What options need to be turned on?

**Comment by dzenanz** [comment]
I don't know what is important, but as it happens with CircleCI, its [config file](https://github.com/InsightSoftwareConsortium/ITK/blob/master/.circleci/config.yml) should be a good starting point.

**Comment by blowekamp** [comment]
It looks like the compiler recently changed from GCC 6.3.0 to 8.30.

**Comment by hjmjohnson** [comment]
@blowekamp Were you going to look into this any more?

**Comment by thewtex** [comment]
Addressed by @blowekamp  in #1101 and #1099
