### ISSUE TITLE
Asked question On top of the - Issue number: 1083 (Minor)

### ISSUE THREAD

**Issue by ShibaPrasad** [InsightSoftwareConsortium/ITK#1097]
Hi
I am trying to read the dogImage[] and write the Image to my local directory (In my program). I have provided the dogImage[] output and also code i am trying. Would you please give me some advise here?

https://github.com/InsightSoftwareConsortium/ITK/issues/1083

**dogImage:**
-------------------------------------
RTTI typeinfo: itk::Image<float, 3u>
Reference Count: 3
Modified Time: 1239
Debug: Off
Object Name:
Observers:
none
Source: (0x55be42550910)
Source output name: Primary
Release Data: Off
Data Released: False
Global Release Data: Off
PipelineMTime: 1232
UpdateMTime: 1240
RealTimeStamp: 0 seconds
LargestPossibleRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [256, 256, 202]
BufferedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [256, 256, 202]
RequestedRegion:
Dimension: 3
Index: [0, 0, 0]
Size: [256, 256, 202]
Spacing: [0.664062, 0.664062, 0.5]
Origin: [0, 0, 0]
Direction:
1 0 0
0 1 0
0 0 1

IndexToPointMatrix:
0.664062 0 0
0 0.664062 0
0 0 0.5

PointToIndexMatrix:
1.50588 0 0
0 1.50588 0
0 0 2

Inverse Direction:
1 0 0
0 1 0
0 0 1

PixelContainer:
ImportImageContainer (0x55be42544440)
RTTI typeinfo: itk::ImportImageContainer<unsigned long, float>
Reference Count: 1
Modified Time: 1238
Debug: Off
Object Name:
Observers:
none
Pointer: 0x7f3da57f4010
Container manages memory: true
Size: 13238272
Capacity: 13238272
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
**Below Is the code I am trying:**
------------------------------------------------
char filename[256];
sprintf(filename, "dog-%d-%d.png", i, j);
std::cout << filename << std::endl;
this->writeImage(dogImage[j], filename);                 /html/namespaceitk_1_1simple.html#ae67de579bc4b36c11f322af08061f697

typedef  short InputPixelType;
typedef  short OutputPixelType;
const unsigned int Dimension = 3; // or 2

typedef itk::Image <InputPixelType,  Dimension>  InputImageType;
typedef itk::Image <OutputPixelType, Dimension>  OutputImageType;

typedef itk::ImportImageFilter <InputPixelType, Dimension>  ImportFilterType;  // A filter object created and // can try to make a ScaleInvariantFeatureImageFilter

ImportFilterType::Pointer importFilter = ImportFilterType::New();

ImportFilterType::SizeType  size;               
size[0]  = 256;  				                // size along X
size[1]  = 256;  				                // size along Y
size[2]  = 256;  				                // size along z

ImportFilterType::IndexType start;
start.Fill( 0 );

ImportFilterType::RegionType region;
region.SetIndex( start );
region.SetSize(  size  );
importFilter->SetRegion( region );

double origin[Dimension];
origin[0] = 0.0;                                // X coordinate
origin[1] = 0.0;                                // Y coordinate
origin[2] = 0.0;                                // Z coordinate

importFilter->SetOrigin( origin );              // origin of output image is specified with SetOrigin

double spacing[Dimension];
spacing[0] = 1;                                // along X direction
spacing[1] = 1;                                // along Y direction
spacing[2] = 1;                                // along z direction

importFilter->SetSpacing( spacing );

const unsigned int numberOfPixels =  size[0] * size[1] * size[2];
std::cout << " Shiba-numberOfPixels" << " ... " << numberOfPixels << std::endl;
const bool importImageFilterWillOwnTheBuffer = false;                      
importFilter->SetImportPointer( (InputPixelType *)dogImage, numberOfPixels,importImageFilterWillOwnTheBuffer );

typedef itk::ImageFileWriter< OutputImageType >  WriterType;
WriterType::Pointer writer = WriterType::New();

std::cout << " Shiba-before writer" << " ... " << std::endl;
writer->SetInput(importFilter->GetOutput());
writer->SetFileName( "./1DOG.nii" );
std::cout << " Shiba-after writer" << " ... " << std::endl;

**Comment by dzenanz** [comment]
The code looks OK. Without description of what the problem is, I can only suggest to turn
```C++
importFilter->SetImportPointer((InputPixelType *)dogImage, numberOfPixels, importImageFilterWillOwnTheBuffer);
```
into
```C++
importFilter->SetImportPointer((InputPixelType *)&dogImage[0], numberOfPixels, importImageFilterWillOwnTheBuffer);
```

**Comment by dzenanz** [comment]
Oh, you seem to have forgotten to call `writer->Update();`

**Comment by ShibaPrasad** [comment]
Thank You. It worked.But I am not getting the correct image .... Just an binary image. So I am missing something and looking into it. But I have to get those difference of Gaussian images (dog) to do further analysis

**Comment by dzenanz** [comment]
For a different problem, open a different issue. It is preferable to post questions on the [forum](https://discourse.itk.org/).
