### ISSUE TITLE
Dashboard configure errors with Python 2.7

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#1106]
#938 # Description
https://open.cdash.org/index.php?project=Insight&filtercount=1&showfilters=0&field1=revision&compare1=63&value1=a4bbdfd&showfeed=0

![image](https://user-images.githubusercontent.com/313970/61465700-355f1100-a93e-11e9-9386-86731737954a.png)

``` none
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
CMake Warning at Wrapping/Generators/Python/CMakeLists.txt:8 (message):
  Python versions less than 3.5 are not supported.  Python version: "2.7.16".

CMake Warning at Wrapping/Generators/Python/CMakeLists.txt:14 (message):
  Python executable ("2.7.16") and library ("2.7.10") version mismatch.
```

### Impact analysis

CDash reports are failing for python builds.

### Expected behavior

ITK master branch should configure cleanly in the CI environments with python 3.5 or greater.

### Actual behavior

Python 2.7 is found and used.

### Versions
ITK master branch

### Environment
CI Python build environments.

**Comment by thewtex** [comment]
This PR should address this issue:

  https://github.com/InsightSoftwareConsortium/ITK/pull/1072
