### ISSUE TITLE
ITK BoneMorphometry Runtime Error

### ISSUE THREAD

**Issue by kcstauffer21** [InsightSoftwareConsortium/ITK#1107]
Hello, I am trying to use the bone morphometry addon in python and when I use the filtr.Update() command I get the following error. 

Code--------------------------------------------------------------
filtr = itk.BoneMorphometryFeaturesFilter.New(im)
filtr.SetThreshold(int(1000))
filtr.SetInput(im)
filtr.Update()

Error---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-1c61abe0203f> in <module>()
----> 1 filtr.Update()

RuntimeError: C:\P\IPP\standalone-build\ITK-source\Modules\Core\Common\src\itkProcessObject.cxx:1387:
itk::ERROR: BoneMorphometryFeaturesFilter(000002982EF1D860): Input Primary is required but not set.

I am wondering if there is a fix in python or another step that needs to me taken so I can get this up and running.

Thanks for your help in advance.
Kendall

**Comment by thewtex** [comment]
Thanks for the report, Kendall. We need to update the `itk-bonemorphometry` for ITK 5. I will create a new package and report here after it has been uploaded.

**Comment by thewtex** [comment]
Hi Kendall,

A new version of *itk-bonemorphometry* has been uploaded, *1.1.1*. Please try

```
python -m pip install --upgrade itk-bonemorphometry
```

Please let us know how it goes. If the issue persists, please re-open this issue.
