### ISSUE TITLE
Problem with AVX MSVC flag

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#1114]
Since commit 41203a5 and 9c6053e (of @rmukh and @hjmjohnson), RTK is not compiling on MSVC. See July 3 [dashboard page](https://my.cdash.org/index.php?project=RTK&date=2019-07-03), the commit appears in ITK after InITK-Windows7-64bit-MSVC-ITKmaster-Shared-RelWithDebInfo-FFTWON successfully compiled and before InITK-Windows7-64bit-MSVC-ITKmaster-Static-RelWithDebInfo-FFTWON-TBB fails (both succeed/fail the days before/after). I have no idea how to deal with this but if I remove [these lines](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKSetStandardCompilerFlags.cmake#L146-L152), it compiles fine, see this [dashboard result](https://my.cdash.org/buildSummary.php?buildid=1680011)... Is my machine too old for ITK (~2010) or is there an error in these cmake changes? Thanks for your help and let me know if I can test anything.

**Comment by dzenanz** [comment]
Since the error messages are mostly in French, I don't understand what they are saying. Maybe @jcfr could read them? But your machine might be too old to have these instructions. Does that happen on one machine only, or on multiple machines?

**Comment by SimonRit** [comment]
Sorry about that but the messages are not informative. Two types for problems:
- the files generated by gengetopt are not generated because gengetopt crashes. Gengetopt is compiled in the same build so the new instructions make it crash.
- the tests crash.
I don't have another Windows machine but the problems are not there on AppVeyor

**Comment by rmukh** [comment]
@SimonRit It might be a problem with VS compiler, but not sure. You are using Visual Studio 14 2015 Win64, is it possible for you to test the same build, but with Visual Studio 15 2017 Win64? Thank you in advance.

**Comment by SimonRit** [comment]
Yes, and the same thing seems to occur. See Experimental build [here](https://my.cdash.org/buildSummary.php?buildid=1680821).

**Comment by rmukh** [comment]
Thank you for sharing results. 

Then, you are probably right that 'the files generated by gengetopt are not generated because gengetopt crashes. Gengetopt is compiled in the same build so the new instructions make it crash.'

I will take a look at possible solutions for that particular build configuration in free time.

**Comment by hjmjohnson** [comment]
You should be able to set the cache values for the compiler optimizations to something suitable for this old machine. As a quick solution, simply setting them to empty values should be enough to tell the compiler to avoid using instructions that are too new for your computer.

```
-DITK_C_OPTIMIZATION_FLAGS:STRING=""
-DITK_CXX_OPTIMIZATION_FLAGS:STRING=""
```

**Comment by SimonRit** [comment]
A quick update. I have added the following code to my ctest script
```
file(READ "${CTEST_SOURCE_DIRECTORY}\\CMake\\ITKSetStandardCompilerFlags.cmake" ITKSETSTANDARDCOMPILERFLAGS_FILE)
string(REGEX REPLACE "/arch:AVX " "\"\"" ITKSETSTANDARDCOMPILERFLAGS_FILE "${ITKSETSTANDARDCOMPILERFLAGS_FILE}")
string(REGEX REPLACE "/arch:AVX2" "\"\"" ITKSETSTANDARDCOMPILERFLAGS_FILE "${ITKSETSTANDARDCOMPILERFLAGS_FILE}")
file(WRITE "${CTEST_SOURCE_DIRECTORY}\\CMake\\ITKSetStandardCompilerFlags.cmake" "${ITKSETSTANDARDCOMPILERFLAGS_FILE}")
```
and the compilation worked fine last night. This computer is still less than 10 years so I would suggest to detect the availability of the avx instructions... Maybe this piece of code can help:
https://gist.github.com/UnaNancyOwen/263c243ae1e05a2f9d0e

What do you think?

**Comment by dzenanz** [comment]
While we might do that, it adds more configure-time tests, when initial configuration time on Windows is on the order of 5 minutes or so. And it also needs to be maintained. @hjmjohnson @rmukh what do you think?

**Comment by hjmjohnson** [comment]
I have mixed feelings on this, but I think that in this case the added complexity is probably worth the extra few seconds of testing.  

I don't have time in the near future to address this :(.

I think the quick solution might be something like

https://cmake.org/cmake/help/v3.10/command/cmake_host_system_information.html

```cmake
cmake_host_system_information(RESULT MSVC_SUPPORTS_AVX QUERY HAS_SSE)
cmake_host_system_information(RESULT MSVC_SUPPORTS_AVX2 QUERY HAS_SSE2)

```

**Comment by SimonRit** [comment]
I'm coming back to this issue. Your solution Hans does not seem to work, this computer has SSE and SSE2 but does not have AVX and AVX2. Should I try to implement what I suggested before?

**Comment by hjmjohnson** [comment]
if you configure with
```
cmake \
   -DITK_C_OPTIMIZATION_FLAGS:STRING=""   \
   -DITK_CXX_OPTIMIZATION_FLAGS:STRING=""
```

That should also set the optimizations to off for your older hardware.

If those cmake variables are not set, they default to settings that work for more recent (i.e. ~9 year old) hardware and newer.

Hans

**Comment by hjmjohnson** [comment]
I don't want 99% of the users to take a significant performance to support the older hardware.

I'd prefer a solution that automatically tests for AVX instructions and works with much older hardware by automatically (in those rare cases) selecting a different set of code optimizations.

**Comment by SimonRit** [comment]
I perfectly understand and agree with you on all points. Is [this solution](https://gist.github.com/UnaNancyOwen/263c243ae1e05a2f9d0e) too costly in your opinion? I don't see an alternative...

**Comment by hjmjohnson** [comment]
@SimonRit I don't have a better solution.  If you propose that solution it may provoke someone to speakup with a better solution.
