### ISSUE TITLE
Inconsistent _snprintf define 

### ISSUE THREAD

**Issue by KBaur** [InsightSoftwareConsortium/ITK#1115]
### Description

Above VS2015 the 

> #define snprintf _snprintf

is no longer necessary and will cause problemens on compiling with windows.

### Steps to Reproduce
In
itkImageSeriesWriter.hxx line 32
libsrc2/minc2_pricate.h line 213
include/minc2_private.h line 213
libmin/libsrc2/minc2_private.h line 213

> #if _MSC_VER
> #define snprintf _snprintf
> #endif // _MSC_VER

change to

> #if _MSC_VER < 1900 /* MSVC-14 defines real snprintf()... just about time! */
> #define snprintf _snprintf
> #endif // _MSC_VER

### Actual behavior

```none
```

### Versions

ITK 5.0.0

### Environment
OS: Windows
Platform Toolset: MSVS 2017 Visual Studio 2017 (v141)
Windows SDK Version: 10.0.15063.0

**Comment by dzenanz** [comment]
@gdevenyi I guess this should be changed in MINC, and then we should update ITK's version of MINC.

**Comment by TMeindl** [comment]
I think the patch for libsrc2/minc2_private.h still needs 

#define strncasecmp strnicmp
#define strcasecmp stricmp

in the common case if _MSC_VER is defined.

See attached patch:
[ITK-5.0.0-snprintf.patch.txt](https://github.com/InsightSoftwareConsortium/ITK/files/3421780/ITK-5.0.0-snprintf.patch.txt)

**Comment by seanm** [comment]
I made the same conditionalization in two places in ITK itself: https://github.com/InsightSoftwareConsortium/ITK/pull/1359

and in GDCM: https://github.com/malaterre/GDCM/pull/99

I believe this can be closed after those are in.

**Comment by N-Dekker** [comment]
Please note that `snprintf` and `_snprintf` behave slightly different.

    char str1[4] = "";
    char str2[4] = "";

    snprintf(str1, 3, "1234567");  // str1 = "12"
    _snprintf(str2, 3, "1234567");  // str2 = "123"

As I observed with VS2019 (version 16.3.6)

**Comment by seanm** [comment]
I think the only ones left are in:
- MINC's config.h.msvc-win32
- teem nrrd
- googletest

**Comment by dzenanz** [comment]
Has this been resolved? Can we close it?

**Comment by hjmjohnson** [comment]
```
git grep "define.*_snprintf"

Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmFilenameGenerator.cxx:#define snprintf _snprintf
Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmSystem.cxx:#define snprintf _snprintf
Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmJPEG2000Codec.cxx:#define snprintf _snprintf
Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/include/gtest/internal/gtest-port.h:// Windows CE does not define _snprintf_s
Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/include/gtest/internal/gtest-port.h:# define GTEST_SNPRINTF_ _snprintf
Modules/ThirdParty/HDF5/src/itkhdf5/src/H5win32defs.h:#define HDsnprintf          c99_snprintf /*varargs*/
Modules/ThirdParty/MINC/src/libminc/libcommon/minc_config.c:#define snprintf _snprintf 
Modules/ThirdParty/MINC/src/libminc/libcommon/time_stamp.c:#define snprintf _snprintf
Modules/ThirdParty/MINC/src/libminc/libsrc/config.h.msvc-win32:#define snprintf _snprintf
Modules/ThirdParty/MINC/src/libminc/libsrc2/minc2_private.h:#define snprintf _snprintf 
Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTypes.h:#define snprintf _snprintf
Modules/ThirdParty/NrrdIO/src/NrrdIO/biffbiff.c:#  define snprintf _snprintf
Modules/ThirdParty/NrrdIO/src/NrrdIO/enum.c:#  define snprintf _snprintf
Modules/ThirdParty/VNL/src/vxl/vcl/vcl_legacy_aliases.h:#define vcl_snprintf std::snprintf
Modules/ThirdParty/ZLIB/src/itkzlib/gzguts.h:#  define snprintf _snprintf
Modules/ThirdParty/ZLIB/src/itkzlib/gzlib.c:#if !defined(NO_snprintf) && !defined(NO_vsnprintf)
Modules/ThirdParty/ZLIB/src/itkzlib/gzlib.c:#if !defined(NO_snprintf) && !defined(NO_vsnprintf)
Modules/ThirdParty/ZLIB/src/itkzlib/gzlib.c:#if !defined(NO_snprintf) && !defined(NO_vsnprintf)
q

```

**Comment by dzenanz** [comment]
All of this is third-party code. Can MINC guys to update their library? @gdevenyi @vfonov GDCM might want to support older VS too. @malaterre I could update MetaIO.

**Comment by dzenanz** [comment]
MetaIO [PR89](https://github.com/Kitware/MetaIO/pull/89).

**Comment by malaterre** [comment]
@dzenanz GDCM is a false-positive here. I've pulled in a PR from @seanm months ago:

* https://github.com/InsightSoftwareConsortium/ITK/issues/1115#issuecomment-546534370

**Comment by hjmjohnson** [comment]
@dzenanz Perhaps #1750 fixes this false-positive.

**Comment by vfonov** [comment]
`Modules/ThirdParty/MINC/src/libminc/libsrc/config.h.msvc-win32` is not used for anything
all the other files have `#if  defined(_MSC_VER) && _MSC_VER < 1900` to limit this to old Visual studio

**Comment by seanm** [comment]
The original complaint was that things weren't conditionalized properly, and I believe they now are.

Removing it entirely, as @dzenanz did in MetaIO, doesn't seem necessary.

**Comment by hjmjohnson** [comment]
I agree 100% with @seanm

**Comment by thewtex** [comment]
Per discussion, closing. If there are locations we missed, please re-open.
