### ISSUE TITLE
itkDCMTKImageIO.h RGB Converter

### ISSUE THREAD

**Issue by KBaur** [InsightSoftwareConsortium/ITK#1125]
### Description
In Line 320 ~ 337 in itkDCMTKImageIO.cxx the buffer of the DICOM Image is copied to the itkImage buffer. For the RGB(A) Pixels a reorder of the RGB(A) Pixel (itkDCMTKImageIO.h Line 123 ~134) is made, which is useless, because in Line 337 (itkDCMTKImageIO.cxx) the old buffer is again copied over the new sorted buffer.

### Steps to Reproduce
See above

### Versions

ITK 5.0.0

### Environment

OS: Windows
Platform Toolset: MSVS 2017 Visual Studio 2017 (v141)
Windows SDK Version: 10.0.15063.0

**Comment by thewtex** [comment]
[Patches](https://github.com/InsightSoftwareConsortium/ITK) welcome :-)
