### ISSUE TITLE
SimpleITK LabelShapeStatisticsFilter GetOrientedBoundingBox Coordinates Appear Incorrect

### ISSUE THREAD

**Issue by kevinalexbrown** [InsightSoftwareConsortium/ITK#1128]
@blowekamp asked me to submit this issue. 

Vertices produced by sitk.LabelShapeStatisticsFilter()'s GetOrientedBoundingBoxVertices() are properly in real-world coordinates of the label image only after applying a rotation.

Here is a minimal example that reproduces and solves the issue: https://gist.github.com/kevinalexbrown/d2474bc8245f9aa36af64fcc7c52e8f1

**Comment by blowekamp** [comment]
Thanks for reporting the issue. I looked at the ITK code: https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/LabelMap/include/itkShapeLabelObject.h#L565-L598

The code clearly does not take into consideration the directions matrix for orientation when generating the vertices list. I'll report this to the ITK repo.
