### ISSUE TITLE
Development build problems

### ISSUE THREAD

**Issue by melrobin** [InsightSoftwareConsortium/ITK#1130]
### Description
Development ITK fails to build for me.  There are numerous errors of this sort:
/home/melrobin/packages/ITK/Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.hxx:93:73:   required from ‘void itk::CastImageFilter<TInputImage, TOutputImage>::DynamicThreadedGenerateData(const OutputImageRegionType&) [with TInputImage = itk::Image<itk::RGBPixel<unsigned char> >; TOutputImage = itk::Image<itk::Vector<float, 3> >; itk::CastImageFilter<TInputImage, TOutputImage>::OutputImageRegionType = itk::ImageRegion<2>]’
/home/melrobin/packages/ITK/Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx:53:21:   required from here
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkMetaProgrammingLibrary.h:183:36: error: no matching function for call to ‘itk::Vector<float, 3>::Vector(itk::RGBPixel<unsigned char>)’
                           decltype(static_cast<TToType>(std::declval<TFromType>()))>
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Steps to Reproduce
The error comes when building this object:
Building CXX object Modules/Filtering/ImageFilterBase/test/CMakeFiles/ITKImageFilterBaseTestDriver.dir/itkCastImageFilterTest.cxx.o

### Expected behavior

Completed build

### Actual behavior

Build Error

### Versions
Development

### Environment

Fedora 29, gcc 8.3.1

**Comment by issakomi** [comment]
FYI, one my old module fails to build with current master branch too

```
Modules/Core/Common/include/itkMetaProgrammingLibrary.h:183:36: error:
no matching function for call to
‘itk::Vector<float, 3>::Vector(itk::RGBPixel<short int>)’
decltype(static_cast<TToType>(std::declval<TFromType>()))>
```


```
Modules/Core/Common/include/itkImageAlgorithm.hxx:45:17: error:
no matching function for call to
‘itk::Vector<float, 3>::Vector(itk::ImageConstIterator<itk::Image<itk::RGBPixel<short int>, 3> >::PixelType)’
ot.Set( static_cast< typename OutputImageType::PixelType >( it.Get() ) );
```

Best regards

**Comment by blowekamp** [comment]
I have been able to reproduce the issue on centos 7.6 with gcc8 from the devtoolset-8-toolchain package.
