### ISSUE TITLE
Flaky itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#1131]
I caught `itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest` crashing in [itkPointSetToPointSetMetricv4.hxx, line 347](https://github.com/InsightSoftwareConsortium/ITK/blob/c376cf6bd17b07e730ee1f146c9e06846dc6aaa7/Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.hxx#L347). This was most recently modified by @samuelgerber in 687c49176ba97fbbe805fc468bd96ec36b46ffc0.

**Comment by dzenanz** [comment]
I will look into this a bit more, but ideas are welcome.

**Comment by samuelgerber** [comment]
I think I see the issue. I can fix it.

Needs another variable of different dimension to store intermediate results before jacobian transform.

**Comment by dzenanz** [comment]
The failure is non-deterministic, but relatively frequent at about 10-20%.

**Comment by samuelgerber** [comment]
I put a fix here:
https://github.com/InsightSoftwareConsortium/ITK/compare/master...samuelgerber:FixPointSetMetricv4?expand=1

I did not open a pull request yet since i think there is a logic / math error somewhere as well when computing the derivative in tangent space.

**Comment by hjmjohnson** [comment]
Failing test persists here.

**Comment by dzenanz** [comment]
Offending changes reverted by #1139.
