### ISSUE TITLE
Unused function template warning

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#1147]
```text
/Users/builder/externalModules/Core/Common/test/itkImageRegionRangeGTest.cxx:188:8: warning: unused function template 'Check_Range_constructor_throws_ExceptionObject_when_iteration_region_is_outside_of_buffered_region' [-Wunused-template]
  void Check_Range_constructor_throws_ExceptionObject_when_iteration_region_is_outside_of_buffered_region(
       ^
```
appears in [this build](https://open.cdash.org/viewBuildError.php?type=1&buildid=6046498).

**Comment by N-Dekker** [comment]
Thanks @dzenanz This particular test only runs in Release mode (when the "non-debug" macro `NDEBUG` is defined):

https://github.com/InsightSoftwareConsortium/ITK/blob/f162460efc347025d063634153b4dce4db6c3937/Modules/Core/Common/test/itkImageRegionRangeGTest.cxx#L573-L577

I wrote the test to check if `itkAssertOrThrowMacro` is being called properly, within the `ImageRegionRange` constructor. Do I understand correctly that such a test can only run in Release mode?

**Comment by dzenanz** [comment]
If this is a false positive, please close the issue. And sorry for the noise!

**Comment by N-Dekker** [comment]
> If this is a false positive, please close the issue.

No it's a true positive, but it only occurs with debug builds. I'll soon take another look!

**Comment by blowekamp** [comment]
I believe the function can be marked inline, and the compiler will not use it without complaint.

**Comment by N-Dekker** [comment]
@blowekamp 
> I believe the function can be marked inline, and the compiler will not use it without complaint.

Thanks for the suggestion, Bradley. Instead, I think the issue could also be solved by just surrounding the function  by `#ifdef NDEBUG` ... `#endif`.

But the more fundamental question remains: how to test if a function correctly does `itkAssertOrThrowMacro`?

Suppose there would be an `itk::CheckedDereference(T* ptr)` function, as follows:

    namespace itk
    {
      template <typename T>
      T& CheckedDereference(T* ptr)
      {
        itkAssertOrThrowMacro(ptr != nullptr, "Check!");
        return *ptr;
      }
    }

How to test that `itkAssertOrThrowMacro` is called when a user does `itk::CheckedDereference<int>(nullptr)`?

**Comment by blowekamp** [comment]
@N-Dekker To detect an assert you might have to use a [Death Test](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-tests) but that seems a little heavy weight.
