### ISSUE TITLE
enum ThreaderType --> enum class ThreaderType

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#1194]
### Description

enum ThreaderType { Platform = 0, First = Platform, Pool, TBB, Last = TBB, Unknown = -1 };
### Expected coding style

Should be an enum class as was done in #1061

**Comment by thewtex** [comment]
Implemented in https://github.com/InsightSoftwareConsortium/ITK/commit/3c4806e0235fc29e04d535986a4832e7060494c7
