### ISSUE TITLE
Build ITK with itkLabelGeometryImageFilter.h

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#1200]
I am having issues building ANTs (which depends on ITK), and the issue seems to be the following:

```
/var/tmp/portage/sci-biology/ants-9999/work/ants-9999/Examples/ImageMath_Templates.hxx:67:10: fatal error: itkLabelGeometryImageFilter.h: No such file or directory
   67 | #include "itkLabelGeometryImageFilter.h"
```

I am assuming the file in question was not generated as part of ITK, which I built with the following command:

```
cmake -C /var/tmp/portage/sci-libs/itk-5.0.1/work/itk-5.0.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DGDCM_USE_SYSTEM_OPENJPEG=ON -DITK_FORBID_DOWNLOADS:BOOL=OFF -DITK_USE_SYSTEM_DCMTK=ON -DITK_USE_SYSTEM_DOUBLECONVERSION=ON -DITK_USE_SYSTEM_CASTXML=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SWIG=ON -DITK_USE_SYSTEM_TIFF=ON -DITK_USE_SYSTEM_ZLIB=ON -DITK_USE_KWSTYLE=OFF -DITK_BUILD_DEFAULT_MODULES=ON -DITK_COMPUTER_MEMORY_SIZE=1 -DWRAP_ITK_JAVA=OFF -DWRAP_ITK_TCL=OFF -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -DExternalData_OBJECT_STORES=/var/tmp/portage/sci-libs/itk-5.0.1/work/InsightToolkit-5.0.1/.ExternalData -DModule_GenericLabelInterpolator:BOOL=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DITK_USE_REVIEW=OFF -DITK_INSTALL_LIBRARY_DIR=lib64 -DITK_WRAP_PYTHON=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/itk-5.0.1/work/itk-5.0.1_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/itk-5.0.1/work/InsightToolkit-5.0.1
```

Using `grep` to look at the source code of ITK I could not find any indication as to what build flag might trigger the creation of this file.

**Comment by blowekamp** [comment]
Hello,

The LabelGeometryImageFilter was is in the Review module. To enable it set the CMake flag `Module_ITKReview` to On.

@ntustison The ShapeLabel map infrastructure should be preferred over this filter. Please consider upgrading ANTs to use the `itk::LabelImageToShapeLabelMapFilter` filter.

**Comment by ntustison** [comment]
Thanks @blowekamp --- I'll do that.  

@TheChymera --- we answered your question [here](https://github.com/ANTsX/ANTs/issues/817).

**Comment by TheChymera** [comment]
@ntustison please note that this was another issue. This is `itkLabelGeometryImageFilter.h`, the last one we discussed was `itkLabelImageGenericInterpolateImageFunction.h`.

**Comment by TheChymera** [comment]
Closed it :) though if you are knowledgeable about the matter, maybe you could help me out [here](https://github.com/InsightSoftwareConsortium/ITK/issues/1157#issuecomment-524303323)? But this is clearly an ITK issue now, not ANTs.

**Comment by TheChymera** [comment]
Ok, this worked, the `Module_ITKReview` flag was all that was needed.
