### ISSUE TITLE
Relax clang-format version from 8.0.1 to just 8.0.x

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#1215]
### Description

I don't think the format changes in clang-format patch versions, and the tools are typically named without the patch version, so is 8.0.1 too much

See PR #1201  that over-prescribes the version of clang-format.

### Expected behavior

Any 8.0.x version of clang-format should work.

### Actual behavior

Explicitly require 8.0.1 for the moment.

**Comment by issakomi** [comment]
I believe that i run on Linux into the issue, downloaded is 8.0.0, required is 8.0.1, so have to use _--no-verify_. Current Debian 10.1 system clang is clang-7.

**Comment by dzenanz** [comment]
Did #1321 fix this issue?
