### ISSUE TITLE
There is no GPU-compatible MultiResolutionPDEDeformableRegistration

### ISSUE THREAD

**Issue by chacha21** [InsightSoftwareConsortium/ITK#1221]
Since MultiResolutionPDEDeformableRegistration only accepts a PDEDeformableRegistrationFilter as registrationFilter, it cannot be defined to a GPUPDEDeformableRegistrationFilter.
And there is no GPUMultiResolutionPDEDeformableRegistration.

What would be the best way to handle that ?

**Comment by thewtex** [comment]
If it is possible to make the `RegistrationType` a template parameter, patches would be welcome :+1:

**Comment by chacha21** [comment]
#1223
