### ISSUE TITLE
OrientImageFilter changes the origin of the image

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#1224]
Reported on [discourse](https://discourse.itk.org/t/orientimagefilter-changes-the-origin-of-the-image/2200).

Anisotropic images cause wrong origin to be calculated by `OrientImageFilter`.

Data: https://1drv.ms/u/s!AgvRZZtXCbbOnIwGa6dEHvJ75jvSOQ?e=xf5TiS
Code: https://github.com/sarthakpati/ITKOrientFilterExample

**Comment by sarthakpati** [comment]
New finding reported: https://discourse.itk.org/t/orientimagefilter-changes-the-origin-of-the-image/2200/16?u=sarthakpati

Basically, there is a difference when the Orientation filter is applied on the raw itk::Image::Pointer v/s the read image from disk:

```powershell
Original Orientation: LPI
Started verification.
Original Image Properties:
        Origin: [86.9175, 90.0284, -101.794]
Oriented Image [RAI] Properties:
        Origin: [-100.04, -158.669, -101.794]
Re-Oriented Image [LPI] - from Raw RAI Properties:
        Origin: [86.9175, 90.0284, -101.794]
Re-Oriented Image [LPI] - from Written RAI Properties:
        Origin: [86.9378, 90.0131, -101.794]
```

**Comment by sarthakpati** [comment]
New finding reported: https://discourse.itk.org/t/orientimagefilter-changes-the-origin-of-the-image/2200/19?u=sarthakpati

**Comment by dzenanz** [comment]
The real issue is #1237.
