### ISSUE TITLE
Eigen warnings with GCC 4.8.5

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#1254]
I have a bunch of shadow warnings when compiling with GCC 4.8.5, see
[RTK dashoard](https://my.cdash.org/buildSummary.php?buildid=1702853). I am willing to fix them but I'm not sure what's the best procedure. Since they are coming from a third party software, Eigen3, should I add a rule in CMake/CTestCustom.cmake.in to ignore them or try to correct the Eigen3 code?

**Comment by dzenanz** [comment]
Perhaps one way is to keep updating `Eigen`. @phcerdan integrated it first, if you look at his PRs you will find more details about it. As `Eigen` is a third-party library, another possibility is to suppress the warnings in that library.

**Comment by SimonRit** [comment]
Thanks for your answer. As far as I can tell, the current HEAD of Eigen would not solve the warnings. One solution is to make a PR to Eigen but that's too much work for me. If you're ok, I'll make an ITK PR with the warning suppression.

**Comment by phcerdan** [comment]
Hi Simon, open the PR to the Eigen fork for ITK and I can contribute it to proper Eigen if that overhead sets you back.

**Comment by phcerdan** [comment]
Gcc 4.8 is getting really old though, not sure if its worth more work around it.

**Comment by dzenanz** [comment]
A PR with suppression is welcome.

**Comment by SimonRit** [comment]
Sorry for the delay, I was traveling. I wasn't sure what was the conclusion so I tried @phcerdan first suggestion (before commenting on the age of GCC 4.8). I'm aware the patch is not the nicest with parameters becoming meaningless but I don't know how to call them. I don't mind adding a line to CMake/CTestCustom.cmake.in if it's preferable or changing it after better suggestions.

**Comment by seanm** [comment]
CC: @seanm @vfonov 

eigen was just updated in ITK master, but even after that, I see shadow warnings on my dashboard:

https://open.cdash.org/viewBuildError.php?type=1&buildid=6174899

and it uses a current AppleClang.

@SimonRit Are those the same warnings you see?

**Comment by SimonRit** [comment]
It seems that they were not exactly the same. You can still click on the link in my initial report.

**Comment by seanm** [comment]
Your initial report predates eigen being updated in ITK. Could you try again with ITK master?

**Comment by SimonRit** [comment]
Sorry, I guess I misunderstood your question. I don't see shadow warnings on my dashboard anymore, they were here on the [24](https://my.cdash.org/viewBuildError.php?type=1&buildid=1719339) and they are gone [now.](https://my.cdash.org/buildSummary.php?buildid=1720616) with the same configuration. Great! This is using GCC 4.8.5. This issue can be closed as far as I'm concerned. Thanks!
