### ISSUE TITLE
Image resolution too small, can't read content

### ISSUE THREAD

**Issue by EmileSonneveld** [InsightSoftwareConsortium/ITK#1268]
### Description

Image resolution too small, can't read content. In documentation chapter "Using CMake for Configuring and Building ITK" https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch2.html#x22-180002.2

### Expected information

The image resolution should be high enough so that the text in it is readable.

### Versions

Book1ch2

**Comment by dzenanz** [comment]
While it doesn't solve this issue, the resolution is high in [printable version](https://itk.org/ItkSoftwareGuide.pdf). Generally, HTML version has lower-resolution images than PDF version.

**Comment by thewtex** [comment]
@EmileSonneveld thanks for the report.

We are focusing effort on the PDF version of the Software Guide, so closing this issue.
