### ISSUE TITLE
CVMatToITKImage

### ISSUE THREAD

**Issue by tingfengwanxiao** [InsightSoftwareConsortium/ITK#1269]
I want to use this function (CVMatToITKImage) to convert cv::mat to itk,and the input of the function is(const cv::mat&in),I use imread in opencv and get an img,but it cannot be used as input,show the error No template matching the parameter type,how can I do,thanks.

**Comment by dzenanz** [comment]
What is the source code you are trying to compile?

**Comment by tingfengwanxiao** [comment]
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkOpenCVImageBridge.h"

// includes from OpenCV
#include "cv.h"
#if CV_VERSION_MAJOR > 2
#  include "opencv2/opencv.hpp" // cv::imwrite
#771 
#if CV_VERSION_MAJOR > 2
#  include "opencv2/opencv.hpp" // cv::imwrite
#endif
main()
{
typedef itk::Image<unsigned char, 2> ImageType; 
Mat img = imread("F:/test-unet-end/ConsoleApplication1/x64/Debug/data/1.jpg");
ImageType::Pointer itkImage = ImageType::New();
itkImage=itk::OpenCVImageBridge:CVMatToITKImage(img)
}
//-----------------------------------------------------------------------------------
then,I will get the img cannot match the cvMatToITKImage,you should input cv::mat&in instead of cv::mat

**Comment by dzenanz** [comment]
The main problem is lack of specifying template parameter. This compiles for me:
```C++
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkOpenCVImageBridge.h"
#include "opencv2/opencv.hpp" // cv::imwrite

int main()
{
    typedef itk::Image<unsigned char, 2> ImageType;
    cv::Mat img = cv::imread("F:/test-unet-end/ConsoleApplication1/x64/Debug/data/1.jpg");
    ImageType::Pointer itkImage = ImageType::New();
    itkImage = itk::OpenCVImageBridge::CVMatToITKImage< ImageType >(img);
}
```

**Comment by tingfengwanxiao** [comment]
ok,thank you.it's right.

**Comment by Kunyadav** [comment]
HI,
 i am using the "CVMatToITKImage" api and later i am using it for image translation, i am getting null pointer exception at    filter->Update(); , will you help me in figuring out the issue?





#include <itkElastixRegistrationMethod.h>
#include <elxParameterObject.h>
#include <Core/elxVersionMacros.h>
#include <iostream>
#include <itkImage.h>
#include "itkImageFileReader.h"
#include "itkOpenCVImageBridge.h"
#include <itkSize.h>
#include <cassert>
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/opencv.hpp"
#include "param.h"
#include "itkImage.h"
#include "itkImageFileWriter.h"
using namespace std;

int
main()
{
  enum
  {
    imageSizeX = 6,
    imageSizeY = 5
  };
  try
  {
   typedef itk::Image<unsigned char, 2> ImageType;
  //typedef itk::Image<float> ImageType;
  cout << "Built with OpenCV 0" << CV_VERSION << endl;
  cv::Mat sem_input= cv::imread("C:/Users/e182000/Documents/cad2semm/waveform/B79Y22ADD/wf9_Meas.tif");  
  cv::Mat cad_input = cv::imread("C:/Users/e182000/Documents/cad2semm/waveform/B79Y22ADD/wf9_Model.tif");  
  ImageType::Pointer itkFixedImage = ImageType::New();  
  ImageType::Pointer itkMovingImage = ImageType::New();
 
  CADBasedCoarseEdgeRecipeParams *recipe_params = new CADBasedCoarseEdgeRecipeParams();
  recipe_params->setMaxNumOfIerationsFactor(0.1);
  itkFixedImage = itk::OpenCVImageBridge::CVMatToITKImage< ImageType >(sem_input);
  itkMovingImage = itk::OpenCVImageBridge::CVMatToITKImage< ImageType >(cad_input);

  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();
  auto writerImg = WriterType::New();;
  writerImg->SetFileName("F:\\elast\\Moving_image1.tif");
  writerImg->SetInput(itkMovingImage);

  writer->SetFileName("F:\\elast\\fixed_image1.tif");
  writer->SetInput(itkFixedImage);
  try
  {
    writer->Update();
    writerImg->Update();
  }
  catch (const itk::ExceptionObject & error)
  {
    std::cerr << "Error: " << error << std::endl;
    return EXIT_FAILURE;
  }
  cv::imshow("Sample", sem_input);
  cv::waitKey(0);
  cv::Mat image_blurred_with_3x3_kernel;
  cv::GaussianBlur(sem_input, image_blurred_with_3x3_kernel, cv::Size(3, 3), 0);
  cv::imshow("Blurred", image_blurred_with_3x3_kernel);
  cv::waitKey(0);

 if( itkFixedImage.IsNull()==true || itkMovingImage.IsNull()==true)
 {
   cout << "its Null" << endl;
   return EXIT_FAILURE;
 }
 else
 {
   cout << "Not Null\n";
 }  
  const auto parameterObject = elx::ParameterObject::New();
  parameterObject->SetParameterMap(
    elx::ParameterObject::ParameterMapType{ { "ImageSampler", { "Full" } },
                                            { "MaximumNumberOfIterations", { "44" } },
                                            { "Metric", { "AdvancedNormalizedCorrelation" } },
                                            { "Optimizer", { "AdaptiveStochasticGradientDescent" } },
                                            { "Transform", { "TranslationTransform" } } });

  const auto filter = itk::ElastixRegistrationMethod<ImageType, ImageType>::New();
  if (filter.IsNull() == true || parameterObject.IsNull()==true)
  {
    cout << "filter failed 4->" << CV_VERSION << endl;
    return EXIT_FAILURE;
  }
  else
  {
    cout << "all good till now" << endl;
  }
  filter->SetFixedImage(itkFixedImage);
  filter->SetMovingImage(itkMovingImage);
  filter->SetParameterObject(parameterObject);
  auto tempFixedImg=filter->GetFixedImage();
    filter->Update();
    cout << "Update was successful" << endl;
  }
  catch (itk::ExceptionObject & err)
  {
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  catch (...)
  {
    std::cerr << "ExceptionObject caught !" << std::endl;
    return EXIT_FAILURE;
  }
 

} // end main()

Regards
Kunal
