### ISSUE TITLE
Give credit to remote modules contributors at release time

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#1272]
### Description

Contributors to the ITK code base for a given release or RC are credited through the list of their Pull Requests.

Remote modules may have also gone through updates and their commit hashes updated in ITK. Yet, these contributors are not credited when an ITK release candidate (RC) or release is announced.

Besides crediting contributors and building a stronger tie with them, this would allow readers to know better the remotes and be aware of changes in them.

### Expected information

List of PRs grouped by contributor and remote module name in RC and release notes.

### Actual information

None concerning remotes.

### Versions

`master`

**Comment by thewtex** [comment]
@jhlegarreta awesome idea!

We can update [this script](https://gist.github.com/thewtex/5045b8e13b5d12b8fdcf) to add contributors to Remote Modules and generate a change log to add to the end of the release notes.
