### ISSUE TITLE
itkRayCastInterpolateImageFunction performs ray-casting with the input volume shifted

### ISSUE THREAD

**Issue by IbaiGenuaGamio** [InsightSoftwareConsortium/ITK#1276]
### Description
The itkRayCastInterpolateImageFunction performs ray-casting as if the volume origin would be located in the left bottom part of the first voxel. The volume is assumed to be with the origin in the O (0,0,0) point. According to ITK image geometry, that means that the centre of the first voxel should be in this point, leaving the left bottom corner of this image half voxel lower in every direction. When computing the bounding borders and consequently, the bounding planes, the volume is assumed to be located with the LEFT BOTTOM corner of the first voxel in the O(0,0,0) point. 
Further in the code, 0.5 value is subtracted from the incident point of the ray with the volume. This is explained in the code as trying to fix something related with voxel centres, but it does not fix this issue, it is actually useful for further interpolation calculations.

### Steps to Reproduce
To test this bug, a theoretical scenario of a DRR (Digitally Reconstructed Radiograph) was created. There, the source point of the X-Ray (the focal point) was set in point P1(0,0,20). The volume (CT scan emulation) was located with origin in O(0,0,0) and the DRR image in P2(0,0,-2). In order to create the most basic scenario as possible, the DRR consists on a single pixel image (centred in P2 following ITK image geometrical properties). The volume should ideally consist also in a single voxel. Nevertheless, as itkRayCastInterpolateImageFunction works just with neighbour voxels for interpolation calculations, it finally consisted on a bigger volume. This volume though, was manipulated to have every voxel to null value, except for one voxel having 1000 value. This way, the ray-casting algorithm could be tested just for that voxel.
The centre of the high intensity voxel of the volume was set in the pathway connecting the source-point with the DRR pixel. Ideally, the ray traced, should pass through the voxel and project its intensity value in the image. 
Here is the code where this ray-casting was implemented:

```C++
#include "iostream"

#include <itkEuler3DTransform.h>
#include <itkGPUImage.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkRayCastInterpolateImageFunction.h>
#include <itkResampleImageFilter.h>
#include <itkTimeProbe.h>

const unsigned int Dimension = 3;
using PixelType = float;
using ImageType = itk::GPUImage<PixelType, Dimension>;
using FilterType = itk::ResampleImageFilter<ImageType, ImageType>;
using InterpolatorType = itk::RayCastInterpolateImageFunction<ImageType, double>;
using TransformType = itk::Euler3DTransform<double>;
using WriterType = itk::ImageFileWriter<ImageType>;
using ReaderType = itk::ImageFileReader<ImageType>;
using PointType = itk::Point<double>;

ImageType::Pointer createSyntheticImage(ImageType::PointType origin, ImageType::SpacingType spacing, ImageType::SizeType size, ImageType::DirectionType direction)
{
	typename ImageType::RegionType imageRegion;
	typename ImageType::IndexType imageIndex;

	imageIndex[0] = 0;
	imageIndex[1] = 0;
	imageIndex[2] = 0;

	imageRegion.SetIndex(imageIndex);
	imageRegion.SetSize(size);

	typename ImageType::Pointer volume = ImageType::New();
	volume->SetSpacing(spacing);
	volume->SetOrigin(origin);
	volume->SetDirection(direction);
	volume->SetRegions(imageRegion);
	volume->Allocate();

	using VolumeIteratorType = itk::ImageRegionIteratorWithIndex<ImageType>;
	VolumeIteratorType it(volume, imageRegion);
	float v = 0;
	typename ImageType::IndexType idx;
	for (it.GoToBegin(); !it.IsAtEnd(); ++it)
	{
		it.Set(v);
	}

	return volume;
}
int main()
{
	// Source point of the DRR generation
	itk::Point<double, 3> sourcePoint;
	sourcePoint[0] = 0;
	sourcePoint[1] = 0;
	sourcePoint[2] = 20;

	// The volume will consist on more than one voxel but just one of them will have
	// non null intensity value. The test is based on that single voxel but as ray-casting 
	// algorithm is not pretended to be used in a single voxel image, the input will be 
	// a volume.
	ImageType::PointType volumeOrigin;
	volumeOrigin[0] = 0;
	volumeOrigin[1] = 0;
	volumeOrigin[2] = 0;
	ImageType::SpacingType volumeSpacing;
	volumeSpacing[0] = 1;
	volumeSpacing[1] = 1;
	volumeSpacing[2] = 1;
	ImageType::SizeType volumeSize;
	volumeSize[0] = 10;
	volumeSize[1] = 10;
	volumeSize[2] = 10;
	ImageType::DirectionType volumeDirection;
	volumeDirection.SetIdentity();

	ImageType::Pointer synt_vol = ImageType::New();
	synt_vol = createSyntheticImage(volumeOrigin, volumeSpacing, volumeSize, volumeDirection);

	// Voxel (0,0,3) is the one with high intensity value
	ImageType::IndexType volumeIndex;
	volumeIndex[0] = 0;
	volumeIndex[1] = 0;
	volumeIndex[2] = 3;
	synt_vol->GetBufferPointer()[volumeSize[0] * (volumeIndex[2] * volumeSize[1] + volumeIndex[1]) + volumeIndex[0]] = 1000;
	ImageType::PointType volumeTestPoint;
	synt_vol->TransformIndexToPhysicalPoint(volumeIndex, volumeTestPoint);

	// The image where ray tracing will be projected consists on a single pixel image in the ray traced 
	// when linking the volume and the source point.

	ImageType::PointType imageOrigin;
	imageOrigin[0] = 0;
	imageOrigin[1] = 0;
	imageOrigin[2] = -2;
	ImageType::SpacingType imageSpacing;
	imageSpacing[0] = 1;
	imageSpacing[1] = 1;
	imageSpacing[2] = 1;
	ImageType::SizeType imageSize;
	imageSize[0] = 1;
	imageSize[1] = 1;
	imageSize[2] = 1;
	ImageType::DirectionType imageDirection;
	imageDirection.SetIdentity();

	ImageType::Pointer synt_xray = ImageType::New();
	synt_xray = createSyntheticImage(imageOrigin, imageSpacing, imageSize, imageDirection);

	// Verify if the index of the high intensity voxel of the volume and the pixel in the image
	// are aligned with the source-point. 
	ImageType::IndexType imageIndex;
	imageIndex[0] = 0;
	imageIndex[1] = 0;
	imageIndex[2] = 0;
	ImageType::PointType imageTestPoint;
	synt_vol->TransformIndexToPhysicalPoint(imageIndex, imageTestPoint);

	std::cout << "Source point is in:" << sourcePoint << '\n';
	std::cout << "High intensity voxel is in:" << volumeTestPoint << '\n';
	std::cout << "Projected image pixel is in:" << imageTestPoint << '\n';
	std::cout << "The voxel center is between the source-point and the projected pixel center. So," <<
		" the voxel is expected to be projected in the pixel (a non null value).\n";

	// No transformation will be applied to the volume in order to test the most basic scenario
	TransformType::ParametersType parameters(6);
	parameters[0] = 0;
	parameters[1] = 0;
	parameters[2] = 0;
	parameters[3] = 0;
	parameters[4] = 0;
	parameters[5] = 0;
	TransformType::Pointer transform = TransformType::New();
	transform->SetParameters(parameters);

	InterpolatorType::Pointer interpolator = InterpolatorType::New();
	interpolator->SetTransform(transform);
	interpolator->SetThreshold(0); // Just consider voxeles above 0 value
	interpolator->SetFocalPoint(sourcePoint);

	FilterType::Pointer filter = FilterType::New();
	filter->SetInput(synt_vol);
	filter->SetDefaultPixelValue(0);
	filter->SetInterpolator(interpolator);
	filter->SetTransform(transform);

	filter->SetOutputOrigin(synt_xray->GetOrigin());
	filter->SetOutputDirection(synt_xray->GetDirection());
	filter->SetOutputSpacing(synt_xray->GetSpacing());
	filter->SetSize(synt_xray->GetLargestPossibleRegion().GetSize());

	filter->Update();
	
	ImageType::Pointer outputImage = ImageType::New();
	outputImage = filter->GetOutput();

	double outputPixelValue = outputImage->GetBufferPointer()[0];

	std::cout << "The ray passes vertically through the voxel and projects its " <<
		"value in the projected image. The output image value should be 1000. " <<
		"The actual projected value is: " << outputPixelValue << '\n';

	/*sourcePoint[0] += 0.5 * volumeSpacing[0];
	sourcePoint[1] += 0.5 * volumeSpacing[1];
	sourcePoint[2] += 0.5 * volumeSpacing[2];

	imageOrigin[0] += 0.5 * volumeSpacing[0];
	imageOrigin[1] += 0.5 * volumeSpacing[1];
	imageOrigin[2] += 0.5 * volumeSpacing[2];
	
	synt_xray->SetOrigin(imageOrigin);

	InterpolatorType::Pointer correctedInterpolator = InterpolatorType::New();
	correctedInterpolator->SetTransform(transform);
	correctedInterpolator->SetThreshold(0); // Just consider voxeles above 0 value
	correctedInterpolator->SetFocalPoint(sourcePoint);

	FilterType::Pointer correctedFilter = FilterType::New();
	correctedFilter->SetInput(synt_vol);
	correctedFilter->SetDefaultPixelValue(0);
	correctedFilter->SetInterpolator(correctedInterpolator);
	correctedFilter->SetTransform(transform);
	
	correctedFilter->SetOutputOrigin(synt_xray->GetOrigin());
	correctedFilter->SetOutputDirection(synt_xray->GetDirection());
	correctedFilter->SetOutputSpacing(synt_xray->GetSpacing());
	correctedFilter->SetSize(synt_xray->GetLargestPossibleRegion().GetSize());

	correctedFilter->Update();

	ImageType::Pointer correctedOutputImage = ImageType::New();
	correctedOutputImage = correctedFilter->GetOutput();

	double correctedOutputPixelValue = correctedOutputImage->GetBufferPointer()[0];

	std::cout << "The ray passes vertically through the voxel and projects its " <<
		"value in the projected image. The output image value should be 1000. " <<
		"The actual projected value is: " << correctedOutputPixelValue << '\n';*/
}
```

### Expected behavior
The pixel value of the DRR should be 1000, as the ray passes through the voxel with this intensity.

### Actual behaviour
The DRR pixel value is 0 because the ray casting considers the voxel value to have the left bottom corner in the ray path (not the centre as would be coherent with ITK image geometry). 

### Reproducibility
This happens every time this test is executed. This behaviour also happens for other volumes, but difference is usually hard to appreciate as it consists on the half of the volume voxel spacing in every direction. 

### Versions
This test was executed using ITK 4.13 and ITK 5.0. However, a bit of ITK history was searched and this ray-casting algorithm was introduced around 2010 and has not been changed since then.

### Environment
The test was executed in Windows 10 and with VisualStudio 2017 and QtCreator 4.9. Same behaviour was observed. 

### Additional Information
In order to correct this bug, several changes could be performed. The first one (but probably not the ideal one due to its complexity) would be to change the bounding corners to be coherent with ITK image geometrical properties. This solution would also require some condition changes in AdjustRayLength function (and possibly further in IntegrateAboveThreshold or IncrementVoxelPointers as well). 
The simplest solution we found is to compensate this geometry issues by shifting the source point and the image plane pixels by a value equal to half of the volume spacing in each direction. This would compensate for the volume incorrect position without requiring major code changes, emulating the ideal volume positioning.
In the test provided, there is a block comment at the end. In this comment, the changes required for the correct ray-casting are implemented. The ideal changes would be the ones performed in the block comment, but they should be executed internally (inside itkRayCastInterpolateImageFunction). Probably, when the source-point and the output pixel point are transformed, an additional transformation should be done.
The code posted below taken from itkRayCastInterpolateImageFunction.hxx (Evaluate function).
```C++
  OutputPointType transformedFocalPoint =
    m_Transform->TransformPoint(m_FocalPoint);

  DirectionType direction = transformedFocalPoint - point;

This code should be substituted by:
  OutputPointType transformedFocalPoint =
    m_Transform->TransformPoint(m_FocalPoint);

  // The ray casting computes the bounding corners as if the origin of the volume
  // would be in the left bottom corner of the first voxel. In order to be coherent
  // with ITK image geometry (origin in the centre of the first voxel), the following
  // adjustment must be done in focal point and output pixel point.
  transformedFocalPoint[0] += 0.5 * m_VoxelDimensionInX;
  transformedFocalPoint[1] += 0.5 * m_VoxelDimensionInY;
  transformedFocalPoint[2] += 0.5 * m_VoxelDimensionInZ;
  point[0] += 0.5 * m_VoxelDimensionInX;
  point[1] += 0.5 * m_VoxelDimensionInY;
  point[2] += 0.5 * m_VoxelDimensionInZ;

  DirectionType direction = transformedFocalPoint - point;
```
This correction would follow ITK image geometry standards creating a more accurate ray-casting.
An image representing the scene is attached.
![itkRayCastingTheoreticalScenario](https://user-images.githubusercontent.com/53933299/65750973-dff76b00-e109-11e9-8169-19b063704c61.jpg)

In addition, there is a part of code in this class posted below:
```C++
    // This section is to alter the start position in order to
    // place the center of the voxels in there correct positions,
    // rather than placing them at the corner of voxels which is
    // what happens if this is not carried out.  The reason why
    // x has no -0.5 is because this is the direction we are going
    // to iterate in and therefore we wish to go from center to
    // center rather than finding the surrounding voxels.

    m_RayVoxelStartPosition[1] += ( (int)m_RayVoxelStartPosition[0]
                                    - m_RayVoxelStartPosition[0] ) * m_VoxelIncrement[1] * m_VoxelIncrement[0]
                                  + 0.5 * m_VoxelIncrement[1] - 0.5;

    m_RayVoxelStartPosition[2] += ( (int)m_RayVoxelStartPosition[0]
                                    - m_RayVoxelStartPosition[0] ) * m_VoxelIncrement[2] * m_VoxelIncrement[0]
                                  + 0.5 * m_VoxelIncrement[2] - 0.5;

    m_RayVoxelStartPosition[0] = (int)m_RayVoxelStartPosition[0] + 0.5 * m_VoxelIncrement[0];
```
This section is supposed (according to the previous comment) to correct something similar to what this report is about, but it actually makes a counter-compensation, and takes the ray in the other way around. Nevertheless, this code is very helpful and gives great results in what concerns to voxel interpolation. As four voxels are considered in InitializeVoxelPointers, and taking into account which voxels are considered, these -0.5 compensations work perfectly. Consequently, this code section should not be removed, but should be documented for what it is used.
Moreover, there are many examples where volume centre is calculated in the following way:
```C++
  // Set the center of the image as the isocenter.
  isocenter[0] = imOrigin[0] + imRes[0] * static_cast< double >( imSize[0] ) / 2.0;
  isocenter[1] = imOrigin[1] + imRes[1] * static_cast< double >( imSize[1] ) / 2.0;
  isocenter[2] = imOrigin[2] + imRes[2] * static_cast< double >( imSize[2] ) / 2.0;
```
This piece of code was found in midas-journal-784/getDRRSiddonJacobsRayTracing.cxx. However, it is not the only location where volume centre is computed this way. These calculations would be correct again if the origin of the volume would be located in the left bottom part of the first voxel. As it is not like that, volume centre should be compensated subtracting half of the voxel size in each dimension, or calculate it using the image largest possible region instead.

**Comment by dzenanz** [comment]
@SimonRit @cyrilmory is anyone from RTK team willing to tackle this?

**Comment by SimonRit** [comment]
I'll have a look later, we had our own implementation of this code but we have removed it to avoid duplicates, see [here](https://github.com/SimonRit/RTK/blob/v1.4.0/code/rtkRayCastInterpolateImageFunction.hxx).

**Comment by SimonRit** [comment]
Thanks a lot for the detailed analysis @IbaiGenuaGamio. I have followed your suggestion to do a half voxel shift, I think this is the right ray to do it.
