### ISSUE TITLE
TestDriverInclude parameter checking inconsistency

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#1289]
Some parameters are checking for one extra `argc`,
https://github.com/InsightSoftwareConsortium/ITK/blob/2074c2f9e5ed3f087d0e2059f8e0e8992fcad7ef/Modules/Core/TestKernel/src/itkTestDriverInclude.cxx#L285
while seemingly equivalent others are checking for two extra `argc`:
https://github.com/InsightSoftwareConsortium/ITK/blob/2074c2f9e5ed3f087d0e2059f8e0e8992fcad7ef/Modules/Core/TestKernel/src/itkTestDriverInclude.cxx#L296

Is this an oversight, or is there some intention behind it?

**Comment by blowekamp** [comment]
Nice fine! The first "+1" looks like a bug to me since the flag consumes 2 parameters below.
