### ISSUE TITLE
[Important] Can cmake create "include" folder

### ISSUE THREAD

**Issue by thkvc** [InsightSoftwareConsortium/ITK#1325]
### Description

Enviroment: Windows 10
Compiler: Visual Studio 2019 Enterprise
Step: cmake-gui (3.15.4) -> config (default + BUILD_SHARED_LIB + BUILD_EXAMPLE) -> open with vs2019 -> build solution

My problem is that after the build is completed I only see the bin and lib directories, I don't see the include directory.
Can CMake copy all of .h files to a single include directory when building? If yes, how?

### Expected behavior

My project uses vs2019 and I expect that the output will be include, lib, bin. I also used some other libraries and they also have 3 similar folders. I need the include folder because I want to copy the itk library after build to other computers to use.

### Additional Information

I find that "vcpkg" can do this but I don't want to use it because it doesn't have the latest beta version.

**Comment by dzenanz** [comment]
What you expect (include, lib, bin) is produced by building the `INSTALL` target.

**Comment by thkvc** [comment]
OMG, you save me. thanks @dzenanz
