### ISSUE TITLE
Why MetaImageIOFactory are not created by default in BoneEnhancementExamples?

### ISSUE THREAD

**Issue by dpshamonin** [InsightSoftwareConsortium/ITK#1345]
Dear Devs,

I saw new remote module called **BoneEnhancement** in ITK 5.1. While playing with example **BoneEnhancementExamples**, I've noticed that **itk::ImageFileReader** crashing while attempting to read the *.mha image with exception:

> " Could not create IO object for reading file bone.mha\n Tried to create one of the following:\n    NiftiImageIO\n    NrrdImageIO\n  You probably failed to set a file suf..."

Discovered that **MetaImageIOFactory** is not created by default as was expected.

I can fix it by manually creating it using:
```
#include "itkMetaImageIOFactory.h"
itk::MetaImageIOFactory::RegisterOneFactory()
```

Why should I do it? All factories have to be created and registered with ImageFileReader, but I only see two image readers being available by default (**NiftiImageIO** and **NrrdImageIO**) in this particular example. 

Running the tests for ITK, I could see that tests with ImageFileReader are working.
Can you explain it? 

Thanks, Denis

**Comment by dzenanz** [comment]
The examples there only request [Nifti and NRRD](https://github.com/InsightSoftwareConsortium/ITKBoneEnhancement/blob/00f62b474a74079d04397bad881b080743f41b9d/examples/CMakeLists.txt#L5) IOs. Examples are separate from the rest of the module, and module itself (including tests) gets all of the IOs available in ITK.
