### ISSUE TITLE
Add ttype keyword parameter for NumPy conversion functions

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#1348]
Similar to the [functional ITK Python filter interfaces](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html#basic-examples), support passing a `ttype` keyword argument to the ITK NumPy interface functions. The will enable explicit specification of the type desired. For example:

```
ImageType = itk.Image[itk.RGBPixel[itk.UC], 3]
itk_image = itk.image_from_array(np_image, ttype=(ImageType,))
```

@hina-shah

**Comment by hina-shah** [comment]
This would be nice!
