### ISSUE TITLE
The N4biasFieldCorrection calls the modified time too many times.

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#1352]
This issue was discovered here: SimpleITK/SimpleITK#750

This is SimpleITK code to demonstrate the issue:
```
import re; import SimpleITK as sitk
img = sitk.Image([512,512], sitk.sitkUInt8)
x = img
img_mask = sitk.OtsuThreshold(x)
x = sitk.Cast(x, sitk.sitkFloat32)
corrector = sitk.N4BiasFieldCorrectionImageFilter()
c=  corrector.Execute(x, img_mask)
re.findall("^.*Time:.*", str(c),re.MULTILINE)
```
The resulting Modified Time: 1,087,445. If the image is double so size [1024,512] the resulting time stamp 2,136,021 That is still doubled!

This demonstrates that there are many "Modified" being called on a per pixel basis. This is inefficient and can lead to overflow with the global time stamp.

**Comment by blowekamp** [comment]
> I'm not sure as to the source of the issue but my guess would be the underlying B-spline fitting class which is used to generate the estimated bias field. Specifically, the reconstruction function employs an optimization trick specific to B-splines for which I use multiple images as temporary data structures. Would that be a possible culprit?

I suspect that there is some operation on a per-pixel basis calling an object "Modified". The location needs to be found inside the filter by monitoring object's "ModifiedTime" in a debugger or with print statements.

**Comment by ntustison** [comment]
Okay.  That makes sense although, off the top of my head, I can't imagine where something like that would be happening in the algorithm.  Is there a quick way to determine a general location within the code?

**Comment by blowekamp** [comment]
The trick will be to get the global modified time. It's a private member of `itk::TimeStamp`, but if an `itk::TimeStamp` object is created, it can be "Modified" then `GetMTime` called to get the next global time stamp.



> Okay. That makes sense although, off the top of my head, I can't imagine where something like that would be happening in the algorithm. Is there a quick way to determine a general location within the code?
The code will need to be search by inserting the above to get the global modified time while being execute. Hopefully an existing test with a trial image can be used. From a computer science perspective a binary search can be performed in O(log_2) time when compared to a linear search it is quicker :)

**Comment by ntustison** [comment]
I like that---that's pretty funny.   I'll put that on my to-do list and should get to it soon.  Thanks again.

**Comment by ntustison** [comment]
Okay, @blowekamp , I think I have a candidate but I'm hoping you can provide some input towards a possible solution.   The bias field estimate is represented by a B-spline grid of control points which is stored as an itk::Image data structure.  It is [updated at  each iteration for each resolution level](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx#L599-L609) and then at the last iteration of each resolution level, this bias field is ["refined"](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx#L243)---essentially the number of control points in each dimension is doubled to allow for a greater degree of fitting freedom for the upcoming resolution level.  If I print out the ``MTime()`` of this class member, it grows at, what seems to me, an alarming rate with both number of iterations and/or input image size.    If I added some bookkeeping, we could probably defer saving this class variable until the very end and circumvent this problem.  Sound like a plan?

**Comment by blowekamp** [comment]
> Sound like a plan?

Plan B: I make a PR #1352.

**Comment by ntustison** [comment]
Awesome.  Thanks @blowekamp.  And good to know about InsertElement().

**Comment by blowekamp** [comment]
I believe it is a problem with the VectorContainer class in general. All the STL like operations call Modify... not very suitable to working on point sets...
