### ISSUE TITLE
Update migration guide with Hough transform changes

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#136]
`typedef itk::HoughTransform2DCirclesImageFilter<ImageProcessingConstants::DefaultPixelType, ImageProcessingConstants::FloatPixelType> HoughTransformFilterType;` now fails to compile:

> 47>c:\misc\bluequartz\dream3d_plugins\imageprocessing\imageprocessingfilters\itkhoughcircles.cpp(193): error C2976: 'itk::HoughTransform2DCirclesImageFilter': too few template arguments

A sentence or two about reasoning, and a suggested solution should be added to _Class changes_ section of the [migration guide](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md#class-changes).

**Comment by N-Dekker** [comment]
@dzenanz  OK, I'll add a line or two on this topic to the migration guide.

By the way, this is the related commit:
https://github.com/InsightSoftwareConsortium/ITK/commit/06afe0fbd031da52630e107968b8d7862b4d53b2#diff-cd71664328a9fe41ea4b2c144e7ea9e5

**Comment by N-Dekker** [comment]
@dzenanz What about this one?

> With ITK 5.0, `HoughTransform2DCirclesImageFilter<TInputPixelType, TOutputPixelType, TRadiusPixelType>` no longer has a default argument for its last template parameter. Instead, users of the filter should now explicitly specify all three template arguments. Earlier versions of ITK assumed `TRadiusPixelType` to be equal to `TOutputPixelType`, but it appears that for `TRadiusPixelType`, a floating point type is often preferred, whereas for `TOutputPixelType`, an unsigned integer type is often more appropriate.
