### ISSUE TITLE
ITK failed to run 9 tests on release and debug configuration with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [InsightSoftwareConsortium/ITK#1364]
ITK failed to run 9 tests on release and debug configuration with MSVC on windows. It can be reproduced on latest master version bfe79f6 and it can be run pass on 70e65bb version. Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:
1.git clone http://itk.org/ITK.git D:\ITK\src
2.open VS2017 x86 command prompt as admin and browse to D:\ITK
3.set CL=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %CL%
4.mkdir build_x86 && pushd build_x86
5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..\src
6.msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild
7. ctest --build-config Release -V -R "itkImageFillBufferTest4.1"
   ctest --build-config Release -V -R "itkLargeMetaImageWriteReadTest1"
   ctest --build-config Release -V -R "itkLargeMetaImageWriteReadTest2"
   ctest --build-config Release -V -R "itkLargeMetaImageWriteReadTest3"
   ctest --build-config Release -V -R "itkLargeMetaImageWriteReadTest4"
   ctest --build-config Release -V -R "itkLargeTIFFImageWriteReadTest1"
   ctest --build-config Release -V -R "itkLargeTIFFImageWriteReadTest2"
   ctest --build-config Release -V -R "itkLargeTIFFImageWriteReadTest3"
   ctest --build-config Release -V -R "itkLargeTIFFImageWriteReadTest4"

The whole log file please see attachment.
[log_x86_test.log](https://github.com/InsightSoftwareConsortium/ITK/files/3776972/log_x86_test.log)

Acutal result:
Total Test time (real) = 476.50 sec

The following tests FAILED:
	611 - itkImageFillBufferTest4.1 (SEGFAULT)
	1132 - itkLargeMetaImageWriteReadTest1 (Failed)
	1133 - itkLargeMetaImageWriteReadTest2 (Failed)
	1134 - itkLargeMetaImageWriteReadTest3 (Failed)
	1135 - itkLargeMetaImageWriteReadTest4 (Failed)
	1266 - itkLargeTIFFImageWriteReadTest1 (Failed)
	1267 - itkLargeTIFFImageWriteReadTest2 (Failed)
	1268 - itkLargeTIFFImageWriteReadTest3 (Failed)
	1269 - itkLargeTIFFImageWriteReadTest4 (SEGFAULT)

**Comment by dzenanz** [comment]
Failure of these tests is expected, as private memory in 32-bit address space is limited to 2-3 GB, and these tests require more than that. If you want to get rid of the test failres, set `ITK_COMPUTER_MEMORY_SIZE` to 2, for example by passing `-DITK_COMPUTER_MEMORY_SIZE=2` on the command line when first invoking CMake.

**Comment by hjmjohnson** [comment]
@dzenanz We could also modify the CMakeLists.txt file to detect a 32 bit build and set ITK_COMPUTER_MEMORY to 2 in that case as the default behavior.

**Comment by dzenanz** [comment]
We could, but if someone accidentally chooses 32-bit build they would be unaware of any problems.
