### ISSUE TITLE
[Question] Compile ITK with gcc 9

### ISSUE THREAD

**Issue by tarnh** [InsightSoftwareConsortium/ITK#1371]
Dear ITK developers,

I currently need a OTB 6.2 superbuild. My distro ArchLinux has already switched over to gcc 9. Downgrading first seemed easy to me, but all packages in the main repos are now compiled to a newer version of libstdc++.

So I've tried to build https://github.com/InsightSoftwareConsortium/ITK/tree/release-4.13 with gcc-9, which currently fails [due to "deprecated copy" warnings](https://pastebin.com/vBpVaRiM). 

I assume that you are working on that.

How I can I patch the superbuild to compile with `-Wno-deprecated-copy` to fix my compilation problem now?

**Comment by thewtex** [comment]
This seems to be a duplicate of https://github.com/InsightSoftwareConsortium/ITK/issues/1302

@tarnh it would be worth the effort upgrading to ITK 5 in the meantime.

CC: @phcerdan

**Comment by tarnh** [comment]
Of course I'm using ITK 5 on my main system.
https://github.com/CNES/WASP is the culprit which pushes me to use the obsolete OTB 6.2.

**Comment by phcerdan** [comment]
@tarnh Are you compiling with `-Werror`? I am able to compile ITK with gcc9, despite those warnings.

**Comment by tarnh** [comment]
I'm building with an opaque "SuperBuild" script, so probably yes.

BTW: Do you have any experience in compiling HDF4? If not, this issue may be closed.
