### ISSUE TITLE
SmoothingRecursiveGaussianImageFilter with sharp discontinuity to background produces negative values in output

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#1425]
### Description

SmoothingRecursiveGaussianImageFilter, as for example, implemented in ANTs' SmoothImage https://github.com/ANTsX/ANTs/blob/master/Examples/SmoothImage.cxx produces negative values for images with an object in the foreground surrounded by "0" or some very small value produces negative values after smoothing.

### Steps to Reproduce

1. Grab http://www.bic.mni.mcgill.ca/~vfonov/icbm/2009/mni_icbm152_nlin_asym_09c_nifti.zip
2. ImageMath 3 extracted.nii.gz m mni_icbm152_t1_tal_nlin_sym_09c_mask.nii mni_icbm152_t1_tal_nlin_sym_09c.nii
3. SmoothImage 3 extracted.nii.gz 5 smooth.nii.gz 1 0
3. Observe negative values:
register smooth.nii.gz (set values under zero to be magenta)
![image](https://user-images.githubusercontent.com/3001850/69066433-4a80a500-09ef-11ea-8ec4-c703bce74c5d.png)

### Expected behavior

No negative values

### Actual behavior

Negative values

### Reproducibility

100%

### Versions

ANTs HEAD

### Environment

Linux Ubuntu 14.04

**Comment by blowekamp** [comment]
This may be expected for this implementation of the Gaussian. Here is the referenced paper:
Details of the implementation are described in the technical report: R. Deriche, "Recursively Implementing The Gaussian and Its Derivatives", INRIA, 1993, ftp://ftp.inria.fr/INRIA/tech-reports/RR/RR-1893.ps.gz

**Comment by gdevenyi** [comment]
Thanks, I suspected the implementation details might be the cause.

Unfortunately, I think this may cause some issues with registration, since RecursiveGaussian was set as the default for optimizers as of https://github.com/InsightSoftwareConsortium/ITK/commit/569a4701b740d849a1efe20c9fd76a928c645fbb it can create features which aren't actually present.

At least a documentation update is warranted, beyond that I'm not sure what to do about it in general.
