### ISSUE TITLE
VNL Valgrind defects

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#1438]
There are new valgrind defect related to recent changes in VNL to vnl_vector and vnl_matrix.

https://open.cdash.org/viewDynamicAnalysis.php?buildid=6220140

**Comment by blowekamp** [comment]
@hjmjohnson @dzenanz

**Comment by hjmjohnson** [comment]
I'll look at this soon (over the weekend).

**Comment by hjmjohnson** [comment]
FYI:  I did not get any failures when running ctest -D ExpermentalMemCheck on vxl.

More work is needed.

**Comment by blowekamp** [comment]
The referenced errors were from the same CentOS7 docker image as the other day. I also ran Valgrind on Ubuntu 18.04.3 LTS and got the same defects ( plus some not suppress libs ones too): https://open.cdash.org/viewDynamicAnalysis.php?buildid=6220955

Maybe there is something in the configuration file:
https://open.cdash.org/viewNotes.php?buildid=6221090

**Comment by hjmjohnson** [comment]
FYI:  I narrowed down the problem and have been able to replicate the problem.

Testing tomorrow should have a PR to fix this.

**Comment by hjmjohnson** [comment]
See https://github.com/vxl/vxl/pull/726,  Tracking down memory bug also identified a bug in the build process as well that was fixed.

**Comment by dzenanz** [comment]
Fixed by #1441.
