### ISSUE TITLE
Wrapping Typedefs ITKOptimizersBase fails on VS2017 LEGACY_REMOVE

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/ITK#1442]
On VS2017 (fully updated) I get the following error message:
cmd.exe /C "cd /D C:\src\ITK-Release\Wrapping\Typedefs\python && C:\src\ITK-Release\Wrapping\Generators\SwigInterface\swigwin-3.0.12\swig.exe -c++ -python -O -features autodoc=1 -py3 -Werror -w302 -w303 -w312 -w314 -w361 -w362 -w350 -w383 -w384 -w389 -w394 -w395 -w467 -w508 -w509 -o C:/src/ITK-Release/Wrapping/Modules/ITKOptimizers/ITKOptimizersBasePython.cpp -IC:/src/ITK-Release/Wrapping/Generators/SwigInterface/swig/share/swig/3.0.12/python -IC:/src/ITK-Release/Wrapping/Generators/SwigInterface/swig/share/swig/3.0.12 -IC:/src/ITK/Wrapping/Generators -IC:/src/ITK-Release/Wrapping/Typedefs/python -IC:/src/ITK-Release/Wrapping/Typedefs -outdir C:/src/ITK-Release/lib C:/src/ITK-Release/Wrapping/Typedefs/ITKOptimizersBase.i"
Assertion failed: Getattr(n, "sym:name"), file Modules/lang.cxx, line 1657
ninja: build stopped: subcommand failed.

The last checkout that works is:
https://github.com/InsightSoftwareConsortium/ITK/commit/f426a2a27b66d3fbb69ad3d31370d6e3205a7cb0

Suggesting that the error was introduced in
https://github.com/InsightSoftwareConsortium/ITK/commit/35865cadf56fb5350561e1dbdd6ddb2d5144830a

This bug persists in Master/Head today.

CMake options used
ITK_LEGACY_REMOVE = ON

I thought it was due to the removal of the conditional defined(ITK_WRAPPING_PARSER) in several places, but restoring them does not fix the issue.

**Comment by dzenanz** [comment]
I can reproduce this:
```text
1>------ Build started: Project: castxml (ExternalProjectTargets\castxml\castxml), Configuration: Debug x64 ------
2>------ Build started: Project: swig (ExternalProjectTargets\swig\swig), Configuration: Debug x64 ------
3>------ Build started: Project: ITKCommonCastXML, Configuration: Debug x64 ------
4>------ Build started: Project: ITKStatisticsCastXML, Configuration: Debug x64 ------
5>------ Build started: Project: ITKOptimizersCastXML, Configuration: Debug x64 ------
6>------ Build started: Project: ITKCommonSwig, Configuration: Debug x64 ------
7>------ Build started: Project: ITKStatisticsSwig, Configuration: Debug x64 ------
8>------ Build started: Project: ITKOptimizersSwig, Configuration: Debug x64 ------
9>------ Build started: Project: ITKOptimizersPython, Configuration: Debug x64 ------
9>Generating ITKCostFunctionsPython.cpp, ../../../lib/ITKCostFunctionsPython.py
9>Generating ITKOptimizersBasePython.cpp, ../../../lib/ITKOptimizersBasePython.py
9>Assertion failed: Getattr(n, "sym:name"), file Modules/lang.cxx, line 1657
9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3.
9>Done building project "ITKOptimizersPython.vcxproj" -- FAILED.
========== Build: 8 succeeded, 1 failed, 107 up-to-date, 0 skipped ==========
```
I guess that this is a bug in SWIG.

**Comment by dzenanz** [comment]
The file mentioned in the error message is `C:\Dev\ITK-2017\Wrapping\Generators\SwigInterface\swigwin-3.0.12\Source\Modules\lang.cxx`.

**Comment by thewtex** [comment]
I have a patch for this coming :-) -- will push after I have finished testing variants.

**Comment by thewtex** [comment]
Our Windows Azure Python is green again :green_heart: :tada:
