### ISSUE TITLE
ITK 4.13.0 build from source fails to download castxml-linux.tar.gz 

### ISSUE THREAD

**Issue by jhein32** [InsightSoftwareConsortium/ITK#145]
# Description

When building ITK 4.13.0 (gcc 6.4.0, CentOS 7, using the Easybuild frame work https://easybuilders.github.io/easybuild/) I got a file not found error (404) on https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=84c2851a4df419b5834114bbfafa8d3e&name=castxml-linux.tar.gz, which the build procedure wants to download.  If I tell EasyBuild to build version 4.13.1 it builds an ITK installation, without any issue.

I tried this for a couple of days - the issue appears persistent.  

# Questions
We like to ask a few questions:

* Has the file indeed "vanished" or is it a temporary issue.
* If it has vanished, is it normal that these download failures happen once a new ITK version is released?  We are speaking about one subversion down from the current release.
* Is it possible to do an "offline" installation of ITK, where all required source tarballs are downloaded up front and "cached" somewhere that the ITK installation procedure can pick them up?

Let us know if you need more info.  Thanks for reading.

-----
Edited for spelling

**Comment by thewtex** [comment]
Hi @jhein32 ,

Please try ITK 4.13.1; this issue was addressed there.


> Has the file indeed "vanished" or is it a temporary issue.

The server had to be taken offline. We moved to a different server.

> If it has vanished, is it normal that these download failures happen once a new ITK version is released? We are speaking about one subversion down from the current release.

This should be a rare event.

> Is it possible to do an "offline" installation of ITK, where all required source tarballs are downloaded up front and "cached" somewhere that the ITK installation procedure can pick them up?

To help Linux distributions, etc., we maintain an `ITK_FORBID_DOWNLOADS` CMake configuration variable. Set this variable, and it will not fetch from the network. However, you then need to satisfy the dependencies with your package manager.

HTH,
Matt

CC: @jeffbaumes @zachmullen @mgrauer

**Comment by thewtex** [comment]
@jhein32 PS. Thanks for maintaining support for ITK in Easybuild!

**Comment by boegel** [comment]
@thewtex Where can we find detailed information about which dependencies ITK requires, and how we can tell ITK where they are installed?

**Comment by thewtex** [comment]
@boegel By default, ITK ships all required dependencies. To use your package manager, enable the CMake flags `ITK_USE_SYSTEM_*`,

```
git clone https://github.com/InsightSoftwareConsortium/ITK
cd ITK
git grep ITK_USE_SYSTEM
```

These variables can be set individually. Some dependencies are rare -- to enable the commonly provided ones, e.g. zlib, jpeg, etc, set `ITK_USE_SYSTEM_LIBRARIES` to `ON`.

To specify where the are, pass the typical CMake variables for the [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=i) command, usually `<dep>_DIR` for the directory that contains the CMake [project configuration file](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html). For non-CMake projects, you may need to pass in the install prefix, include directory or library.

**Comment by boegel** [comment]
Thanks for the feedback @thewtex!

It seems like this is the right way to go for us.

One scary thing I noticed is that ITK by default downloads a pre-built FFTW. Am I getting that right? That's definitely *not* what we want...

**Comment by boegel** [comment]
@thewtex I'm trying to get this working by setting the necessary `-DITK_USE_SYSTEM*` and enabling `-DITK_FORBID_DOWNLOADS=ON`.

The latter seems to be working, i.e. it is generating CMake errors, but it's not clear to me how I can seed in a pre-downloaded `BridgeNumPy`:

```
CMake Error at CMake/ITKDownloadSetup.cmake:14 (message):
  Attempted to download Module_BridgeNumPy when ITK_FORBID_DOWNLOADS is ON
Call Stack (most recent call first):
  CMake/ITKModuleRemote.cmake:136 (itk_download_attempt_check)
  Modules/Remote/BridgeNumPy.remote.cmake:2 (itk_fetch_module)
  Modules/Remote/CMakeLists.txt:6 (include)


CMake Error at CMake/ITKModuleRemote.cmake:140 (message):
  error: could not find git for clone of BridgeNumPy
Call Stack (most recent call first):
  Modules/Remote/BridgeNumPy.remote.cmake:2 (itk_fetch_module)
  Modules/Remote/CMakeLists.txt:6 (include)

-- Configuring incomplete, errors occurred!
```

How can I fix this? I'm already pre-downloading `BridgeNumpy` into `Modules/Remote/BridgeNumpy`.
Also, can I somehow tell CMake not to try and download `BridgeNumpy` (or should it detect it automatically)?

**Comment by thewtex** [comment]
@boegel there are a few options:

1. Pre-download `BridgeNumPy` into `Modules/External/BridgeNumPy`. Set `Module_BridgeNumPy=ON` in the CMake Configuration. Remove `ITK/Modules/Remote/BridgeNumPy.remote.cmake` for good measure.

2. Set `Module_BridgeNumPy=OFF` in the ITK CMake configuration.

3. Package ITK 5 Beta 1 -- the NumPy bridge has been integrated into the main repository in ITK 5.

**Comment by boegel** [comment]
@thewtex What side-effect does `-DModule_BridgeNumPy=OFF` have, how crippled will the result `ITK` installation be?

W.r.t. your earlier comment on `FFTW`: are there any good benchmarks I can run for the ITK installation, preferably something that heavily relies on FFTW?

**Comment by thewtex** [comment]
The NumPy bridge enables conversion of ITK images to and from NumPy arrays. If your users apply Python a lot, they will likely need it.

We have some other performance benchmarks, but FFT installation benchmarks do not come to mind. In general, FFTW is twice as fast as the VNL implementation. In ITK 5, it is possible to build against MKL or cuFFTW, if that is of interest.
