### ISSUE TITLE
MetaDataDictionary::Print only prints [UNKNOWN_PRINT_CHARACTERISTICS]

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#1454]
### Description

For any MetaDataObject calling `obj->Print(std::cout)` produces "[UNKNOWN_PRINT_CHARACTERISTICS]" on the console. 

https://github.com/InsightSoftwareConsortium/ITK/blob/60469760ee13f48b265ca7424e3e9fd652672710/Modules/Core/Common/include/itkMetaDataObject.hxx#L63-L69

### Expected behavior

For `itk::Object` base objects the `Print` method should be used while those which support `operator<<`, that method should be used.

It is expected to be able to iterate over the metadata dictionary and print the key and value of all types and get descriptive output.

**Comment by phcerdan** [comment]
Facing this as well...

By the way @blowekamp, it would be absolutely fantastic to transfer some of the SimpleITK great goodies on handling metadata dictionaries to ITK wrappings.
