### ISSUE TITLE
Disable CMake user registry lookup by find_package

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITK#1469]
### Description

Configuring ITK on a system where unrelated build exported their build tree using [export(PACKAGE)](https://cmake.org/cmake/help/latest/command/export.html#command:export) can have unintended side effect.

For example, on my system the package registry contains the following:

### Steps to Reproduce

Configure ITK with `ITK_USE_SYSTEM_EIGEN` set to `ON` on a system where `Eigen3` is found in the cmake registry:

```
ls -1 ~/.cmake/packages/
Eigen3
```

### Expected behavior

Find Eigen3 installed with the package manager or fail if not available.

### Actual behavior

`CMakeCache.txt` has the following value:

```
Eigen3_DIR:PATH=/home/jcfr/Projects/SlicerSALT-Release-Qt5/Slicer-build/E/Eigen3
```

### Proposed solution

Set `CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY` to `1`

See https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#disabling-the-package-registry

### Versions

Observed with d2e511437d

### Environment

Any

**Comment by phcerdan** [comment]
Closed in #1470
