### ISSUE TITLE
TiffImageIO z spacing

### ISSUE THREAD

**Issue by zivy** [InsightSoftwareConsortium/ITK#148]
When writing a 3D image to file using TiffImageIO, the z spacing is lost (set to 1). 

This is related  to https://github.com/SimpleITK/SimpleITK/issues/586

**Comment by zivy** [comment]
Not sure about OpenSlide, they had a discussion about supporting 3D about three years ago (https://github.com/openslide/openslide/issues/166) and the project isn't too active, at least on github (https://github.com/openslide/openslide/graphs/code-frequency).

**Comment by nslay** [comment]
This also happens when writing individual DICOM slices/files from a 3D DICOM volume (it clobbers the SpacingBetweenSlices tag "0018|0088" with value 1.0, even if it was there before and not 1.0). My workaround (rather tedious) is to promote the 2D image slice to a 3D volume with a singleton z dimension and extracting/setting the spacing, direction cosines and origin... and *then* saving the 3D slice to a DICOM file.

**Comment by nslay** [comment]
P.S. openslide, to my knowledge, does not support writing slides/tiffs. If it did, ITKIOOpenSlide would have supported that ability.

**Comment by maekclena** [comment]
There is no standard way of storing a Z spacing in TIFF but the format allows private tags. For example, MIPAV handles [ZResolution](https://mipav.cit.nih.gov/documentation/api/gov/nih/mipav/model/file/FileTiff.html#ZRESOLUTION) and GeoTIFF defines [ModelPixelScaleTag](http://geotiff.maptools.org/spec/geotiff2.6.html#2.6).

For DICOM slices, here's an example to preserve metadata:
```c++
itk::GDCMImageIO::Pointer gdcmIO = itk::GDCMImageIO::New();
ReaderType::DictionaryRawPointer dict = (*(reader->GetMetaDataDictionaryArray()))[sliceNumber];
gdcmIO->SetMetaDataDictionary(*dict);
writer->SetImageIO(gdcmIO);
writer->UseInputMetaDataDictionaryOff();
writer->SetInput(slice2D);
writer->Update();
```

**Comment by maekclena** [comment]
Some more informations: [VTK](https://gitlab.kitware.com/vtk/vtk/blob/master/IO/Image/vtkTIFFReader.cxx#L856) uses Zeiss 3D TIFF and [MeVisLab](http://mevislabdownloads.mevis.de/docs/2.8/MeVisLab/Resources/Documentation/Publish/SDK/GettingStarted/ch12s07.html) uses SGI 3D TIFF.

**Comment by blowekamp** [comment]
There are also a couple ImageJ TIFF private tags which can contain 3D information: https://github.com/imagej/ImageJA/blob/master/src/main/java/ij/io/TiffDecoder.java#L43-L44

I can't seem to find a specification for them right now.

**Comment by blowekamp** [comment]
More info about these tags in this ITK discourse thread:
https://discourse.itk.org/t/unknown-tags-reading-tiff/1719/2
