### ISSUE TITLE
gdcmSerieHelper.h not found on Ubuntu 18.04 despite ITKGDCM module enabled

### ISSUE THREAD

**Issue by KrisThielemans** [InsightSoftwareConsortium/ITK#1493]
### Description
Installing ITK 5.0.1 via conda leads to a compilation problem when using gdcm IO despite a system gdcm being present. See https://github.com/conda-forge/libitk-feedstock/issues/42

This seems to say that in whatever way ITK was built for conda, it doesn't find the system GDCM. Nevertheless, `/home/sirfuser/miniconda3/lib/cmake/ITK-5.0/ITKConfig.cmake` sets `ITK_MODULES_ENABLED` to include `ITKGDCM`.

### Steps to Reproduce
```
conda install libitk-dev
sudo apt install libgdcm2-dev
git clone https://github.com/UCL/STIR.git
mkdir build; cd build; cmake ../STIR; make
```
### Actual behavior
output
```
In file included from /home/sirfuser/devel/STIR/src/IO/ITKImageInputFileFormat.cxx:41:0:
/home/sirfuser/miniconda3/include/ITK-5.0/itkGDCMSeriesFileNames.h:25:10: fatal error: gdcmSerieHelper.h: No such file or directory
 #include "gdcmSerieHelper.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
This is despite `/usr/include/gdcm-2.8/gdcmSerieHelper.h` existing.

### Reproducibility

always
### Versions
5.0.1

### Environment
Ubuntu 18.04, cmake version 3.13.1

**Comment by thewtex** [comment]
ITK provides GDCM by default, and a quick glance at the conda libitk recipe indicates that this GDCM is used in the conda recipe.

Where is the relevant `find_package(ITK [...]` of the dependent project?

**Comment by blowekamp** [comment]
Are you using windows?

**Comment by blowekamp** [comment]
There are some know issues with Conda not fixing up the paths in the CMake files correctly, but that is known to only happen on windows:
https://github.com/conda-forge/libitk-feedstock/issues/43

It may be working grep-ing around the installation director as done in the above issue to see if something similar is occurring on your platform.

**Comment by KrisThielemans** [comment]
thanks for picking this up. I'll try to reproduce this with current conda on Ubuntu 18.04 using our VM https://doi.org/10.5281/zenodo.3552234

[Our `find_package` ](https://github.com/UCL/STIR/blob/29133a3ffa690b444894b4392aa710e8bb33a42e/CMakeLists.txt#L94-L97) is quite simple :-)
```cmake
   find_package(ITK QUIET)
   if (ITK_FOUND)
      include(${ITK_USE_FILE})
   endif()
```
We use `target_link_libraries` [here](https://github.com/UCL/STIR/blob/29133a3ffa690b444894b4392aa710e8bb33a42e/src/IO/CMakeLists.txt#L89) but this is a compilation error, so I guess that line is irrelevant.

**Comment by blowekamp** [comment]
It looks like you are including "itkGDCMSeriesFileNames.h" in the project, which includes "gdcmSerieHelper.h".  This does not follow best practices of encapsulation, this PR #1768 addressed that issue.

The Conda-forge has two packages, `libitk` and `itk-devel`. I believe the GDCM "Headers" component used by GDCM. This PR should address it: 
conda-forge/libitk-feedstock#44

**Comment by KrisThielemans** [comment]
@blowekamp both PRs look good to me. thanks a lot!

@rijobro, maybe we can try the new `const` `itk-devel` package once that PR is merged.

**Comment by dzenanz** [comment]
That PR is merged. Reopen if it didn't fix the issue.
