### ISSUE TITLE
std::defaultfloat compilation error

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#1498]
This compilation error is occurring on the dashboard:

https://open.cdash.org/viewBuildError.php?buildid=6254656

Compilation error:
/home/kitware/Dashboards/TestsModules/IO/ImageBase/include/itkImageSeriesReader.hxx:444:70: error: 'defaultfloat' is not a member of 'std'
                           << " Deviation of:" << spacingDeviation << std::defaultfloat);

**Comment by blowekamp** [comment]
@vfonov @dzenanz

**Comment by vfonov** [comment]
looks like this version of gcc doesn't have this patch integrated: https://gcc.gnu.org/ml/gcc-patches/2014-03/msg01505.html

**Comment by vfonov** [comment]
so, I can include <iomanip> and use std::resetiosflags or just disable increased precision in the warning message...

**Comment by blowekamp** [comment]
I think using `resetioflags` would be best. Thank for following up!

**Comment by vfonov** [comment]
it is resolved, I hope

**Comment by thewtex** [comment]
*dash5ubuntu*'s Git *origin* has been updated, so it should report to the dashboard tomorrow.

**Comment by blowekamp** [comment]
closed by #1499, error is no longer on dashboard.
