### ISSUE TITLE
ConnectedComponentImageFilter default background value inconsistent with documentation

### ISSUE THREAD

**Issue by vicory** [InsightSoftwareConsortium/ITK#1500]
Commit d9e6b51fb9b2ccd4df06579c2ed7bb7487e80567 changed the default background value in the connected components filter from NumericTraits< OutputPixelType >::ZeroValue() to NumericTraits< OutputPixelType >::NonpositiveMin(). If using a signed pixel type this is inconsistent with the filter's documentation:
 https://github.com/InsightSoftwareConsortium/ITK/blob/d4ff96b9ecf16716a22b5d29caabf6d4d4bdb36e/Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.h#L35

and can cause breakages in code that rely on that default behavior.

I'm happy to make either change (default value or documentation) myself, just wanted confirmation on which is the desired behavior.

**Comment by dzenanz** [comment]
I think it is pretty rare to have connected components' output as a signed type, so it will not matter much.

But if we use the current default more values are possible before arithmetic overflow, so I slightly prefer updating the documentation.

@blowekamp @hjmjohnson?

**Comment by blowekamp** [comment]
Does Slicer use a signed integer for their label type?

**Comment by blowekamp** [comment]
I also have SimpleITK instantiated with signed integers. I'd prefer to restore the value to 0.

**Comment by dzenanz** [comment]
I am fine with that too.

**Comment by thewtex** [comment]
+1 for a `0` default for the background value.

**Comment by hjmjohnson** [comment]
I agree with 0 value for default background value.
