### ISSUE TITLE
"Threads::Threads" alias not found.

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#1502]
### Description

When configuring SimpleITK against a build tree of ITK I get the following configuration error:

CMake Error at Testing/Unit/CMakeLists.txt:94 (add_executable):
  Target "SimpleITKUnitTestDriver5" links to target "Threads::Threads" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

This appears to be coming from the update to google test with this line:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/cmake/internal_utils.cmake#L187

This is causing the following to be generated in `ITKTargets.cmake`:
# Import target "GTest::GTest" for configuration "Release"
set_property(TARGET GTest::GTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GTest::GTest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "Threads::Threads"
  IMPORTED_LOCATION_RELEASE "/scratch/blowekamp/ITK/lib/libitkgtest-5.1.a"
  )

The `Threads::Threads` alias is part of CMake's [FindThreads](https://cmake.org/cmake/help/v3.1/module/FindThreads.html).

**Comment by dzenanz** [comment]
Why is this part of 4.13.3 milestone? Google test was updated in master.

**Comment by blowekamp** [comment]
Corrected to the next RC, hopefully it can be addressed by then.

**Comment by blowekamp** [comment]
The easiest thing to do would be just to set "gtest_disable_pthreads" to off. A proper CMake exporting which combine the old variables of ITK-style with the newer target properties used here in Google test would be error prone for myself and would require a CMake guru to do it properly.

**Comment by dzenanz** [comment]
> set "gtest_disable_pthreads" to ON

Sounds good. Why does GTest even want `pthreads`?

**Comment by blowekamp** [comment]
I know it's used here for "death tests":
https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-tests

So we are not using that.

**Comment by blowekamp** [comment]
closed by #1503.
