### ISSUE TITLE
Transform Type in ResampleImageFilter forces Input and Output dimensions to be same.

### ISSUE THREAD

**Issue by HaaPut** [InsightSoftwareConsortium/ITK#1512]
### Description

Why does transform type [here](https://github.com/InsightSoftwareConsortium/ITK/blob/f15a14b3cacdc04eb20edaa225a730769cd89612/Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h#L123) force both input and output dimension to be same?  

I have a custom transform which maps images to to a higher dimensional feature space and I would like to use ResampleImageFilter. I understand that I can defined my own ResampleFilter, but is there a reason why  this is defined as it is?  

### Expected behavior

```
  static constexpr unsigned int OutputImageDimension = TOutputImage::ImageDimension; 
  using TransformType = Transform<TTransformPrecisionType, Self::OutputImageDimension, Self::InputImageDimension>;
```
### Actual behavior

```
  using TransformType = Transform<TTransformPrecisionType, Self::ImageDimension, Self::ImageDimension>;
```

**Comment by dzenanz** [comment]
Option: try changing it to fit your expectation and see what errors you encounter.

**Comment by HaaPut** [comment]
@dzenanz  Well.. one runs into quite a few errors..  [here](https://github.com/HaaPut/RectangularTransformResampling) is a working example after taking care of them!
If you guys think that this should be the default behavior I can make a PR. Apart from the changes required in ResampleImageFilter. I think assumption of square transform in [EnlargeRegionOverBox](https://github.com/HaaPut/RectangularTransformResampling/blob/bfce3296aa4a75dad95685af6fb212d14da2444f/include/itkMyImageAlgorithm.hxx#L188) is a separate (but very similar) bug. This could be a separate PR?

**Comment by dzenanz** [comment]
PRs are very welcome! "assumption of square transform" can be a different commit, or a different PR - it is up to you.
