### ISSUE TITLE
StoreNonPixelDataInImage in ITKExamples not working

### ISSUE THREAD

**Issue by jues** [InsightSoftwareConsortium/ITK#1524]
### Description

StoreNonPixelDataInImage in ITKExamples not working, `reader->GetMetaDataDictionary()` can't get the "ASimpleFloat" key and value.

### Actual behavior

```none
```

### Reproducibility

100%

### Versions

ITK 5.1

### Environment

win10, vs2019 16.4

**Comment by jues** [comment]
just need to add `reader->Update();`

**Comment by thewtex** [comment]
> just need to add reader->Update();

@jues could you please create a pull request?
