### ISSUE TITLE
ITK wrap python: module machine type 'x64' conflicts with target machine type 'x86'

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITK#1558]
I want to compile ITK from source and wrap with python. But the following bug happen:
![4](https://user-images.githubusercontent.com/29271051/72202455-acfb9c00-349a-11ea-9db6-e57760cb0464.PNG)

My environment is:
window 10 64 bit
vs 2015 64 bit
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
cmake 3.16.0-rc4

Any suggestion is appreciated!

**Comment by dzenanz** [comment]
Your Python build is 32-bit. You need 64-bit Python/Anaconda install if you want to build ITK as 64-bit.

**Comment by thewtex** [comment]
Follow-up discussion is here: https://discourse.itk.org/t/itk-wrap-python-compile-error/2606/3
