### ISSUE TITLE
module 'itk' has no attribute 'GPUDemonsRegistrationFilter'

### ISSUE THREAD

**Issue by qiang-zhang-neu** [InsightSoftwareConsortium/ITK#1570]
I have compiled ITK from the source, and I set the module ITK_USE_GPU on. I wrap the ITK with python. The compileing is OK, and some examples is OK, just like: `itk.Image[type, Dimension]`. 

However, when I want to use gpu registration, it reported: `module 'itk' has no attribute 'GPUDemonsRegistrationFilter'`. What should I do to use GPUDemonsRegistrationFilter? Moreover, could somebody provide an example to use GPU in registration?

**Comment by thewtex** [comment]
`GPUDemonsRegistrationFilter` is not currently wrapped.

Further work on ITK GPU OpenCL updates will occur in the [OpenCL](https://github.com/InsightSoftwareConsortium/ITKOpenCL) module / repository -- this will allow us to move forward with backwards incompatible improvements to the OpenCL infrastructure.

*Experimental* Python packages for GPU-based registration on Linux are available with `pip install itk-elastix-opencl`. A reproducible Jupyter notebook available in free cloud resources [can be found here](https://www.paperspace.com/temmx3m64/notebook/prdfn7bsz). For more information, see

  https://github.com/InsightSoftwareConsortium/ITKElastix
