### ISSUE TITLE
ComposeImageFilter is not wrapped for complex types

### ISSUE THREAD

**Issue by vicory** [InsightSoftwareConsortium/ITK#1581]
From what I can tell, ComposeImageFilter is the preferred method for combining real + imaginary images into a single complex image but it is not currently wrapped for complex data types. Adding this would make it easier to work with complex-valued images in Python. 

I did a quick test with a local build where I added wrapping for the float->complex float scenario and it seems to be working. Is there any reason not to wrap the filter for complex types?

**Comment by dzenanz** [comment]
The most likely reason is oversight. Please propose a PR which adds this wrapping.
