### ISSUE TITLE
Loading of JPEG-compressed CT DICOM volume slowed down in ITK-v5.1rc01

### ISSUE THREAD

**Issue by lassoan** [InsightSoftwareConsortium/ITK#1586]
### Description

We've upgraded 3D Slicer to ITK-v5.1rc01 and we noticed this regression.

Loading of JPEG-compressed DICOM images take 5-10x longer than before. This is important because previously loading time was about 10sec, which was users easily waited, but minutes for loading a single image is just too long.

### Steps to Reproduce

I can provide an anonymized data set on request but it is not for public sharing but this should be reproducible with all 12-bit JPEG volumes.

### Expected behavior

Image is loaded in 10 seconds.

### Actual behavior

Image is loaded in minutes.

### Reproducibility

100% reproducible.

### Versions

ITK-v5.1rc01

### Environment

Windows, Visual Studio 2015

**Comment by dzenanz** [comment]
@malaterre is this a regression in GDCM, or perhaps something else?

**Comment by issakomi** [comment]
This might be the same issue as here,
for _bits stored < bits allocated_ there is a change 4.13.1 -> 4.13.2

https://github.com/InsightSoftwareConsortium/ITK/issues/1542

Or may be it is not related, if not - no idea, my rather recent fork doesn't have problems with JPEG, OMHO, i can not easy reproduce just now, sorry.

**Comment by lassoan** [comment]
Yes, this is the same issue as #1542. Let's continue the discussion there.
