### ISSUE TITLE
python-itk: module 'itk' has no attribute 'GPUImage'

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITK#1605]
I want to use the GPU based itk for registrdation. Thus, I compile the itk from the source code, and set the ITK_USE_GPU to ON. The compiling is OK.
![捕获](https://user-images.githubusercontent.com/29271051/74302210-a198da80-4d90-11ea-88cc-d15281ba1a25.PNG)

The itk can be imported in python:

>>> import itk
>>> itk.Image[itk.F, 3]
<class 'itkImagePython.itkImageF3'>

However, when I want to import the GPU module, bug is reported:

>>> itk.GPUImage[itk.F, 3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\ITK_gpu\lib\site-packages\itkLazy.py", line 48, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'GPUImage'

Also, module 'itk' has no attribute 'GPUDemonsRegistrationFilter'. 
How can I use GPU based itk for registration in python? Could somebody provide a demo?

**Comment by thewtex** [comment]
There are alpha Python packages available on Linux [as described here](https://github.com/InsightSoftwareConsortium/ITKElastix) and [demo here](https://www.paperspace.com/temmx3m64/notebook/prdfn7bsz).
