### ISSUE TITLE
Hypersensitive "Non unform sampling or missing slices detected" warning

### ISSUE THREAD

**Issue by lassoan** [InsightSoftwareConsortium/ITK#1607]
### Description

ITK's new non-uniform "sampling" detection (actually, slice spacing) is so sensitive that it is useless. It also generates so many warnings that it floods the log and slows down DICOM loading.

Example:

WARNING: In c:\d\s42d\itk\modules\io\imagebase\include\itkImageSeriesReader.hxx, line 440
ImageSeriesReader (000001F94F144440): Non unform sampling or missing slices detected , expected 0.3 got: 0.3

The compared values are 0.29999999999999716 and 0.29999999999999999 (absolute difference is 2.8310687127941492e-15).

### Steps to Reproduce

Load any DICOM series - but to give a specific example:
https://wiki.cancerimagingarchive.net/display/Public/QIN-HEADNECK
TCGA-BA-4074

### Expected behavior

Only give a warning when spacing variation is non-negligible.

If the difference is magnitudes lower then the expected slice spacing then I definitely don't want to see any warning and don't want the image to be considered as having varying slice spacing.

### Actual behavior

A warning is logged for each slice.

### Reproducibility

100%

### Versions

Latest ITK 5.0.1rc01

### Environment

Windows.

**Comment by vfonov** [comment]
didn't we address this in #1476 ?

**Comment by dzenanz** [comment]
Perhaps instead of AlmostEquals use [FloatAlmostEqual](https://itk.org/Doxygen/html/namespaceitk_1_1Math.html#ae9f0d6137957033eecb66c0e1356d022) with some medium tolerance (1e-6)?

**Comment by vfonov** [comment]
I suppose it will depend on the context?

**Comment by dzenanz** [comment]
Perhaps use a more strict tolerance (e.g. 1e-14)?

**Comment by vfonov** [comment]
we can also disable the warning completely and keep metadata information only

**Comment by dzenanz** [comment]
Yes, that is one way too.

**Comment by lassoan** [comment]
I use the latest release candidate (ITK v5.1-rc01), which does not have this yet.

I've cherry-picked the content of https://github.com/InsightSoftwareConsortium/ITK/pull/1476 but it did not help much. It still pollutes the log with hundreds of these messages (but at least it now shows the "deviation", too):

WARNING: In c:\d\s42rdi\itk\modules\io\imagebase\include\itkImageSeriesReader.hxx, line 444
ImageSeriesReader (0000025699395090): Non uniform sampling or missing slices detected , expected 0.3 got: 0.3 Deviation of:2.8310687127941e-15

Things that still need to be fixed:

1. The current implementation still does not detect significant spacing variability correctly. If difference of slice spacing is less than 1% of the expected slice spacing then we should not report this (because if computed interpolated values at the real slice position then such small difference in slice position would not make any difference in the resulting voxel value). If we want to be very strict then we can make the threshold 0.1%; or if we suspect that there are paranoid ITK users then make this % threshold value configurable with a member variable.

2. Showing a warning message for each slice is not useful (maybe add a verbose flag, default off, to enable it). One log message at the end could tell that "Variation of slice spacing is above the permitted threshold for x of N slices. Expected slice spacing is y, average difference is z, maximum difference is w".

3. Terms are somewhat confusing:
- "Non uniform sampling or missing slices detected" => I'm not sure what "sampling" this message is talking about; I think it should be "Non uniform slice spacing or missing slices detected"
- "expected 0.3 got: 0.3 Deviation of:2.8310687127941e-15" => this suggests that we compute some kind of "standard deviation", while this is actually a simple "difference" or "error"; this would be better: "expected 0.3, got: 0.3, difference: 2.8310687127941e-15"

**Comment by aksg87** [comment]
Hello, I am getting this warnings but confirmed the outputs are correct. Is there a clean way to turn this warning off? Thank you!

**Comment by lassoan** [comment]
What is the "maximum non-uniformity" value that you get?
Can you share the data set so that we can verify that it is indeed correct?

You can set the comparison threshold in SpacingWarningRelThreshold property (see https://github.com/InsightSoftwareConsortium/ITK/pull/1616/files).

**Comment by hksonngan** [comment]
Hi,
I got the same issue. Any idea to fix this?

**Comment by dzenanz** [comment]
Which version of ITK are you using? It should have been fixed by #1616.

**Comment by hksonngan** [comment]
Thanks. I update my ITK and it fixed

**Comment by Sudayberry** [comment]
> Hi all. Sorry for commenting on a closed issue, please let me know if this should go somewhere else.
> 
> I'm getting this warning for many (all?) of the images in [this BraTS dataset](https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification). The maximum nonuniformities seem to be between 1e-4 and 1e-3, e.g. 0.000738335. Do you know if there is a way to change the SpacingWarningRelThreshold in SimpleITK? @blowekamp
hello


> Hi all. Sorry for commenting on a closed issue, please let me know if this should go somewhere else.
> 
> I'm getting this warning for many (all?) of the images in [this BraTS dataset](https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification). The maximum nonuniformities seem to be between 1e-4 and 1e-3, e.g. 0.000738335. Do you know if there is a way to change the SpacingWarningRelThreshold in SimpleITK? @blowekamp

hi, I have the same problem with you when I preprocess the BraTS dataset 2021. Is it serious? Can I ignore the warning?

**Comment by Sudayberry** [comment]
Hi, I have the same problem with you when I preprocess the BraTS dataset 2021. Is it serious? Can I ignore the warning?
@fepegar

**Comment by vfonov** [comment]
> Hi, I have the same problem with you when I preprocess the BraTS dataset 2021. Is it serious? Can I ignore the warning? @fepegar

you can ignore the warning.
