### ISSUE TITLE
itk:GPUImage::Graft cannot access protected member declared in class itk::GPUImage

### ISSUE THREAD

**Issue by zhang-qiang-github** [InsightSoftwareConsortium/ITK#1613]
I am starting my registration project. I modify the code: Examples/RegistrationITKv4/DeformableRegistration16, and it work. 

Then, I want to use GPU to accelarate the program, and replace the DemonsRegistrationFilter with GPUDemonsRegistrationFilter, then the bug is reported:

error	C2248	'itk::GPUImage<VectorPixelType,3>::Graft': cannot access protected member declared in class 'itk::GPUImage<VectorPixelType,3>'	 d:\itk_gpu\insighttoolkit-5.0.1\modules\registration\gpupdedeformable\include\itkGPUPDEDeformableRegistrationFilter.hxx

**Comment by dzenanz** [comment]
You might need to convert from `itk::Image` to `itk::GPUImage` before you set is as input to a GPU filter. Some [background](https://itk.org/Wiki/ITK/Release_4/GPU_Acceleration#Usage_Example). Some [discussion](http://itk-insight-users.2283740.n2.nabble.com/Problems-Using-GPU-Filters-td7590036.html) of a similar problem and an [example](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/GPUAnisotropicSmoothing/test/itkGPUGradientAnisotropicDiffusionImageFilterTest.cxx) of using a GPU filter.

**Comment by zhang-qiang-github** [comment]
Thank you very much for the suggestion. In the DeformableRegistration16, it use multi-resolution framework for registration by itkMultiResolutionPDEDeformableRegistration. However, I find it don't accept GPU module. My revised code is:

	constexpr unsigned int Dimension = 3;
	using PixelType = double;
	using InternalPixelType = float;

	using ImageType = itk::Image<PixelType, Dimension >;
	using InternalImageType = itk::GPUImage< InternalPixelType, Dimension >;
	using ImageCasterType = itk::CastImageFilter< ImageType, InternalImageType >;

	using ReaderType = itk::ImageFileReader<ImageType>;
	ReaderType::Pointer targetReader = ReaderType::New();
	targetReader->SetFileName(fileCat(path, "fixImg.mha"));
	targetReader->Update();
	//auto a = targetReader->GetOutput()->GetLargestPossibleRegion().GetSize();
	ReaderType::Pointer sourceReader = ReaderType::New();
	sourceReader->SetFileName(fileCat(path, "movingImg.mha"));
	sourceReader->Update();
	
	ImageCasterType::Pointer targetImageCaster = ImageCasterType::New();
	ImageCasterType::Pointer sourceImageCaster = ImageCasterType::New();
	targetImageCaster->SetInput(targetReader->GetOutput());
	sourceImageCaster->SetInput(sourceReader->GetOutput());

	using MatchingFilterType = itk::HistogramMatchingImageFilter<
		InternalImageType, InternalImageType >;

	MatchingFilterType::Pointer matcher = MatchingFilterType::New();

	matcher->SetInput(sourceImageCaster->GetOutput());
	matcher->SetReferenceImage(targetImageCaster->GetOutput());
	matcher->SetNumberOfHistogramLevels(1024);
	matcher->SetNumberOfMatchPoints(7);
	matcher->ThresholdAtMeanIntensityOn();


	// setup the deformation field and filter
	using VectorPixelType = itk::Vector< float, Dimension >;

	using DisplacementFieldType = itk::Image< VectorPixelType, Dimension >;

	using RegistrationFilterType = itk::GPUDemonsRegistrationFilter<
		InternalImageType,
		InternalImageType,
		DisplacementFieldType>;
	//itk::DemonsRegistrationFilter
	//itk::GPUDemonsRegistrationFilter
	RegistrationFilterType::Pointer filter = RegistrationFilterType::New();

	filter->SetStandardDeviations(10.0);

	//
	// Create the Command observer and register it with the registration filter.
	//
	CommandIterationUpdate::Pointer observer = CommandIterationUpdate::New();
	filter->AddObserver(itk::IterationEvent(), observer);


	// use multiresolution scheme
	using MultiResRegistrationFilterType = itk::MultiResolutionPDEDeformableRegistration<
		InternalImageType,
		InternalImageType,
		DisplacementFieldType >;

	MultiResRegistrationFilterType::Pointer multires =
		MultiResRegistrationFilterType::New();

	multires->SetRegistrationFilter(filter);
	multires->SetNumberOfLevels(4);
	multires->SetFixedImage(targetImageCaster->GetOutput());
	multires->SetMovingImage(matcher->GetOutput());
	unsigned int nIterations[4] = { 256, 256, 128, 30 };
	multires->SetNumberOfIterations(nIterations);

	//
	// Create the Command observer and register it with the registration filter.
	//
	CommandResolutionLevelUpdate::Pointer levelobserver = CommandResolutionLevelUpdate::New();
	multires->AddObserver(itk::IterationEvent(), levelobserver);

	multires->Update();

And it report bug as:

itk::MultiResolutionPDEDeformableRegistration<InternalImageType,InternalImageType,DisplacementFieldType,float>::SetRegistrationFilter(itk::PDEDeformableRegistrationFilter<itk::Image<float,3>,itk::Image<float,3>,itk::Image<VectorPixelType,3>> *)': cannot convert argument 1 from 'itk::SmartPointer<itk::GPUDemonsRegistrationFilter<InternalImageType,InternalImageType,DisplacementFieldType,itk::DemonsRegistrationFilter<TFixedImage,TMovingImage,TDisplacementField>>>' to 'itk::PDEDeformableRegistrationFilter<itk::Image<float,3>,itk::Image<float,3>,itk::Image<VectorPixelType,3>> *'	GPURegistration	C:\Users\MLoong\Desktop\ITKReg\GPURegistration.cxx	179	

I set the itk::GPUDemonsRegistrationFilter< itk::GPUImage<float,3>, itk::GPUImage<float,3>,  DisplacementFieldType> to itk::MultiResolutionPDEDeformableRegistration, but MultiResolutionPDEDeformableRegistration can not accept this parameter.  Is that means that GPUDemonsRegistrationFilter can not be used in multi-resolution framework?

**Comment by dzenanz** [comment]
> GPUDemonsRegistrationFilter can not be used in multi-resolution framework

That is correct. There are 3 (mutually incompatible) registration frameworks: classic (ITKv3-), new (ITKv4+) and GPU. Mixing classes from these frameworks is not possible.
