### ISSUE TITLE
Update remote modules to cleanly build with new scoped enums

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITK#1640]
### Description

With the recent changes of #1471, many of the remote modules must have their enum calls refactored to accommodate the new scoped enum classes. Without these changes many of the modules cannot completely build with ITK_LEGACY_REMOVE = ON. Below is a checklist of the modules @hjmjohnson and I will be updating.

## READY FOR MERGING IMMEDIATELY

* Completed clang-tidy updates
* Completed copyright updates
* clang-format applied
* build succeeded with both ITK_LEGACY_REMOTE = ON & OFF
* builds with VTK, cuda, fftw extensions enabled

- [x] Module_AnalyzeObjectMapIO
- [x] Module_AnisotropicDiffusionLBR
- [x] Module_BSplineGradient
- [x] Module_BioCell
- [x] Module_BoneMorphometry
- [x] Module_Cuberille
- [x] Module_FixedPointInverseDisplacement
- [x] Module_GenericLabelInterpolation
- [x] Module_HigherOrderAccurateGrad
- [x] Module_IOFDF
- [x] Module_IOMeshSTL
- [x] Module_IOTransformDCMTK
- [x] Module_LabelErodeDilate
- [x] Module_LesionSizingToolkit
- [x] Module_MGHIO
- [x] Module_MinimalPathExtraction
- [x] Module_MorphologicalContourInt
- [x] Module_MultipleImageIterator
- [x] Module_ParabolicMorphology
- [x] Module_PhaseSymmetry
- [x] Module_PolarTransform
- [x] Module_PrincipalComponentsAnalysis
- [x] Module_RLEImage
- [x] Module_RTK
- [x] Module_SimpleITKFilters
- [x] Module_SkullStrip
- [x] Module_SplitComponents
- [x] Module_Strain
- [x] Module_TextureFeatures
- [x] Module_Thickness3D
- [x] Module_TwoProjectionRegistration
- [x] Module_VariationalRegistration

- [x] Module_Montage
- [x] Module_PerformanceBenchmarking

- [x] Module_SCIFIO
- [x] Module_SphinxExamples

- [x] Module_BoneEnhancement (Please review my changes, this was a tricky solution. [Fork](https://github.com/mseng10/ITKBoneEnhancement/tree/update-changed-enums))
- [x] Module_MeshNoise (No changes)
- [x] Module_IsotropicWavelets ([Fork](https://github.com/mseng10/ITKIsotropicWavelets/tree/update-changed-enums))
- [x] Module_SmoothingRecursiveYvvGa(No changes)
- [x] Module_SubdivisionQuadEdgeMesh([Fork](https://github.com/mseng10/ITKSubdivisionQuadEdgeMeshFilter/tree/update-changed-enums))
- [x] Module_IOScanco([Fork](https://github.com/mseng10/ITKIOScanco/tree/update-changed-enums))
## Needs work
- [ ] Module_IOOpenSlide (Could NOT find OPENSLIDE, need better instructions)
- [ ] Module_TotalVariation (https://github.com/InsightSoftwareConsortium/ITKTotalVariation/issues/33)

## Abandoned modules
- [ ] Module_NeuralNetworks <-- THIS JUST NEEDS TO BE REMOVED, DO NOT UPDATE

**Comment by SimonRit** [comment]
FYI, I have update Module_RTK so it can either be checked or removed from the list, SimonRit/RTK@8b903d3.

**Comment by dzenanz** [comment]
I already made some PRs:
https://github.com/InsightSoftwareConsortium/ITKMontage/pull/157
https://github.com/KitwareMedical/ITKMorphologicalContourInterpolation/pull/86
https://github.com/KitwareMedical/ITKRLEImage/pull/45

**Comment by mseng10** [comment]
Closing issue. Creating new one to reflect new actions needed for ITKv5.1 remote modules.
