### ISSUE TITLE
BUILD_SHARED_LIBS forced to off on Win32 causing wrong system hdf5 libs to be selected

### ISSUE THREAD

**Issue by kenavolic** [InsightSoftwareConsortium/ITK#1658]
### Description

When building shared libraries for ITK and using system hdf5, static hdf5 libraries are selected under Windows.

### Steps to Reproduce

1. Install HDF5 manually with cmake (in my case 1.10.3)
2. With CMake, select BUILD_SHARED_LIBS=ON and ITK_USE_SYSTEM_HDF5
3. Configure

You will see that BUILD_SHARED_LIBS is forced to OFF in ITKSetStandardCompilerFlags on Windows. Then, in Modules/ThirdParty/HDF5/itk-module-init.cmake and Modules/ThirdParty/HDF5/CMakeLists.txt:29, the wrong libraries are searched and selected.

### Expected behavior

Selection of the HDF5 shared libraries when BUILD_SHARED_LIBS=ON. 

### Actual behavior

Selection of the HDF static libraries.

### Reproducibility

100%

### Versions

ITK version 5.0.1

### Environment

Windows 10 64 bits
Visual Studio 2019
CMake 3.15

**Comment by kenavolic** [comment]
I attached a possible patch here (note that other third parties could suffered the same problem).

**Comment by dzenanz** [comment]
Do you want to turn this into a PR, or do you want me to do it?

**Comment by dzenanz** [comment]
Contribution instructions are [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md).

**Comment by kenavolic** [comment]
OK! I'll do it! Do you want me to check if the same issue lies for other third parties as well?

**Comment by dzenanz** [comment]
It would be great if you did that too!
