### ISSUE TITLE
Python: equality operator for itkSize3 behaves like "is" operator in ITK 5

### ISSUE THREAD

**Issue by djboersma** [InsightSoftwareConsortium/ITK#1672]
### Description

Suppose I have two images A and B, and I want to compare their sizes in a python script. I get the size of the image by querying the size of the largest possible region: `sizeA=imgA.GetLargestPossibleRegion().GetSize()`. (In SimpleITK the syntax is simpler: `sizeA=imgA.GetSize()`.) When I compare the size of two images using the '==' operator on the corresponding size objects, then I expect the result "True" for images that have the same size. In ITK 4.13.2 this worked indeed like I expected. But in version 5.0.1 the result is "False" even for identical images. The only way that I found to get the result "True" from the "==" on size objects was by comparing a itkSize object with itself, like `sizeA == sizeA`.

So to me it looks like the '==' operator behaves in ITK 5.0.1 like the 'is' operator. That is wrong. The 'is' operator is indeed supposed to tell me whether lhs and rhs are the same object. The '==' is supposed to tell me whether the value of lhs and rhs are "equal". These are fundamentally different kinds of comparisons.

### Steps to Reproduce

MWE:

```
import itk
import numpy as np
imgA=itk.GetImageFromArray(np.ones((3,4,5)))
imgB=itk.GetImageFromArray(np.ones((3,4,5)))
sizeA=imgA.GetLargestPossibleRegion().GetSize()
sizeB=imgB.GetLargestPossibleRegion().GetSize()
if sizeA == sizeB:
    print("A and B have the same size")
else:
    print("A and B have different sizes")
if sizeA is sizeB:
    print("sizeA and sizeB are the same object")
else:
    print("sizeA and sizeB are different objects")
```

With ITK 4.13.2, I get as output "same size" and "different objects", while with ITK 5.0.1 I get "different sizes" and "different objects".

### Expected behavior

The equality operator `==` on itkSize3 objects should return True if the images have the same size. If `sizeA` and `sizeB` are objects of type itkSize3, then the expression `sizeA==sizeB` should behave identically to `sizeA[0]==sizeB[0] and sizeA[1]==sizeB[1] and sizeA[2]==sizeB[2]`.

### Actual behavior

I see that the equality operator `==` only evaluates to True if lhs and rhs are the same itkSize object. In all other cases it evaluates to False, even when lhs and rhs actually contain identical size values for each dimension.

```none
```

### Reproducibility

100%

### Versions

In version 4.13.2, the `==` operator for itkSize3 objects behaves like I expect it to. In ITK version 5.0.1 it behaves incorrectly, as described above.

### Environment

Ubuntu 18.04, python 3.6.8

**Comment by djboersma** [comment]
As a workaround in my current ITK/python work, I am converting ITK size objects to numpy arrays:
```
sizeA=np.array(imgA.GetLargestPossibleRegion().GetSize())
sizeB=np.array(imgB.GetLargestPossibleRegion().GetSize())
if (sizeA==sizeB).all():
    print("equal")
else:
    print("different")
```

**Comment by djboersma** [comment]
Another workaround, without using numpy:
```
sizeA=tuple(imgA.GetLargestPossibleRegion().GetSize())
sizeB=tuple(imgB.GetLargestPossibleRegion().GetSize())
if sizeA==sizeB:
    print("equal")
else:
    print("different")
```

**Comment by thewtex** [comment]
Addressed by this patch: https://github.com/InsightSoftwareConsortium/ITK/pull/1686

> sizeA=imgA.GetLargestPossibleRegion().GetSize().

The simpler syntax is

```
sizeA = itk.size(imgA)
```
