### ISSUE TITLE
FindPython3.cmake unavailable before CMake 3.12

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#1700]
### Description

I have a warning with cmake v3.11 since 07705bd (@thewtex), see [RTK dashboard](https://my.cdash.org/viewConfigure.php?buildid=1788739). That's because FindPython3.cmake is available since CMake 3.12 only. I'm not sure what's the strategy to fix it, either raise cmake minimal version or find a workaround backward compatible with cmake 3.10. I'm happy to help if I can...

### Steps to Reproduce

Configure with cmake 3.11.

### Expected behavior

Smooth cmake configuration

### Actual behavior

Cmake warning 

```
CMake Warning at D:/src/itk/ITK-master/CMake/ITKModuleExternal.cmake:22 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:257 (include)
```

```none
```

### Reproducibility

100%

### Versions

07705bd

### Environment

Tested on Windows but should occur on any platform.

**Comment by dzenanz** [comment]
CC: @hjmjohnson.

**Comment by thewtex** [comment]
@SimonRit thanks for the report.

It is too much of a burden for the community to install a newer CMake when they want to build ITK, so we cannot bump the CMake minimum version.

We could vendor the FindPython3.cmake module. The version from 3.16 or later is the one that has the least worst behavior on Windows. We have to ensure that the module code is not using any CMake features that were introduced past 3.10.

**Comment by thewtex** [comment]
Closing pre #1072
