### ISSUE TITLE
ITK_FORBID_DOWNLOADS doesn't warn about BUILD_TESTING

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#1715]
ITK_FORBID_DOWNLOADS doesn't currently (at 74783be6bb25f450000e3681d114e2e3f5260d7b) complain about BUILD_TESTING being enabled (like it does for KWStyle)

This means I can configure for a HPC and the submit a build job and it fails out immediately.

**Comment by thewtex** [comment]
`BUILD_TESTING` can be enabled without downloads by using the [`InsightData`](https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.1rc02/InsightData-5.1rc02.tar.gz) tarballs distributed with the releases.

**Comment by gdevenyi** [comment]
I think perhaps ITK_FORBID_DOWNLOADS should hint at that?

**Comment by hjmjohnson** [comment]
> I think perhaps ITK_FORBID_DOWNLOADS should hint at that?

A pull request with your preferred documentation improvement would be welcomed!
