### ISSUE TITLE
Example code to use DICOMParser in ITK/tree/master/Modules/ThirdParty/DICOMParser

### ISSUE THREAD

**Issue by ardeal** [InsightSoftwareConsortium/ITK#1729]
Hi,

```C
https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/DICOMParser
```

Do you have example to use the DICOMParser third party code?

I would like to run DICOMParser to read the image data in DICOM file.
At present, I could run the code in VS2017, but I have no idea about how to read the image data:

The following code is my test code which is not finalized:
```C
#include <stdio.h>
#include <stdlib.h>
#include "DICOMParser.h"

int main(int argc, char ** argv)
{
	printf("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n");
	DICOMParser dp;

	const std::string dicomfile = "../1.dcm";
	dp.OpenFile(dicomfile);
	//int dpsize = dp.DataFile->GetSize();
	//dp.ReadHeader
	dp.ReadHeader();

	//Todo: how to read the image data in DICOM file-------

	return 1;
}





```

**Comment by dzenanz** [comment]
You don't need to specify the format when reading images using ITK. This [simple example](https://itk.org/ITKExamples/src/IO/ImageBase/ReadAnImage/Documentation.html) should do for your case.
