### ISSUE TITLE
ExhaustiveOptimizerv4 SetInitialPosition unexpected behavior

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#1747]
### Description

SetInitialPosition() is documented to "Set the position to initialize the optimization." but its value is immediately overwritten in StartWalking()

```
template <typename TInternalComputationValueType>
void
ExhaustiveOptimizerv4<TInternalComputationValueType>::StartWalking()
{
  itkDebugMacro("StartWalking");
  this->InvokeEvent(StartEvent());
  m_StopConditionDescription.str("");
  m_StopConditionDescription << this->GetNameOfClass() << ": Running";

  ParametersType initialPos = this->m_Metric->GetParameters();
```

### Expected behavior

Actually, open question on this.  Is there any use case for actually setting the InitialPosition?  I'm presuming for the typical use of ExhaustiveOptimizerv4, we would encourage the InitialPosition to be indirectly set by the user modifying the InitialTransforms in ImageRegistrationMethodv4?

My suggestion would be to make it `protected` but I'd want feedback about the consequence of that.  I'm reading the docs in ObjectToObjectOptimizerBase and it looks the metric handles the transfer of parameters.

### Actual behavior

```
	auto optimizer = OptimizerType::New();
	optimizer->SetDebug(true);
	auto steps = OptimizerType::StepsType(2);
	steps[0] = 5;
	steps[1] = 0;
	optimizer->SetNumberOfSteps(steps);
	optimizer->SetStepLength(1);
	auto pos = OptimizerType::ParametersType(2);
	pos.SetElement(0, 12); // is the optimal registration transform
	pos.SetElement(1, 0);
	optimizer->SetInitialPosition(pos); // doesn't effect start or span of the exhaustive optimizer

	auto registration = RegistrationType::New();

	registration->SetNumberOfLevels(1); // default is 3

	registration->SetFixedImage(atlas);
	registration->SetMovingImage(img);
	registration->SetInitialTransform(transform);
	registration->SetMovingInitialTransform(transform2);

	registration->SetOptimizer(optimizer);
	registration->SetMetric(metric);
	registration->Update(); // optimization centered on [0,0], not [12, 0]
	registration->GetModifiableTransform()->Print(std::cout);
```

**Comment by dzenanz** [comment]
`SetInitialPosition` is a virtual public method defined in `Modules\Numerics\Optimizers\include\itkOptimizer.h`. I am not sure whether we can just declare it protected, and even if compiler allows that whether it would be wise. If fixing the code to take that initial position into account is time consuming, we could change the method's docstring to say it is being ignored?

**Comment by dzenanz** [comment]
This does not inherit from `itkOptimizer`, but from `ObjectToObjectOptimizerBaseTemplate`. Patch coming up to respect initial position.
