### ISSUE TITLE
Warning when writing with 1D and 4D images due to unknown metadata type

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#1753]
### Description

When writing a 1D or a >4D image which has been read from disk, I get the following warning
```
WARNING: In /home/srit/src/itk/itk/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 672
MetaImageIO (0x1b723a0): Unsupported or empty metaData item ITK_original_direction of type N3itk6MatrixIdLj1ELj1EEEfound, won't be written to image file
```
The following example shows it for 1D but can also be used to show it for 4D images:

```C
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>

int
main(int argc, char ** argv)
{
  const unsigned int dim = 1;
  using ImageType = itk::Image<float, dim>;
  ImageType::RegionType r;
  for(unsigned int i=0; i<dim; i++)
    r.SetSize(i,16);
  auto img = ImageType::New();
  img->SetRegions(r);
  img->Allocate(true);
  auto writer = itk::ImageFileWriter<ImageType>::New();
  writer->SetFileName("img.mha");
  writer->SetInput(img);
  writer->Update();
  auto reader = itk::ImageFileReader<ImageType>::New();
  reader->SetFileName("img.mha");
  writer->SetInput(reader->GetOutput());
  writer->Update();
  return EXIT_SUCCESS;
}
```
The warning has been introduced by @vfonov in 0a1fd9e. @aylward addressed it for 2D and 3D images with 9e76e34 but not for other dimensions.

### Expected behavior

I don't expect a warning with the example program.

### Actual behavior

Above warning.

### Reproducibility

100%

### Versions

ITK master

### Environment

Any

**Comment by dzenanz** [comment]
@vfonov @seanm I think this is about lack of wrapping for the matrices which are added to metadata during consistency check of spacing. Can you look into it?

**Comment by dzenanz** [comment]
Meanwhile, Simon has proposed a fix 😄
