### ISSUE TITLE
Conversion issue in itk.image_from_array

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#1757]
### Description

Get corruption of first few pixels when using itk.image_from_array.

### Steps to Reproduce

[test-eye1.zip](https://github.com/InsightSoftwareConsortium/ITK/files/4452517/test-eye1.zip)

```
img = itk.imread('test-eye1.tiff')
npimg = itk.array_from_image(img)
npatlas = npimg[250:400, 350:500]
bad = (itk.array_from_image(itk.image_from_array(npatlas)))
print('npatlas:', npatlas)
print('bad', bad)
```
```

npatlas: [[0.00392157 0.00392157 0.00392157 ... 0.2        0.23137255 0.28627452]
 [0.00392157 0.00392157 0.00392157 ... 0.19607843 0.2        0.21176471]
 [0.00392157 0.00392157 0.00392157 ... 0.21176471 0.21176471 0.21176471]
 ...
 [0.627451   0.65882355 0.6784314  ... 0.31764707 0.3529412  0.3529412 ]
 [0.654902   0.70980394 0.7529412  ... 0.34901962 0.34509805 0.34509805]
 [0.6039216  0.6392157  0.67058825 ... 0.33333334 0.34117648 0.3372549 ]]
bad [[-1.1209438e+35  8.2256220e-43 -5.1477161e+36 ...  2.0000000e-01
   2.3137255e-01  2.8627452e-01]
 [ 3.9215689e-03  3.9215689e-03  3.9215689e-03 ...  1.9607843e-01
   2.0000000e-01  2.1176471e-01]
 [ 3.9215689e-03  3.9215689e-03  3.9215689e-03 ...  2.1176471e-01
   2.1176471e-01  2.1176471e-01]
 ...
 [ 6.2745100e-01  6.5882355e-01  6.7843139e-01 ...  3.1764707e-01
   3.5294119e-01  3.5294119e-01]
 [ 6.5490198e-01  7.0980394e-01  7.5294119e-01 ...  3.4901962e-01
   3.4509805e-01  3.4509805e-01]
 [ 6.0392159e-01  6.3921571e-01  6.7058825e-01 ...  3.3333334e-01
   3.4117648e-01  3.3725491e-01]]
```

If it helps, running this in Python using the itk-5.1.rc3 package gives different values for the first few pixels (still extreme).  Above was from Jupyter Lab using a recent build of the release branch.

### Expected behavior

Roughly equivalent values.

### Reproducibility

100%, between two different 3.7.6 virtual envs and a local build and the 5.1rc3 package.

### Versions

Local build of release branch and the itk-5.1rc3 package.

### Environment

Windows with Python 3.7.6.

**Comment by brad-t-moore** [comment]
@thewtex FYI, I have workaround where I can use Pillow/PIL to save the numpy array as a .tiff.  I can read that .tiff with itk and even convert back to a numpy array the and values are correct.  So, it seems isolated to something in itk.image_from_array

**Comment by thewtex** [comment]
@brad-t-moore thanks for the detailed report.

I think this is related to reference counting -- will work on a patch.
