### ISSUE TITLE
Error loading TIFF image

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#1766]
### Description

Wrote a float32 single-channel TIFF image using PIL in Python.  PIL and ImageJ can read the file fine, ITK returns garbled image.  I tried just using itk.imread as well as a float-instantiated itk.ImageReader.  itk.imread also loaded the file as unsigned char when it should have been float.

![image](https://user-images.githubusercontent.com/59569148/79123842-0492f780-7d69-11ea-88d9-6897a6518fbd.png)

![image](https://user-images.githubusercontent.com/59569148/79123892-25f3e380-7d69-11ea-905c-a3693d1c6e71.png)

### Steps to Reproduce

Attached the image and notebook.

[BadIOTest.zip](https://github.com/InsightSoftwareConsortium/ITK/files/4469697/BadIOTest.zip)

Below is the output from the .TIF file when PIL saves the data matrix and when ITK save the data matrix.  ITK can read its file.

```
from PIL import Image
from PIL.TiffTags import TAGS

with Image.open('badimage.tif') as img:
    meta_dict = {TAGS[key] : img.tag[key] for key in img.tag.keys()}
print('badimage.tif', meta_dict)
    
with Image.open('badimage-itk.tif') as img:
    meta_dict = {TAGS[key] : img.tag[key] for key in img.tag.keys()}

print('badimage-itk.tif', meta_dict)
```
```
badimage.tif {'ImageWidth': (428,), 'ImageLength': (210,), 'BitsPerSample': (32,), 'Compression': (1,), 'PhotometricInterpretation': (1,), 'StripOffsets': (134,), 'SampleFormat': (2,), 'RowsPerStrip': (210,), 'StripByteCounts': (359520,), 'PlanarConfiguration': (1,)}
badimage-itk.tif {'ImageWidth': (428,), 'ImageLength': (210,), 'BitsPerSample': (32,), 'Compression': (1,), 'PhotometricInterpretation': (1,), 'StripOffsets': (8,), 'Orientation': (1,), 'SampleFormat': (3,), 'SamplesPerPixel': (1,), 'RowsPerStrip': (612,), 'StripByteCounts': (359520,), 'XResolution': ((4294967295, 169093203),), 'YResolution': ((4294967295, 169093203),), 'PlanarConfiguration': (1,), 'ResolutionUnit': (2,), 'Software': ('InsightToolkit',)}
```

### Expected behavior

Confirm that ImageJ and PIL aren't mishandling (albeit correctly in my case) the badimage.tif file and adjust ITK to correctly read the image.

### Reproducibility

100%

### Versions

Release branch of ITK as of 4/13/2020.  

### Environment

Pillow 7.0, Python 3.7.6.

**Comment by thewtex** [comment]
According to:

https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html

If `SampleFormat` is `1`, it is unsigned integer data, and if `SampleFormat` is `2`, it is signed integer data; @brad-t-moore could you please create a patch to add support for `IOComponentEnum::INT` and `IOComponentEnum::UINT` along with a test to:

 https://github.com/InsightSoftwareConsortium/ITK/blob/623bef5c104458a6df4e2ebe0d85d3804b311223/Modules/IO/TIFF/src/itkTIFFImageIO.cxx#L403-L409

accordingly?
