### ISSUE TITLE
LabelStatisticsImageFilter::SetNumberOfStreamDivisions warning

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITK#1819]
### Description

Warning | C4373 | 'itk::LabelStatisticsImageFilter<ImageType,ImageType>::SetNumberOfStreamDivisions': virtual function overrides 'itk::ImageSink<TInputImage>::SetNumberOfStreamDivisions', previous versions of the compiler did not override when parameters only differed by const/volatile qualifiers | TestSuite_iSegCore | f:\pack\insighttoolkit-5.1\install\x64\debug\include\itk-5.1\itkLabelStatisticsImageFilter.h | 336 |  

### Steps to Reproduce

1. Build [example](https://itk.org/Doxygen/html/SphinxExamples_2src_2Filtering_2ImageStatistics_2StatisticalPropertiesOfRegions_2Code_8cxx-example.html#_a3) with Visual Studio 2015, x64 

### Expected behavior

No warnings.

### Actual behavior

```none
```
A warning is generated.

### Reproducibility

100%

### Environment

Visual Studio 2015, Windows, CMake 3.15.2

**Comment by blowekamp** [comment]
Thanks for reporting the warning and a clear error message.

**Comment by dyollb** [comment]
wow. that was quick. thanks!
