### ISSUE TITLE
Cannot set input image

### ISSUE THREAD

**Issue by wanderine** [InsightSoftwareConsortium/ITK#1843]
I am trying to run itk.ContourExtractor2DImageFilter on numpy arrays, but I cannot set the input image. I load a 3D volume first, not using ITK, and then try to process one slice at a time.
```py
ExtractorType = itk.ContourExtractor2DImageFilter[ImageType]
extractor = ExtractorType.New()

# Loop over slices
image = volume[:,:,slice] % numpy array
itk_image = itk.image_from_array(image)
extractor.SetInput(itk_image)
```

```txt
TypeError: in method 'itkImageToPathFilterIF2PLPP2_SetInput', argument 2 of type 'itkImageF2 const *'
Additional information:
Wrong number or type of arguments for overloaded function 'itkImageToPathFilterIF2PLPP2_SetInput'.
  Possible C/C++ prototypes are:
    itkImageToPathFilterIF2PLPP2::SetInput(itkImageF2 const *)
    itkImageToPathFilterIF2PLPP2::SetInput(unsigned int,itkImageF2 const *)
```

I don't understand what this means

**Comment by wanderine** [comment]
I am using the python version, if it makes any difference.

**Comment by thewtex** [comment]
> ExtractorType = itk.ContourExtractor2DImageFilter[ImageType]

This creates an `ExtractorType` that is optimized for `ImageType`. One issue may be that your input image is not of `ImageType`, in this case a 2D image with 32-bit `float` pixels.

If this is the case, casting to 32-bit `float` may help:

```
itk_image = itk.image_from_array(image.astype(np.float32))
```

But, it is easier to dynamically create an optimized filter based on the input image type, e.g.

```
extractor = itk.ContourExtractor2DImageFilter.New(itk_image)
```

Or, use the functional, Pythonic interface:

```
paths = itk.contour_extractor2_d_image_filter(cthead1, contour_value=150)
```

With the latest version of `itk`, `5.1.0.post2`, this may take NumPy arrays directly as inputs.

Here is a notebook: https://gist.github.com/thewtex/56ca60e9db19dc73a1b3ca25caa93e18

![image](https://user-images.githubusercontent.com/25432/84220792-b157cf80-aaa1-11ea-8063-71ac8a31c9fe.png)
