### ISSUE TITLE
Dashboard with USE_SYSTEM_VXL need to be updated

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#186]
CMake Error at Modules/ThirdParty/VNL/CMakeLists.txt:8 (find_package):
  Could not find a configuration file for package "VXL" that is compatible
  with requested version "2.0.0".

  The following configuration files were considered but not accepted:

    /usr/share/vxl/cmake/VXLConfig.cmake, version: unknown

faraway.kitware | Linux-Ubuntu-GCC-Doxygen |
eldorado.kitware | Ubuntu-g++-4.8.2-Release-System-VXL | 
dash4win7.kitware.com | Win-VS14-Ninja-Release-Shared |

**Comment by thewtex** [comment]
These should all be updated now.
