### ISSUE TITLE
ITK 5.1.0 : Can't build because of ITKInternalEigen3

### ISSUE THREAD

**Issue by chacha21** [InsightSoftwareConsortium/ITK#1888]
On Windows 7 64b
With Visual Studio 2019+Windows 10 SDK installed
With CMake 3.17.3
I can't build ITK 5.1.0, here is the CMake log :

`Setting build type to 'Release' as none was specified.
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.
The CXX compiler identification is MSVC 19.26.28806.0
The C compiler identification is MSVC 19.26.28806.0
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.26.2.windows.1") 
Performing Test C_HAS_WARNING-Wno-uninitialized
Performing Test C_HAS_WARNING-Wno-uninitialized - Failed
Performing Test C_HAS_WARNING-Wno-unused-parameter
Performing Test C_HAS_WARNING-Wno-unused-parameter - Failed
Performing Test C_HAS_WARNING-W3
Performing Test C_HAS_WARNING-W3 - Success
Performing Test C_HAS_WARNING-Wno-long-double
Performing Test C_HAS_WARNING-Wno-long-double - Failed
Performing Test C_HAS_WARNING-Wcast-align
Performing Test C_HAS_WARNING-Wcast-align - Failed
Performing Test C_HAS_WARNING-Wdisabled-optimization
Performing Test C_HAS_WARNING-Wdisabled-optimization - Failed
Performing Test C_HAS_WARNING-Wextra
Performing Test C_HAS_WARNING-Wextra - Failed
Performing Test C_HAS_WARNING-Wformat_2
Performing Test C_HAS_WARNING-Wformat_2 - Failed
Performing Test C_HAS_WARNING-Winvalid-pch
Performing Test C_HAS_WARNING-Winvalid-pch - Failed
Performing Test C_HAS_WARNING-Wno-format-nonliteral
Performing Test C_HAS_WARNING-Wno-format-nonliteral - Failed
Performing Test C_HAS_WARNING-Wpointer-arith
Performing Test C_HAS_WARNING-Wpointer-arith - Failed
Performing Test C_HAS_WARNING-Wshadow
Performing Test C_HAS_WARNING-Wshadow - Failed
Performing Test C_HAS_WARNING-Wunused
Performing Test C_HAS_WARNING-Wunused - Failed
Performing Test C_HAS_WARNING-Wwrite-strings
Performing Test C_HAS_WARNING-Wwrite-strings - Failed
Performing Test C_HAS_WARNING-funit-at-a-time
Performing Test C_HAS_WARNING-funit-at-a-time - Failed
Performing Test C_HAS_WARNING-Wno-strict-overflow
Performing Test C_HAS_WARNING-Wno-strict-overflow - Failed
Performing Test CXX_HAS_WARNING-W3
Performing Test CXX_HAS_WARNING-W3 - Success
Performing Test CXX_HAS_WARNING-Wno-long-double
Performing Test CXX_HAS_WARNING-Wno-long-double - Failed
Performing Test CXX_HAS_WARNING-Wcast-align
Performing Test CXX_HAS_WARNING-Wcast-align - Failed
Performing Test CXX_HAS_WARNING-Wdisabled-optimization
Performing Test CXX_HAS_WARNING-Wdisabled-optimization - Failed
Performing Test CXX_HAS_WARNING-Wextra
Performing Test CXX_HAS_WARNING-Wextra - Failed
Performing Test CXX_HAS_WARNING-Wformat_2
Performing Test CXX_HAS_WARNING-Wformat_2 - Failed
Performing Test CXX_HAS_WARNING-Winvalid-pch
Performing Test CXX_HAS_WARNING-Winvalid-pch - Failed
Performing Test CXX_HAS_WARNING-Wno-format-nonliteral
Performing Test CXX_HAS_WARNING-Wno-format-nonliteral - Failed
Performing Test CXX_HAS_WARNING-Wpointer-arith
Performing Test CXX_HAS_WARNING-Wpointer-arith - Failed
Performing Test CXX_HAS_WARNING-Wshadow
Performing Test CXX_HAS_WARNING-Wshadow - Failed
Performing Test CXX_HAS_WARNING-Wunused
Performing Test CXX_HAS_WARNING-Wunused - Failed
Performing Test CXX_HAS_WARNING-Wwrite-strings
Performing Test CXX_HAS_WARNING-Wwrite-strings - Failed
Performing Test CXX_HAS_WARNING-funit-at-a-time
Performing Test CXX_HAS_WARNING-funit-at-a-time - Failed
Performing Test CXX_HAS_WARNING-Wno-strict-overflow
Performing Test CXX_HAS_WARNING-Wno-strict-overflow - Failed
Performing Test CXX_HAS_WARNING-Wno-deprecated
Performing Test CXX_HAS_WARNING-Wno-deprecated - Failed
Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof
Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof - Failed
Performing Test CXX_HAS_WARNING-Wno-undefined-var-template
Performing Test CXX_HAS_WARNING-Wno-undefined-var-template - Failed
Performing Test CXX_HAS_WARNING-Woverloaded-virtual
Performing Test CXX_HAS_WARNING-Woverloaded-virtual - Failed
Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel
Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel - Failed
Performing Test have_avx_extensions_var
Performing Test have_avx_extensions_var - Success
Performing Test have_avx2_extensions_var
Performing Test have_avx2_extensions_var - Success
Performing Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG
Performing Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG - Failed
CMake Warning at CMake/itkExternal_Eigen3.cmake:58 (find_package):
  By not providing "FindITKInternalEigen3.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ITKInternalEigen3", but CMake did not find one.

  Could not find a package configuration file provided by "ITKInternalEigen3"
  with any of the following names:

    ITKInternalEigen3Config.cmake
    itkinternaleigen3-config.cmake

  Add the installation prefix of "ITKInternalEigen3" to CMAKE_PREFIX_PATH or
  set "ITKInternalEigen3_DIR" to a directory containing one of the above
  files.  If "ITKInternalEigen3" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:466 (include)

CMake Error at CMake/itkExternal_Eigen3.cmake:60 (message):
  ITKInternalEigen3 configuration faileed

  REPORT:

  -- Selecting Windows SDK version 8.1 to target Windows 6.1.7601.

  -- The C compiler identification is unknown

  -- The CXX compiler identification is unknown

  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
  Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe

  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
  Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe -
  broken

  -- Configuring incomplete, errors occurred!

  See also
  "E:/InsightToolkit-5.1.0/build/vs2019/x64/ITKInternalEigen3-build/CMakeFiles/CMakeOutput.log".

  See also
  "E:/InsightToolkit-5.1.0/build/vs2019/x64/ITKInternalEigen3-build/CMakeFiles/CMakeError.log".

  

  CMake Error at C:/Program
  Files/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):

    The C compiler

  

      "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe"

  

    is not able to compile a simple test program.

  

    It fails with the following output:

  

      Change Dir: E:/InsightToolkit-5.1.0/build/vs2019/x64/ITKInternalEigen3-build/CMakeFiles/CMakeTmp
      
      Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_74442.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e pour .NET Framework
      Copyright (C) Microsoft Corporation. Tous droits rÃ©servÃ©s.
      
        Compilateur d'optimisation Microsoft (R) C/C++ versionÂ 19.26.28806 pour x64
        testCCompiler.c
        Copyright (C) Microsoft Corporation. Tous droits rÃ©servÃ©s.
        cl /c /W3 /WX- /diagnostics:column /O2 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_74442.dir\Debug\\" /Fd"cmTC_74442.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "E:\InsightToolkit-5.1.0\build\vs2019\x64\ITKInternalEigen3-build\CMakeFiles\CMakeTmp\testCCompiler.c"
      LINK : fatal error LNK1104: impossible d'ouvrir le fichier 'ucrt.lib' [E:\InsightToolkit-5.1.0\build\vs2019\x64\ITKInternalEigen3-build\CMakeFiles\CMakeTmp\cmTC_74442.vcxproj]
      
      

  

    

  

    CMake will not be able to correctly generate this project.

  Call Stack (most recent call first):

    CMakeLists.txt:1 (project)

  

  

Call Stack (most recent call first):
  CMakeLists.txt:466 (include)

Configuring incomplete, errors occurred!
See also "E:/InsightToolkit-5.1.0/build/vs2019/x64/CMakeFiles/CMakeOutput.log".
See also "E:/InsightToolkit-5.1.0/build/vs2019/x64/CMakeFiles/CMakeError.log".`

**Comment by phcerdan** [comment]
I don't think its related to Eigen, but it happens that Eigen is the first thing ITK is trying to compile.
There are problems passing the compiler to the Eigen sub-project.

The error is:
```
The C compiler

  "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe"

is not able to compile a simple test program.
```

Why are the differences between this report and our green CI in windows?

**Comment by phcerdan** [comment]
@chacha21 Could you provide the `CMake` options that you are using to compile ITK?

**Comment by chacha21** [comment]
Since I have installed VS 2019 and Windows 10 SDK, I can't use Windows SDK 8.1 any more.
Thus before configuring anything in CMake, I set the CMAKE_SYSTEM_VERSION to 10.0, then run "Configure".
It fails with the above message before I access to second-stage customizing options.

**Comment by dzenanz** [comment]
This looks like either Visual Studio problem, or installation problem, or possibly a CMake problem, but not an ITK problem. Closing - reopen if you have some arguments as to why ITK should handle this.

**Comment by chacha21** [comment]
After unsucessful uninstall/reinstall or "repairing" of Windows 8.1 SDK only, I finally "repaired" the while VS2017 installation, and now CMake  works.
Maybe CMake still has problems with the W10 SDK, but indeed that was not an ITK problem

**Comment by phcerdan** [comment]
Thanks for reporting @chacha21
