### ISSUE TITLE
missing implementation of std::ostream & operator<<(std::ostream & out, const ESMDemonsRegistrationFunctionEnums::Gradient value)

### ISSUE THREAD

**Issue by chacha21** [InsightSoftwareConsortium/ITK#1891]
ITK 5.1
When using itkESMDemonsRegistrationFunction, a link error occurs because of missing symbol for
`std::ostream & operator<<(std::ostream & out, const ESMDemonsRegistrationFunctionEnums::Gradient value)`

adding
`namespace itk {
std::ostream & operator<<(std::ostream & out, const ESMDemonsRegistrationFunctionEnums::Gradient value) {return out;}
}`

in any compilation unit will fix it (until a real implementation is given)

**Comment by dzenanz** [comment]
This is similar to, and maybe even a duplicate of #1890.

**Comment by dzenanz** [comment]
In such situations, it is better to report all the error messages of the same kind in a single issue report.

**Comment by chacha21** [comment]
Fixed : that was my fault
I missed a dependency to ITKPDEDeformableRegistration
