### ISSUE TITLE
RTK remote module find_package by components

### ISSUE THREAD

**Issue by finetjul** [InsightSoftwareConsortium/ITK#1892]
### Description

When ITK is built with RTK module, building a project - that depends on ITK with `find_package(ITK COMPONENTS ...)` - fail.

### Impact analysis

RTK MUST be provided in the list of components to find.

### Expected behavior

```none
...
find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
include(${ITK_USE_FILE})
...
target_link_libraries(foo ${ITK_LIBRARIES}) 
```

### Actual behavior

At build time (MSVC 2017), I have the following error:
```
LINK : fatal error LNK1104: cannot open file 'lpsolve55.lib'
```

### Versions

ITK 5.1rc3 (from Slicer)
RTK v2.1.0

### Environment

Windows 10, CMake 3.15.7

### Additional Information

CMake variable `ITK_LIBRARIES` contains `RTK` in its list however I did not ask for it.
Removing RTK from ITK_LIBRARIES fixes the problem.

Alternatively, adding RTK to the list of components fixes as well `find_package(ITK COMPONENTS ... RTK)

In my use case, I have no control over (both solutions are not available to me) the project that depends on the ITK build I provide.

**Comment by thewtex** [comment]
> CMake variable ITK_LIBRARIES contains RTK in its list however I did not ask for it.

Hmm, if `RTK` was not in the list of `COMPONENTS`, it should not be in `ITK_LIBRARIES`.

**Comment by finetjul** [comment]
Thanks @thewtex for your confirmation, that helped me digged a bit further. Here is actually what really happens:
[ModuleDescriptionParser/CMakeLists.txt](https://github.com/Slicer/SlicerExecutionModel/blob/master/ModuleDescriptionParser/CMakeLists.txt):
```
...
find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
include(${ITK_USE_FILE})
...
find_package(ParameterSerializer REQUIRED)
...
target_link_libraries(foo ${ITK_LIBRARIES}) # ITK_LIBRARIES contains RTK here
```

Where [ParameterSerializerConfig.cmake](https://github.com/Slicer/ParameterSerializer/blob/master/cmake/ParameterSerializerConfig.cmake.in) contents:
```
...
find_package(ITK REQUIRED)
set(ITK_FOUND false)
...
````

Is it still ok to contain RTK at line `target_link_libraries(foo ${ITK_LIBRARIES})` ?

**Comment by thewtex** [comment]
Since `ITK_LIBRARIES` is determined by `find_package(ITK COMPONENTS ...`, perhaps:

```
...
find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
include(${ITK_USE_FILE})
...
find_package(ParameterSerializer REQUIRED)
...
find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
target_link_libraries(foo ${ITK_LIBRARIES}) # ITK_LIBRARIES contains RTK here
```

**Comment by finetjul** [comment]
We are getting close.

If I remove `find_package(ITK REQUIRED)` from [ParameterSerializerConfig.cmake](https://github.com/Slicer/ParameterSerializer/blob/master/cmake/ParameterSerializerConfig.cmake.in), then there are errors at generate time such as:

    CMake Error at ModuleDescriptionParser/CMakeLists.txt:166 (add_library):
      Target "ModuleDescriptionParser" links to target "ITKInternalEigen3::Eigen"
      but the target was not found.  Perhaps a find_package() call is missing for
      an IMPORTED target, or an ALIAS target is missing?

Interestingly, 
```
find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
include(${ITK_USE_FILE})
```
sets to `""` (i.e. empty) the `ITK_LIBRARY_DIRS` variable.

However in [ParameterSerializerConfig.cmake](https://github.com/Slicer/ParameterSerializer/blob/master/cmake/ParameterSerializerConfig.cmake.in), 
```
find_package(ITK REQUIRED)
```
sets to `C:/Work/S-b/ITK-build/lib` the `ITK_LIBRARY_DIRS` variable.

I guess this is the reason of the [that fix](https://github.com/Slicer/ParameterSerializer/commit/d1a08c5dc2ec190e9034eeae6fb4e1332f313643) in ParameterSerializerConfig.cmake

The question now is: shouldn't  `find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)` set something in `ITK_LIBRARY_DIRS` ?

For information `ITK_LIBRARIES` is equal to `ITKCommon;ITKInternalEigen3::Eigen;itksys;itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl;ITKIOXML;ITKIOImageBase;ITKEXPAT`

**Comment by thewtex** [comment]
> RTK still has some code left from the time it was not an ITK module. For lpsolve, we have not used itk_module_add_library but the code here. Could this be the source of the problem and should this be solved?

This sound  promising and worthwhile.

> The question now is: shouldn't find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED) set something in ITK_LIBRARY_DIRS ?

If all the target exports are set up, we do not need `ITK_LIBRARY_DIRS`.


> For information ITK_LIBRARIES is equal to ITKCommon;ITKInternalEigen3::Eigen;itksys;itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl;ITKIOXML;ITKIOImageBase;ITKEXPAT

> find_package(ITK COMPONENTS ITKCommon ITKIOXML ITKExpat REQUIRED)
> target_link_libraries(foo ${ITK_LIBRARIES})

Then, `RTK` is no longer a in `ITK_LIBRARIES` and this works?

**Comment by finetjul** [comment]
> Then, RTK is no longer a in ITK_LIBRARIES and this works?

No it still does not work, but it is because of  #1897

**Comment by SimonRit** [comment]
Did SimonRit/RTK@214b137 fix this?

**Comment by finetjul** [comment]
> Did SimonRit/RTK@214b137 fix this?
Yes, in addition to:
https://github.com/Slicer/ParameterSerializer/pull/8
https://github.com/Slicer/SlicerExecutionModel/pull/130

**Comment by SimonRit** [comment]
Great, well done. Thanks!
