### ISSUE TITLE
UseITK.cmake is incomplete

### ISSUE THREAD

**Issue by finetjul** [InsightSoftwareConsortium/ITK#1897]
### Description

When exporting targets linking against ITK libraries, the directories of the ITK libraries are not exported.

### Expected behavior

fooTargets.cmake should contain the path of the ITK libraries

Here is an example to reproduce the issue:
```
bar
  CMakeLists.txt
  bar.cxx
  barConfig.cmake.in
foo
  CMakeLists.txt
  foo.cxx
```

where bar/CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)

project(bar)

find_package(ITK REQUIRED)
include(${ITK_USE_FILE})

add_library(bar STATIC bar.cxx)
target_link_libraries(bar ${ITK_LIBRARIES})

export(TARGETS bar FILE "${PROJECT_BINARY_DIR}/barTargets.cmake")

configure_file( "barConfig.cmake.in"
  "${PROJECT_BINARY_DIR}/barConfig.cmake"
  @ONLY )
```

bar/barConfig.cmake.in:
```
set( bar_FOUND 1 )

set(bar_TARGETS_IMPORTED 1 )
include( "${bar_CMAKE_DIR}/barTargets.cmake" )
set( bar_LIBRARIES bar )
```

foo/CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)

project(foo)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_DIR}/../bar")
find_package(bar)

add_library(foo foo.cxx)
target_link_libraries(foo bar)
```

At CMake generate time, the following error is generated:
```
CMake Error at CMakeLists.txt:11 (add_library):
  Target "foo" links to target "ITKInternalEigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

### Actual behavior

`link_directories` in UseITK.cmake is not enough, it will not export the library directories.

### Versions

ITK master

### Environment

Windows 10, CMake 3.15.7

### Additional Information

This example is a simplification of [ParameterSerializer](https://github.com/Slicer/ParameterSerializer) (i.e. bar) and [SlicerExecutionModel](https://github.com/Slicer/SlicerExecutionModel)(i.e. bar)

**Comment by finetjul** [comment]
The problem is that the exported `barTargets.cmake` does not exports the ITK library directories. It does just the following:

```
# Create imported target bar
add_library(bar STATIC IMPORTED)

set_target_properties(bar PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkdouble-conversion;ITKInternalEigen3::Eigen;itksys;itkvnl_algo;itkvnl;itkv3p_netlib;..."
)
```

Libraries should either be in absolute/relative path. Or INTERFACE_LINK_DIRECTORIES should also be set.

**Comment by finetjul** [comment]
Solution I found is to have in `bar/barConfig.cmake.in`:

```
set( bar_FOUND 1 )

set(bar_TARGETS_IMPORTED 1 )
include( "${CMAKE_CURRENT_LIST_DIR}/barTargets.cmake" )
set( bar_LIBRARIES bar )

set(ITK_DIR "@ITK_DIR@")
include(CMakeFindDependencyMacro)
find_dependency(ITK REQUIRED)
```

Please close the issue if such solution is best practice

**Comment by jcfr** [comment]
In the example:

I think :

```
set( bar_FOUND 1 )

set(bar_TARGETS_IMPORTED 1 )
include( "${bar_CMAKE_DIR}/barTargets.cmake" )
set( bar_LIBRARIES bar )
```

should instead be : 

```
include( "${CMAKE_CURRENT_LIST_DIR}/barTargets.cmake" )
set( bar_LIBRARIES bar )
```

Now, best practice would require use to use `include(CMakePackageConfigHelpers)`

Some relevant reads:

* https://stackoverflow.com/questions/51564251/correct-way-to-use-third-party-libraries-in-cmake-project/51567322#51567322

* https://stackoverflow.com/questions/56135785/correctly-set-the-location-of-imported-cmake-targets-for-an-installed-package/56288628#56288628
   - and associated demo project: https://github.com/jcfr/stackoverflow-56135785-answer

And some example of CMake projects:

* proxTV: https://github.com/phcerdan/proxTV/blob/a503293ed567d7114bee85e4e068305d4afe7dbe/CMakeLists.txt#L84-L136

* python-cmake-buildsystem: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/2b036f110364a9295760345c9bbb3337c2ca9d72/CMakeLists.txt#L636-L687

* CTKAppLauncher: https://github.com/commontk/AppLauncher/blob/1c7156701ee96ab7b69ecc8322dc5443514927fa/CMakeLists.txt#L363-L469

**Comment by thewtex** [comment]
@jcfr @finetjul excellent discussion :book: :school:. Thanks for opening these issues and discussing them.

@finetjul it seems you are on the correct path in the package configuration file dependent project improvements. Please close this issue after your patches have been merged into ParameterSerializer / RTK and the fixes are confirmed to address your use case.
