### ISSUE TITLE
OpenCVImageBridge does not support signed 32-bit integer matrix conversions.

### ISSUE THREAD

**Issue by PierreWargnier** [InsightSoftwareConsortium/ITK#1906]
### Description

Attempts to convert an OpenCV cv::Mat single-channel signed 32-bit integers (CV_32SC1) matrix to itk::Image<int, 2> throw an exception saying "Unknown OpenCV type" whereas this type does exist and there is no reason for it not to be compatible with the itk Image class.

The inverse conversion itk::Image<int, 2> to cv::Mat of type CV_32SC1 also throws an exception: "OpenCV does not support the input pixel type" whereas it is actually supported.

By reading the code in itkOpenCVImageBridge.hxx, it appears that this type was simply forgotten because all other OpenCV types are supported.

### Steps to Reproduce

    #include <opencv2/core.hpp>
    #include <itkImage.h>
    #include <itkOpenCVImageBridge.h>

    int main()
    {
        using IntImageType = itk::Image<int, 2>;

        int width = 1920;
        int height = 1080;

        cv::Mat singleChannelIntMat(height, width, cv::CV_32FC1);

        IntImageType::Pointer itkIntImage = itk::OpenCVImageBridge::CVMatToITKImage<IntImageType>(singleChannelIntMat);

       cv::Mat inverseConversion = itk::OpenCVImageBridge::ITKImageToCVMat<IntImageType>(itkIntImage);
   
       return 0;
    }

### Expected behavior

Conversion should work, since both libraries support int images/matrices.

### Actual behavior

- Conversion from CV_32SC1 Mat to Image<int, 2> throws "Unknown OpenCV type".

- Conversion from Image<int, 2> to CV_32SC1 Mat throws "OpenCV does not support the input pixel type".

### Reproducibility

Always

### Versions

ITK 5.2.0
OpenCV 4.3.0

Unless the signed 32-bit int type was ever supported, this is likely to appear with any versions of both libraries.

### Environment

Ubuntu 20.04 Virtual Box virtual machine. But this is clearly an issue independant of the platform since the int matrix type is clearly missing in the itkOpenCVImageBridge.hxx file.

### Additional Information

There is an easy fix that I implemented and tested:

- In itkOpenCVImageBridge.hxx after line 74, adding
`CONVERSION_CASE(IPL_DEPTH_32S, int)`
fixes the OpenCV -> ITK converstion issue.

- In itkOpenCVImageBridge.hxx after line 196, adding
`
else if(typeid(ValueType) == typeid(int))
{
    out = cvCreateImage(cvSize(w, h), IPL_DEPTH_32S, outChannels);
    typeSize = 4;
}
`
fixes the ITK -> OpenCV conversion issue.

On a side note, it appears that multi-channel ITK -> OpenCV conversion is not supported for signed types char, short and double with an exception message that OpenCV does not support color images of these types whereas it is definitely possible to contain this data in a Mat object (up to 4 channels) although it might not always be possible to display them using cv::imshow("title", matObject).

If anyone is interested, I will try to update/fix the convertion functions and submit a pull request following two goals:

- Implement conversions from/to cv::Mat that do not use IplImage, since IplImage is long deprecated and was officially removed in OpenCV versions 4+, although it is still accessible as of version 4.3.0. See this other issue: [https://github.com/InsightSoftwareConsortium/ITK/issues/1651](https://github.com/InsightSoftwareConsortium/ITK/issues/1651)

- Making sure that conversion for all OpenCV-supported types, with up to 4 channels are supported.

**Comment by dzenanz** [comment]
A PR for this would be quite welcome!

**Comment by PierreWargnier** [comment]
Hello @dzenanz , I am working on it. I have a question on the desired behavior: should the type mismatches for pixels/components between throw an exception or at least a warning?

**Comment by dzenanz** [comment]
Yes, at least a warning. Exception is probably better, but it is up to you.

**Comment by PierreWargnier** [comment]
Thanks for your answer. I also think that an exception is more appropriate. Although it will work to convert mismatched types it will not produce what is expected.
