### ISSUE TITLE
Error compiling ITK examples due to incorrect `#include`

### ISSUE THREAD

**Issue by justbennet** [InsightSoftwareConsortium/ITK#1907]
### Description

Error compiling the `2DGaussianMixtureModelExpectMax` from the ITKExamples because of incorrect include statement.

Line 21 of `Modules/Numerics/Statistics/include/itkExpectationMaximizationMixtureModelEstimator.hxx` seems to have an erroneous path to the header file,

```
#include "../include/itkExpectationMaximizationMixtureModelEstimator.h"
```
which should be
```
#include "itkExpectationMaximizationMixtureModelEstimator.h"
```

After making the modification to my installed ITK-5.1.0, the compilation succeeded.

### Steps to Reproduce

I compiled and installed ITK-5.1.0, then fetched the ITK Examples.  The error should occur when compiling the `2DGaussianMixtureModelExpectMax` example.

### Expected behavior

Compilation and linking would succeed.

### Actual behavior

When compiling ITKExamples, I got
```
Scanning dependencies of target 2DGaussianMixtureModelExpectMax
[ 97%] Building CXX object src/Numerics/Statistics/2DGaussianMixtureModelExpectMax/CMakeFiles/2DGaussianMixtureModelExpectMax.dir/Code.cxx.o
In file included from /tmp/local/include/ITK-5.1/itkExpectationMaximizationMixtureModelEstimator.h:246,
                 from /tmp/bennetsw/build/ITK/BuildIt/ITKExamples/src/Numerics/Statistics/2DGaussianMixtureModelExpectMax/Code.cxx:21:
/tmp/local/include/ITK-5.1/itkExpectationMaximizationMixtureModelEstimator.hxx:21:10: fatal error: ../include/itkExpectationMaximizationMixtureModelEstimator.h: No such file or directory
 #include "../include/itkExpectationMaximizationMixtureModelEstimator.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Reproducibility

For me, it was every time.

### Versions

Downloaded from
https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.1.0/InsightToolkit-5.1.0.tar.gz

573ddc3aade8117c5aea7ded135f2ca6  /sw/src/arcts/ITK/InsightToolkit-5.1.0.tar.gz

### Environment

CentOS 7.7.1908
```
$ cmake --version
cmake version 3.13.2
$ gcc --version
gcc (GCC) 8.2.0
```

I can submit a PR if you agree that it is a problem.

**Comment by dzenanz** [comment]
Please make a PR. This was almost certainly done by IDE's auto-correct or something similar.

**Comment by justbennet** [comment]
I submitted https://github.com/InsightSoftwareConsortium/ITK/pull/1908 for this.

**Comment by justbennet** [comment]
Sorry, I didn't see the initial Descriptions tag convention for Ghostflow.  I edited it to start with BUG: after the fact, but that might need to be rerun.  Mea culpa.
