### ISSUE TITLE
Python crashes when itk.GetMatrixFromArray executed with transposed numpy array.

### ISSUE THREAD

**Issue by lesaintjerome** [InsightSoftwareConsortium/ITK#1910]
### Description

Python kernel crashes when I pass a transposed array to the itk.GetMatrixFromArray() function.

### Steps to Reproduce
import numpy as np
import itk as itk
mat = np.random.randn(3,3)
itk.GetMatrixFromArray(mat)

### Expected behavior

I would expect ITK to handle such transpose operation on array. At least, an error message rather than a crash. The problem seems related to [this](https://discourse.itk.org/t/set-image-direction-from-numpy-array/844) and non C-contiguous array.

### Actual behavior

Kernel crash

### Reproducibility

100%

### Versions
itk.Version.GetITKVersion() : 5.0.0

### Environment
Windows (it works fine on a macos install).

**Comment by dzenanz** [comment]
Does this happen with versions 5.0.1 and 5.1.0?

**Comment by lesaintjerome** [comment]
I cannot install any other version on my computer due to company restrictions. But I wasn't able to reproduce on a colleague's 5.0.1 version.
No idea on a 5.1.0.
Jérome

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dzenanz** [comment]
I think it was fixed since.
