### ISSUE TITLE
ENH: Configure PyPi API Tokens For ITK Remote Modules: Part 1

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#1921]
### Description

We have completed about 1/2 of the repositories.

This issue details ITK's remote repositories requiring a PyPi API token generated to allow deployment from GitHub Actions. Essentially, @mseng10 will be iterating through the remote modules and contacting @hjmjohnson to complete the following steps extracted from ITK's issue [here](https://github.com/InsightSoftwareConsortium/ITK/issues/1828). Below are the steps that must be completed for each package:

1.Contact @thewtex, @dzenanz about Python package name, who will add @hjmjohnson, @dzenanz, @thewtex, ???  to the maintainer list on PyPI.
1. Create an API token on PyPI for the package, and puts in the repository *Settings -> Secrets* under the key *pypi_password*.
1. Create new Git tag, either locally and pushing, or in the GitHub web Release page, this will trigger builds and push the packages to PyPI.

Below is a TODO list of repositories that are completed and need the token generated for its respective module.  
The name of the ITK Python Package that must be discussed with Matt McCormick. When the steps are complete, @johnsonhj will notify @mseng

* [x] Module_PerformanceBenchmarking
* [x] Module_MGHIO
* [x] Module_GenericLabelInterpolation
* [x] Module_Cuberille
* [x] Module_AnalyzeObjectMapIO
* [x] Module_AnisotropicDiffusionLBR
* [x] Module_BioCell
* [x] Module_BoneMorphometry
* [x] Module_IOMeshSTL
* [x] Module_MinimalPathExtraction
* [x] Module_MultipleImageIterator
* [x] Module_ParabolicMorphology
* [x] Module_TextureFeatures
* [x] Module_TwoProjectionRegistration
* [x] Module_Montage
* [x] Module_MeshNoise
* [x] Module_SubdivisionQuadEdgeMesh
* [x] Module_IOScanco

### Expected coding style

PyPi automated generation completed by CI.

### Actual coding style

Final CI integration steps needed

### Versions

**Comment by thewtex** [comment]
@hjmjohnson @dzenanz what are your PyPI account names?

**Comment by dzenanz** [comment]
I just created: https://pypi.org/user/dzenanz/

**Comment by hjmjohnson** [comment]
Notes from @mseng10 
```
itk-bsplinegradient: This module needs the tag created in Web Release history as it has already been merged.
itk-higherorderaccurategradient: This module can have it's tag created through a PR using this branch. If you want a template for the PR just copy this.
itk-simpleitkfilters: This module can have it's tag created through a PR using this branch.
itk-fixedpointinversedisplacementfield: This module can have it's tag created through a PR using this branch.

NOTE: For itk-simpleitkfilters and itk-fixedpointinversedisplacementfield these modules did not have any packages published to PyPi (that I could see). When discussing with Matt McCormick please mention this as a package may have to be created by him.

itk-labelerodedilate: This module can have it's tag created through a PR using this branch
itk-iofdf: This module can have it's tag created through a PR using this branch
itk-skullstripping: This module can have it's tag created through a PR using this branch

Repositories with published PyPi packages
itk-thickness3d: This module can have it's tag created through a PR using this branch
itk-strain: This module can have it's tag created through a PR using this branch
itk-principalcomponentsanalysis: This module can have it's tag created through a PR using this branch
itk-polartransform: This module can have it's tag created through a PR using this branch
itk-phasesymmetry: This module can have it's tag created through a PR using this branch
```

**Comment by hjmjohnson** [comment]
I also created a pypi account:
```
https://pypi.org/user/hjmjohnson/
```

**Comment by mseng10** [comment]
I believe there was a miscommunication on my end. The modules listed in the `Description` (PerformanceBenchmarking through IOScanco) have already been completed and need no further actions. This new `TODO` list contains all the modules that are completed and need authorized actions. I have linked my forked branch for each of the modules, so all that should be required is a PR with proper authorization.

- [ ] **itk-bsplinegradient**: This module needs the tag created in Web Release history as it has already been merged.
- [ ] **itk-higherorderaccurategradient**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKHigherOrderAccurateGradient/tree/github-actions).
- [ ] **itk-simpleitkfilters**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKSimpleITKFilters/tree/github-actions).
- [ ] **itk-fixedpointinversedisplacementfield**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKFixedPointInverseDisplacementField/tree/github-actions).
- [ ] **itk-labelerodedilate**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKLabelErodeDilate/tree/github-actions)
- [ ] **itk-iofdf**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKIOFDF/tree/github-actions)
- [ ] **itk-skullstripping**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKSkullStrip/tree/github-actions)
- [ ] **itk-thickness3d**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKThickness3D.git)
- [ ] **itk-strain**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKStrain/tree/github-actions)
- [ ] **itk-principalcomponentsanalysis**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPrincipalComponentsAnalysis/tree/github-actions)
- [ ] **itk-polartransform**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPolarTransform/tree/github-actions)
- [ ] **itk-phasesymmetry**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPhaseSymmetry/tree/github-actions)

**NOTE:** itk-labelerodedilate, itk-iofdf, itk-skullstripping, itk-fixedpointinversedisplacementfield, itk-simpleitkfilters DO NOT have their packages published to PyPi (that I could find). They will likely need an initial creation in PyPi.

**Comment by thewtex** [comment]
The following have the CI, API Token, Multi-PyPI collaborators setup:

- itk-genericlabelinterpolator
- itk-cuberille
- itk-anisotropicdiffusionlbr
- itk-bonemorphometry
- itk-iomeshstl
- itk-minimalpathextraction
- itk-parabolicmorphology
- itk-texturefeatures
- itk-twoprojectionregistration
- itk-montage
- itk-meshnoise
- itk-subdivisionquadedgemeshfilter
- itk-ioscanco
- itk-bsplinegradient

**Comment by mseng10** [comment]
@thewtex I have gone through and fixed the following branches to have the recent changes from the `ITKModuleTemplate`. These modules are ready to have GitHub Actions enabled.

- [ ] **itk-fixedpointinversedisplacementfield**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKFixedPointInverseDisplacementField/tree/github-actions).
- [ ] **itk-labelerodedilate**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKLabelErodeDilate/tree/github-actions)
- [ ] **itk-iofdf**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKIOFDF/tree/github-actions)
- [ ] **itk-skullstripping**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKSkullStrip/tree/github-actions)
- [ ] **itk-strain**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKStrain/tree/github-actions)
- [ ] **itk-principalcomponentsanalysis**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPrincipalComponentsAnalysis/tree/github-actions)
- [ ] **itk-polartransform**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPolarTransform/tree/github-actions)
- [ ] **itk-phasesymmetry**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKPhaseSymmetry/tree/github-actions)
- [ ] **itk-smoothingrecursiveyvvgaussianfilter**: This module can have it's tag created through a PR using this [branch](https://github.com/mseng10/ITKSmoothingRecursiveYvvGaussianFilter/tree/github-actions)

**Comment by thewtex** [comment]
@mseng10 marvelous! Old CI services have been disabled, PyPI tokens have been created, @hjmjohnson @dzenanz were added as admins, and PyPI tokens were created for all the noted packages.

**Comment by mseng10** [comment]
@thewtex Awesome!
