### ISSUE TITLE
Linking with FFTW fails

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#1930]
### Description

Since the recent update of FFTW (7d033c2463f185f477365900f6a93fe8200510fc by @hmjohnson I believe), the linking of FFTW fails on RTK dashboard, see [here](https://my.cdash.org/index.php?project=RTK&date=2020-07-23). I'm not sure if something must be fixed on the ITK side or changed on the RTK side, it used to work fine.

### Steps to Reproduce

See dashboard configuration.

### Expected behavior

Green dashboard!

### Actual behavior

Cannot link, see [dashboard errors](https://my.cdash.org/index.php?project=RTK&date=2020-07-23)
### Versions

ITK master

### Environment

Both on Windows and MacOS

**Comment by dzenanz** [comment]
Possibly related #1922.

**Comment by dzenanz** [comment]
Looking at your dashboard, this might be a duplicate of #1922, since only your Windows build have errors.

**Comment by SimonRit** [comment]
It might be but MacOS too, see [this one](https://my.cdash.org/viewBuildError.php?buildid=1858088) for example.

**Comment by hjmjohnson** [comment]
I just built ITK with 

BUILD_SHARED_LIBS:BOOL=ON
Module_RTK:BOOL=ON
ITK_USE_FFTWD:BOOL=ON
ITK_USE_FFTWF:BOOL=ON

on my mac without any linking issues.

**Comment by SimonRit** [comment]
I'm using a system FFTW, see configure step
<https://my.cdash.org/viewConfigure.php?buildid=1858088>. Was it the same
for you?

**Comment by hjmjohnson** [comment]
No.  There must be some mis-match in the variable names between these two build paths.  

My guess is a minor change to CMake/FindFFTW.cmake will fix this problem.  I'll try to carve out some time this weekend to investigate.

How was fftw installed on the system?

**Comment by SimonRit** [comment]
With brew, it's the 3.3.8 version. Thanks a lot for investigating this!

**Comment by hjmjohnson** [comment]
@SimonRit I think this is now fixed.

**Comment by SimonRit** [comment]
Yes, both the Windows and MacOS compilations on [RTK dashboard](https://my.cdash.org/index.php?project=RTK) are fixed, thanks a lot!
