### ISSUE TITLE
build results vary from build machine CPU

### ISSUE THREAD

**Issue by bmwiedemann** [InsightSoftwareConsortium/ITK#1939]
# Description

While working on reproducible builds for openSUSE, I found that
our insighttoolkit package varied from the type of build machine CPU
that randomly gets chosen from the pool of build workers.

This is because `InsightToolkit-5.1.0/CMake/ITKSetStandardCompilerFlags.cmake` has `-mtune=native`
and [dropping this helped](https://build.opensuse.org/request/show/823615) to make builds reproducible.

See https://reproducible-builds.org/ for why this matters.

### Steps to Reproduce

1. build ITK on 2 hosts with different CPU types
2. compare binaries

### Expected behavior

It should be possible to get bit-identical build results on different build machines.
May be triggered via a cmake flag or the [`SOURCE_DATE_EPOCH` environment variable](https://reproducible-builds.org/specs/source-date-epoch/)

### Actual behavior

build results vary from build machine CPU

### Reproducibility

100%

### Versions

5.1

### Environment

openSUSE-Tumbleweed-20200728

### Additional Information

This PR was done while working on reproducible builds for openSUSE.

**Comment by thewtex** [comment]
@bmwiedemann thanks for working on the openSUSE packages! :package: :pray: 

Perhaps a different `-mtune` value should be specified in the package build configuration to select the target cpu?

**Comment by gdevenyi** [comment]
I believe -mtune=generic is the recommended way to produce "code optimized for the most common CPUs at the time the version of gcc was released"

**Comment by gdevenyi** [comment]
> ‘generic’
> Produce code optimized for the most common IA32/AMD64/EM64T processors. If you know the CPU on which your code will run, then you should use the corresponding -mtune or -march option instead of -mtune=generic. But, if you do not know exactly what CPU users of your application will have, then you should use this option.
> 
> As new processors are deployed in the marketplace, the behavior of this option will change. Therefore, if you upgrade to a newer version of GCC, code generation controlled by this option will change to reflect the processors that are most common at the time that version of GCC is released.
> 
> There is no -march=generic option because -march indicates the instruction set the compiler can use, and there is no generic instruction set applicable to all processors. In contrast, -mtune indicates the processor (or, in this case, collection of processors) for which the code is optimized.

https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

**Comment by bmwiedemann** [comment]
Yes, `-mtune=generic` sounds good. I tested that it also builds reproducibly.

**Comment by dzenanz** [comment]
Close the issue?

**Comment by bmwiedemann** [comment]
@dzenanz I'd prefer to see #1953 merged

**Comment by hjmjohnson** [comment]
-mtune=generic is the least common denominator, which means only use instructions from 20 years ago.

**Comment by blowekamp** [comment]
> -mtune=generic is the least common denominator, which means only use instructions from 20 years ago.

It is my understanding that this is for the optimization of the instructions ( order, delay etc. ),  not which instruction sets it can use. The `march` flag ( and others ) dictate which instruction can be used.
