### ISSUE TITLE
[ITK4.13] The origin of output using CropImageFilter is not updata

### ISSUE THREAD

**Issue by FrankyTang** [InsightSoftwareConsortium/ITK#1949]
when i use CropImageFilter to crop image, i found that the origin of output image is the same as input image, but when I write the crop image, the origin has updated.

The code:
    using CropType = itk::CropImageFilter<InternalType, InternalType>;
    CropType::Pointer cropFilter = CropType::New();
    cropFilter->SetInput(m_image); // origin is [-113.7, -102.3, -66.57], spacing is [0.5, 0.5, 2], size is[400,400,48]
    InternalType::SizeType crop_size;
    crop_size[0] = 96;
    crop_size[1] = 96;
    crop_size[2] = 0;
    cropFilter->SetBoundaryCropSize(crop_size);
    auto image_sample = cropFilter->GetOutput();
    cropFilter->Update();
    
  //  it can write crop_image correctly. 
    auto writerSample = WriterInternalType::New();
    std::string debug_path = debug_root + "\\sample.mha";
    writerSample->SetInput(image_sample);
    writerSample->SetFileName(debug_path);
    writerSample->Update(); // origin is [-65.66, -54.28, -66.57], spacing is [0.5, 0.5, 2], size is[208, 208,48]

  // it is wrong origin
   std::cout << "internal origin:" <<image_sample->GetOrigin() << std::endl;
   // origin must be [-65.66, -54.28, -66.57], but cout is  [-113.7, -102.3, -66.57] same as input image.

**Comment by FrankyTang** [comment]
I found the code at itkExtractImageFilter(from Line 137-Line184):

1. // Set the output spacing and origin
2.   const ImageBase< InputImageDimension > *phyData;
3. 
4.   phyData =
5.     dynamic_cast< const ImageBase< InputImageDimension > * >( this->GetInput() );
6. 
7.   if ( phyData )
8.     {
9.     // Copy what we can from the image from spacing and origin of the input
10.     // This logic needs to be augmented with logic that select which
11.     // dimensions to copy
12. 
13.     const typename InputImageType::SpacingType &
14.     inputSpacing = inputPtr->GetSpacing();
15.     const typename InputImageType::DirectionType &
16.     inputDirection = inputPtr->GetDirection();
17.     const typename InputImageType::PointType &
18.     inputOrigin = inputPtr->GetOrigin();
19. 
20.     typename OutputImageType::SpacingType outputSpacing;
21.     typename OutputImageType::DirectionType outputDirection;
22.     typename OutputImageType::PointType outputOrigin;
23.     outputOrigin.Fill(0.0);
24. 
25.     if ( static_cast< unsigned int >( OutputImageDimension ) >
26.          static_cast< unsigned int >( InputImageDimension ) )
27.       {
28.       // copy the input to the output and fill the rest of the
29.       // output with zeros.
30.       for ( unsigned int i = 0; i < InputImageDimension; ++i )
31.         {
32.         outputSpacing[i] = inputSpacing[i];
33.         outputOrigin[i] = inputOrigin[i];
34.         for ( unsigned int dim = 0; dim < InputImageDimension; ++dim )
35.           {
36.           outputDirection[i][dim] = inputDirection[i][dim];
37.           }
38.         }
39.       for (unsigned int i=InputImageDimension; i < OutputImageDimension; ++i )
40.         {
41.         outputSpacing[i] = 1.0;
42.         outputOrigin[i] = 0.0;
43.         for ( unsigned int dim = 0; dim < InputImageDimension; ++dim )
44.           {
45.           outputDirection[i][dim] = 0.0;
46.           }
47.         outputDirection[i][i] = 1.0;
48.         }
49.       }

I don't understand why the output origin = input origin, because the position is different?

**Comment by blowekamp** [comment]
Look at `LargestPossibleRegion::Index`. Most images will have a zero vector for this, but after cropping it may be non-zero. The Origin is defined as the physical location of the zero index. As mosts file format don't support the concept of "LargestPossibleRegion", so the written image adjust the LargestPossibleRegion to have a starting index of zero, and adjusts the origin accordingly.

**Comment by FrankyTang** [comment]
soga,thanks.
