### ISSUE TITLE
gold linker is deprecated now

### ISSUE THREAD

**Issue by opoplawski** [InsightSoftwareConsortium/ITK#1952]
### Description

ITK defaults to using the "gold" linker on linux if present.  Word on the street is that this linker is deprecated - at least as of Fedora 33 - and in particular does not support LTO (link time optimizations) that Fedora is starting to enable by default.  The build fails with:
```
/usr/bin/ld.gold: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
gmake[2]: *** 
[Modules/Filtering/ImageIntensity/test/CMakeFiles/ITKImageIntensityTestDriver.dir/build.make:1307: 
bin/ITKImageIntensityTestDriver] Error 1
```
When compiled with ```-flto=auto -ffat-lto-objects```

A test of compiles on Fedora rawhide saw no overall speed different between using "gold" and the default linker.  Time to change the default?

### Versions
4.13.3

**Comment by gdevenyi** [comment]
References
https://fedoraproject.org/wiki/Changes/BINUTILS_GOLD
https://www.phoronix.com/scan.php?page=news_item&px=GNU-Gold-Stagnate-F31

**Comment by opoplawski** [comment]
I will not however that reverting to the standard linker does not resolve the LTO build failure, so it's less of a concern than I initially thought it was.  At least for now.

**Comment by thewtex** [comment]
When performing a fresh, build compile times dominate over link times, so the linker speed benefits only really shine with incremental (development builds).

But, if the gold linker is not well maintained, we could remove support for it.
