### ISSUE TITLE
Nifti file writing failure is not reported

### ISSUE THREAD

**Issue by lassoan** [InsightSoftwareConsortium/ITK#1958]
### Description

When attempting to write a nifti file to an invalid location (for example, `C:\Windows\something.nii`) then no file is created there yet no error is reported.

The issue is that the error is swallowed in both niftilib and nifti2 (just "reported" with LNI_FERR macro, which does not throw an exception or reports the error to ITK in any other way):

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_io.c#L5775

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/NIFTI/src/nifti/nifti2/nifti2_io.c#L7763

### Steps to Reproduce

Attempt to save an image into a read-only folder (such as `C:/Windows/something.nii`).

### Expected behavior

The file is not created and an error is reported.

### Actual behavior

The file is not created but error is NOT reported.

### Reproducibility

100%

### Versions

v5.1rc03 (based on code review, latest master works the same way)

### Environment

Windows 10

**Comment by hjmjohnson** [comment]
I will look into this sometime in the middle of next week.

**Comment by mbarann** [comment]
I also encountered this problem on Ubuntu 18.04. It took me a while to figure this out, because it was only visible as a subsequent error in my code.

**Comment by lassoan** [comment]
It would be important to fix this because it can lead to data loss.

**Comment by lassoan** [comment]
The issue is still relevant (it can lead to data loss). @hjmjohnson you indicated earlier that you would be willing to work on this.Is this still the case?

**Comment by lassoan** [comment]
The issue is still relevant (it can lead to data loss). @hjmjohnson you indicated earlier that you would be willing to work on this. Is this still the case?

**Comment by hjmjohnson** [comment]
@kian-weimer  Kian,  can you please review and correct this outstanding issue.  I was supposed to take care of it almost 2 years ago, but forgot.

Hans

**Comment by kian-weimer** [comment]
@hjmjohnson I'm looking into this. I'll have to familiarize myself with the process first.

**Comment by hjmjohnson** [comment]
Initial part of this fix is being investigated upstream:  https://github.com/NIFTI-Imaging/nifti_clib/pull/146

**Comment by hjmjohnson** [comment]
Finally have nifti fixed incorporated upstream that will allow this to be addressed.  https://github.com/InsightSoftwareConsortium/ITK/pull/3509

**Comment by dzenanz** [comment]
Will you propose the changes Hans?

**Comment by hjmjohnson** [comment]
Yes.  I just need to find the time.
