### ISSUE TITLE
Resample with LabelImageGaussianInterpolateImageFunction is spending 90% time in vnl_vector allocation/destruction

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITK#1961]
### Description

Profiling where time is spent resampling (increase resolution in z-direction) a large 3D segmentation with many labels (>350) I found the surprising result that most of the time (>90%) is spent allocating/destroying  vnl_vectors (new/delete) in EvaluateAtContinuousIndex.
I set Alpha = Sigma = 2*Spacing[0], so the cut-off distance is small.

These arrays are used for the ERF difference arrays computed in ComputeErrorFunctionArray.

On my Windows 10 machine, code compiled with Visual Studio 2015 (x64, Release):
50% of the time is spent in the destructor,
and 44% in the allocation. 

I would propose to use one of the following strategies:

1. A thread specific (tbb::enumerable_thread_specific_) vnl_vector could be used, which is allocated once and reused.

2. Or the memory could be allocated on the stack instead of the heap for a small cut-off sizes, using a fixed size array, and dynamic size array for large cut-off.

### Impact analysis

Removing the 90% time for new/delete would increase performance by up to factor 10, at least for MSVC.

### Expected behavior

```none
```

Example code is available e.g. here: https://itk.org/Doxygen/html/SphinxExamples_2src_2Core_2ImageFunction_2ResampleSegmentedImage_2Code_8cxx-example.html#_a5

### Versions

ITk version 4.13

### Environment

Windows
Visual Studio 2015, x64, CMake RelWithDebInfo

**Comment by gdevenyi** [comment]
Not to ignore this performance bug, but you may be interested in https://itk.org/Doxygen/html/group__GenericLabelInterpolator.html

Which is a generalization of the code you're using. In addition, the tests developed during its implementation indicate that Linear interpolator yields better results.

**Comment by dzenanz** [comment]
I think @blowekamp and @hjmjohnson might have touched allocation/deallocation in a similar scenario since version 4.13. As the relevant code has changed since ([old](https://github.com/InsightSoftwareConsortium/ITK/blob/v4.13.3/Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.hxx#L179-L223), [new](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.hxx#L179-L214)) it is worth trying with ITKv5 (either 5.1.1 or master).

**Comment by hjmjohnson** [comment]
@dyollb Can you verify that this problem persists in ITK 5.1.1?

**Comment by dyollb** [comment]
for ITK 5.1.1 most of the time is spent computing the error function, so the issue is resolved.
