### ISSUE TITLE
itkExpectationMaximizationMixtureModelEstimator.hxx includes its header as ../include/itkExpectationMaximizationMixtureModelEstimator.h

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITK#1964]
### Description

The file itkExpectationMaximizationMixtureModelEstimator.hxx

https://github.com/InsightSoftwareConsortium/ITK/blob/9d0f5f7398287c24d5c926a214582d53b81f4596/Modules/Numerics/Statistics/include/itkExpectationMaximizationMixtureModelEstimator.hxx

includes its header as ../include/itkExpectationMaximizationMixtureModelEstimator.h

while this works when you build ITK, it breakes compilation of client projects, when ITK is installed, because then itkExpectationMaximizationMixtureModelEstimator.h is inside a folder include/ITK-5.1

### Steps to Reproduce

Build and install. Try to build client project which includes itkExpectationMaximizationMixtureModelEstimator.h

### Expected behavior

Client project should compile.

### Actual behavior

explained above

```none
```

### Reproducibility

100% all the time

### Versions

ITK-5.1

**Comment by dzenanz** [comment]
That change was made during a refactoring. It should be `#include "itkExpectationMaximizationMixtureModelEstimator.h"`. Do you want to make this a [PR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by dyollb** [comment]
already fixed in master two months ago: 880a932fce9ea2902465042e989c0ab65a8d7f6d
