### ISSUE TITLE
ITK failed to build due to error C2169: 'lrintf': intrinsic function, cannot be defined with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [InsightSoftwareConsortium/ITK#1967]
Hi All,

ITK failed to build due to error C2169: 'lrintf': intrinsic function, cannot be defined with MSVC on windows. It can be reproduced on master branch latest commit 26079ef.  Could you please help look at this? Thanks a lot!

Repro Steps:
1. git clone https://github.com/InsightSoftwareConsortium/ITK.git F:\gitP\InsightSoftwareConsortium\ITK
2. Open VS2019 x64 command prompt as admin and browse to F:\gitP\InsightSoftwareConsortium\ITK
3. Apply itk_bug623130.patch
4. mkdir build_amd64 and cd build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..
6. set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %_CL_%
7. msbuild /m /p:Platform=x64 /p:Configuration=Release All_BUILD.vcxproj /t:Rebuild

Build_log:
[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/5141200/build.log)
itk_bug623130.patch:
[itk_bug623130.zip](https://github.com/InsightSoftwareConsortium/ITK/files/5141203/itk_bug623130.zip)

ErrorMessage:
188>F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\OpenJPEG\src\openjpeg\opj_includes.h(106,35): error C2169: 'lrintf': intrinsic function, cannot be defined [F:\gitP\InsightSoftwareConsortium\ITK\build_amd64\Modules\ThirdParty\OpenJPEG\src\openjpeg\itkopenjpeg.vcxproj]

**Comment by dzenanz** [comment]
This looks like a problem in OpenJPEG, and it should be updated [[1](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/OpenJPEG/src/README-ITK.txt)][[2](https://discourse.itk.org/t/incomplete-mangling-of-the-gdcm-openjpeg-library/1334/4?u=dzenanz)]. @malaterre it looks like you wrote OpenJPEG's [CMake buildsystem](https://github.com/uclouvain/openjpeg/blob/c7798bb0c636c89ab7f0bab4d89e7f0136e0e55a/CMakeLists.txt#L2). Do you have time to update it in ITK?

**Comment by spacelg** [comment]
@dzenanz , Thanks for your info. This issue can still reproduced on ITK latest reversion. @malaterre could you please look at this issue?

Thanks,
Lin

**Comment by malaterre** [comment]
BTW `lrintf` has been renaming `opj_lrintf` upstream for a while

**Comment by dzenanz** [comment]
We need to update the version of OpenJPEG which is [bundled with ITK](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/OpenJPEG). As third party libraries are not overly related to ITK, even people not proficient with ITK should be able to update them. @spacelg could you give it a try?

**Comment by spacelg** [comment]
@dzenanz  Thanks for your info and help.  I tried to apply a patch for ../Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h as below. It can build pass. Thank you very much.

diff --git a/Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h b/Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h
index e75a220d4d..60d185e233 100644
--- a/Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h
+++ b/Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h
@@ -92,7 +92,7 @@ Most compilers implement their own version of this keyword ...
 
 /* MSVC 64bits doesn't support _asm */
 #if !defined(_WIN64)
-static INLINE long lrintf(float f){
+static INLINE long opj_lrintf(float f){
   int i;
 
   _asm{
@@ -103,7 +103,7 @@ static INLINE long lrintf(float f){
   return i;
 }
 #else
-static INLINE long lrintf(float x){
+static INLINE long opj_lrintf(float x){
   long r;
   if (x>=0.f)
   {

**Comment by dzenanz** [comment]
Could you turn that [into a PR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by N-Dekker** [comment]
@spacelg @dzenanz @malaterre Is there a specific reason why it was decided not to upgrade OpenJPEG? The `lrintf` problem is properly fixed with commit https://github.com/uclouvain/openjpeg/commit/c423cc84e7be79051a7f9631fa26aa7d072361f2#diff-91c70438e617694516cb0ab60919517ff67034354cf73070cb243a7680411f89R126 which is included with OpenJPEG [v2.1.1](https://github.com/uclouvain/openjpeg/releases/tag/v2.1.1) (July 2016)

**Comment by dzenanz** [comment]
Yes. The specific reason is: that is expected to take non-trivial effort. Of course, anyone can volunteer to do it. Skill required is mostly CMake-related, not really ITK-related.
