### ISSUE TITLE
BUG: hdf5 missing version

### ISSUE THREAD

**Issue by thkvc** [InsightSoftwareConsortium/ITK#1971]
### Description
After building latest code on github, all binaries with the suffix "-5.2" before ".so" and ".dll" except hdf5 don't have them.
Tested on Ubuntu and Windows
This doesn't happen in vtk

Note:
I build shared library and the result of hdf5 is:
ITK:
      - Windows: itkhdf5.dll, itkhdf5_cpp.dll
      - Ubuntu: libitkhdf5.so, libitkhdf5_cpp.so
VTK:
      - Windows: vtkhdf5-9.0.dll, vtkhdf5_hl-9.0.dll
      - Ubuntu: libvtkhdf5-9.0.so, libvtkhdf5_hl-9.0.so

**Comment by dzenanz** [comment]
In addition to missing `-5.2` suffix, it also has `lib` prefix, so the file is named `libitkhdf5.lib` instead of `itkhdf5-5.2.lib`.

**Comment by dzenanz** [comment]
@thewtex where does the version suffix come from? I looked at double conversion for comparison and could not spot significant difference.

**Comment by thewtex** [comment]
A call to `itk_module_target_name` in the HDF5 module CMake configuration may help:

https://github.com/InsightSoftwareConsortium/ITK/blob/7f36e8e2ff52f402a4c9377fbdc68c3ba018e6c9/CMake/ITKModuleMacros.cmake#L393-L411

**Comment by dzenanz** [comment]
@thkvc can you give #2229 a try?
