### ISSUE TITLE
Extract Number of boundary pixels

### ISSUE THREAD

**Issue by spyridon97** [InsightSoftwareConsortium/ITK#1973]
Given an N-D (unsigned char) image , which has 0 for background value and 1 for the foreground value, Is it possible to easily calculate the number of pixels that are boundary?

A boundary foreground pixel is the one that has at least one neighbor background pixel

**Comment by dzenanz** [comment]
This is more of a question for the [forum](https://discourse.itk.org/), and not exactly an issue in ITK.

One possible way is to use [binary erosion](https://itk.org/Doxygen/html/group__ITKBinaryMathematicalMorphology.html) and count the eroded pixels, or maybe even use [LabelStatistics](https://itk.org/Doxygen/html/classitk_1_1LabelStatisticsImageFilter.html) directly.
