### ISSUE TITLE
Need keep_axis in itk.size()

### ISSUE THREAD

**Issue by Nic-Ma** [InsightSoftwareConsortium/ITK#2006]
### Description

I used `itk.array_view_from_image(img, keep_axes=False)` to load array data, but `itk.size(img)` gives reverse order of shape.
For example:
```py
data = itk.array_view_from_image(img, keep_axes=False)
shape = list(itk.size(img))
data.shape: (64, 128, 96)
shape: [96, 128, 64]
```
### Expected behavior

Need to add `keep_axes=False` for itk.size.

**Comment by dzenanz** [comment]
numpy and ITK use different convention of specifying/displaying image size. ITK uses IJK (i coordinate varies the fastest, then j, k varies the slowest). Assuming identity direction, that corresponds to XYZ. I think that numpy uses ZYX. If this is not the point of the issue, please elaborate.

**Comment by Nic-Ma** [comment]
OK, I will use `shape = list(itk.size(img)).reverse()` instead.
Thanks.
