### ISSUE TITLE
unterminated string constant when compiling ITK 5.1.1

### ISSUE THREAD

**Issue by mboisson** [InsightSoftwareConsortium/ITK#2026]
### Description
I am trying to compile ITK 5.1.1 from source. I have VTK 8.2.0 installed as a dependency. I get the following error when compiling : 

```
13687 /tmp/mboisson/avx2/ITK/5.1.1/GCC-9.3.0/easybuild_obj/Wrapping/Typedefs/VtkGlue.i:97: Error: Unterminated string constant
13688 /tmp/mboisson/avx2/ITK/5.1.1/GCC-9.3.0/easybuild_obj/Wrapping/Typedefs/VtkGlue.i:50: Error: Missing #endif for conditional starting here
13689 make[2]: *** [Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/build.make:166: Wrapping/Modules/ITKVtkGlue/itkImageToVTKImageFilterPython.cpp] Error 1
13690 make[2]: Leaving directory '/tmp/mboisson/avx2/ITK/5.1.1/GCC-9.3.0/easybuild_obj'
13691 make[1]: *** [CMakeFiles/Makefile2:33039: Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/all] Error 2
``` 

### Reproducibility

100% of the time

### Versions

ITK 5.1.1, downloaded from the release section on Github

**Comment by mboisson** [comment]
I think I figured out the reason. I think cmake was not picking up the "right" python.

**Comment by mboisson** [comment]
Well, no... that was not it. I still encounter the issue.

**Comment by mboisson** [comment]
Note that ITK 5.0.1 compiles just fine on the same system.

**Comment by dzenanz** [comment]
@thewtex is VTKGlue supposed to work with wrapping?

**Comment by thewtex** [comment]
Should be addressed by https://github.com/InsightSoftwareConsortium/ITK/pull/2242/files
