### ISSUE TITLE
Fix ITK Python Windows CI failing

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#2056]
### Description
The Windows ITK Python Azure pipeline has/is failing.

We've several different reasons, all due to linking with the Python wrapped classes.  For example, MSVC, a few days ago, threw a python38.lib could not be found when building _ITKPyBasePython.pyd.  Today, _ITKCommonPython throws a ```ImportError: DLL load failed while importing _ITKCommonPython: The specified module could not be found.
```.  I think these all have to do with an inconsistency in which Python version ITK is building/linking against.  I think it's ignoring what is specified in the Azure Pipeline.  The VM likely has a MSVC Python in scope, as well as several versions in the ``` C:/hostedtoolcache/``` directory.

### Actual behavior

```none
```

**Comment by brad-t-moore** [comment]
So, when I ran this the Windows Python actually passed my account Azure Pipelines.  I think it might be due to issue #2068.  I think the hostedcache directory is saved between runs, so it could be that my new account didn't have other versions of Python that could have been picked up from there.  I'm going to try and configure it use another (newer) version Python and then rerun the original.

**Comment by brad-t-moore** [comment]
#2068 might fix this, if not, I think additionally specifying Python_FIND_REGISTRY=NEVER in the WindowsPython YAML will fix it.  It looks like Azure uses PATH to specify the YAML Python version, but on Windows CMake's FindPython defaults to using registry.  Also, CMP0094 was searching everything and then returning the highest Python version found, so that behavior has been changed by #2068.

**Comment by thewtex** [comment]
:tada: :taco:
