### ISSUE TITLE
ITK_USE_GPU related issue

### ISSUE THREAD

**Issue by hubutui** [InsightSoftwareConsortium/ITK#2071]
Hey, glad to know that ITK got a `ITK_USE_GPU` option, is cuda supported?
It seems that you'd like to find nvidia's OpenCL with hardcode path, https://github.com/InsightSoftwareConsortium/ITK/blob/fa1082b92953b09c48ae0d65a96ddfbfd33c7c36/CMake/FindOpenCL.cmake#L82
You might wanna use https://cmake.org/cmake/help/v3.14/module/FindCUDA.html to find CUDA. cudafftw is shipped with cuda, so you might wanna take care of https://github.com/InsightSoftwareConsortium/ITK/blob/fa1082b92953b09c48ae0d65a96ddfbfd33c7c36/CMake/FindFFTW.cmake#L61-L85

**Comment by SimonRit** [comment]
Cuda is not supported by the ITK_USE_GPU and it's not just a matter of finding the package, the GPU code is specific to the package. OpenCL is compatible with NVidia cards so you might not need to use Cuda to use the GPU code included by ITK_USE_GPU. If you want to use it, Kitware has developped an ITKCudaCommon package which is currently included in RTK, see [here](https://github.com/SimonRit/RTK/tree/master/utilities/ITKCudaCommon).

**Comment by hubutui** [comment]
OK, I see. I'm currently use [ocl-icd](https://www.archlinux.org/packages/extra/x86_64/ocl-icd/)

**Comment by dzenanz** [comment]
If your question has been answered, please close the issue.
