### ISSUE TITLE
Update Python version checks

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#2082]
### Description

Refer to discussion in #2068.  [ITKSetPython3Vars.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKSetPython3Vars.cmake) needs update the version checking to Python 3.6 as well as extend the version checking when CMake > 3.15 is used (current code doesn't check this case).

### Actual behavior

```none
```

**Comment by thewtex** [comment]
Should be addressed by https://github.com/InsightSoftwareConsortium/ITK/commit/0c3b8cbf9b0b25f2fed789c1a7effe48f29b6967 since we require CMake >= 3.16.
