### ISSUE TITLE
Handle.net Links Broken in Online Doxygen Documentation

### ISSUE THREAD

**Issue by crocodoyle** [InsightSoftwareConsortium/ITK#2089]
### Description
The https://hdl.handle.net links are all broken in the online documentation. For example, at:
https://itk.org/Doxygen/html/classitk_1_1MaximumProjectionImageFilter.html

### Expected information

Enough information to retrieve the original paper

### Actual information

A broken hyperlink without even the title of the paper

**Comment by thewtex** [comment]
The handle links need to be replaced by the *insight-journal.org/browse/publication/XXX* links.

**Comment by thewtex** [comment]
Addressed in https://github.com/InsightSoftwareConsortium/ITK/pull/2129
