### ISSUE TITLE
Support running filters on multi-channel torch tensors

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2120]
### Description

ITK filters now support running on `torch.Tensor`. However, `torch.Tensor`'s have a contiguous channel memory layout while `itk.Image` is interleaved channels. We need to adjust the memory layout to account for this.

### Steps to Reproduce

Run an ITK filter on a torch tensor with multiple channels.

### Expected behavior

Changes in the `itk.Image` -> `torch.Tensor` direction can be found here:

https://github.com/Project-MONAI/MONAI/blob/c561521068c062e95c937ee2e94b9ce7b3275484/monai/data/image_reader.py#L247-L259

A similar layout change is required to go the opposite direction.

### Actual behavior

We should have tests to verify the correct behavior. 

### Versions

This functionality is in ITK `master` for the 5.2.0 release.

**Comment by dzenanz** [comment]
See also https://github.com/Project-MONAI/MONAI/pull/1147.

**Comment by thewtex** [comment]
Code locations:

https://github.com/InsightSoftwareConsortium/ITK/blob/82754b50fc3bb9591a1341cff12e2125413109fa/Wrapping/Generators/Python/itk/support/itkHelpers.py#L123-L125

https://github.com/InsightSoftwareConsortium/ITK/blob/82754b50fc3bb9591a1341cff12e2125413109fa/Wrapping/Generators/Python/itk/support/itkHelpers.py#L140-L142

https://github.com/InsightSoftwareConsortium/ITK/blob/82754b50fc3bb9591a1341cff12e2125413109fa/Wrapping/Generators/Python/itk/support/itkHelpers.py#L160-L162

https://github.com/InsightSoftwareConsortium/ITK/blob/82754b50fc3bb9591a1341cff12e2125413109fa/Wrapping/Generators/Python/itk/support/itkHelpers.py#L172-L174

**Comment by dzenanz** [comment]
Is there a filter which takes two 2D RGB images as inputs and produces a 2D RGB image as output? What is the best filter to use in the test?

**Comment by thewtex** [comment]
How about `AddImageFilter`?

**Comment by dzenanz** [comment]
`AddImageFilter` is not [wrapped](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageIntensity/wrapping/itkAddImageFilter.wrap) for RGB images, only scalar ones. I will try to add wrapping for RGB-UC and see whether that works.
