### ISSUE TITLE
Enable Python import analysis for bundlers like pyinstaller, py2app, py2exe

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#214]
Python tools to bundle applications and generate installers analyze Python `import`'s to determined what should be included in the package. Some examples include [pyinstaller](www.pyinstaller.org), [py2app](https://py2app.readthedocs.io/en/latest/), [py2exe](http://www.py2exe.org/).

To enable these apps to work with the ITK Python package, we need to make some changes to `itkBase.py`, e.g.

- [`known_modules`](https://github.com/InsightSoftwareConsortium/ITK/blob/66b1d1de60279aed30b8ac9575f99f5e7780ca9e/Wrapping/Generators/Python/itkBase.py#L274) should be defined in the global namespace
- Instead of [`exec`'ing the modules](https://github.com/InsightSoftwareConsortium/ITK/blob/66b1d1de60279aed30b8ac9575f99f5e7780ca9e/Wrapping/Generators/Python/itkBase.py#L282-L286), use [Python's import machinery](https://docs.python.org/3/library/importlib.html).

**Comment by fbudin69500** [comment]
A [PR for pyinstaller was opened](https://github.com/pyinstaller/pyinstaller/pull/3998)

**Comment by fbudin69500** [comment]
In the meantime, before the PR is merged in pyinstaller (See link above), one can use the hook file above and add the following file to their command line when calling pyinstaller: `--additional-hooks-dir`

**Comment by fbudin69500** [comment]
Closing this issue as there is no problem in ITK to use PyInstaller (see comments and links above).
