### ISSUE TITLE
CMake Error: install(EXPORT "ITKTargets" ...) includes target "gdcmjpeg8" more than once in the export set.

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#2162]
### Description

RTK CI now fails with this error in the Build ITK step, see https://github.com/SimonRit/RTK/runs/1524238640. I noticed #2146 but the problem is on Ubuntu, not on mac OS. Since RTK uses the new github actions, I assume that the same problem will occur with the CI of all remote modules which use the ITKModuleTemplate.

### Steps to Reproduce

See https://github.com/SimonRit/RTK/blob/master/.github/workflows/build-test-package.yml#L52-L56.

### Expected behavior

ITK configuration and compilation!

### Actual behavior

Error in the title when configuring ITK.

### Reproducibility

100%

### Versions

ITK v5.1.2

**Comment by issakomi** [comment]
There is already the issue on _Sourceforge_ [515](https://sourceforge.net/p/gdcm/bugs/515/). Probably the owner will look at it soon.
It is related to code like (not only here, many places)

```
if(NOT JPEG_INSTALL_NO_LIBRARIES)
  install(TARGETS ${JPEG_LIBRARY_NAME}8
    EXPORT ${GDCM_TARGETS_NAME} <---------------------------------
    RUNTIME DESTINATION ${JPEG_INSTALL_BIN_DIR} COMPONENT Applications
    LIBRARY DESTINATION ${JPEG_INSTALL_LIB_DIR} COMPONENT Libraries ${NAMELINK_SKIP}
    ARCHIVE DESTINATION ${JPEG_INSTALL_LIB_DIR} COMPONENT DebugDevel
  )
  if(NAMELINK_ONLY)
  install(TARGETS ${JPEG_LIBRARY_NAME}8
    EXPORT ${GDCM_TARGETS_NAME} <-----------------------------------
    LIBRARY DESTINATION ${JPEG_INSTALL_LIB_DIR} COMPONENT DebugDevel ${NAMELINK_ONLY}
  )
  endif()
endif()
```
In top level GDCM CMakeLists.txt file is block
```
if(BUILD_SHARED_LIBS)
  set(NAMELINK_ONLY NAMELINK_ONLY)
  set(NAMELINK_SKIP NAMELINK_SKIP)
endif()
```
where it is possible e.g. to comment _NAMELINK_ONLY_ and _Cmake_ will generate files, for example, not tested, just FYI.

**Comment by issakomi** [comment]
Seems to work again as is with nightly build _CMake 3.19.2_

**Comment by SimonRit** [comment]
Thanks. The .github action of remote packages does not install cmake, it uses the version delivered with the ubuntu-18.04 os. Should this be changed?
I admit I don't understand this problem because it appeared suddenly without changing the os nor the ITK version...

**Comment by SimonRit** [comment]
Sorry, they actually update the os env, see the problem [here](https://github.com/actions/virtual-environments/commit/5987ab0f60c8788d73e883406c9a17e7ea054194#diff-8d528b68ca937dfe5a0194829f0eb2633bc3d7a3105a637ccb534a4da765f7a3).

**Comment by thewtex** [comment]
This is related to a regression in CMake 3.19.1, xref https://gitlab.kitware.com/cmake/cmake/-/issues/21529

Yes, we should start using an explicit CMake version in the remote module GitHub Actions. I can start a patch.

CC @bradking @malaterre

**Comment by thewtex** [comment]
PR: https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/98

**Comment by SimonRit** [comment]
This worked for me, thanks, see [here](https://github.com/SimonRit/RTK/commit/a3512e999126dab87702726b656484afb2e0569e), (but I now have [another problem](https://github.com/SimonRit/RTK/runs/1553838296?check_suite_focus=true) with MacOS python packages).

**Comment by thewtex** [comment]
> This worked for me, thanks, see here,

:+1: 

> (but I now have another problem with MacOS python packages).

I am working on this -- a different issue, but also related to updates on the build system.

**Comment by thewtex** [comment]
@SimonRit both issues should now be addressed following updates in `ITKModuleTemplate` `master` -- if not, please re-open.

**Comment by SimonRit** [comment]
Yes, thanks, I confirm that it solved it.
