### ISSUE TITLE
 Target "ITKReview" requests linking to directory "/opt/cuda/lib64".

### ISSUE THREAD

**Issue by hatiden** [InsightSoftwareConsortium/ITK#217]
#209 [Before submitting an issue, please check that your issue hasn't been already
filed]

### Description

Hello,
I tried to build the ITKREVIEW in Ubuntu 16.04,When I set Module_ITKREVIEW ON and use ccmake to generante the files.WARNING ERRORS AS FOLLOWS:

 WARNING: Target "ITKReview" requests linking to directory "/opt/cuda/lib64".  Targets may link only to libraries.  CMake is dropping the
 item.

 WARNING: Target "ITKReview" requests linking to directory "/opt/cuda/lib64".  Targets may link only to libraries.  CMake is dropping the
 item.

 WARNING: Target "ITKReview" requests linking to directory "/opt/cuda/lib64".  Targets may link only to libraries.  CMake is dropping the
 item.

 WARNING: Target "ITKReview" requests linking to directory "/opt/cuda/lib64".  Targets may link only to libraries.  CMake is dropping the
 item.
I 'VE tried to add the link_directories（“/opt/cuda/lib64”） in the top of the CMakeList.txt,error still

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

[Provide a minimal, complete, compilable, and verifiable example (commonly
abbreviated as MWE, minimal working example) or code snippet, either through a
[GitHub gist](https://gist.github.com/) or providing your own files (including
your source code, `CMakeLists.txt` file and your data) reproducing the issue or
clearly showing where your concern lies.

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproducibility

[What percentage of the time does it reproduce?]

### Versions

[If a tagged version, you can get this information by inspecting the
`ITK_VERSION_MAJOR` `ITK_VERSION_MINOR` and `ITK_VERSION_PATCH` variable
values in the `ITKConfig.cmake` file]

[If the commit number is required, run `$ git rev-parse --short HEAD`]

### Environment

[Which your OS and compiler are]

### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue.]

Note: Use issues for their purpose; issues are not for code help. Need help? Ask
your question at [https://discourse.itk.org/](https://discourse.itk.org/)

**Comment by thewtex** [comment]
Hi @hatiden ,

Could you please provide more information on the ITK version that you are trying to build and the CMake configuration options passed?

Also, note that there are [ITK packages available in Ubuntu 16.04](https://blog.kitware.com/itk-packages-in-linux-distributions/).
