### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by melrobin** [InsightSoftwareConsortium/ITK#2253]
### Description
This may not count as a bug, but I have encountered a build error from the latest developer sources.  

### Steps to Reproduce
1.  Turn on Module_MorphologicalContourInt 
2.  Ensure that all wrappings are turned ON.
3. Build (generate Makefile and make)

### Expected behavior
Build complete

### Actual behavior
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:220:16: error: cannot convert 'itk::CovariantVector<double, 4>' to 'unsigned short' without a conversion operator
      auto b = static_cast<T2>(a);

```none
```

### Reproducibility

All the time
### Environment
Fedora 33, gcc 10.2.1

### Additional Information

Without enabling the module, ITK builds fine.
 Here is more of the error which is repeated several times:
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:227:3: note: in instantiation of member function 'itk::Concept::Convertible<itk::CovariantVector<double, 4>, signed char>::Constraints::constraints' requested here
  itkConceptConstraintsMacro();

**Comment by melrobin** [comment]
I narrowed down the failing command here:
cd /home/melrobin/packages/ITK/build/Wrapping/Modules/RLEImage && ../../Generators/CastXML/castxml/bin/castxml -o /home/melrobin/packages/ITK/build/Wrapping/itkRLERegionOfInterestImageFilter.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-gnu "(" /usr/lib64/ccache/c++ -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel -msse2 -msse2 -std=c++11 ")" -w -c @/home/melrobin/packages/ITK/build/Wrapping/RLEImage.castxml.inc /home/melrobin/packages/ITK/build/Wrapping/itkRLERegionOfInterestImageFilter.cxx

**Comment by dzenanz** [comment]
I have a fix: https://github.com/KitwareMedical/ITKRLEImage/pull/52. It has a minor const-ness issue on Linux, I will fix that soon and force-push.
