### ISSUE TITLE
NRRD to Bit Array

### ISSUE THREAD

**Issue by praveen5959** [InsightSoftwareConsortium/ITK#2263]
I want to read a NRRD file and convert the data to Bit Array format. Can this be done using ITK or any other tools?

If so can someone point me to the resource or documentation. 

I have tried the ITK NRRD Reader but it can only give output in ASCII not in Bit Array format.

**Comment by dzenanz** [comment]
What is Bit Array format? If you mean packing 8 bits into a byte, NRRD doesn't do that. Most other libraries don't do it, either. You have to do it yourself. And you need to decide whether to "pack" 8 consecutive bits along i axis, what to do about case when dimensions do not divide evenly (let's say a 9x9x9 image), whether to pack a block of 2x2x2 pixels into one byte, and again what to do about uneven image sizes etc. A lot of hassle, which only makes sense in very specific circumstances.

**Comment by dzenanz** [comment]
Closing, as this seems to have been a question and not an issue.
