### ISSUE TITLE
Need to find/replace all #include with new path which doesn’t fit with old path

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2277]
Opened a thread on CMake forum : https://discourse.cmake.org/t/need-to-find-replace-all-include-with-new-path-which-doesnt-fit-with-old-path/2661

Clone github repo https://github.com/al-sabr/CTK/tree/ctk-blueberry-port-from-mitk and try to compile with CMake.

Compilation without the following errors:

```
G:\programming\cplusplus\CTK\Libs\mbilog\itkThreadPool.cxx(21,10): fatal error C1083: Cannot open include file: 'src/itksys/SystemTools.hxx': No such file or directory [G:\programming\cplusplus\CTK\build\CTK-build\Libs\mbilog\CTKmbilog.vcxproj]
2>    itkMultiThreaderBase.cxx
2>  G:\programming\cplusplus\CTK\Libs\mbilog\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cplusplus\CTK\build\CTK-build\Libs\mbilog\CTKmbilog.vcxproj]
```

Normal compilation

```none
```

100% of time it happens

### Versions

Windows 10 with VS 2019

**Comment by dzenanz** [comment]
Why are you trying to incorporate ITK into CTK? They have different purposes, image analysis and user interface. Both are usually direct dependencies of image processing applications with a GUI.

**Comment by dzenanz** [comment]
I took a look at your branch. You only copied a part of ITK into your repo. It is super-hard to make that work, with ITK and most other libraries.

**Comment by al-sabr** [comment]
I wanted to make CTK totally independent of ITK but somehow there is a minor part which is really used from mbilog, Blueberry Framework. I was trying to understand why the #include are not working although everything is compiling.

**Comment by dzenanz** [comment]
Than it is more of a issue with CMake code, not ITK. It is best to continue this discussion on the CMake forum.

**Comment by al-sabr** [comment]
Thank you I really appreciate your inputs.
