### ISSUE TITLE
ITKV4_COMPATIBILITY disables filter progress reporting

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#228]
With `ITKV4_COMPATIBILITY` enabled during CMake configuration, the filters not longer report any progress or handle the abort flag. This is causing several test failure in SimpleITK related to testing for command, call backs, and progress with ITKv5.

https://open.cdash.org/testDetails.php?test=684541299&build=5643448
https://open.cdash.org/testDetails.php?test=709738030&build=5643448

This appears to be caused by setting `m_DynamicMultiThreading` to false in the ImageSource base class. The `ClassicMultiThread` method does not appear to report progress.

**Comment by dzenanz** [comment]
Thanks for the bug report Brad!

**Comment by blowekamp** [comment]
The following ITK test fail on ITK when `ITKV4_COMPATIBILITY` is enabled:
	1597 - itkStatisticsImageFilterTest (Failed)
	1598 - itkLabelStatisticsImageFilterTest (Failed)
	1605 - itkMinimumMaximumImageFilterTest (Failed)

These failures are due to the lack of progress reporting in this configuration.
