### ISSUE TITLE
Add assignment operator to H5DataSet

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITK#2288]
### Description

The assignment operator for `class DataSet` is used [here](https://github.com/InsightSoftwareConsortium/ITK/blob/586862ee3cd40d148cef1447513a11dbafb326e5/Modules/IO/HDF5/src/itkHDF5ImageIO.cxx#L715), [here](https://github.com/InsightSoftwareConsortium/ITK/blob/586862ee3cd40d148cef1447513a11dbafb326e5/Modules/IO/HDF5/src/itkHDF5ImageIO.cxx#L1089), and perhaps elsewhere but is not explicitly declared in `Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSet.h`.  Given that `class DataSet` uses reference counts and explicitly increments them in some constructors (see `H5DataSet.cpp`), this is scary if not actually a bug. 

### Expected coding style

Explicit declaration of the assignment operator would be more reassuring; whichever of the following is appropriate within the `class DataSet` declaration:
```C++
DataSet& operator=(const DataSet& original) = delete; // assignment is not supported
DataSet& operator=(const DataSet& original) = default; // even with reference counts, default is appropriate
DataSet& operator=(const DataSet& original);
```
The last form would need a supporting definition for the method.

### Actual coding style

The assignment operator is not explicitly declared.

### Versions

5.2.0

**Comment by thewtex** [comment]
We would want to submit this to upstream HDF5 first.
