### ISSUE TITLE
Compilation error with CTK and ITK

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2298]
All infos related to this is on another thread : commontk/CTK#949

https://discourse.itk.org/t/only-necessary-to-compile-itkcommon-with-kwsys-vxl/3863

**Comment by al-sabr** [comment]
Effort to move some parts of ITKCommon into another module : https://github.com/al-sabr/ITK/commits/itk-basic-internal-kws-vxl

**Comment by thewtex** [comment]
As commented in the CTK thread and on Discourse, this is not an issue with ITK.
