### ISSUE TITLE
Clean up CMake non-advanced cache variables

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2300]
### Description

In ITK's CMake configuration, only a few, commonly changed, high level cache variables  should be presented in the CMake GUI.

### Steps to Reproduce

Configure ITK with CMake, and use the ncurses or Qt GUI.

### Expected behavior

Only the cache variables:

- `BUILD_EXAMPLES`
- `BUILD_TESTING`
- `ITK_BUILD_DEFAULT_MODULES`
- `ITK_WRAP_PYTHON` should be present.

### Actual behavior

There are a number of other variables present that should be [`mark_as_advanced`](https://cmake.org/cmake/help/latest/command/mark_as_advanced.html) in the CMake configuration. Some should not be presented at all, and [`set` as `INTERNAL`](https://cmake.org/cmake/help/latest/command/set.html).

### Versions

 ITK 5.2 RC 2

**Comment by Leengit** [comment]
Pull Request #2423 marks all but those 4 variables as advanced.  Which ones should instead be `INTERNAL`?

**Comment by thewtex** [comment]
@Leengit thanks! Looks good.
