### ISSUE TITLE
Compiling ITK from CMake generated Project triggers hundreds of errors

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2326]
![image](https://user-images.githubusercontent.com/26530975/108257319-e521e380-715e-11eb-9657-72eccbd2ca12.png)

**Comment by dzenanz** [comment]
Which version of ITK you used, and which CMake options you used to configure it?

**Comment by al-sabr** [comment]
Latest found here : https://github.com/InsightSoftwareConsortium/ITK

No options at all only did configure & generate & open project & compile.

**Comment by thewtex** [comment]
Please take a look at the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf), Book 1, Chapter 2, on how to build ITK and an example project.

**Comment by al-sabr** [comment]
Isn't it supposed to build by default without any problem the way I did ?

**Comment by dzenanz** [comment]
It is supposed to build. Are you sure you did a clean build? And that Visual Studio installation is working well? Which version of VS and CMake are you using? Which version of Windows?

**Comment by al-sabr** [comment]
We should open this thread because I just tried to compile MITK and I get the same error as with when I tried to compile ITK independently.

Here is the log : https://www.pastbin.net/untitled-5

![](https://user-images.githubusercontent.com/26530975/108406375-a190ad80-7222-11eb-9c55-e3743d24443a.png)

**Comment by al-sabr** [comment]
Link to https://github.com/commontk/CTK/issues/949#issuecomment-777070686
