### ISSUE TITLE
PERF: Parallelize the loop over labels within ContourExtractor2DImageFilter

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITK#2343]
### Description

There is little to no interaction between the iterations of the loop over labels that computes contours with marching squares, in the `ContourExtractor2DImageFilter::GenerateDataForLabels` method.  It could instead be multi-threaded.

Possibilities include the approach from https://itk.org/ITKExamples/src/Core/Common/FilterAndParallelizeImageRegion/Documentation.html?highlight=lambda

Additionally, it may be possible to also parallelize by handling different parts of the image region in separate threads.

**Comment by dzenanz** [comment]
I could do this, unless you want it Lee.

**Comment by Leengit** [comment]
Yes, that would be great, though please wait until pull request #2323 is merged.

**Comment by dzenanz** [comment]
Can this be closed now?

**Comment by Leengit** [comment]
Addressed by #2384.
