### ISSUE TITLE
itk gpuBinaryMorphology

### ISSUE THREAD

**Issue by junqiangchen** [InsightSoftwareConsortium/ITK#2354]
hi,
i use BinaryMorphology with cpu,such as binary open,binary close operation in 3d medical image,but it’s very slowly,so i want use GPUBinaryMorphology to improve computational efficiency,and i find the link [https://github.com/medons/ITK_GPUBinaryMorphology/tree/master/Modules/Filtering/GPUBinaryMorphology]
 that is very useful,but i can’t build it with cmake,can anyone help me solving it?

thank you

**Comment by dzenanz** [comment]
The author of that filter is responding in https://github.com/medons/ITK_GPUBinaryMorphology/issues/1, so I will close this issue.
