### ISSUE TITLE
ThirdParty\GDCM\src\gdcm\Source\Common\gdcmSystem.cxx(815,3): error C3861: 'gettimeofday': identifier not found 

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2362]
ITK 4.13 downloaded by CTK

![image](https://user-images.githubusercontent.com/26530975/109975940-7cf50500-7cfb-11eb-8fce-3844f4119d35.png)

2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmSystem.cxx(815,3): error C3861: 'gettimeofday': identifier not found [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]

**Comment by al-sabr** [comment]
I added these lines in gdcmSystem.cxx in ITK 4.13

```
#include <chrono>

int gettimeofday(struct timeval* tp, struct timezone* tzp) {
   namespace sc = std::chrono;
   sc::system_clock::duration d = sc::system_clock::now().time_since_epoch();
   sc::seconds s = sc::duration_cast<sc::seconds>(d);
   tp->tv_sec = s.count();
   tp->tv_usec = sc::duration_cast<sc::microseconds>(d - s).count();

   return 0;
}
```

**Comment by al-sabr** [comment]
\`\`\`

Build started...

1>------ Build started: Project: ITK, Configuration: Debug x64 ------

1>Build started 3/4/2021 3:14:30 PM.

1>Target ResolveProjectReferences:

1>Target InitializeBuildStatus:

1>  Touching "x64\\Debug\\ITK\\ITK.tlog\\unsuccessfulbuild".

1>Target CustomBuild:

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-patch.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\ITK-CMAKE\\SRC\\ITK-STAMP\\DEBUG\\ITK-UPDATE' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-update.rule'. The items cannot be built in parallel."

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-configure.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\ITK-CMAKE\\SRC\\ITK-STAMP\\DEBUG\\ITK-PATCH' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-patch.rule'. The items cannot be built in parallel."

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-build.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\ITK-CMAKE\\SRC\\ITK-STAMP\\DEBUG\\ITK-CONFIGURE' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-configure.rule'. The items cannot be built in parallel."

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-install.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\ITK-CMAKE\\SRC\\ITK-STAMP\\DEBUG\\ITK-BUILD' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-build.rule'. The items cannot be built in parallel."

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\e7214e0488a731d6761433974101ee74\\ITK-complete.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\ITK-CMAKE\\SRC\\ITK-STAMP\\DEBUG\\ITK-INSTALL' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\49db1edb128ae857bc2adce3b068477e\\ITK-install.rule'. The items cannot be built in parallel."

1>  "The build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\467cb7dc9cb056b0931a152455a50551\\ITK.rule' depends on 'G:\\PROGRAMMING\\CPP\\CTK\\BUILD\\CMAKEFILES\\DEBUG\\ITK-COMPLETE' which is produced by the build of 'G:\\programming\\cpp\\CTK\\build\\CMakeFiles\\e7214e0488a731d6761433974101ee74\\ITK-complete.rule'. The items cannot be built in parallel."

1>  Performing update step for 'ITK'

1>  CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>  You may want to amend it after fixing the message, or set the config

1>  variable i18n.commitencoding to the encoding your project uses.

1>  CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>  You may want to amend it after fixing the message, or set the config

1>  variable i18n.commitencoding to the encoding your project uses.

1>  CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>  You may want to amend it after fixing the message, or set the config

1>  variable i18n.commitencoding to the encoding your project uses.

1>  No patch step for 'ITK'

1>  Performing configure step for 'ITK'

1>  loading initial cache file G:/programming/cpp/CTK/build/ITK-cmake/tmp/ITK-cache-Debug.cmake

1>  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.

1>  -- Enabled ITKCommon, needed by \[ITKGroup\_Core;ITKFiniteDifference;ITKGPUCommon;ITKGPUFiniteDifference;ITKImageAdaptors;ITKStatistics;ITKTransform;ITKImageFilterBase;ITKQuadEdgeMesh;ITKSpatialObjects;ITKTestKernel;ITKIOImageBase\].

1>  -- Enabled ITKDoubleConversion, needed by \[ITKCommon;ITKTestKernel\].

1>  -- Enabled ITKExpat, needed by \[ITKGDCM\].

1>  -- Enabled ITKFiniteDifference, needed by \[ITKGroup\_Core;ITKGPUFiniteDifference\].

1>  -- Enabled ITKGDCM, needed by \[ITKIOGDCM\].

1>  -- Enabled ITKGPUCommon, needed by \[ITKGroup\_Core;ITKGPUFiniteDifference\].

1>  -- Enabled ITKGPUFiniteDifference, needed by \[ITKGroup\_Core\].

1>  -- Enabled ITKIOBMP, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOGDCM, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOGIPL, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOImageBase, needed by \[ITKIOBMP;ITKIOGDCM;ITKIOGIPL;ITKTestKernel;ITKIOJPEG;ITKIOMeta;ITKIONIFTI;ITKIONRRD;ITKIOPNG;ITKIOTIFF;ITKIOVTK\].

1>  -- Enabled ITKIOJPEG, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOMeta, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIONIFTI, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIONRRD, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOPNG, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOTIFF, needed by \[ITKTestKernel\].

1>  -- Enabled ITKIOVTK, needed by \[ITKTestKernel\].

1>  -- Enabled ITKImageAdaptors, needed by \[ITKGroup\_Core;ITKImageFunction\].

1>  -- Enabled ITKImageFilterBase, needed by \[ITKTransform\].

1>  -- Enabled ITKImageFunction, needed by \[ITKGroup\_Core;ITKSpatialObjects\].

1>  -- Enabled ITKJPEG, needed by \[ITKIOJPEG;ITKTIFF\].

1>  -- Enabled ITKKWIML, needed by \[ITKCommon;ITKTIFF\].

1>  -- Enabled ITKKWSys, needed by \[ITKCommon;ITKTestKernel\].

1>  -- Enabled ITKMesh, needed by \[ITKGroup\_Core;ITKQuadEdgeMesh;ITKSpatialObjects\].

1>  -- Enabled ITKMetaIO, needed by \[ITKSpatialObjects;ITKIOMeta\].

1>  -- Enabled ITKNIFTI, needed by \[ITKIONIFTI\].

1>  -- Enabled ITKNetlib, needed by \[ITKStatistics\].

1>  -- Enabled ITKNrrdIO, needed by \[ITKIONRRD\].

1>  -- Enabled ITKPNG, needed by \[ITKIOPNG\].

1>  -- Enabled ITKQuadEdgeMesh, needed by \[ITKGroup\_Core\].

1>  -- Enabled ITKSpatialObjects, needed by \[ITKGroup\_Core\].

1>  -- Enabled ITKStatistics, needed by \[ITKImageFunction;ITKTransform\].

1>  -- Enabled ITKTIFF, needed by \[ITKIOTIFF\].

1>  -- Enabled ITKTestKernel, needed by \[ITKGroup\_Core\].

1>  -- Enabled ITKTransform, needed by \[ITKImageFunction;ITKMesh;ITKSpatialObjects;ITKIONIFTI;ITKGroup\_Core\].

1>  -- Enabled ITKVNL, needed by \[ITKVNLInstantiation;ITKNetlib\].

1>  -- Enabled ITKVNLInstantiation, needed by \[ITKCommon\].

1>  -- Enabled ITKZLIB, needed by \[ITKMetaIO;ITKGDCM;ITKIOGIPL;ITKNIFTI;ITKNrrdIO;ITKPNG;ITKTIFF\].

1>  CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.18/Modules/Documentation.cmake:27 (message):

1>    Policy CMP0106 is not set: The Documentation module is removed.  Run "cmake

1>    --help-policy CMP0106" for policy details.  Use the cmake\_policy command to

1>    set the policy and suppress this warning.

1>

1>    Documentation.cmake is VTK-specific code and should not be used in non-VTK

1>    projects.  This logic in this module is best shipped with the project using

1>    it rather than with CMake.

1>  Call Stack (most recent call first):

1>    Utilities/Doxygen/CMakeLists.txt:4 (include)

1>  This warning is for project developers.  Use -Wno-dev to suppress it.

1>

1>  -- Could NOT find Perl (missing: PERL\_EXECUTABLE)

1>  -- Configuring done

1>  -- Generating done

1>  -- Build files have been written to: G:/programming/cpp/CTK/build/ITK-build

1>  Performing build step for 'ITK'

1>  Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework

1>  Copyright (C) Microsoft Corporation. All rights reserved.

1>

1>    itknetlib.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itknetlib-4.13.lib

1>    itkv3p\_netlib.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkv3p\_netlib-4.13.lib

1>    itkvcl.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkvcl-4.13.lib

1>    itkvnl.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkvnl-4.13.lib

1>    itkvnl\_algo.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkvnl\_algo-4.13.lib

1>    ITKVNLInstantiation.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKVNLInstantiation-4.13.lib

1>    itkdouble-conversion.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkdouble-conversion-4.13.lib

1>    itksys.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itksys-4.13.lib

1>    ITKCommon.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKCommon-4.13.dll

1>    ITKEXPAT.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKEXPAT-4.13.lib

1>    gdcmSystem.cxx

1>    gdcmTrace.cxx

1>    gdcmCAPICryptoFactory.cxx

1>    Generating Code...

1>    gdcmCommon.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmCommon-4.13.lib

1>    itkzlib.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkzlib-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/CMakeLists.txt

1>    gdcmByteValue.cxx

1>    gdcmDataElement.cxx

1>    gdcmDataSet.cxx

1>    gdcmExplicitDataElement.cxx

1>    gdcmFile.cxx

1>    gdcmFileMetaInformation.cxx

1>    gdcmFragment.cxx

1>    gdcmImplicitDataElement.cxx

1>    gdcmItem.cxx

1>    gdcmMediaStorage.cxx

1>    gdcmPrivateTag.cxx

1>    gdcmReader.cxx

1>    gdcmSequenceOfFragments.cxx

1>    gdcmSequenceOfItems.cxx

1>    gdcmValue.cxx

1>    gdcmReader.strict.cxx

1>    gdcmTag.cxx

1>    gdcmTagToVR.cxx

1>    gdcmCodeString.cxx

1>    gdcmFileSet.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmByteSwapFilter.cxx

1>    gdcmUNExplicitImplicitDataElement.cxx

1>    gdcmWriter.cxx

1>    gdcmCSAHeader.cxx

1>    gdcmMrProtocol.cxx

1>    gdcmPDBHeader.cxx

1>    gdcmTransferSyntax.cxx

1>    gdcmVM.cxx

1>    gdcmVR.cxx

1>    gdcmPreamble.cxx

1>    gdcmParseException.cxx

1>    gdcmUNExplicitDataElement.cxx

1>    gdcmCP246ExplicitDataElement.cxx

1>    gdcmExplicitImplicitDataElement.cxx

1>    gdcmVR16ExplicitDataElement.cxx

1>    Generating Code...

1>    strict\_gdcmByteValue.cxx

1>    strict\_gdcmDataElement.cxx

1>    strict\_gdcmDataSet.cxx

1>    strict\_gdcmExplicitDataElement.cxx

1>    strict\_gdcmFile.cxx

1>    strict\_gdcmFileMetaInformation.cxx

1>    strict\_gdcmFragment.cxx

1>    strict\_gdcmImplicitDataElement.cxx

1>    strict\_gdcmItem.cxx

1>    strict\_gdcmMediaStorage.cxx

1>    strict\_gdcmPrivateTag.cxx

1>    strict\_gdcmReader.cxx

1>    strict\_gdcmSequenceOfFragments.cxx

1>    strict\_gdcmSequenceOfItems.cxx

1>    strict\_gdcmValue.cxx

1>    Generating Code...

1>    gdcmDSED.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmDSED-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition/CMakeLists.txt

1>    gdcmModule.cxx

1>    gdcmMacro.cxx

1>    gdcmModules.cxx

1>    gdcmMacros.cxx

1>    gdcmNestedModuleEntries.cxx

1>    gdcmIODEntry.cxx

1>    gdcmTable.cxx

1>    gdcmSeries.cxx

1>    gdcmDefs.cxx

1>    gdcmDefinedTerms.cxx

1>    gdcmEnumeratedValues.cxx

1>    gdcmStudy.cxx

1>    gdcmPatient.cxx

1>    gdcmType.cxx

1>    gdcmUsage.cxx

1>    gdcmIOD.cxx

1>    Generating Code...

1>    gdcmTableReader.cxx

1>    gdcmIOD.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmIOD-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/CMakeLists.txt

1>    gdcmDicts.cxx

1>    gdcmDictEntry.cxx

1>    gdcmDefaultDicts.cxx

1>    gdcmPrivateDefaultDicts.cxx

1>    gdcmGlobal.cxx

1>    gdcmGroupDict.cxx

1>    gdcmDefaultGroupNames.cxx

1>    gdcmUIDs.cxx

1>    gdcmSOPClassUIDToIOD.cxx

1>    gdcmCSAHeaderDefaultDicts.cxx

1>    Generating Code...

1>    gdcmDICT.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmDICT-4.13.lib

1>    gdcmcharls.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmcharls-4.13.lib

1>    gdcmjpeg12.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmjpeg12-4.13.lib

1>    gdcmjpeg16.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmjpeg16-4.13.lib

1>    gdcmjpeg8.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmjpeg8-4.13.lib

1>    itkgdcmopenjp2.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmopenjp2-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeLists.txt

1>    gdcmEmptyMaskGenerator.cxx

1>    gdcmFileStreamer.cxx

1>    gdcmJSON.cxx

1>    gdcmFileChangeTransferSyntax.cxx

1>    gdcmAnonymizer.cxx

1>    gdcmFileAnonymizer.cxx

1>    gdcmIconImageFilter.cxx

1>    gdcmIconImageGenerator.cxx

1>    gdcmDICOMDIRGenerator.cxx

1>    gdcmSpacing.cxx

1>    gdcmFileExplicitFilter.cxx

1>    gdcmFileDerivation.cxx

1>    gdcmImageFragmentSplitter.cxx

1>    gdcmTagPath.cxx

1>    gdcmSimpleSubjectWatcher.cxx

1>    gdcmAnonymizeEvent.cxx

1>    gdcmPixmap.cxx

1>    gdcmBitmap.cxx

1>    gdcmRescaler.cxx

1>    gdcmImageToImageFilter.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmBitmapToBitmapFilter.cxx

1>    gdcmPixmapToPixmapFilter.cxx

1>    gdcmImageChangeTransferSyntax.cxx

1>    gdcmImageApplyLookupTable.cxx

1>    gdcmFileDecompressLookupTable.cxx

1>    gdcmOrientation.cxx

1>    gdcmDataSetHelper.cxx

1>    gdcmImageChangePlanarConfiguration.cxx

1>    gdcmImageChangePhotometricInterpretation.cxx

1>    gdcmDirectionCosines.cxx

1>    gdcmSorter.cxx

1>    gdcmSerieHelper.cxx

1>    gdcmIPPSorter.cxx

1>    gdcmApplicationEntity.cxx

1>    gdcmDICOMDIR.cxx

1>    gdcmSpectroscopy.cxx

1>    gdcmEncapsulatedDocument.cxx

1>    gdcmSplitMosaicFilter.cxx

1>    gdcmFiducials.cxx

1>    gdcmWaveform.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmPersonName.cxx

1>    gdcmIconImage.cxx

1>    gdcmUIDGenerator.cxx

1>    gdcmUUIDGenerator.cxx

1>    gdcmPrinter.cxx

1>    gdcmDictPrinter.cxx

1>    gdcmXMLPrinter.cxx

1>    gdcmScanner.cxx

1>    gdcmStrictScanner.cxx

1>    gdcmPixmapReader.cxx

1>    gdcmImageReader.cxx

1>    gdcmPixmapWriter.cxx

1>    gdcmImageWriter.cxx

1>    gdcmStringFilter.cxx

1>    gdcmImageHelper.cxx

1>    gdcmValidate.cxx

1>    gdcmDumper.cxx

1>    gdcmImage.cxx

1>    gdcmImageConverter.cxx

1>    gdcmImageCodec.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmJPEG12Codec.cxx

1>    gdcmRLECodec.cxx

1>    gdcmPDFCodec.cxx

1>    gdcmAudioCodec.cxx

1>    gdcmJPEG16Codec.cxx

1>    gdcmJPEG8Codec.cxx

1>    gdcmJPEGCodec.cxx

1>    gdcmPVRGCodec.cxx

1>    gdcmKAKADUCodec.cxx

1>    gdcmPNMCodec.cxx

1>    gdcmPGXCodec.cxx

1>    gdcmRAWCodec.cxx

1>    gdcmLookupTable.cxx

1>    gdcmOverlay.cxx

1>    gdcmCurve.cxx

1>    gdcmPhotometricInterpretation.cxx

1>    gdcmPixelFormat.cxx

1>    gdcmSegmentedPaletteColorLookupTable.cxx

1>    gdcmStreamImageReader.cxx

1>    gdcmImageRegionReader.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmDirectoryHelper.cxx

1>    gdcmSegment.cxx

1>    gdcmSurface.cxx

1>    gdcmMeshPrimitive.cxx

1>    gdcmSegmentWriter.cxx

1>    gdcmSurfaceWriter.cxx

1>    gdcmSegmentReader.cxx

1>    gdcmSurfaceReader.cxx

1>    gdcmSurfaceHelper.cxx

1>    gdcmSegmentHelper.cxx

1>    rle.cxx

1>    info.cxx

1>    io.cxx

1>    Generating Code...

1>    gdcmJPEGLSCodec.cxx

1>    gdcmJPEG2000Codec.cxx

1>    gdcmMSFF.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmMSFF-4.13.lib

1>    gdcmsocketxx.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmsocketxx-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition/CMakeLists.txt

1>    gdcmAAbortPDU.cxx

1>    gdcmAAssociateACPDU.cxx

1>    gdcmAAssociateRJPDU.cxx

1>    gdcmAAssociateRQPDU.cxx

1>    gdcmAbstractSyntax.cxx

1>    gdcmApplicationContext.cxx

1>    gdcmAReleaseRPPDU.cxx

1>    gdcmAReleaseRQPDU.cxx

1>    gdcmARTIMTimer.cxx

1>    gdcmAsynchronousOperationsWindowSub.cxx

1>    gdcmBaseQuery.cxx

1>    gdcmBaseRootQuery.cxx

1>    gdcmCEchoMessages.cxx

1>    gdcmCFindMessages.cxx

1>    gdcmCMoveMessages.cxx

1>    gdcmCommandDataSet.cxx

1>    gdcmCompositeMessageFactory.cxx

1>    gdcmCompositeNetworkFunctions.cxx

1>    gdcmCStoreMessages.cxx

1>    gdcmFindPatientRootQuery.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmFindStudyRootQuery.cxx

1>    gdcmImplementationClassUIDSub.cxx

1>    gdcmImplementationUIDSub.cxx

1>    gdcmImplementationVersionNameSub.cxx

1>    gdcmMaximumLengthSub.cxx

1>    gdcmModalityPerformedProcedureStepCreateQuery.cxx

1>    gdcmModalityPerformedProcedureStepSetQuery.cxx

1>    gdcmMovePatientRootQuery.cxx

1>    gdcmMoveStudyRootQuery.cxx

1>    gdcmNActionMessages.cxx

1>    gdcmNCreateMessages.cxx

1>    gdcmNDeleteMessages.cxx

1>    gdcmNEventReportMessages.cxx

1>    gdcmNGetMessages.cxx

1>    gdcmNormalizedMessageFactory.cxx

1>    gdcmNormalizedNetworkFunctions.cxx

1>    gdcmNSetMessages.cxx

1>    gdcmPDataTFPDU.cxx

1>    gdcmPDUFactory.cxx

1>    gdcmPresentationContext.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmPresentationContextAC.cxx

1>    gdcmPresentationContextGenerator.cxx

1>    gdcmPresentationContextRQ.cxx

1>    gdcmPresentationDataValue.cxx

1>    gdcmQueryBase.cxx

1>    gdcmQueryFactory.cxx

1>    gdcmQueryImage.cxx

1>    gdcmQueryPatient.cxx

1>    gdcmQuerySeries.cxx

1>    gdcmQueryStudy.cxx

1>    gdcmRoleSelectionSub.cxx

1>    gdcmServiceClassApplicationInformation.cxx

1>    gdcmServiceClassUser.cxx

1>    gdcmSOPClassExtendedNegociationSub.cxx

1>    gdcmTransferSyntaxSub.cxx

1>    gdcmULActionAA.cxx

1>    gdcmULActionAE.cxx

1>    gdcmULActionAR.cxx

1>    gdcmULActionDT.cxx

1>    gdcmULBasicCallback.cxx

1>    Generating Code...

1>    Compiling...

1>    gdcmULConnection.cxx

1>    gdcmULConnectionInfo.cxx

1>    gdcmULConnectionManager.cxx

1>    gdcmULTransitionTable.cxx

1>    gdcmULWritingCallback.cxx

1>    gdcmUserInformation.cxx

1>    gdcmWLMFindQuery.cxx

1>    Generating Code...

1>    gdcmMEXD.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkgdcmMEXD-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/ThirdParty/GDCM/CMakeLists.txt

1>    ITKIOImageBase.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOImageBase-4.13.dll

1>    ITKIOBMP.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOBMP-4.13.dll

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/IO/GDCM/src/CMakeLists.txt

1>    itkGDCMImageIO.cxx

1>    itkGDCMImageIOFactory.cxx

1>    itkGDCMSeriesFileNames.cxx

1>    Generating Code...

1>       Creating library G:/programming/cpp/CTK/build/ITK-build/lib/Debug/ITKIOGDCM-4.13.lib and object G:/programming/cpp/CTK/build/ITK-build/lib/Debug/ITKIOGDCM-4.13.exp

1>    ITKIOGDCM.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOGDCM-4.13.dll

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/IO/GDCM/CMakeLists.txt

1>    ITKIOGIPL.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOGIPL-4.13.dll

1>    itkjpeg.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkjpeg-4.13.lib

1>    ITKIOJPEG.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOJPEG-4.13.dll

1>    ITKMetaIO.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKMetaIO-4.13.lib

1>    ITKIOMeta.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOMeta-4.13.dll

1>    ITKTransform.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKTransform-4.13.dll

1>    ITKznz.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKznz-4.13.lib

1>    ITKniftiio.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKniftiio-4.13.lib

1>    ITKIONIFTI.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIONIFTI-4.13.dll

1>    ITKNrrdIO.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKNrrdIO-4.13.lib

1>    ITKIONRRD.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIONRRD-4.13.dll

1>    itkpng.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkpng-4.13.lib

1>    ITKIOPNG.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOPNG-4.13.dll

1>    itktiff.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itktiff-4.13.lib

1>    ITKIOTIFF.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOTIFF-4.13.dll

1>    ITKIOVTK.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKIOVTK-4.13.dll

1>    ITKMesh.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKMesh-4.13.dll

1>    itkNetlibSlatec.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itkNetlibSlatec-4.13.lib

1>    ITKQuadEdgeMesh.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKQuadEdgeMesh-4.13.dll

1>    ITKSpatialObjects.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\ITKSpatialObjects-4.13.lib

1>    ITKStatistics.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\ITKStatistics-4.13.dll

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/Core/TestKernel/src/CMakeLists.txt

1>    itkTestDriver.cxx

1>    itkTestDriver.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\bin\\Debug\\itkTestDriver.exe

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/Modules/Core/TestKernel/CMakeLists.txt

1>    itktestlib.vcxproj -> G:\\programming\\cpp\\CTK\\build\\ITK-build\\lib\\Debug\\itktestlib-4.13.lib

1>    Building Custom Rule G:/programming/cpp/CTK/build/ITK/CMakeLists.txt

1>  No install step for 'ITK'

1>  Completed 'ITK'

1>Done building target "CustomBuild" in project "ITK.vcxproj".

1>Target GetReferencedVCProjectsInfo:

1>Target FinalizeBuildStatus:

1>  Deleting file "x64\\Debug\\ITK\\ITK.tlog\\unsuccessfulbuild".

1>  Touching "x64\\Debug\\ITK\\ITK.tlog\\ITK.lastbuildstate".

1>

1>Done building project "ITK.vcxproj".

1>

1>Build succeeded.

1>

1>CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>CUSTOMBUILD : warning : commit message did not conform to UTF-8.

1>    3 Warning(s)

1>    0 Error(s)

1>

1>Time Elapsed 00:06:00.43

\========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

\`\`\`

**Comment by dzenanz** [comment]
This is maybe due to some conditional compilation enabling Linux code. @malaterre might know more.

**Comment by al-sabr** [comment]
Well it seems that linux code is being compiled on Windows. But with the little addition I did it compile fully. Maybe that's a temporary solution what do you think?

**Comment by thewtex** [comment]
This is not an issue with GDCM or ITK but @al-sabr 's fork.

**Comment by al-sabr** [comment]
This is a dependency issue concerning a Superbuild which uses external projects as dependency based on CTK which itself is depending on ITK & VTK. It has nothing to do with my fork. My fork is using those dependencies equally as CTK uses them.

**Comment by al-sabr** [comment]
And actually I followed many of the recommendations proposed by @dzenanz and still could not achieve what I intended to.

**Comment by thewtex** [comment]
CTK has worked with ITK, VTK and other third party libraries for quite some time. I have contributed to CTK -- I am aware of the project. The problems you are encountering are created by your fork. To address issues in a maintainable way without creating more issues, update CTK, MITK, to use the latest version of ITK and other third party dependencies without deviating from the upstream library.

**Comment by al-sabr** [comment]
This is a false positive it seems that the following flag gets enabled by default:

\`\`\`

//Have function gettimeofday

GDCM\_HAVE\_GETTIMEOFDAY:INTERNAL=1

\`\`\`

I really don't understand why does it enabled it by default but when I set it back to

\`\`\`//Have function gettimeofday

GDCM\_HAVE\_GETTIMEOFDAY:INTERNAL=\`\`\`

The compilation goes through!
