### ISSUE TITLE
`itk::PatchBasedDenoisingImageFilter` tests failing

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#2394]
### Description

The tests:
```
itkPatchBasedDenoisingImageFilterTest0
itkPatchBasedDenoisingImageFilterTestGaussian
itkPatchBasedDenoisingImageFilterTestPoisson
itkPatchBasedDenoisingImageFilterTestRician
```

are reporting failures on the `silicon.bluequartz.net` site, `Mac11.1-AppleClang-rel-arm64` build:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=7089134

### Steps to Reproduce

Execute
```
itkPatchBasedDenoisingImageFilterTest0
itkPatchBasedDenoisingImageFilterTestGaussian
itkPatchBasedDenoisingImageFilterTestPoisson
itkPatchBasedDenoisingImageFilterTestRician
```
macOS 11.1 using Apple Clang.

### Expected behavior

All tests passing (i.e. output and baselines matching perfectly).

### Actual behavior

The tests' output images and baselines are disagreeing on a few pixels, e.g.
https://open.cdash.org/test/359949516

The latest error report is available at:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=7089134

### Reproducibility

100% on the `silicon.bluequartz.net` site, `Mac11.1-AppleClang-rel-arm64` build.

### Versions

ITK `master` (oldest failing commit eb61446; most recent at the time of the report: f3b9f27).

### Environment

macOS 11.1 using Apple Clang.

### Additional Information

The tests are failing since at least Feb 18, 2021:
https://open.cdash.org/viewTest.php?buildid=7049831&onlyfailed

Tests are defined
[here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/Denoising/test/CMakeLists.txt).

Looks like not all tests exercising the filter at issue are failing.

Might be linked to issue #2387.

**Comment by thewtex** [comment]
I think we just need new baselines for this new platform -- the tests have been failing since we started to add support. Discussed more in #2250
