### ISSUE TITLE
Braces missing around initialization in `itk::ContourExtractor2DImageFilter` and test

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#2395]
### Description

Braces missing around initialization in `itk::ContourExtractor2DImageFilter` and test according to the build
report corresponding to the `RogueResearch18` site, `Mac10.10-AppleClang-dbg-x86_64-static` build:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7089287

### Steps to Reproduce

Build ITK `master` on a macOS 10.10 using Apple Clang.

### Expected behavior

ITK building with no errors.

### Actual behavior

Brace initialization build warnings are being reported for the `itk::ContourExtractor2DImageFilter` class and `itkContourExtractor2DImageFilterTest` file:
```
[CTest: warning matched] /Users/builder/externalModules/Filtering/Path/test/
itkContourExtractor2DImageFilterTest.cxx:666:39:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
     extractor->SetRequestedRegion({ { 0, 4 }, { 3, 4 } });
                                       ^~~~
                                       {   }
[CTest: warning matched] /Users/builder/externalModules/Filtering/Path/test/
itkContourExtractor2DImageFilterTest.cxx:666:49:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
     extractor->SetRequestedRegion({ { 0, 4 }, { 3, 4 } });
                                                 ^~~~ 
                                                 {   }
```

and a few similar others on the same `itkContourExtractor2DImageFilter.hxx` file, e.g.
```
[CTest: warning matched] /Users/builder/externalModules/Filtering/Path/include/
itkContourExtractor2DImageFilter.hxx:298:30:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
  const IndexType right_bot{ inputRegion.GetIndex()[0] + static_cast<IndexValueType>(inputRegion.GetSize()[0]) - 1,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reproducibility

100%.

### Versions

ITK `master` (as of commit 6810968 at the time of the report).

### Environment

macOS 10.10 using Apple Clang.

### Additional information

Reported for the first time in:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7073915

Immediately previous build found no warnings:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7071827

Git blame shows that the code was introduced in PR #2323, commit e2cfba4.

**Comment by jhlegarreta** [comment]
@Leengit, as time permits, you may want to investigate the issue and hopefully propose a fix.

**Comment by Leengit** [comment]
I have put fixes into Pull Request @2384.  If I've found all the places that macOS 10.10 doesn't like then we can close this issue.

**Comment by jhlegarreta** [comment]
> I have put fixes into Pull Request #2384. If I've found all the places that macOS 10.10 doesn't like then we can close this issue.

Thanks @Leengit . I had a quick look at the changes, and it looks like the warnings would be addressed with the fix. I'd wait to see that they effectively disappear once your PR gets merged and the sites submit their reports to the dashboard the day after.

**Comment by jhlegarreta** [comment]
Unfortunately, it looks like there are a few that were not addressed by the PR:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7093900

and new build warnings emerged related to the class :pensive:, e.g.
https://open.cdash.org/viewBuildError.php?buildid=7093944

**Comment by jhlegarreta** [comment]
The proposed fixes have addressed the build warnings according to the dashboard :tada: Thanks @Leengit @N-Dekker .

**Comment by jhlegarreta** [comment]
Looks like I did not check them all properly 😭 :
```
[CTest: warning matched] /home/kitware/Dashboards/TestsModules/Filtering/Path/include/
itkContourExtractor2DImageFilter.hxx:116:89:
warning: missing initializer for member 'itk::Index<2u>::m_InternalArray' [-Wmissing-field-initializers]
   NeighborhoodRange neighborhoodRange{ *input, InputIndexType{}, offsets, m_UnusedLabel };
```
https://open.cdash.org/viewBuildError.php?type=1&buildid=7104014

**Comment by N-Dekker** [comment]
Please try old-style value-initialization of the index by parentheses: `InputIndexType()` instead of by C++11 curly braces `InputIndexType{}`. I think the old GCC4 likes the parentheses better in this case.

**Comment by jhlegarreta** [comment]
The warnings seem to be gone from the affected build. Thanks both.
