### ISSUE TITLE
Add direct access to itk.array_from_vector_container, itk.array_view_from_vector_container, itk.vector_container_from_array

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2428]
These functions are defined on `itk.PyVectorContainer`, but they should be exposed like `itk.array_from_image` by adding them to `itkExtras.py`.

Reference:

https://github.com/InsightSoftwareConsortium/ITK/blob/4c785c2176785e57048d67ec618c8712bcc99782/Wrapping/Generators/Python/itk/support/itkExtras.py#L196-L242

Note: we should skip the `CamelCase` versions.

**Comment by tbirdso** [comment]
Should we continue to support a tuple or list for `ttype`? If so, for what purpose?

**Comment by thewtex** [comment]
Yes -- because for all the other `itkTemplate` uses, a tuple is supported.
