### ISSUE TITLE
Question: Registration reproducibility

### ISSUE THREAD

**Issue by nilgoyette** [InsightSoftwareConsortium/ITK#2479]
I already asked this question on the [ANTs github](https://github.com/ANTsX/ANTs/issues/1174) and they told me to ask here.

It is explained [here](https://itk.org/Doxygen413/html/ThreadingPage.html) that ITK v4 (unsure about v5) divide the output image in N regions (one per thread). Each threaded filter does that when it's its turn, start the threads to do the actual work, until we have the output image. What I don't understand is how this threading model can produce different results. I code this kind of applications at my work with this threading model (Rust, ndarray and rayon) and I don't have this problem. Afaik, the fp operations order should be the same.

The ANTs owner told me this:
> However, if you are updating a global variable the results will differ with the ordering of floating point operations. That is the situation with some of the similarity metrics in ITK.

Can I have more information on this matter? Which metrics? Any way to find them myself?

**Comment by gdevenyi** [comment]
I think this is better suited for https://discourse.itk.org/

**Comment by nilgoyette** [comment]
Ok, perfect, I'll ask there :)
