### ISSUE TITLE
itk::BinaryThresholdImageFilter does not preserve input's parameters

### ISSUE THREAD

**Issue by mbrzus** [InsightSoftwareConsortium/ITK#2485]
### Description

The itk::BinaryThresholdImageFilter changes the Origin, Spacing and Direction to the default values.

### Steps to Reproduce

1. Read or create an ITK image.
2. Input the image to the itk::BinaryThresholdImageFilter and set the filter's parameters
3. Get output from the filter.

### Expected behavior

The image after thresholding should have the same Origin, Spacing and Direction as the input image.

### Actual behavior

The output image spacing is set to the default values.

"
Origin: [0, 0]
Spacing: [1, 1]
Direction: 1 0
0 1
"

### Reproducibility

100%

### Versions

ITK 5.2.0

### Environment

Ubuntu 18.04
CMake 3.19.3

### Additional Information

I am attaching a code that takes 1 input: file path of 2d image, overrites the input image origin spacing and direction and prints the parameters of the image before and after performing Binary Threshold.
The behavior using 3d images is the same

[BinaryThresholdTest.txt](https://github.com/InsightSoftwareConsortium/ITK/files/6321058/BinaryThresholdTest.txt)

**Comment by dzenanz** [comment]
You seem to be missing `reader->Update();` on line 28 and `filter->Update();` on line 60. Calling `filter->GetOutput()` before `filter->Update()` will return a default-initialized empty image.

**Comment by mbrzus** [comment]
That solved the issue. Thank you!
