### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [InsightSoftwareConsortium/ITK#2494]
On 'pip3 install itk' I get errors like the below one. However, 'cmake' + 'make install' work: 

```text
...
    In file included from /tmp/pip-install-1y5hn7d7/itk/_skbuild/linux-aarch64-3.9/cmake-build/ITKb/Wrapping/itkCovariantVector.cxx:11:
    In file included from /tmp/pip-install-1y5hn7d7/itk/_skbuild/linux-aarch64-3.9/cmake-build/ITKs/Modules/Core/Common/include/itkSymmetricSecondRankTensor.h:29:
    In file included from /tmp/pip-install-1y5hn7d7/itk/_skbuild/linux-aarch64-3.9/cmake-build/ITKs/Modules/Core/Common/include/itkSymmetricEigenAnalysis.h:23:
    In file included from /tmp/pip-install-1y5hn7d7/itk/_skbuild/linux-aarch64-3.9/cmake-build/ITKs/Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/Eigenvalues:11:
    In file included from /tmp/pip-install-1y5hn7d7/itk/_skbuild/linux-aarch64-3.9/cmake-build/ITKs/Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/Core:237:
    /usr/lib/gcc/aarch64-redhat-linux/10/include/arm_neon.h:42:9: error: unknown type name '__Float16x4_t'
    typedef __Float16x4_t float16x4_t;
            ^
    /usr/lib/gcc/aarch64-redhat-linux/10/include/arm_neon.h:43:9: error: unknown type name '__Float32x2_t'; did you mean '_Float32x'?
    typedef __Float32x2_t float32x2_t;
            ^
    /usr/include/bits/floatn-common.h:268:16: note: '_Float32x' declared here
    typedef double _Float32x;
...
```

**Comment by dzenanz** [comment]
Is this on a machine with ARM or AMD64 architecture?

**Comment by LutzWeischerFujitsu** [comment]
Arm / AArch64

**Comment by thewtex** [comment]
@LutzWeischerFujitsu what version of Python are you using? e.g. 3.9?

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 jw]$ python3 --version
Python 3.9.4
[jw@cn06 jw]$

**Comment by thewtex** [comment]
Please try:

```
pip install --upgrade pip
pip install -i https://test.pypi.org/simple itk
```

and let us know how it goes.

**Comment by thewtex** [comment]
Note: there is a known issue if you try to run these related to `np.float128`, but I am interested if the install works OK.

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 itk]$ pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/jw/.local/lib/python3.9/site-packages (21.0.1)
Collecting pip
  Downloading pip-21.1-py3-none-any.whl (1.5 MB)
     |################################| 1.5 MB 4.6 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0.1
    Uninstalling pip-21.0.1:
      Successfully uninstalled pip-21.0.1
Successfully installed pip-21.1
[jw@cn06 itk]$ pip install -i https://test.pypi.org/simple itk
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib64/python3.9/site-packages
sysconfig: /usr/lib64/python3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.9/site-packages
sysconfig: /usr/lib/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/include/python3.9
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/bin
sysconfig: /usr/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local
sysconfig: /usr
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
Looking in indexes: https://test.pypi.org/simple
Collecting itk
  Downloading https://test-files.pythonhosted.org/packages/83/76/d11c35d00cbedddb4c54a5bee1cf030dd1ce9180fd49dc194b3759b0572d/itk-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (8.3 kB)
Collecting itk-registration==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/06/9f/6c2d708cf350bfce7344366400b9c8924cda6b8c422a41676f334d254433/itk_registration-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (18.6 MB)
     |################################| 18.6 MB 5.9 MB/s
Collecting itk-io==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/86/8a/ff08359051c2b5fe0959988bdb68fda5ebb2b2ede3c4c716e40330c6df9c/itk_io-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (14.1 MB)
     |################################| 14.1 MB 7.9 MB/s
Requirement already satisfied: numpy in /home/jw/.local/lib/python3.9/site-packages (from itk) (1.19.2)
Collecting itk-core==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/a7/8b/9d3fcaebc32f04908d6a464a479d4466d7ad425459e49c4bdfd973efaf76/itk_core-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (62.7 MB)
     |################################| 62.7 MB 53 kB/s
Collecting itk-filtering==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/63/93/c7131cd7265c58f75dcaa2a301c0bb2f64ee2d6f04d4fb1bae8c8e3dd65b/itk_filtering-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (88.6 MB)
     |################################| 88.6 MB 48 kB/s
Collecting itk-segmentation==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/e5/82/d9d7181298429dd7bbcccda2efc1b08af65fd0caa4cc19e6027ba4b66b22/itk_segmentation-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (15.3 MB)
     |################################| 15.3 MB 3.7 MB/s
Collecting itk-numerics==5.2.0.post1
  Downloading https://test-files.pythonhosted.org/packages/e9/a3/b3b1dbc408f90a3dbf40c6b4aed0d872cebb5588283ca5e6df5d8286acb9/itk_numerics-5.2.0.post1-cp39-cp39-manylinux2014_aarch64.whl (50.4 MB)
     |################################| 50.4 MB 24 kB/s
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
Installing collected packages: itk-core, itk-numerics, itk-filtering, itk-segmentation, itk-registration, itk-io, itk
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/jw/.local/lib/python3.9/site-packages
  sysconfig: /home/jw/.local/lib64/python3.9/site-packages
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /home/jw/.local/lib/python3.9/site-packages
sysconfig: /home/jw/.local/lib64/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /home/jw/.local/include/python3.9/UNKNOWN
sysconfig: /home/jw/.local/include/python3.9
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
Successfully installed itk-5.2.0.post1 itk-core-5.2.0.post1 itk-filtering-5.2.0.post1 itk-io-5.2.0.post1 itk-numerics-5.2.0.post1 itk-registration-5.2.0.post1 itk-segmentation-5.2.0.post1
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -event (/home/jw/.local/lib/python3.9/site-packages)
[jw@cn06 itk]$

**Comment by dzenanz** [comment]
> Successfully installed itk-5.2.0.post1 itk-core-5.2.0.post1 itk-filtering-5.2.0.post1 itk-io-5.2.0.post1 itk-numerics-5.2.0.post1 itk-registration-5.2.0.post1 itk-segmentation-5.2.0.post1

I guess that installation succeeded for you. Do you run into `np.float128` on runtime?

**Comment by thewtex** [comment]
Thanks for the feedback. The packages without the `np.float128` issues are now available on standard PyPI.

```
pip install --upgrade pip
pip install itk
```

should work.

**Comment by LutzWeischerFujitsu** [comment]
Yes.
