### ISSUE TITLE
pip install itk-texturefeatures results in 3.4.0 rather than 5.2.0 version

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#2497]
### Description

installing itk-texturefeatures from pip breaks the use of ITK

### Expected behavior
A recent version of the itk-texturefeatures component should be installed.

### Actual behavior
An old version is installed.  Use of itk from python is broken during introspection when itkCoocurrenceTextureFeaturesImageFilterPython.py is loaded.

### Additional Information

The itkHelpers.py file does not exist in itk 5.2.0.
```bash
(miatt394) l-ece119% grep -rl itkHelpers *
itkCoocurrenceTextureFeaturesImageFilterPython.py
itkRunLengthTextureFeaturesImageFilterPython.py
__pycache__/itkCoocurrenceTextureFeaturesImageFilterPython.cpython-39.pyc
__pycache__/itkRunLengthTextureFeaturesImageFilterPython.cpython-39.pyc
```

**Comment by thewtex** [comment]
Will be addressed byhttps://github.com/InsightSoftwareConsortium/ITKTextureFeatures/pull/92

**Comment by thewtex** [comment]
Please `pip install --upgrade itk-texturefeatures` to get 3.5.0, which addresses this.
