### ISSUE TITLE
itk.resample_image_filter(..., size = itk.size(input_image)) fails.

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITK#2520]
### Description
The `size` parameter for `itk.resample_image_filter` gives an error if the object it is given is that which is returned from an `itk.size(...)` command.

### Steps to Reproduce

1. Modify the call to `itk.resample_image_filter` in `ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Code.py b/src/Filtering/ImageGrid/ResampleAnImage/Code.py` to use `size=itk.size(input_image)`.
2. Build `ITKExamples`.
3. Run `ctest -V -R ResampleAnImageTestPython`

### Expected behavior

Test passes.

### Actual behavior
```none
test 238
    Start 238: ResampleAnImageTestPython

238: Test command: ~/venv/ITK-master/bin/python "~/git/ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Code.py" "~/git/ITKExamples-build/src/Filtering/ImageGrid/ResampleAnImage/BrainProtonDensitySlice.png" "OutputPython.png" "2"
238: Test timeout computed to be: 1500
238: Traceback (most recent call last):
238:   File "~/git/ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Code.py", line 61, in <module>
238:     resampled = itk.resample_image_filter(
238:   File "~/git/ITK-master-build/Wrapping/Generators/Python/itk/support/helpers.py", line 173, in image_filter_wrapper
238:     return image_filter(*args, **kwargs)
238:   File "~/git/ITK-master-build/Wrapping/Generators/Python/itk/itkResampleImageFilterPython.py", line 1931, in resample_image_filter
238:     specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] != ... }
238:   File "~/git/ITK-master-build/Wrapping/Generators/Python/itk/itkResampleImageFilterPython.py", line 1931, in <dictcomp>
238:     specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] != ... }
238:   File "~/git/ITK-master-build/Wrapping/Generators/Python/itk/itkSizePython.py", line 188, in __eq__
238:     return tuple(self) == tuple(other)
238: TypeError: 'ellipsis' object is not iterable
1/1 Test #238: ResampleAnImageTestPython ........***Failed    1.27 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.30 sec
```

### Reproducibility

100%

### Versions

ITK master branch (commit 8fd1fec6b7818f7bae982f51d9bcf12ef7d9fa08).
ITKExamples master branch (commit [`bcb6ed39`](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/commit/bcb6ed39dbd57c0d75800dde6906bfca1e4a5d37)).

### Environment
Ubuntu 20.04.  cmake 3.16.3.  gcc/g++ 10.2.0.  ctest 3.16.3.

**Comment by Leengit** [comment]
I am using Python 3.8.5.

The trace above shows that the error is occurring on line 188 of `git/ITK-master-build/Wrapping/Generators/Python/itk/itkSizePython.py` that is trying to execute the illegal operation `tuple(...)` within the `__eq__` method of `class itkSize2`.  That method tests for equality between `self` and `other` by first casting each to a tuple; which fails when `other` is `...`.

 _A more type-careful test for equality of `itkSize2` instances might fix this immediate issue.  However, there may be a larger issue._

Equality is being checked because of line 1931 of `~/git/ITK-master-build/Wrapping/Generators/Python/itk/itkResampleImageFilterPython.py` whose job it is to check all supplied arguments to `resample_image_filter` for equality with `...`.  Because there easily could be Python classes other than `itkSize2` that don't know how to compare to `...` this could be hazardous more widely.  Making sure that all `__eq__` methods can handle `...`; or even better, making sure that no `__eq__` method can fail or throw an exception is one way to address this larger issue.  Possibly another way, is to make line 1931 (and lines similar to it) more type-careful before they call a `__eq__` method.

**Comment by thewtex** [comment]
How about changing:

```
if kwarg_typehints[k] != ...
``` 

to

```
if not kwarg_typehints[k] is ...
```

?
