### ISSUE TITLE
VNL: "+" in source or build path leads to an error

### ISSUE THREAD

**Issue by akalali** [InsightSoftwareConsortium/ITK#2531]
### Description

I try to use ITK with Conan by using an ITK 4.13.3 Conan recipe. This works as expected. Next step would be to use GitLab CI/CD to have a job that regularly builds the Conan ITK 4.13.3 package and uploads it to my GitLab Conan repository.
However, I'm using an [instance remote](https://docs.gitlab.com/ee/user/packages/conan_repository/#add-a-remote-for-your-instance) to access the GitLab Conan repository. The [package recipe naming convention for instance remotes](https://docs.gitlab.com/ee/user/packages/conan_repository/#package-recipe-naming-convention-for-instance-remotes) states that one has to use e.g. `my-package/1.0.0@foo+bar/stable` for the project `foo/bar`, where `foo/bar` corresponds to `<group-name>/<project-name>`.
The problem is that I get an error while creating the package (building the library) due to [VNL](https://github.com/InsightSoftwareConsortium/ITK/blob/release-4.13/Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt#L172). This does not happen on Windows but on Ubuntu.

### Steps to Reproduce

1. clone ITK into a directory containing a `+`-sign
2. generate ITK project files with `cmake <directory-to-CMakeLists.txt> -G"Unix Makefiles`

### Actual behavior

```
CMake Error at Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt:172 (message):
  You cannot have a + in your binary path

CMake Error at Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt:175 (message):
  You cannot have a + in your source path
```

### Versions / Environment

The error occurred with
- Conan 1.35.1
- CMake 3.18.0 and 3.19.4
- ITK 4.13.3 (`git clone --depth 1 --branch v4.13.3 https://github.com/InsightSoftwareConsortium/ITK.git`)
- ITK 5.1.0 (`git clone --depth 1 --branch v5.1.0 https://github.com/InsightSoftwareConsortium/ITK.git`) (here lines 223 and 226 are pointing to the error)
- gcc7

**Comment by dzenanz** [comment]
This is maybe better reported to VNL? I think we might be able to simply remove this error, given the message of the [commit](https://github.com/vxl/vxl/commit/298950230323b4c704b9643abfd0250bddaecb98) which introduced it. Could you please test whether it works if you remove those few lines? And if it does make a PR to `vxl`?

**Comment by dzenanz** [comment]
Please reopen if this is still valid.
