### ISSUE TITLE
Computing Curvature for 3D LevelSet

### ISSUE THREAD

**Issue by HaaPut** [InsightSoftwareConsortium/ITK#2541]
### Description

I think [this](https://github.com/InsightSoftwareConsortium/ITK/blob/b8d95b7cad6dba2b995a769cfd5ab850e7525d1a/Modules/Segmentation/LevelSets/include/itkLevelSetFunction.hxx#L40) line  should call `Compute3DMinimalCurvature()` instead of  `ComputeMinimalCurvature()`
### Steps to Reproduce
No steps required, but the if-elseif-else code structure only makes sense if the original author intended 3D case to actually calls the specialized version. Further, currently the `Compute3DMinimalCurvature()` seems kind of pointless.

### Additional Information

I can do a quick PR if this makes sense.

**Comment by dzenanz** [comment]
It makes sense, and a PR is welcome.

**Comment by jhlegarreta** [comment]
#2542 was merged. @HaaPut can this be considered as solved?
