### ISSUE TITLE
Multiple aliases for same type in `itk::Image`

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#2548]
### Description

There are multiple classes, [`itk::Image`](https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/master/Modules/Core/Common/include/itkImage.h), [`itk::PhasedArray3DSpecialCoordinatesImage`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkPhasedArray3DSpecialCoordinatesImage.h), and [`itk::SpecialCoordinatesImage.h`](https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/master/Modules/Core/Common/include/itkSpecialCoordinatesImage.h), defining multiple aliases for the same type with some unclear documentation:

```
  /** Pixel type alias support Used to declare pixel type in filters
   * or other operations. */
  using PixelType = TPixel;

  /** Typedef alias for PixelType */
  using ValueType = TPixel;

  /** Internal Pixel representation. Used to maintain a uniform API
   * with Image Adaptors and allow to keep a particular internal
   * representation of data while showing a different external
   * representation. */
  using InternalPixelType = TPixel;
```

Although the later might be useful, I am not convinced about the advantages for a `ValueType`-like type when the type is not a special/multi-component one, and unless it is defined otherwise. The [`itk::VectorImage`](https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/master/Modules/Core/Common/include/itkVectorImage.h), where the `ValueType` could potentially be the actual native C++ type of the vector pixel/the component type, does not help getting a clearer picture of such multiple aliases.

### Impact analysis

Not sure if this requires only better documentation or attempting to remove the `ValueType` or `PixelType` alias where it is not essential or its use overlaps with its counterpart.

### Expected behavior

Have a clear distinction between such basic aliases.

### Actual behavior

Unclear purpose of aliases.

### Versions

`master`

### Additional Information

Not sure if my understanding is appropriate or it is just a misconception.

**Comment by blowekamp** [comment]
Hello Jon,

These types of "typedefs" ( sorry for the legacy term ) need be defined in all of the image-like classes. Consider when writing a generic method to work on any of the image types, there should be a "concept" ( named set of requirements ) for an image-like class. This allows `ImageType::ValueType` to be used no matter the image-like class used.

The C++ std library  has a set of generic concepts: https://www.enseignement.polytechnique.fr/informatique/INF478/docs/Cpp/en/cpp/concept.html

**Comment by jhlegarreta** [comment]
Makes perfect sense. Then maybe it's the documentation that should be improved?

**Comment by jhlegarreta** [comment]
I'm closing this as it has not gathered interest as to be considered an actual issue.
