### ISSUE TITLE
Add support for colons in the changelog summary

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2558]
As reported in:

https://discourse.itk.org/t/itk-5-2-0-has-been-released/4165/3

subjects with `::` get cut off in the summary.

The script used is here:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/AuthorsChangesSince.py

@N-Dekker

**Comment by N-Dekker** [comment]
Thank you @thewtex I'm very glad that the colon colon issue is fixed 😃 

Would it be easy for you to fix the section "ITK Changes Since v5.2rc03" at https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.2.0 using the AuthorsChangesSince.py that you just fixed?

**Comment by thewtex** [comment]
@N-Dekker yes, done!
