### ISSUE TITLE
Orientation support for image_from_vtk_image and vtk_image_from_image

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2559]
As discussed:

https://discourse.itk.org/t/itk-5-2-0-has-been-released/4165/2

VTK recently added orientation/`Direction` support to `vtkImageData`. Pass this through in `itk.image_from_vtk_image` and `itk.vtk_image_from_image`.

@lassoan

**Comment by gdevenyi** [comment]
This would be a game changer for some software I've been planning to write for a while. :+1:

**Comment by seanm** [comment]
CCing myself @seanm

**Comment by lassoan** [comment]
@dave3d implemented direction support in his VTK/ITK image conversion utilities that you might find useful - see https://github.com/dave3d/dicom2stl/tree/main/utils

**Comment by dave3d** [comment]
I can take a look at patching the ITK code similarly.

**Comment by dave3d** [comment]
https://github.com/InsightSoftwareConsortium/ITK/pull/2586
