### ISSUE TITLE
BMP files with alpha channel are read with incorrect channel order

### ISSUE THREAD

**Issue by lassoan** [InsightSoftwareConsortium/ITK#2596]
When a 32-bit ARGB BMP file is loaded using ITK, the colors are all mixed up.

### Description

BMP files with transparency are stored with ARGB channel order. It seems that ITK assumes RGBA order.

### Steps to Reproduce

Load this image using ITK: https://1drv.ms/u/s!Arm_AFxB9yqHxcpbEw34sbS-h1pjkA?e=cf39o8

```python
img = sitk.ReadImage('15-14-49.bmp')
myshow(img)  # incorrect
```

```python
nda = sitk.GetArrayFromImage(img)
img2=sitk.GetImageFromArray(nda[:,:,[1,2,3,0]])
myshow(img2)  # correct
```

![image](https://user-images.githubusercontent.com/307929/122123570-228c3a00-cdfc-11eb-80a6-4e536fb78faa.png)

### Expected behavior

Colors should appear correctly in an application, regardless of what file format is loaded from (png, jpg, bmp, ...)

### Actual behavior

Colors are not correct if BMP format is used (if transparency is stored with the image).

### Reproducibility

100%

### Versions

v5.2.0

### Environment

all (Windows and Linux tested)

### Additional Information

See original user report at https://discourse.slicer.org/t/grey-level-image-looking-blue-or-other-color/18095/3

**Comment by dzenanz** [comment]
It turns out BMP files use BGR and BGRA order. ITK assumed ABGR instead. #2596 fixes that.

@leodemachado can you confirm? I guess this will need to be integrated into Slicer first 😄
