### ISSUE TITLE
Suspicious assignment in GDCMImageIO

### ISSUE THREAD

**Issue by Nekto89** [InsightSoftwareConsortium/ITK#2601]
File contains multiple assignments `name[len-1] = '0';` under `ITKIO_DEPRECATED_GDCM1_API`
I suspect that it should have been `'\0'` instead.

https://github.com/InsightSoftwareConsortium/ITK/blob/5df152b4c3493bd788bc63c9b6bb62c233cda8ee/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L1246

**Comment by dzenanz** [comment]
I think you are right. Can you make a PR which fixes it?

**Comment by Nekto89** [comment]
I got there through commit in release notes. It has been already fixed.
