### ISSUE TITLE
Extrem low value in mhd header

### ISSUE THREAD

**Issue by tbaudier** [InsightSoftwareConsortium/ITK#2602]
### Description

Extrem low values in the mhd header lead to reading error on MacOS

### Steps to Reproduce

1. Create a mhd image with this header:
```
ObjectType = Image
NDims = 3
BinaryData = True
BinaryDataByteOrderMSB = False
CompressedData = False
TransformMatrix = 1 0 0 0 1 0 0 0 1 
Offset = -35.995 -136.995 6.95279e-310
CenterOfRotation = 0 0 0 
ElementSpacing = 2 2 2
DimSize = 35 85 35
AnatomicalOrientation = ????
ElementType = MET_FLOAT
ElementDataFile = image.raw
```
The important point is the value `6.95279e-310` in the offset line

2. Try to read the image:
```python
import itk
image = itk.imread("image.mhd")
```
This scrip bugs. The bug occurs with c++ too.

3. Change in the mhd file the low value `6.95279e-310` by `0` and there is no problem anymore. Or try steps 1 and 2 on Linux and the software can read the image.

### Expected behavior

Open the image like on Linux systems.

### Actual behavior

```
DimSize required and not defined.
MetaObject: Read: MET_Read Failed
MetaImage: M_Read: Error parsing file
MetaImage: Read: Cannot parse file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tbaudier/Software/miniconda3/lib/python3.7/site-packages/itk/support/extras.py", line 957, in imread
    reader = template_reader_type.New(**kwargs)
  File "/Users/tbaudier/Software/miniconda3/lib/python3.7/site-packages/itk/support/template_class.py", line 661, in New
    itk.ImageFileReader, False, "FileName", *args, **kwargs
  File "/Users/tbaudier/Software/miniconda3/lib/python3.7/site-packages/itk/support/template_class.py", line 165, in _NewImageReader
    imageIO.ReadImageInformation()
RuntimeError: /Users/svc-dashboard/D/P/ITKPythonPackage/ITK-source/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx:101:
ITK ERROR: MetaImageIO(0x7f82ab963a00): File cannot be read: image.mhd for reading.
Reason: Result too large
```

### Reproducibility

On MacOS, everytime

### Versions

ITK v5.2.0 but also with previous versions

### Environment

Does not work on:
 - MacOS BigSur 11.3 in python 3.7 and itk 5.2.0
 - MacOS BigSur 11.3 in c++, clang 12.0.5 and itk 5.2.0

Expected behavior on:
 - Linux OpenSuse Leap 15.2, in python 3.7 and itk 5.2.0
 - Linux OpenSuse Leap 15.2, in c++ gcc7.5.0 and itk 5.2.0

**Comment by dzenanz** [comment]
@seanm can you reproduce and/or fix this? Or someone else who develops on a Mac?

**Comment by dzenanz** [comment]
The fix might need to go to https://github.com/Kitware/MetaIO.

**Comment by seanm** [comment]
@tbaudier do you have some C++ example code we could run to reproduce?

**Comment by seanm** [comment]
I have no idea if it's actually related, but it does remind me of this: https://bugs.llvm.org/show_bug.cgi?id=17782

**Comment by issakomi** [comment]
I could reproduce the issue (m1, _arm64_ build). On _amd64_ Linux no problem. Strictly said, AFAIK, the header is invalid, there is no problem with smallest valid 32 bit float value `2.2250738585072014e-308`, BTW. I am not familiar with _MetaIO_ internals, unfortunately i can not make a workaround quickly, may be i shall try little later.

**Comment by tbaudier** [comment]
Hi seanm,

> @tbaudier do you have some C++ example code we could run to reproduce?

Here you can find a minimal example in c++ (tried on MacOS with ITKv5.2.0):

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)

project(itk_example)

find_package(ITK REQUIRED)
include(${ITK_USE_FILE})
add_executable ( itk_example itk_example.cxx )
target_link_libraries ( itk_example ${ITK_LIBRARIES} )

```

itk_example.cxx:
```c++
#include "itkImage.h"
#include "itkImageFileReader.h"

int
main()
{

  constexpr unsigned int Dimension = 3;

  using PixelType = short;
  using ImageType = itk::Image<PixelType, Dimension>;

  using ReaderType = itk::ImageFileReader<ImageType>;
  ReaderType::Pointer reader = ReaderType::New();
  reader->SetFileName("patient-2mm.mhd");
  reader->Update();

  ImageType::Pointer image = reader->GetOutput();

  return EXIT_SUCCESS;
}
```
And it leads to the same error:

**Comment by issakomi** [comment]
At least the expression _6.95279e-310 < std::numeric_limits<double>::min()_ seems to work on macOS, so probably a check at appropriate place in _MetaIO_ could be done

```
#include <limits>
#include <iostream>
int main(int, char**)
{
  const double x  = 6.95279e-310;
  const double min  = std::numeric_limits<double>::min();
  const double dmin = std::numeric_limits<double>::denorm_min();
  std::cout << "x=" << x << std::endl;
  std::cout << "min=" << min << std::endl;
  std::cout << "dmin=" << dmin << std::endl;
  if (x < min)
  {
    std::cout << "x < min" << std::endl;
  }
  return 0;
}
```

**Comment by issakomi** [comment]
> I have no idea if it's actually related, but it does remind me of this: https://bugs.llvm.org/show_bug.cgi?id=17782

i guess not this bug, this works, probably the error happens somewhere during calculating dependencies of fields, WIP

```cpp
#include <iostream>
#include <sstream>

int main(int,char**)
{
  std::istringstream iss("6.95279e-310");
  double n;
  iss >> n;
  std::cout << n << std::endl;
  return 0;
}
```

```
mi@mis-Mac-mini ~ % ./a.out 
6.95279e-310
```

**Comment by issakomi** [comment]
Seems a possible workaround is to replace lines like
```cpp
  fp >> (*fieldIter)->value[0];
```

with code there the value will be put into temporary variable, compared and _istream_ checked for _fail_ bit, if bit is set - try to clear it (on macOS). Worked for me with Big Sur. WIP.

```cpp
  double tmp0;
  fp >> tmp0;
  if (tmp0 < std::numeric_limits<double>::min())
  {
    tmp0 = 0.0f;
  }
  (*fieldIter)->value[0] = tmp0;
#ifdef __APPLE__
  if (fp.fail())
  {
    try
    {
      fp.clear();
    }
    catch(std::ifstream::failure & e)
    {
      std::cerr << e.what() << std::endl;
      return false;
    }
  }
#endif
```

This should be done on many places (float, double, float/double arrays, matrix).
Not sure i will do a PR or look further at the issue, it depends how important this is.
Here is a branch:
https://github.com/issakomi/MetaIO/tree/macos_underflow

To test simply try _metaUtils.cxx_ from the branch.

**Comment by dzenanz** [comment]
The suggested code could be put into a method so `fp >> (*fieldIter)->value[0];` becomes `readField(fp, (*fieldIter)->value[0]);`. But I think that this problem is of low importance.

**Comment by dzenanz** [comment]
Now I see you branch @issakomi. You have written quite a bit of code there? Why not make it into a PR?

@tbaudier can you please test @issakomi's branch?

**Comment by issakomi** [comment]
Interesting, on Linux almost everything works, .e.g for `1e-9999999999999999999999999` the value is `0` and stream doesn't fail.

**Comment by issakomi** [comment]
> Why not make it into a PR?

One reason is that i am not sure how important it is, float value less is minimum is probably an error somewhere and also there is one unanswered issue related to stream too, this one 
https://github.com/Kitware/MetaIO/issues/106
But if owner think it makes sense, why not, of course

**Comment by Leengit** [comment]
> Interesting, on Linux almost everything works, e.g for `1e-9999999999999999999999999` the value is `0` and stream doesn't fail.

The failing values are subnormals for float64 values, where 1e-9999999999999999999999999 is not.

**Comment by tbaudier** [comment]
> Now I see you branch @issakomi. You have written quite a bit of code there? Why not make it into a PR?
> 
> @tbaudier can you please test @issakomi's branch?

I tested the issakomi branch and it works on my Mac. Thank you very much

**Comment by blowekamp** [comment]
Perviously when it was discovered of the lack of consistent double/float point reading from ASCII, ITK integrated the third party library [DoubleConversion](https://github.com/google/double-conversion):
https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/DoubleConversion

**Comment by issakomi** [comment]
> The failing values are subnormals for float64 values, where 1e-9999999999999999999999999 is not.

On macOS for _double_ everything less than `numeric_limits<double>::min()` ends up with failed bit, on Linux nothing.

**Comment by seanm** [comment]
> On macOS (tested on Big Sur) for _double_ everything less than `numeric_limits<double>::min()` ends up with _fail_ bit, on Linux nothing.

I wonder if it's really macOS vs linux, and not: [libc++](https://libcxx.llvm.org/) vs [libstdc++](https://gcc.gnu.org/onlinedocs/libstdc++/).

Could be interesting to try FreeBSD, or linux with libc++...

**Comment by issakomi** [comment]
> I wonder if it's really macOS vs linux, and not: [libc++](https://libcxx.llvm.org/) vs [libstdc++](https://gcc.gnu.org/onlinedocs/libstdc++/).
> 
> Could be interesting to try FreeBSD, or linux with libc++...

Yes, it is libc++ vs libstdc++.

On Linux (Debian 10), exactly the same behavior:

```cpp
#include <iostream>
#include <sstream>

int main(int,char**)
{
  std::istringstream iss("6.95279e-310");
  //std::istringstream iss("2.2250738585072014e-308");
  //std::istringstream iss("-1e-9999999999999999999999999999");
  double n;
  iss >> n;
  std::cout << "fail=" << (iss.fail() ? "true" : "false") << std::endl;
  std::cout << n << std::endl;
  return 0;
}
```

```
r@deb:~$ clang++-7 -stdlib=libc++ test0.cpp -lc++abi
r@deb:~$ ./a.out 
fail=true
6.95279e-310
```

```
r@deb:~$ ./a.out 
fail=false
2.22507e-308
```

**Comment by Leengit** [comment]
Although I didn't find the official standard, folks on the web claim that the C++ standard allows a bit of freedom with subnormal numbers, in whether and how to handle them.  So, I see three options:

1. Hunt around on each platform for libraries that handle subnormals well, and tell users that if they don't do what we do then their results may be unpredictable. 
2. Deliberately hamper any implementation that we have that tries to deliver more than a minimum standard we set.  For example, we could set all input subnormal values to zero.
3. Allow different platforms to work differently, and tell users this somewhere in the documentation.

**Comment by blowekamp** [comment]
> Although I didn't find the official standard, folks on the web claim that the C++ standard allows a bit of freedom with subnormal numbers, in whether and how to handle them. So, I see three options:
> 
> 1. Hunt around on each platform for libraries that handle subnormals well, and tell users that if they don't do what we do then their results may be unpredictable.
> 2. Deliberately hamper any implementation that we have that tries to deliver more than a minimum standard we set.  For example, we could set all input subnormal values to zero.
> 3. Allow different platforms to work differently, and tell users this somewhere in the documentation.

I would also add:
 4. Have the MetaIO library use ( be default or have as an option), the [DoubleConvert](https://github.com/google/double-conversion) library for reading and writing float/double numbers.

**Comment by issakomi** [comment]
> The suggested code could be put into a method so `fp >> (*fieldIter)->value[0];` becomes `readField(fp, (*fieldIter)->value[0]);`. But I think that this problem is of low importance.

Done in WIP [PR](https://github.com/Kitware/MetaIO/pull/108)
