### ISSUE TITLE
Leaked semaphore object in MONAI integration tests

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2603]
### Description

In https://github.com/Project-MONAI/MONAI/pull/2274 we are observing:

```
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 33 leaked semaphore objects to clean up at shutdown
```

https://github.com/Project-MONAI/MONAI/runs/2728004520?check_suite_focus=true#step:7:2534

### Steps to Reproduce

MONAI integration tests in https://github.com/Project-MONAI/MONAI/pull/2274

### Expected behavior

No warnings.

### Actual behavior

Pesky warnings.

### Versions

Observed with `itk-5.2.0.post3`.

### Additional Information

We thought https://github.com/InsightSoftwareConsortium/ITK/commit/cfdb5023a82fc61f3825231b257ca47f4d9d4d8a should avoid this, but there may be another code path, etc.

CC @wyli @aylward @hjmjohnson @dzenanz

**Comment by wyli** [comment]
Thanks for tracking this @thewtex. 
Not sure if this could be treated as a fix for this issue, but I'm able to avoid the warning by using 
`torch.multiprocessing.get_context("spawn")`  instead of  
`torch.multiprocessing.set_start_method("spawn")` 
(please see https://github.com/Project-MONAI/MONAI/pull/2615/commits/ac7944e1a296cef39b71106fc204abd771b8a825).

**Comment by dzenanz** [comment]
@wyli Can you check whether PR #2649 helps this semaphore leak?

**Comment by wyli** [comment]
> @wyli Can you check whether PR #2649 helps this semaphore leak?

Happy to test if there are compiled binaries for Ubuntu or Macos... Otherwise I don't currently set up the build environment for the c++ core, I may try to build and get back to you later

**Comment by wyli** [comment]
now able to reproduce the issue with itk-5.2.0.post3 + torch (it's not a monai issue)
```py
import multiprocessing

try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass

from itk import Image
import torch

if __name__ == "__main__":
    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass

```

**Comment by dzenanz** [comment]
With #2649 now in master, there is no semaphore leak, even when un-commenting the commented code:
```py
#import multiprocessing
#
#try:
#    multiprocessing.set_start_method("fork")
#except RuntimeError:
#    pass
#
from itk import Image
import torch

if __name__ == "__main__":
    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass
```
With "spawn" method, the leak is still present.

My setup:
```text
Linux corista 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

MONAI version: 0.6.0rc2+2.g3254ac39
Numpy version: 1.20.3
Pytorch version: 1.9.0+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 3254ac39c57cdd6df1bc21b36c03cb9171dbcfb2

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: NOT INSTALLED or UNKNOWN VERSION.
Tensorboard version: 2.5.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: 5.3.0
tqdm version: NOT INSTALLED or UNKNOWN VERSION.
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.8.0
pandas version: 1.2.5
einops version: NOT INSTALLED or UNKNOWN VERSION.
```

**Comment by thewtex** [comment]
> but I'm able to avoid the warning by using
torch.multiprocessing.get_context("spawn") instead of
torch.multiprocessing.set_start_method("spawn")
(please see Project-MONAI/MONAI@ac7944e,

@wyli great work here.

Indeed, the CPython documentation on `multiprocessing` start methods states, 

> set_start_method() should not be used more than once in the program.

And their example puts the `set_start_method` call under the condition `if __name__ == '__main__':`:

```
import multiprocessing as mp

[...]

if __name__ == '__main__':
    mp.set_start_method('spawn')
```

Debugging:

```
import multiprocessing

try:
    multiprocessing.set_start_method("spawn")
except RuntimeError:
    pass

from itk import Image
import torch

if __name__ == "__main__":
    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass
```

I found that `set_start_method` gets called multiple times, and this causes the leak.

This works:

```
import multiprocessing

from itk import Image
import torch

print(__name__)

if __name__ == '__main__':
    try:
        multiprocessing.set_start_method("spawn")
    except RuntimeError:
        pass

    for d in torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4):
        pass
```

In the spawned process, `__name__` is `__mp_main__`.

MONAI is working, we have a good handle on the cause, so closing. Thanks, everyone who helped with this tricky issue!
