### ISSUE TITLE
Similarity3DTransform::SetScale should recompute m_Offset

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#2629]
### Description

When `Similarity3DTransform::SetScale` is called, it does not compute `m_Offset`, which appears to cause an incorrect result from `similarity3DTransform.TransformPoint` when  `TransformPoint` is called directly after `SetScale`. 

https://github.com/InsightSoftwareConsortium/ITK/blob/895fc718e814527aa156f7ff63ca8d5e15761d26/Modules/Core/Transform/include/itkSimilarity3DTransform.hxx#L59-L65

The 2D version behaves differently: `Similarity2DTransform::SetScale` does compute `m_Offset`:

https://github.com/InsightSoftwareConsortium/ITK/blob/895fc718e814527aa156f7ff63ca8d5e15761d26/Modules/Core/Transform/include/itkSimilarity2DTransform.hxx#L112-L119

### Steps to Reproduce

The 2D transform:

    const auto transform2D = itk::Similarity2DTransform<double>::New();
    transform2D->SetCenter(7.0);
    transform2D->SetScale(3.0);
    std::cout << transform2D->TransformPoint({}) << '\n';

Prints _[-14, -14]_, which looks fine to me. However, the 3D version:

    const auto transform3D = itk::Similarity3DTransform<double>::New();
    transform3D->SetCenter(7.0);
    transform3D->SetScale(3.0);
    std::cout << transform3D->TransformPoint({}) << '\n';

Prints _[0, 0, 0]_, which appears wrong!

### Expected behavior

In general, `PointType(center + (scale * (input - center))`. When the input point is entirely zero (`{}`),  `center = PointType(7.0)` and `scale = 3.0`, I would expect `PointType(7.0 + (3.0 * (0.0 - 7.0))` == `PointType(-14.0)`.

### Versions

ITK 5.2, as well as revision 895fc718e814527aa156f7ff63ca8d5e15761d26 (today July 2, 2021 at the master branch)

### Additional Information

It looks like this inconsistency between the 2D and the 3D version of the similarity transform has been there for a long time already! Comparing the 2D and 3D version from commit 5d9e2fc59e94e0f8f9e862af10c423abcda8a144 by Luis Ibanez (@luisibanez), 29 April 2005:

https://github.com/InsightSoftwareConsortium/ITK/blob/5d9e2fc59e94e0f8f9e862af10c423abcda8a144/Code/Common/itkSimilarity2DTransform.txx#L121-L129

https://github.com/InsightSoftwareConsortium/ITK/blob/5d9e2fc59e94e0f8f9e862af10c423abcda8a144/Code/Common/itkSimilarity3DTransform.txx#L56-L64

**Comment by dzenanz** [comment]
Oh, I guess #2627 is testing this.
