### ISSUE TITLE
How to convert NIFTI or DICOM images into 3D mesh by using ITK? 

### ISSUE THREAD

**Issue by Truring** [InsightSoftwareConsortium/ITK#2645]
Hello, I'm using ITK for spine reconstruction. I have some spine segmentation images in NIFTI format, how can I use ITK to reconstruct 3D spine mesh from these segmentation nifti images?

![image](https://user-images.githubusercontent.com/22017747/125551813-d3c4f4c6-b99d-4823-aa1c-989dd3cacbfb.png)

**Comment by dzenanz** [comment]
This was asked and [answered](https://discourse.itk.org/t/how-to-convert-nifti-or-dicom-images-into-3d-mesh-by-using-itk/4265/2?u=dzenanz) on the forum.

**Comment by Truring** [comment]
> This was asked and [answered](https://discourse.itk.org/t/how-to-convert-nifti-or-dicom-images-into-3d-mesh-by-using-itk/4265/2?u=dzenanz) on the forum.

Thanks a lot!
