### ISSUE TITLE
Missing limits include

### ISSUE THREAD

**Issue by pzaffino** [InsightSoftwareConsortium/ITK#2651]
### Description

ITK build fails for a missing include.

### Steps to Reproduce

1. Try to compile ITK 5.2.0

### Expected behavior

Get the code built

### Actual behavior

Build fails for a missing include

### Reproducibility

100%

### Versions

ITK 5.2.0

### Environment

Arch Linux
GCC 11.1
CMake 3.21.0

### Additional Information

Adding
#include <limits>
to Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h
fix the issue.

**Comment by dzenanz** [comment]
Is ITK master affected by this compile error?

**Comment by pzaffino** [comment]
Sorry, yesterday I tried only from the tarball.

Now I tried the main branch too: it is affected but in a different way.

<pre class="prettyprint lang-cpp linenums">
#include &lt;limits&gt;
</pre>
is present in 

Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h

but missing in 

Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_math.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_na.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_quaternion.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_rational.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_rotation_matrix.cxx

**Comment by dzenanz** [comment]
@hjmjohnson @bradking please review/merge the PR:
https://github.com/vxl/vxl/pull/851

**Comment by dzenanz** [comment]
Paolo, can you verify that PR #2655 fixes the problem for you?

**Comment by pzaffino** [comment]
Which commit/tag ID?
I do not see any new commits.

**Comment by dzenanz** [comment]
1d8212081656e315ba8a3d5142caddc005fd9115, but that is currently only in my branch.

**Comment by pzaffino** [comment]
@dzenanz it looks fixed now!
