### ISSUE TITLE
Visual Studio 2019 16.10.4 VXL fatal error C1090: PDB API call failed, error code ‘3’

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#2661]
The PDB API call errors from Visual Studio 2019 (Debug configuration) have returned, with the latest update, [Visual Studio 2019 Version 16.10.4 (July 20, 2021)](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.10.4):

> C:\X\src\ITK\Modules\ThirdParty\VNL\src\vxl\v3p\netlib\libf2c\c_div.c : fatal error C1090: PDB API call failed, error code ‘3’: C:\X\bin\ITK\lib\Debug\itkv3p_netlib-5.3.pdb
> C:\X\src\ITK\Modules\ThirdParty\VNL\src\vxl\v3p\netlib\libf2c\exit_.c : fatal error C1090: PDB API call failed, error code ‘3’: C:\X\bin\ITK\lib\Debug\itkv3p_netlib-5.3.pdb
> C:\X\src\ITK\Modules\ThirdParty\VNL\src\vxl\v3p\netlib\libf2c\c_abs.c : fatal error C1090: PDB API call failed, error code ‘3’: C:\X\bin\ITK\lib\Debug\itkv3p_netlib-5.3.pdb
> C:\X\src\ITK\Modules\ThirdParty\VNL\src\vxl\v3p\netlib\libf2c\c_sqrt.c : fatal error C1090: PDB API call failed, error code ‘3’: C:\X\bin\ITK\lib\Debug\itkv3p_netlib-5.3.pdb
> C:\X\src\ITK\Modules\ThirdParty\VNL\src\vxl\v3p\netlib\v3p_netlib_init.c : fatal error C1090: PDB API call failed, error code ‘3’: C:\X\bin\ITK\lib\Debug\itkv3p_netlib-5.3.pdb
> cl : command line error D8040: error creating or communicating with child process

The compiler bug was originally reported by @dzenanz at https://developercommunity.visualstudio.com/t/fatal-error-c1090-pdb-api-call-failed-error-code-3/552999 

The original workaround by pull request https://github.com/vxl/vxl/pull/661 commit https://github.com/vxl/vxl/commit/c2427965d9a6ca41a007167079fd0636505eb285 (committed by Hans @hjmjohnson on 15 Aug 2019) no longer appears sufficient.

VS2109 16.10.4 does not seem to pass [the /FS compile option](https://docs.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes?view=msvc-160) to the compiler (cl.exe) anymore!

See also https://discourse.itk.org/t/itk-installation-error/3032/7

I just posted another Visual Studio bug report on this issue: https://developercommunity.visualstudio.com/t/VS2019-2019-16104-no-longer-passes-FS/1482274

EDIT: ~~Note: The issue does not apply to the previous version, VS2109 16.10.3.~~
Note: The issue also apply to the previous version, VS2109 16.10.3. It occurs specifically when using CMake 3.21.0, and is intended to be fixed with CMake 3.21.1.

**Comment by N-Dekker** [comment]
@bradking While I still think this is a Visual Studio bug, it appears triggered by a change in the way CMake processes `add_compile_options( "/FS" )`, from CMake version 3.21. Looking at commit https://github.com/Kitware/CMake/commit/887e9df0c7f5898905c670888a44e9a8a8ca82f7 "VS: Update v142 CL flag table for VS 16.10",  4 June 2021:

https://github.com/Kitware/CMake/blob/887e9df0c7f5898905c670888a44e9a8a8ca82f7/Templates/MSBuild/FlagTables/v142_CL.json#L777-L783

It appears that CMake version 3.21 generates (in vcxproj section `<ClCompile>`):

    <ForceSynchronousPDBWrites>true</ForceSynchronousPDBWrites> 

While older versions (including CMake 3.20.5) generate, instead:

    <AdditionalOptions>%(AdditionalOptions) /FS</AdditionalOptions>

On the following CMakeLists.txt

    cmake_minimum_required( VERSION 3.20 )
    project( MyProject )
    set(CMAKE_VERBOSE_MAKEFILE ON)
    add_compile_options( "/FS" )
    add_library(${PROJECT_NAME} MySource.cpp)

Is that an intended change of XML generation? If so, is it still possible with CMake version 3.21 to get the old output ( `AdditionalOptions>%(AdditionalOptions) /FS</AdditionalOptions>`) into the vcxproj file, possibly by using some other CMake commands? Because it appears to be a showstopper!

**Comment by bradking** [comment]
This is now [CMake Issue 22476](https://gitlab.kitware.com/cmake/cmake/-/issues/22476), thanks @N-Dekker.

**Comment by N-Dekker** [comment]
Fixed with CMake 3.21.1, which has just been released: https://discourse.cmake.org/t/cmake-3-21-1-available-for-download/3840/2
