### ISSUE TITLE
How to save nifti / dicom image with provided numpy array and affine matrix?

### ISSUE THREAD

**Issue by Nic-Ma** [InsightSoftwareConsortium/ITK#2663]
Hi @thewtex ,

We are trying to add the ITK writer in project MONAI, I searched the doc of ITK but I didn't find how to save a nifti or dicom image with provided numpy array and affine matrix. Could you please help show some example?

Expected code:
```py
def save(np_array: np.ndarray, affine_matrix: np.ndarray):
    itk_np_view = itk.image_view_from_array(np_array)
    itk_np_view.SetMatrix(affine_matrix)
    itk.imwrite(itk_np_view, filename)
```
But seems there is no `SetMatrix` API.

Thanks in advance.

**Comment by dzenanz** [comment]
The matrix should be broken down into 3x3 rotation, 3x1 offset/tranlation and 3x1 spacing (scaling).
```py
itk_np_view.SetDirection(rotation3x3)
itk_np_view.SetOrigin(translation3x1)
itk_np_view.SetSpacing(scaling3x1)
```
Docs for this are in [ImageBase](https://itk.org/Doxygen/html/classitk_1_1ImageBase.html).

I [recently added ](https://github.com/InsightSoftwareConsortium/ITK/pull/224) `ApplyToImageMetadata` method to `itk::Transform`. Sadly, it is not available in Python. I wasn't able to expose it - my best attempt is here:
https://github.com/dzenanz/ITK/commit/db8157e9edcbad0d9d2a6fd4e98fab8ad1c04fb0 (currently tip of the branch [pythonApplyToImageMetadata](https://github.com/dzenanz/ITK/tree/pythonApplyToImageMetadata)).

You could take a look at its code to see how to decompose 4x4 matrix into the 3 components ITK needs:
https://github.com/InsightSoftwareConsortium/ITK/blob/fba1299262014b6d6bf17139753181c72aa552f3/Modules/Core/Transform/include/itkTransform.hxx#L488-L516

**Comment by Nic-Ma** [comment]
Hi @dzenanz ,

Cool, thanks for your sharing!
I will try with your example ASAP.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @dzenanz and @thewtex ,

Thanks for your help, I added the logic to assign affine for the image.
But I found that I can't set spacing for a 3D image with multiple channels, can we save multiple channels data now?
For example, a image with shape [64, 64, 64, 3], where 3 is the channels.

Thanks.

**Comment by dzenanz** [comment]
If you had image with RGB pixels and shape 64x64x64, I assume the affine logic would work. If you need arbitrary number of components, then I assume you would need to add another dimension to origin, spacing and direction. For example, extend spacing from [0.5, 0.5, 1.5] to [0.5, 0.5, 1.5, 1.0].

**Comment by Nic-Ma** [comment]
Hi @dzenanz ,

Thanks for your explanation.
I am saving 3D medical images and the affine is for 3D dims, seems can't set the spacing.
Do you have an python example to set spacing for a **3D multi-channels** image?

Thanks in advance.

**Comment by Nic-Ma** [comment]
CC @wyli for further discussion.

Thansk.

**Comment by thewtex** [comment]
@Nic-Ma @wyli I have an example script in progress -- will share when finished.

**Comment by thewtex** [comment]
Here is the script with a `def save(np_array: np.ndarray, filename: str, affine_matrix: np.ndarray):` demonstrated on 3D and 2D images, scalar and multi-channel:

https://gist.github.com/thewtex/9503448d2ad1dfacc2cbd620d95d3dac

**Comment by Nic-Ma** [comment]
Hi @wyli , this example may solve the saving issue in our `SaveImage` development.

Thanks.

**Comment by wyli** [comment]
thanks for the support, this is now addressed. implementation at: https://github.com/Project-MONAI/MONAI/blob/4d0baa0a94c1488af188f298c6f0d6087ced083c/monai/data/image_writer.py#L368 please feel free to close this ticket.

**Comment by dzenanz** [comment]
Thanks for the update!
