### ISSUE TITLE
Doubt about itkScalarImageToCooccurenceMatrixFilter

### ISSUE THREAD

**Issue by Itsanewday** [InsightSoftwareConsortium/ITK#2700]
### Description

I found that the  itkScalarImageToCooccurrenceMatrixFilter has this warning:

WARNING: This probably won't work for pixels of double or long-double type
 unless you set the histogram min and max manually. This is because the largest
 histogram bin by default has max value of the largest possible pixel value
 plus 1. For double and long-double types, whose "RealType" as defined by the
 NumericTraits class is the same, and thus cannot hold any larger values,
 this would cause a float overflow.

 What makes me doubtful is that  why the largest possible pixel value plus 1? 
### Actual behavior

```none
```

**Comment by dzenanz** [comment]
This sounds more like a question for the [forum](https://discourse.itk.org/) than an issue.

**Comment by blowekamp** [comment]
Looks like a good fix :) Any change we could get this problematic case tested? Perhaps adding a micron sized test image of a few pixels?

**Comment by emmenlau** [comment]
> What makes me doubtful is that why the largest possible pixel value plus 1?

I think this is the default behavior for a histogram? As an example, a histogram for data type `uint8_t` is typically created so that it can count all integral value that fit into that data type, which is values `0` to `255`. In total that is `256` values, which is the same as "the largest possible pixel value plus 1".

A different question is if that filter should be changed to have a *default* of finding min and max automatically, because without min and max, the filter is basically useless for data types larger than `uint16_t` (which creates already a 4GB histogram!!!). But thats just my two cents...

**Comment by Itsanewday** [comment]
thanks



---Original---
From: "Mario ***@***.***&gt;
Date: Tue, Nov 23, 2021 05:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [InsightSoftwareConsortium/ITK] Doubt aboutitkScalarImageToCooccurenceMatrixFilter (#2700)




  
What makes me doubtful is that why the largest possible pixel value plus 1?
  
I think this is the default behavior for a histogram? As an example, a histogram for data type uint8_t is typically created so that it can count all integral value that fit into that data type, which is values 0 to 255. In total that is 256 values, which is the same as "the largest possible pixel value plus 1".
 
A different question is if that filter should be changed to have a default of finding min and max automatically, because without min and max, the filter is basically useless for data types larger than uint16_t (which creates already a 4GB histogram!!!). But thats just my two cents...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dzenanz** [comment]
Can this issue be closed now?

**Comment by Itsanewday** [comment]
> Can this issue be closed now?

Oh, i fogot it.
