### ISSUE TITLE
Unlimited memory usage when calling several `Image` and `Region` methods from Python

### ISSUE THREAD

**Issue by tao558** [InsightSoftwareConsortium/ITK#2705]
### Description
The below Python programs seem to require unlimited memory.

### Steps to Reproduce
This is a family of seemingly related issues, which have roughly the same setup. Run the below code to set up a few examples

```python
import itk

Dimension = 2
PixelType = itk.F
ImageType = itk.Image[PixelType, Dimension]

image = ImageType.New()

size = itk.Size[Dimension]()
size.Fill(500)

index = itk.Index[Dimension]()
index.Fill(50)

RegionType = itk.ImageRegion[Dimension]
region = RegionType()
region.SetIndex(index)
region.SetSize(size)

image.SetRegions(region)
image.Allocate()
```

With the above setup, run one of the following code cells and monitor memory usage. They all consume an unlimited amount of memory:

1.) `Region::IsInside` with tuple argument with x or y >= 256 or <= -6
```python
x, y = 256, 255
for i in range(10000000000000):
    region.IsInside((x + (i % 2), y + (i % 2)))
```

2.) `Image::TransformPhysicalPointToIndex` with tuple argument with x or y >= 256  or <= -6
```python
x, y = 256, 255
for i in range(10000000000):
    image.TransformPhysicalPointToIndex((x + (i % 2), y + (i % 2)))
```

3.) `Image::TransformPhysicalPointToIndex` with `itk.Point` argument with ANY value of x or y (as far as I can tell)
```python
x, y = 0, 0
for i in range(10000000000):
    p = itk.Point[PixelType, Dimension]()
    p[0] = x + (i % 2)
    p[1] = y + (i % 2)
    image.TransformPhysicalPointToIndex(p)
```

4.) `Image::TransformIndexToPhysicalPoint` with tuple argument with x or y >= 256 or <= -6
```python
x, y = 256, 255
for i in range(10000000000):
    image.TransformIndexToPhysicalPoint((x + (i % 2), y + (i % 2)))
```

Swapping tuples for `itk.Index` arguments for cases 1 and 4 resolves the issue. From [this](https://www.codementor.io/@arpitbhayani/how-python-implements-super-long-integers-12icwon5vk) source:

"Python preallocates small integers in a range of -5 to 256. This allocation happens during initialization and since we cannot update integers (immutability) these preallocated integers are singletons and are directly referenced instead of reallocating. This means every time we use/creates a small integer, python instead of reallocating just returns the reference of preallocated one.". Thanks @brad-t-moore 

This gives a hint to the above behavior.

### Actual behavior

```none
```
### Versions

ITK 5.2.0
### Environment
Python 3.6.9, Ubuntu 18.04

### Additional Information

Valgrind output for case 1:

```
==27314== LEAK SUMMARY:
==27314==    definitely lost: 64 bytes in 1 blocks
==27314==    indirectly lost: 0 bytes in 0 blocks
==27314==      possibly lost: 306,216 bytes in 200 blocks
==27314==    still reachable: 31,665,705 bytes in 36,532 blocks
==27314==                       of which reachable via heuristic:
==27314==                         stdstring          : 445,212 bytes in 5,969 blocks
==27314==         suppressed: 0 bytes in 0 blocks
```

Valgrind gives the same summary when swapping a tuple out for an `itk.Index` argument in case 1

**Comment by brad-t-moore** [comment]
FYI - we think it's due to the use of `PySequence_GetItem` in [Wrapping/Generators/Python/PyBase/pyBase.i](../blob/master/Wrapping/Generators/Python/PyBase/pyBase.i).  According to Python's documentation it returns a new reference and therefore should have an associated `Py_DECREF` after its use.  Working on compiling and verifying a PR now.

Note, this memory issue should impact any method that is using the PyBase.i sequence/vec wrapper code.  Our hypothesis is that the Python reuse of small integers and tuples was suppressing the memory leak.  For me, after calling `gc.collect()` the memory would _eventually_ (like minutes) be released.
