### ISSUE TITLE
Re-use the allocated memory buffer or allocated itk::Image

### ISSUE THREAD

**Issue by 7oud** [InsightSoftwareConsortium/ITK#2714]
### Description
when using a itk::filter, results that get from filter->GetOuput() are allocated by filter, If I want to run the filter in a loop, the filter will allocate and deallocate repeatedly, if allocate a buffer/image with correct size and data type in advance, can the filter reuse the allocated buffer as output memory instead of multi-allocate/deallocate memory. I don't find this function or interface in ITK

### Expected behavior
```
ImageType::Pointer allocedImage = ImageType::New();
// ...
allocedImage->Allocate();
filter->GetOuput(allocedImage);
```

**Comment by dzenanz** [comment]
You should take a look at the detailed description of [ProcessObject](https://itk.org/Doxygen/html/classitk_1_1ProcessObject.html), in particular `ReleaseData*` members. I think you want to call [`filter->SetReleaseDataBeforeUpdateFlag(false);`](https://itk.org/Doxygen/html/classitk_1_1ProcessObject.html#a95864e89fe7cb74593358634be65c38d)

**Comment by 7oud** [comment]
@dzenanz Thanks a lot for your reply, `SetReleaseDataBeforeUpdateFlag(false)` helps when re-using a itk::Image. Another situation, there is a allocated memory for repeated writing into, this buffer can manage itself by smart pointer. Now I want to use this buffer as the itk::Image data area,  if using `ImportImageFilter`, either there is a addtional data copy from fitler->GetOutput() to buffer, or the `fitler->GetOutput()` controlls the buffer lifetime, both are not optimal, Is ITK has the feature to create a `ImageHeader`, which only manage itself(just header), won't deallocate the buffer

**Comment by dzenanz** [comment]
I am not sure whether that can be accomplished. Using `ImportImageFilter` was a good try. One more thing to try is increase reference count on the [pixel container](https://itk.org/Doxygen/html/classitk_1_1Image.html#aab044de7c6a87f5bcd354e29f6c067f7):
```cpp
auto & buf = image->GetPixelContainer();
buf->Register();
// processing
buf->UnRegister(); // decrease reference count (allows deallocation)
```
Now the buffer should not be automatically deallocated. You might need to help it along by calling [`image->SetPixelContainer(buf);`](https://itk.org/Doxygen/html/classitk_1_1Image.html#a8d06b1a40123c542f882642df7cfc24d) to make sure the image uses the allocated buffer.
