### ISSUE TITLE
Mismatch documentation and code SyNImageRegistrationMethod GaussianSmoothingVarianceForTheUpdateField default value

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#273]
There appears a mismatch between documentation and the actual implementation of the default value for the `SyNImageRegistrationMethod` parameter `GaussianSmoothingVarianceForTheUpdateField`.

https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0b01/Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.h#L178 says:
```
  /**
   * Get/Set the Gaussian smoothing variance for the update field.
   * Default = 1.75.
   */
  itkSetMacro( GaussianSmoothingVarianceForTheUpdateField, RealType );
  itkGetConstReferenceMacro( GaussianSmoothingVarianceForTheUpdateField, RealType );
```
However, https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0b01/Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.hxx#L44 does, in the default-constructor of  `SyNImageRegistrationMethod`:
```
  m_GaussianSmoothingVarianceForTheUpdateField( 3.0 ),
```
Do you think the documentation is incorrect, or should the code be fixed?

@ntustison Nick, what do you think?

Note that this mismatch was there already with the initial version (Jan 10, 2012): https://github.com/InsightSoftwareConsortium/ITK/commit/ec3618594ea432f7fbeca9a8cfd5fa5d8aa929f1

**Comment by ntustison** [comment]
@N-Dekker Thanks.  Yeah, it should be 3.0.  I don't know where 1.75 came from.

**Comment by N-Dekker** [comment]
Thanks for your reply, @ntustison Now I see, it is actually 1.75 for two adaptor classes:

- [GaussianSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0b01/Modules/Registration/Common/include/itkGaussianSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor.hxx#L30)
- [GaussianExponentialDiffeomorphicTransformParametersAdaptor](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0b01/Modules/Registration/Common/include/itkGaussianExponentialDiffeomorphicTransformParametersAdaptor.hxx#L31)

Both adaptors have their `m_GaussianSmoothingVarianceForTheUpdateField` initialized to 1.75.  I hope that's just the way it was intended.

**Comment by N-Dekker** [comment]
It looks like there's a more general issue here: when the default value of a data member is documented in a _*.h_ file, while its actual initialization takes place elsewhere (_*.hxx_ or _*.cxx_), documentation and code can easily get out of sync. :frowning:

It appears that C++11 [in-class member initialization](https://isocpp.org/wiki/faq/cpp11-language-classes#member-init) can be of help, as was suggested by @dzenanz at discourse.itk.org topic  [SimpleType m_Var = initialValue;](https://discourse.itk.org/t/simpletype-m-var-initialvalue/651)

When a data member that is initialized _in-class_, within the _*.h_ file, its initial value is included automatically, with the doxygen generated documentation of the class. So it's self-documented! :relaxed:

**Comment by N-Dekker** [comment]
Fixed with the merge of pull request "DOC: issue #273: SyNImageRegistrationMethod default member initializers")
