### ISSUE TITLE
Compilation fail with ITK_WRAP_PYTHON=ON and ITK_USE_GPU=ON

### ISSUE THREAD

**Issue by ebarjou** [InsightSoftwareConsortium/ITK#2746]
### Description

I try to compile ITK with GPU support in order to be able to use the Cuda reconstruction algorithms of RTK under python. I compile ITK without including the RTK module yet.
The CMake runs flawlessly, but the build of ITK fail on my machine on master and on release 5.2.1.

### Steps to Reproduce

I use MSVC2019, called from a ninja build file generated by CMake.
From a fresh copy of the repo (either lastest release 5.2.1 or master), calling 
`cmake -GNinja -DITK_WRAP_PYTHON=ON -DITK_USE_GPU=ON ..`, then `ninja`.
The compilation fails while creating the python wrapper for some GPU-related classes.

### Expected behavior

The compilation should behave the same as without ITK_USE_GPU=ON.

### Actual behavior

A problem occurs during the compilation (happens a few times, reduced to show the issue with one file) : 
`
itkGPUInPlaceImageFilter: warning(4): ITK type not wrapped, or currently not known: itk::ImageToImageFilter< itk::Image< unsigned long long, 2 >, itk::GPUImage< unsigned long long, 2 > >
`

Followed by errors seemingly linked : 

`
FAILED: Wrapping/Modules/ITKGPUCommon/itkGPUInPlaceImageFilterPython.cpp Wrapping/Generators/Python/itk/itkGPUInPlaceImageFilterPython.py
cmd.exe [...]
C:\path\ITK\build\Wrapping\Typedefs\itkGPUInPlaceImageFilter.i(4395) : Warning 401: Nothing known about base class 'itk::ImageToImageFilter< itk::GPUImage< unsigned long long,2 >,itk::GPUImage< unsigned long long,2 > >'. Ignored.
C:\path\ITK\build\Wrapping\Typedefs\itkGPUInPlaceImageFilter.i(4395) : Warning 401: Maybe you forgot to instantiate 'itk::ImageToImageFilter< itk::GPUImage< unsigned long long,2 >,itk::GPUImage< unsigned long long,2 > >' using %template.
`

Full CMake and compilation output: https://pastebin.com/gydq9rBD (error seems to start at L.2101)

### Environment

Windows 10 x64
  MSVC2019
  Python 3.7.9
  Cuda Toolkit 11.2

**Comment by SimonRit** [comment]
ITK_USE_GPU is unrelated to CUDA, it is using OpenCL. To use CUDA in RTK, you should turn on the RTK_USE_CUDA option. See [INSTALLATION.md](https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md). If you have any trouble with this, I suggest reporting bugs on https://github.com/SimonRit/RTK/issues and difficulties on the mailing list rtk-users@openrtk.org.
The bug report is still valid for ITK_USE_GPU though...

**Comment by thewtex** [comment]
Re `ITK_USE_GPU` and Python wrapping, we are updating the OpenCL GPU framework and providing Python packages in:

https://github.com/InsightSoftwareConsortium/ITKCLEsperanto
https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend

These are works in progress, but they will provide binary Python packages that will *just work*.

**Comment by ebarjou** [comment]
Thanks for your responses !
I got RTK to compile and will try the pre-compiled python packages.

Should I close the ticket, or leave it open?

**Comment by thewtex** [comment]
@ebarjou great to hear.

Yes, if you could please close the issue and open more as needed :-)
