### ISSUE TITLE
3d rotation bounding box？

### ISSUE THREAD

**Issue by junqiangchen** [InsightSoftwareConsortium/ITK#2760]
hi,i use LabelGeometryImageFilterType function extract the bounding box,but i want to get rotated bounding box,including the bounding box center point,bounding box size and rotated angles with x-axis,y-axis,z-axis,is there have any function can do it?

**Comment by blowekamp** [comment]
Hello,

I believe you are looking for the "OrientedBoundingBox" attributes of the [ShapeLabelMap](https://itk.org/Doxygen/html/classitk_1_1ShapeLabelObject.html) object. These attributes consist of Direction, Origin, Size and Vertices. The direction and origin are useful when resampling the OBB to a new image. The "center point" could be computed as the average of the vertices, or the origin offset the 0.5 the size. The "rotated angles with x-axis, y-axis, -axis" may require to compute with an unambiguous definition of 3-D as there are multiple axis of rotation possible and the input image's direction cosine matrix needs consideration. It may be worth using quaternion for the rotational representation.
