### ISSUE TITLE
Building v5.2.1 fails on itkDCMTKImageIO.cxx

### ISSUE THREAD

**Issue by jcrudy** [InsightSoftwareConsortium/ITK#2762]
### Description

I get a build failure saying some types are not defined (output below).  It seems that the file ITK-build/Wrapping/itkDCMTKImageIO.cxx generated by the wrapping system is missing some includes. It seems the includes are missing from here: https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/IO/DCMTK/wrapping/itkDCMTKImageIO.wrap

The missing includes seem to be itkDCMTKImageIOFactory.h and itkDCMTKSeriesFileNames.h.

### Steps to Reproduce

Attempt to build the SimpleElastix super build, which clones and builds ITK. 

### Expected behavior

The build completes without error.

### Actual behavior

My build produces the following error:
```
Scanning dependencies of target ITKIODCMTKCastXML
[ 88%] Generating ../../itkDCMTKImageIO.xml
/workspaces/rapid-angio-2/SimpleElastix/build4/ITK-build/Wrapping/itkDCMTKImageIO.cxx:31:18: error: no type named 'DCMTKImageIOFactory' in namespace 'itk'
    typedef itk::DCMTKImageIOFactory itkDCMTKImageIOFactory;
            ~~~~~^
/workspaces/rapid-angio-2/SimpleElastix/build4/ITK-build/Wrapping/itkDCMTKImageIO.cxx:32:18: error: no member named 'DCMTKImageIOFactory' in namespace 'itk'
    typedef itk::DCMTKImageIOFactory::Pointer itkDCMTKImageIOFactory_Pointer;
            ~~~~~^
/workspaces/rapid-angio-2/SimpleElastix/build4/ITK-build/Wrapping/itkDCMTKImageIO.cxx:34:18: error: no type named 'DCMTKSeriesFileNames' in namespace 'itk'
    typedef itk::DCMTKSeriesFileNames itkDCMTKSeriesFileNames;
            ~~~~~^
/workspaces/rapid-angio-2/SimpleElastix/build4/ITK-build/Wrapping/itkDCMTKImageIO.cxx:35:18: error: no member named 'DCMTKSeriesFileNames' in namespace 'itk'
    typedef itk::DCMTKSeriesFileNames::Pointer itkDCMTKSeriesFileNames_Pointer;
            ~~~~~^
4 errors generated.
make[5]: *** [Wrapping/Modules/ITKIODCMTK/CMakeFiles/ITKIODCMTKCastXML.dir/build.make:82: Wrapping/itkDCMTKImageIO.xml] Error 1
```

### Reproducibility

100%

### Versions

v5.2.1

### Environment

I'm building under an anaconda environment in a centos7 docker container.  I am building as part of the superbuild for simpleelastix.  I set the ITK git tag to v5.2.1.  I'm using the compilers package from conda-forge.

**Comment by jcrudy** [comment]
Two more bits of info:
1. Someone else seems to have hit this issue: https://discourse.slicer.org/t/build-error-when-building-itkpython/15302
2. Modifying the file I linked above (https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/IO/DCMTK/wrapping/itkDCMTKImageIO.wrap) to add the missing includes has allowed the build to progress beyond that point for me.  The build is still in progress now.

**Comment by dzenanz** [comment]
Can you please [submit a PR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by jcrudy** [comment]
> Can you please [submit a PR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

Done.  See #2764
