### ISSUE TITLE
itk pythonic interface (imread, imwrite) doesn't support pathlib.Path

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITK#2763]
### Description

The ITK python interface doesn't support `pathlib.Path` paths.

### Steps to Reproduce

Run following code:
```
import itk
from pathlib import Path
p = Path("some_image.mhd")
img = itk.imread(p)
```

This results in following error:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/lloyd/Code/segmantic/.venv/lib/python3.9/site-packages/itk/support/extras.py", line 965, in imread
>     reader = template_reader_type.New(**kwargs)
>   File "/Users/lloyd/Code/segmantic/.venv/lib/python3.9/site-packages/itk/support/template_class.py", line 660, in New
>     return self._NewImageReader(
>   File "/Users/lloyd/Code/segmantic/.venv/lib/python3.9/site-packages/itk/support/template_class.py", line 153, in _NewImageReader
>     imageIO = itk.ImageIOFactory.CreateImageIO(
> TypeError: in method 'itkImageIOFactory_CreateImageIO', argument 1 of type 'char const *'
> 

As a workaround I can import the same file if I convert the `Path` object to  a `str` or f-string, e.g.
```
import itk
from pathlib import Path
p = Path("some_image.mhd")
img = itk.imread(f"{p}")
```

### Expected behavior

`pathlib.Path` is widely used and often better than `os.path`. ITK should support it.

### Actual behavior

Exception is thrown, see above.

### Reproducibility

100% Reproducible.

### Versions

- python 3.9 (Windows 10, MacOs)
- itk==5.2.1.post1

### Environment

na

### Additional Information

na

**Comment by dyollb** [comment]
@thewtex would be great if this could be fixed. if you can point me in the right direction I can have a look if I can come up with a PR, but I have never dug into the ITK wrapping infrastructure.

**Comment by dzenanz** [comment]
I guess you should look at https://github.com/InsightSoftwareConsortium/ITK/blob/895fc718e814527aa156f7ff63ca8d5e15761d26/Wrapping/Generators/Python/itk/support/extras.py#L868
and other similar instances in that file for `imread`, `meshread` etc.

**Comment by dzenanz** [comment]
Perhaps most instructive is handling in `imread`:
https://github.com/InsightSoftwareConsortium/ITK/blob/895fc718e814527aa156f7ff63ca8d5e15761d26/Wrapping/Generators/Python/itk/support/extras.py#L937
You could add a similar if condition to convert `pathlib.Path` into a plain string.

**Comment by thewtex** [comment]
@dyollb thanks for the report. Yes, you are right.

@dzenanz points to good locations. @dyollb if you could please create a patch, that would be appreciated! The changes are, e.g.

https://github.com/InsightSoftwareConsortium/ITK/blob/bcac892743c9171ba74131d29f9b47c53e671409/Wrapping/Generators/Python/itk/support/extras.py#L959

to
```
kwargs = {"FileNames": [str(fn) for fn in filename]}
```

https://github.com/InsightSoftwareConsortium/ITK/blob/bcac892743c9171ba74131d29f9b47c53e671409/Wrapping/Generators/Python/itk/support/extras.py#L964

to

```
kwargs = {"FileName": str(filename)}
```

https://github.com/InsightSoftwareConsortium/ITK/blob/bcac892743c9171ba74131d29f9b47c53e671409/Wrapping/Generators/Python/itk/support/extras.py#L1008-L1009

to

```
    writer = itk.MeshFileWriter[type(mesh)].New(
        Input=mesh, FileName=str(filename), UseCompression=compression
```

etc.

A test can be added by passing a `Path` here:

https://github.com/InsightSoftwareConsortium/ITK/blob/bcac892743c9171ba74131d29f9b47c53e671409/Wrapping/Generators/Python/Tests/extras.py#L145

**Comment by dyollb** [comment]
Thanks. I am on vacation this week. Will try next week.
