### ISSUE TITLE
vnl_matrix multiple definitions

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#279]
### Description

Build fails with shared libraries, tests and CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.

### Steps to Reproduce

Start CMake from Visual Studio command prompt with following options
`cmake -G Ninja -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_TESTING:BOOL=ON /path/to/ITK/source`

### Expected behavior

Build completes successfully

### Actual behavior

Link error is generated: `itkvnl-5.0.lib(itkvnl-5.0.dll) : error LNK2005: "public: __cdecl vnl_matrix<double>::vnl_matrix<double>(void)" (??0?$vnl_matrix@N@@QEAA@XZ) already defined in itkCoxDeBoorBSplineKernelFunctionTest.cxx.obj`

### Reproducibility

Always. Here is a link to a dashboard build: https://open.cdash.org/viewBuildError.php?buildid=5660838

### Environment

Windows 10 and VS2015 or VS2017.

**Comment by dzenanz** [comment]
I can reproduce this locally on my computer, but I don't know why the multiple definition is even invoked for this inline constructor of a template class. [Adding inline specifier](https://stackoverflow.com/questions/10535667/does-it-make-any-sense-to-use-inline-keyword-with-templates) to the [constructor](https://github.com/InsightSoftwareConsortium/ITK/blob/c5e5c614d7bb35379e61cb0cb6c628f9bd1fa35b/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h#L117) does not fix the error.

**Comment by hjmjohnson** [comment]
@dzenanz FYI:  All my windows builds are failing at 
Error	C1083	Cannot open include file: 'itkeigen/Eigen/Eigenvalues': No such file or directory	ITKCommon	d:\src\itk\modules\core\common\include\itksymmetriceigenanalysis.h	23	

I can not even get ITKCommon to build.  Sorry, but I won't be able to look at this right away.

As a quick fix, can you move the definition of vnl_matrix()

from the header to .hxx file?

  
template <class T>
vnl_matrix<T>::vnl_matrix () :
    num_rows(0),
    num_cols(0),
    data(nullptr)
  { }

**Comment by hjmjohnson** [comment]
I'm testing this build on mac.  So it's not a very good test:

diff --git a/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h b/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h
index ab3c7e20a37f..72ea5fb73903 100644
--- a/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h
+++ b/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h
@@ -114,12 +114,7 @@ class VNL_EXPORT vnl_matrix
 {
  public:
   //: Default constructor creates an empty matrix of size 0,0.
-  vnl_matrix() :
-    num_rows(0),
-    num_cols(0),
-    data(nullptr)
-  {
-  }
+  vnl_matrix();
 
   //: Construct a matrix of size r rows by c columns
   // Contents are unspecified.
diff --git a/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx b/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
index 50a57cb7e3ff..e249867454d8 100644
--- a/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
+++ b/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
@@ -133,6 +133,15 @@ do { \
 //: Creates a matrix with given number of rows and columns.
 // Elements are not initialized. O(m*n).
 
+template <class T>
+vnl_matrix<T>::vnl_matrix () :
+    num_rows(0),
+    num_cols(0),
+    data(nullptr)
+  {
+  }
+
+
 template <class T>
 vnl_matrix<T>::vnl_matrix (unsigned rowz, unsigned colz)
 : num_rows(rowz), num_cols(colz)

**Comment by hjmjohnson** [comment]
@dzenanz Would you be able to test this?  I can't get any windows builds working.  I keep running into a problem related to missing Eigen headers long before I get to your problem.

**Comment by dzenanz** [comment]
OK I am testing what happens when the constructor's definition is moved from `.h` into `.hxx` file.
