### ISSUE TITLE
Thread sanitizer reporting non-existing test files

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#2839]
### Description

The thread sanitizer (`Mac12.x-AppleClang-dbg-TSan`) build in `RogueResearch19` has been consistently reporting 5 tests not being run due to required files being missing:
https://open.cdash.org/viewTest.php?onlynotrun&buildid=7534737

### Steps to Reproduce

1. Set up a machine using Clang's thread sanitizer (https://clang.llvm.org/docs/ThreadSanitizer.html)
2. Clone ITK
3. Configure and build with the `BULD_TESTING` flag to `ON`.

### Expected behavior

The expected output files should exist/the dependent tests should not report that the required files are missing.

### Actual behavior

The following 5 tests report that the corresponding required input files are missing:
```
itkAdditiveGaussianNoiseImageFilterTestPSNR
itkJPEG2000Test03
itkSaltAndPepperNoiseImageFilterTestPSNR
itkShotNoiseImageFilterTestPSNR
itkSpeckleNoiseImageFilterTestPSNR
```

### Reproducibility

100%.

### Versions

ITK `master`.

### Environment

macOS
Apple Clang
TSan

But could probably be reproduced on any platform.

### Additional Information

All of the blamed tests depend on a previous test being run before and writing an output that is used/required by them, e.g.
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageNoise/test/CMakeLists.txt#L25

```
itk_add_test(NAME itkAdditiveGaussianNoiseImageFilterTest
  COMMAND ITKImageNoiseTestDriver
  itkAdditiveGaussianNoiseImageFilterTest
   DATA{${ITK_DATA_ROOT}/Input/cthead1.png}
   ${ITK_TEST_OUTPUT_DIR}/itkAdditiveGaussianNoiseImageFilterTest.png
   29.85 0)
itk_add_test(NAME itkAdditiveGaussianNoiseImageFilterTestPSNR
  COMMAND ITKImageNoiseTestDriver
  itkPeakSignalToNoiseRatioCalculatorTest
   DATA{${ITK_DATA_ROOT}/Input/cthead1.png}
   ${ITK_TEST_OUTPUT_DIR}/itkAdditiveGaussianNoiseImageFilterTest.png
   20 1)
set_tests_properties(itkAdditiveGaussianNoiseImageFilterTestPSNR
  PROPERTIES
   DEPENDS itkAdditiveGaussianNoiseImageFilterTest
   REQUIRED_FILES ${ITK_TEST_OUTPUT_DIR}/itkAdditiveGaussianNoiseImageFilterTest.png)
```

So the test `itkAdditiveGaussianNoiseImageFilterTestPSNR` uses `itkPeakSignalToNoiseRatioCalculatorTest.cxx`, which requires an input image and a noisy version of it to compute the PSNR. The noisy version is generated by another test (e.g. `itkAdditiveGaussianNoiseImageFilterTest` through `itkAdditiveGaussianNoiseImageFilterTest.cxx`), and thus the CMake `set_tests_properties` command is used to signal that `itkAdditiveGaussianNoiseImageFilterTestPSNR` depends on `itkAdditiveGaussianNoiseImageFilterTest`, requiring its output file `${ITK_TEST_OUTPUT_DIR}/itkAdditiveGaussianNoiseImageFilterTest.png`.

In the `ImageNoise` module all of the tests correspond to those run through `itkPeakSignalToNoiseRatioCalculatorTest.cxx`.

**Comment by seanm** [comment]
I ***think*** tomorrow's cdash should have a working TSan submission from Rogue19.

**Comment by seanm** [comment]
OK, the build I ran by hand worked, now "only" 283 tests failing:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=7550267

This patch should fix some:

https://github.com/InsightSoftwareConsortium/ITK/pull/2853

**Comment by jhlegarreta** [comment]
@seanm I had a look at the last TSan builds and it looks like the issue I reported has been fixed since a few days/you made the proper setup of the build.

I'd say the issue is fixed. Do you agree if I close?

**Comment by seanm** [comment]
Agreed.
