### ISSUE TITLE
Update to newest version of GDCM

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#284]
GDCM has been updated recently to address forward compatibility issues with cmake.

The ITKv5Migration scripts were applied and accepted to the GDCM build tree, so cleaner ITK compatible codebase is available.

Performance improvements were added to GDCM.

LTO build now succeeds cleanly with newest GDCM.

**Comment by dzenanz** [comment]
We just wait for a release and then run `UpdateFromUpstream.sh` script?

**Comment by hjmjohnson** [comment]
@dzenanz yes.  @malaterre merged some of this into the release branch on Thursday to provide better support for LTO, and I think he stated that they were working on a public tagged release soon (v3.0.0).

The final items needed for better/cleaner ITKv5 builds (more support for LTO with GDCM, and a requirement of GDCM 3.0.0) are still only available on the master branch.

There is not a critical need for this immediately, but hopefully, GDCM will be ready for inclusion in ITKv5 for the next beta release (December 18th ??).

**Comment by dzenanz** [comment]
@malaterre Can you update to latest GDCM once more before final release of ITK?

**Comment by malaterre** [comment]
@seanm Do you have time to do it ? I have never done it before, so I do not feel very comfortable doing it just before the next big release.

**Comment by dzenanz** [comment]
Updating is easy:
```bash
cd ITK-git/Modules/ThirdParty/GDCM
./UpdateFromUpstream.sh
```
What it is not clear to me is how to resolve the merge conflicts. Which version of CMake should be required, 3.9.5 or 3.9.2? And other similar choices.

**Comment by malaterre** [comment]
That's what I feared, those are not complete instructions:

```
...
git: 'worktree' is not a git command. See 'git --help'.
```

**Comment by dzenanz** [comment]
Git version 2.7.4 on my Ubuntu 16.04 is enough, but yours doesn't seem to be. What `git --version` gives?

**Comment by malaterre** [comment]
Here is mine

```
$ git --version
git version 1.8.3.1

```

**Comment by malaterre** [comment]
See:

* https://github.com/InsightSoftwareConsortium/ITK/pull/877
