### ISSUE TITLE
Windows Cross Environment git checkout failures for ITK build

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#286]
### Description

There may not be anything ITK can do to fix this, but a situtation that is very confusing arose on windows builds that is very difficult to understand why failures occur.  This issues is mostly to document the situation so that others who run into this know of one potential solution.

Environment:  WLS (Windows linux subsystem) with ubuntu (or other linux) installed with root user as the default  (poor choice! you should not always be the root user.)

If git is used in the "root" user on the ubuntu terminal, then file permissions are not configured correctly for the windows pathing in Visual studio.

NOTE: This problem is not universal.  many other packages build just fine.  

[Description of the issue]
### Steps to Reproduce

1.   as root on ubuntu, checkout or update or modify ITK source tree
2.   configure and try to build ITK
3.   wait for somewhat random error during build of some file not found or readable (due to permission issues).

### Expected behavior

Well, I guess the expected behavior is failing (due to file system permissions).  It's just confusing. 👍 
 
### Reproducibility
Did not spend time tracking down the exact sequence that causes the problem. But this did manifest in different scenarios differently with respect to which file was first to not be readable.

### Additional Information
Just a cautionary tale when using cross-OS tools/user permissions on a shared filesystem.

**Comment by hjmjohnson** [comment]
@dzenanz Just an FYI.  We can close immediately.

**Comment by dzenanz** [comment]
Thanks for the explanation. I was just about to send you an email asking what was the problem, when I saw you submitted this issue 😄
