### ISSUE TITLE
Progress report overflows

### ISSUE THREAD

**Issue by ozavalistyi** [InsightSoftwareConsortium/ITK#2874]
### Description

Despite that it seems from looking at the code of 
void ProcessObject::IncrementProgress(float increment)
that it protects from overflow, it doesn't and it easily overflows, if, for example, we increment progress 11 times by 0.1.
But because of floating-point arithmetic, it also overflows if we increment progress 10 times by 0.1.
This is because m_Progress.fetch_add(integerIncrement) doesn't return updated value, but the value that was stored in m_Progress before fetch_add() (see the description of fetch_add()). But even if fetch_add() was implemented in such a way, so that it would return an updated value, the code still would be incorrect, because race condition between multiple threads may occur. 
### Steps to Reproduce

Here's the code that reproduces the problem:

```cpp
#include <itk/itkResampleImageFilter.h>
#include <gtest/gtest.h>

TEST(Progress, IncrementOverflow)
{
  auto filter = itk::ResampleImageFilter<itk::Image<double, 3>, itk::Image<double, 3>>::New();
  for (size_t i = 0; i < 11; ++i)
  {
    filter->IncrementProgress(0.1);
    std::cout << filter->GetProgress() << std::endl;
  }
}
```
### Expected behavior

The expected output of the above code would be:
```none
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0
1.0
```
### Actual behavior

But the actual output is:
```none
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.25729e-08
0.1
```
As you can see, on the 10-th step it already overflowed (because of floating-point arithmetic), and on eleven step we get 0.1 instead of expected 1.0

### Reproducibility

100%.
### Versions

ITK 5.1.2 
But I looked at the latest master, and the code of IncrementProgress() is identical, so the issue is reproducible with the latest ITK.
### Environment

Windows 10
Compiler: Visual Studio 2019, version=14.26,host=x64

**Comment by dzenanz** [comment]
Confirmed.

**Comment by blowekamp** [comment]
I think a better implementation of ProcessObject::IncrementProgress could use an std::atomic<T>::atomic_compare_exchange  method. The method could do the overflow check before the "exchange" if the exchange fails then try again.

**Comment by dzenanz** [comment]
The proposed PR fixes the obvious error. It does not address possible race between threads, because all threads are expected to increase progress and it does not matter which one maxes out first.

This also alleviates the problem of numeric accuracy (0.1f being, in fact, 0.100000001).

**Comment by dzenanz** [comment]
The code I used to reproduce is:
```cpp
#include <itkResampleImageFilter.h>

void main()
{
  auto filter = itk::ResampleImageFilter<itk::Image<double, 3>, itk::Image<double, 3>>::New();
  for (size_t i = 0; i < 11; ++i)
  {
    filter->IncrementProgress(0.1);
    std::cout << filter->GetProgress() << std::endl;
  }
}
```
