### ISSUE TITLE
Some filters report progress both from theader and from themselves

### ISSUE THREAD

**Issue by ozavalistyi** [InsightSoftwareConsortium/ITK#2875]
### Description
In ITK 5 there's a possibility to report progress from threader. It can be controlled by flag ThreaderUpdateProgressOff() or ThreaderUpdateProgressOn(). 
Right now, 4 filters report their progress both from themselves and from threader, and because of the bug with progress overflow  that I reported earlier (https://github.com/InsightSoftwareConsortium/ITK/issues/2874), the progress overflows: it reaches 100% once, then it goes to 0%, and then again to 100%.
Those filters are:
itk::ResampleImageFilter, itk::LabelMapToLabelImageFilter, itk::LabelShapeKeepNObjectsImageFilter, itk::LabelMapFilter.

Even after the bug with overflow will be fixed, it is still wrong to report progress from both threader and filter, because it will reach 100% before it is actually 100%, so in any case it is needed to add this->ThreaderUpdateProgressOff() in their constructors.

### Steps to Reproduce

Here's the code that reproduces the bug for itk::ResampleImageFilter. The bug is similar for the rest of the filters.
https://gist.github.com/ozavalistyi/9a234eacb36316d922c0a9571ee13db7
### Expected behavior
Progress should be reported up to 100% and then stop.
The output of the code above should not contain "ERROR: Progress overflowed".

### Actual behavior
Progress is reported up to 100% once, then it overflows and is reported from 0% to 100% again (
The output of the above code contains "ERROR: Progress overflowed".
The output is attached to gist, that I provided.

### Reproducibility
100%

### Versions

ITK 5.1.2
But I looked at the latest master, and those filters do not contain this->ThreaderUpdateProgressOff() in their constructors, so it is reproducible with the latest ITK also.
### Environment

Windows 10
Compiler: Visual Studio 2019, version=14.26,host=x64

**Comment by blowekamp** [comment]
What multi threader are you using? Could you try with others available?

**Comment by dzenanz** [comment]
Good investigation @ozavalistyi! Adding a few `ThreaderUpdateProgressOff()` calls should not be hard. Do you want to [contribute](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md) the fix yourself?

**Comment by dzenanz** [comment]
@ozavalistyi can you check the fix in #3014?

**Comment by dzenanz** [comment]
@ozavalistyi can you check the fix in #3052?
