### ISSUE TITLE
DCMTK_USE_ICU variable does not overwrite DCMTK config when set to OFF

### ISSUE THREAD

**Issue by tim-evain** [InsightSoftwareConsortium/ITK#2877]
Hello folks, another DCMTK related issue here.

### Description

When building the ITKDCMTK_ExtProject with DCMTK_USE_ICU set to OFF, the configuration doesn't overwrite the  DCMTK_WITH_ICU (DCMTK-side) variable. On system where ICU libraries are present, this lead to DCMTK finding and setting itself to DCMTK_WITH_ICU=ON, which in turn lead to linking error when trying to build an application.

### Steps to Reproduce

1. Have ICU libraries installed (ex : `apt-get install libicu-dev`)
2. Build ITK with ITKDCMTK, ITKIODCMTK and ITKIOTransformDCMTK, and DCMTK_USE_ICU=OFF
3. Check ITKDCMTK_ExtProject cmake cache for DCMTK_WITH_ICU value

### Expected behavior

DCMTK_WITH_ICU to be set to OFF when DCMTK_USE_ICU is OFF

### Actual behavior

DCMTK_USE_ICU overwrites DCMTK config only for ON value

### Reproducibility

100%

### Versions

5.2.1

### Environment

Docker Image: Ubuntu 20.04
OS: Ubuntu 20.04
CMake: 3.16.3
Compiler: gcc 9.3

### Additional Information

The [CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.2.1/Modules/ThirdParty/DCMTK/CMakeLists.txt) for the project doesn't set anything in case the DCMTK_USE_ICU is OFF.
I was thinking it might be fixable with adding an `else` clause like:
```
if(DCMTK_USE_ICU)
[...]
else(DCMTK_USE_ICU)
   set(CHARSET_CONVERSION_ARGS
      -DDCMTK_WITH_ICU:BOOL=OFF
      )
endif()
```
but I'm not sure of the full extent of such change.

**Comment by dzenanz** [comment]
Your proposed fix sounds good to me. Can you make a PR?

**Comment by tim-evain** [comment]
Yeah sure. I'll try to do that for the end of the week.
