### ISSUE TITLE
Compilation Warning with Visual Studio C++ v142 (2019) 

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#2892]
We are getting the following compilation warnings 200+ times:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_memory.h(76,5): warning C5105: macro expansion producing 'defined' has undefined behavior (compiling source file D:\a\1\bld\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\chunkset.c) [D:\a\1\bld\ITK-build\Modules\ThirdParty\ZLIB\src\itkzlib-ng\zlib.vcxproj] [D:\a\1\bld\ITK.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_memory.h(76,5): warning C5105: macro expansion producing 'defined' has undefined behavior (compiling source file D:\a\1\bld\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\adler32.c) [D:\a\1\bld\ITK-build\Modules\ThirdParty\ZLIB\src\itkzlib-ng\zlib.vcxproj] [D:\a\1\bld\ITK.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_wstring.h(573,5): warning C5105: macro expansion producing 'defined' has undefined behavior (compiling source file D:\a\1\bld\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\chunkset.c) [D:\a\1\bld\ITK-build\Modules\ThirdParty\ZLIB\src\itkzlib-ng\zlib.vcxproj] [D:\a\1\bld\ITK.vcxproj]

These warnings are occurring on the SimpleITK Dashboard with "Visual Studio 16 2019" and the "v142" toolset.

I don't seem to be able to find VS 2019 v142 on the ITK dashboard.

**Comment by dzenanz** [comment]
I normally use VS2019, and ITK compiles without these warnings. Maybe you have a different warning level? I took a look at `chunkset.c`, which is pretty small, and I could not find a possible offender. Do you have a direct link to that dashboard entry? I could [not find it](https://open.cdash.org/index.php?project=simpleITK).

**Comment by blowekamp** [comment]
Is v141 or v142 the default with VS2019? 

I unaware of additional warning flags being passed to ITK. The external project file is here: https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/External_ITK.cmake

Here are the warnings:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7583963

And the two builds which get the warnings are in the continuous section:
https://open.cdash.org/index.php?project=SimpleITK&date=2021-11-20

**Comment by dzenanz** [comment]
v142 is the default for VS2019.

@N-Dekker did you encounter something like this?

**Comment by N-Dekker** [comment]
I haven't seen this warning before. But it appears reproducible at https://godbolt.org/z/E3nWod3xz

Having the example code from https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5105?view=msvc-170 as follows:
```

// C5105.cpp
// To demonstrate the warning,
// compile by using: cl /EHsc /experimental:preprocessor /DTEST C5105.cpp
// To fix the warning, change the DEFINED_TEST
// definition to the commented version.

#include <iostream>

#define DEFINED_TEST defined TEST
//#if defined TEST
//#define DEFINED_TEST 1
//#else
//#define DEFINED_TEST 0
//#endif

int main()
{
#if DEFINED_TEST  // C5105
    std::cout << "TEST defined\n";
#else
    std::cout << "TEST not defined\n";
#endif
}

```
Hope that helps!

**Comment by dzenanz** [comment]
But I don't see where such a pattern occurs in zlib. Can you point me to that please?

**Comment by N-Dekker** [comment]
Not sure, but maybe the following line of code triggered the warning:

> #if defined(_CRT_INTERNAL_NONSTDC_NAMES) && _CRT_INTERNAL_NONSTDC_NAMES

It's at line 76 of corecrt_memory.h and line 573 of corecrt_wstring.h at C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt on my laptop.

**Comment by dzenanz** [comment]
Yes, but which line in zlib triggers that?

**Comment by blowekamp** [comment]
This CMake issue looks similar:
https://gitlab.kitware.com/cmake/cmake/-/issues/21446

It may be issues related to the Windows SDK version 10.0.17763.0.  This is the version which Azure DevOps is using currently.

I could not reproduce with a new VM with a download of VS2022 ( assuming it is using a very new SDK ).

**Comment by N-Dekker** [comment]
> Yes, but which line in zlib triggers that?

@dzenanz  According to the message reported by Bradley:
> compiling source file D:\a\1\bld\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\chunkset.c

**Comment by N-Dekker** [comment]
A newer version of corecrt_memory.h, from C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt says at line 18:

> #pragma warning(disable: _UCRT_DISABLED_WARNINGS)

I guess that may have disabled their own warning!

**Comment by blowekamp** [comment]
I am going to consider a bug in the "10.0.17763.0" version of the Windows 10 Kit, which is resolved by latter versions, and not an ITK bug.
