### ISSUE TITLE
ITK Build Failure when doing Python Wrapping using Make

### ISSUE THREAD

**Issue by PranjalSahu** [InsightSoftwareConsortium/ITK#2908]
### Description

Build failure when building ITK with cmake using Make. It fails at around 41% progress with the following message.
```
[ 41%] Building CXX object Modules/Segmentation/Watersheds/src/CMakeFiles/ITKWatersheds.dir/itkWatershedMiniPipelineProgressCommand.cxx.o
make[2]: *** [Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonSwig.dir/build.make:461: Wrapping/Typedefs/itkFixedArray.i] Error 1
make[2]: *** Deleting file 'Wrapping/Typedefs/itkFixedArray.i'
make[1]: *** [CMakeFiles/Makefile2:32930: Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonSwig.dir/all] Error 2
```
I have tested both single thread and multi thread build with make (eg. make -j8). It fails for both cases.

It is building fine when using Ninja. 

Also I have narrowed down the change to commit: [ENH: Generate stub-files to support type hints](https://github.com/InsightSoftwareConsortium/ITK/commit/faa3ab0a7e36ad82ad9c817e282bea48e2ac380c)

### Steps to Reproduce
1. Configure cmake to use Make. 
2. Select Python wrapping
3. Build

### Expected behavior

Build should succeed.

### Actual behavior

```none
```

### Environment

Tested on both Linux system and Mac system. It failed on both.

**Comment by PranjalSahu** [comment]
@kian-weimer @hjmjohnson

**Comment by kian-weimer** [comment]
Thanks for alerting me to this issue. I'm now looking into the issue.

**Comment by hjmjohnson** [comment]
I am trying to replicate the problem.

**Comment by hjmjohnson** [comment]
I think I found the problem.  Fix coming shortly.
