### ISSUE TITLE
Fail to build on MacBook Pro M1 Pro

### ISSUE THREAD

**Issue by ChFed** [InsightSoftwareConsortium/ITK#2916]
Hello Everyone, 

I could not build ITK on a new MacBook Pro M1 Pro.  I did pull the latest master. 

Undefined symbols for architecture arm64:  "_itk_png_do_expand_palette_rgb8_neon"

interestingly this issue does not occur on a MacMini M1.

any ideas?

thank you and best regards, 

Christian 

Showing All Messages
[100%] Built target ITKIOMeshOBJ-all

[100%] Built target ITKIOMeshBYU-all

[100%] Built target ITKIOMeshVTK-all

[100%] Built target ITKIOMeshOFF-all

[100%] Built target ITKIOSpatialObjects-all

[100%] Built target ITKIOTransformHDF5-all

[100%] Built target ITKIOTransformInsightLegacy-all

[100%] Built target ITKIOTransformMatlab-all

Consolidate compiler generated dependencies of target itkTestDriver

Consolidate compiler generated dependencies of target ITKRegistrationMethodsv4

[100%] Built target ITKOptimizersv4-all

[100%] Built target ITKDeformableMesh-all

[100%] Built target ITKWatersheds-all

[100%] Built target ITKPDEDeformableRegistration-all

[100%] Linking CXX executable ../../../../bin/itkTestDriver

[100%] Built target ITKRegistrationMethodsv4

[100%] Built target ITKRegistrationMethodsv4-all

Undefined symbols for architecture arm64:

  "_itk_png_do_expand_palette_rgb8_neon", referenced from:

      _itk_png_do_read_transformations in libitkpng-5.2.a(pngrtran.c.o)

  "_itk_png_do_expand_palette_rgba8_neon", referenced from:

      _itk_png_do_read_transformations in libitkpng-5.2.a(pngrtran.c.o)

  "_itk_png_init_filter_functions_neon", referenced from:

      _itk_png_read_filter_row in libitkpng-5.2.a(pngrutil.c.o)

  "_itk_png_riffle_palette_neon", referenced from:

      _itk_png_do_read_transformations in libitkpng-5.2.a(pngrtran.c.o)

ld: symbol(s) not found for architecture arm64

make[2]: *** [bin/itkTestDriver] Error 1

make[1]: *** [Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/all] Error 2

make: *** [all] Error 2

**Comment by seanm** [comment]
What different between your Mini and your MacBook?  OS version?  Xcode version? cmake version?

**Comment by ChFed** [comment]
Thank you for your fast reply

MacMini M1: Mac OS v 12.0.1, XCode 13.1, cmake 3.21.1
MacBookPro M1 Pro: Mac OS v 12.0.1, XCode 13.1, cmake 3.20.1, upgraded to 3.22, still same error.

Copying the build ITK folder from the MacMini to the MacBookPro does work...

**Comment by seanm** [comment]
there must be some difference... you doing a plain build with default cmake options? Or, changing any options?

Might help to diff your CMakeCache.txt files.

**Comment by dzenanz** [comment]
Closing this due to lack of details from original poster.
