### ISSUE TITLE
Enforce positive Spacing

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#2917]
### Description

While image pixel spacing is assumed to be a positive length unit in ITK, this had not been strictly enforced in the past, and some applications used negative spacing to flip data direction. If a flip is desired, this is supported in ITK's `Direction` instead of `Spacing`.

Change the warning here:

master/Modules/Core/Common/include/itkImageBase.hxx#L75

to an error.

### Impact analysis

Changes may be required in existing applications. This update would be associated with ITK 6.

### Expected behavior

An attempt to set negative spacing throws an error.

### Actual behavior

This is not enforced in code.

### Versions

ITK version 5.X and below.

**Comment by blowekamp** [comment]
There exists image files with negative spacing. We must ensure that we are still able to read these files.

I think this is already done in the ImageFileReader:
https://github.com/InsightSoftwareConsortium/ITK/blob/6853d63728a181e437f45473deb53c111eb1a6b7/Modules/IO/ImageBase/include/itkImageFileReader.hxx#L220-L233

**Comment by seanm** [comment]
I recall some previous ITK version (4 to 5?) did some changes with negative space and I had to carry a local patch for a while... I'd be interested to test any PR that comes along...

**Comment by blowekamp** [comment]
Could this be implemented now with a "FUTURE_LEGACY_REMOVE" conditional?

**Comment by dzenanz** [comment]
It was [originally implemented](https://github.com/InsightSoftwareConsortium/ITK/commit/d447f0452bb5ea92a555e630d05b57da535bd3a9) with `FUTURE_LEGACY_REMOVE`, and that has been transformed into `LEGACY_REMOVE` during [transition to 5.0](https://github.com/InsightSoftwareConsortium/ITK/commit/5c84e6e6b4768e596439c9879d86f51fa4bda51a). So when we switch to 6.0, just remove conditional and throw an exception unconditionally.

**Comment by dzenanz** [comment]
The logic in my previous comment would hold, have the feature been working properly, see discussion in https://github.com/InsightSoftwareConsortium/ITK/pull/2911#issuecomment-984941366. Now I am not sure whether to remove it completely in 6.0, or keep it as legacy.

**Comment by blowekamp** [comment]
> The logic in my previous comment would hold, have the feature been working properly, see discussion in [#2911 (comment)](https://github.com/InsightSoftwareConsortium/ITK/pull/2911#issuecomment-984941366). Now I am not sure whether to remove it completely in 6.0, or keep it as legacy.

Perhaps there will be some ITKv5_COMPATIBILITY option, if necessary.
