### ISSUE TITLE
itk::BresenhamLine

### ISSUE THREAD

**Issue by crossmanith** [InsightSoftwareConsortium/ITK#2926]
BuildLine(IndexType p0, IndexType p1) creates lines exceeding the end point p1

https://itk.org/ITKExamples/src/Core/Common/BresenhamLine/Documentation.html?highlight=bresenham:
In method Line() a line from (0,0) to (5,5) is requested but a line from (0,0) to (6,6) is created.

**Comment by dzenanz** [comment]
Confirmed. Increasing (5,5) in that example makes the error more pronounced, e.g. (70,70) gives last index of [98,98].
