### ISSUE TITLE
ITK can only be wrapped for Python

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#2931]
### Description

At the moment, ITK is only tested, and is only successful in wrapping, ITK for Python bindings.

Java, Ruby, TCL all seem to be broken.

### Steps to Reproduce

Try to configure wrapping *ONLY* for one of the non-python languages (i.e. ruby)

### Expected behavior

Successful compilation of non-python bindings.

### Actual behavior

```none
 CMake Error at Modules/Core/Common/wrapping/itkImageDuplicator.wrap:3 (string):
   string sub-command FIND requires 3 or 4 parameters.
 Call Stack (most recent call first):
   Modules/Core/Common/wrapping/itkImageDuplicator.wrap:19 (EXTEND_IMAGE_DUPLICATOR)
   Wrapping/TypedefMacros.cmake:196 (include)
   Wrapping/TypedefMacros.cmake:177 (itk_load_submodule)
   Modules/Core/Common/wrapping/CMakeLists.txt:60 (itk_auto_load_submodules)
```

because .wrap files are hard-coded for python wrapping with ITK_WRAP_PYTHON_SWIG_EXT.

```cmake
macro(EXTEND_IMAGE_DUPLICATOR type)
    set(import_text "%import pyCommon.i\n")
    string(FIND ${ITK_WRAP_PYTHON_SWIG_EXT} ${import_text} pos)   <------------------- ERROR
    if(${pos} EQUAL -1)
        set(ITK_WRAP_PYTHON_SWIG_EXT "${import_text}${ITK_WRAP_PYTHON_SWIG_EXT}")
    endif()
  set(ITK_WRAP_PYTHON_SWIG_EXT "${ITK_WRAP_PYTHON_SWIG_EXT}DECL_PYTHON_FORCE_SNAKE_CASE_CLASS(itkImageDuplicator${type})\n")
endmacro()

```

### Reproducibility

100%

### Versions

At least the current master branch.

### Environment

ubuntu 20.04

**Comment by thewtex** [comment]
@hjmjohnson is there a particular language of interest? `itk-wasm` could provide bindings to other languages.

**Comment by dzenanz** [comment]
The wrapping for other languages was removed in #3212.
