### ISSUE TITLE
Add polyline

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#2956]
### Description

ITK is missing support for PolyLine, which makes interoperability with VTK hard.

### Expected behavior

Reading a .vtk file which contains PolyLines, and then immediately writing to a different file, should result in the file with the same content as the original.

### Actual behavior

All PolyLines in the original file are chopped up into a sequence of Lines, thus losing connectivity information.

### Additional Information

Steps:
1. Add itk::PolyLineCell class
2. Use it in mesh readers
3. Update relevant conversion classes in https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData
4. Check whether anything else needs updating

**Comment by dzenanz** [comment]
@PranjalSahu will work on this.

**Comment by thewtex** [comment]
Resolve via #3393
