### ISSUE TITLE
Check and change typos `it's` -> `its`

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#2997]
The term `it's` can be found 171 times in ITK cxx, h, and hxx files. Check which of these instances should be changed to `its`. From https://github.com/InsightSoftwareConsortium/ITK/pull/2996#discussion_r775281256.

**Comment by N-Dekker** [comment]
Actually I think it is a bug in the English language! The idea that `it's` means `it is` is inconsistent with _both_ Trump's _and_ Biden's presidency! The expression "Biden's presidency" cannot be expanded correctly to "Biden _is_ presidency"! It just means "the presidency _of_ Biden"!

If we just keep using the expression `it's things`, meaning "the things _of_ it", maybe they will eventually fix the English language  😸

**Comment by dzenanz** [comment]
> it is a bug in the English language

I totally agree! However, the English language doesn't have a maintainer, much less a GitHub repository 😄

**Comment by Leengit** [comment]
When I went to school they taught me that "its" is like other possessive pronouns (my, his, her, our, your, their) in that it has no apostrophe.  My retort 'What about "one's", "somebody's", "everyone's", "another's", etc?' fell on deaf ears.
