### ISSUE TITLE
Update eigen to 3.4

### ISSUE THREAD

**Issue by seanm** [InsightSoftwareConsortium/ITK#3045]
From the [look of the branch name](https://github.com/InsightSoftwareConsortium/ITK/blob/51dc8fee7da4e1a52d0190327316da512aac84f0/Modules/ThirdParty/Eigen3/UpdateFromUpstream.sh#L7), ITK master currently uses eigen 3.3.x.

3.4 was [released](https://eigen.tuxfamily.org/index.php?title=3.4) a few months ago.

In order to eventually fix all the [-Wreserved-id-macro warnings](https://open.cdash.org/viewBuildError.php?type=1&buildid=7660676) eigen will eventually need updating.  So I figure at least moving to the latest release will be a first step.

**Comment by thewtex** [comment]
CC @phcerdan

**Comment by seanm** [comment]
Anyone know if ITK's eigen has any customizations/modifications or is it unadulterated?

**Comment by phcerdan** [comment]
@seanm Their top CMakeLists.txt is the only thing altered from upstream. A lot of things (tests, etc) are just commented out.
I can find some time next week to update eigen, as I have done it a couple of times already. But if you want to give it a go ping, please ping me.

**Comment by seanm** [comment]
You'll probably be able to do it 10x faster than me :)

**Comment by phcerdan** [comment]
Yeah, it's a bit convoluted. I will try to clean it up for easier maintenance in the future. I followed the way VTK handled their internal dependencies at the time.
