### ISSUE TITLE
If no FFT filters are registered, then nullptr is returned from `New` causing segmentation faults.

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#3050]
The FFTFilters' New method may return a nullptr if the FFT factory is empty. This causes segmentation faults. It is not standard practice in C++ and ITK to check if a new fails to return an object.

An exception should be thrown if an object can not be allocated and constructed.

**Comment by blowekamp** [comment]
@dzenanz @tbirdso

**Comment by tbirdso** [comment]
I think this is reasonable and would certainly help with debugging. @dzenanz could you assign this one to me?
