### ISSUE TITLE
`itkConnectedRegionsMeshFilterPythonTest` is failing in Windows CI

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITK#3080]
### Description

`itkConnectedRegionsMeshFilterPythonTest` is failing in [recent Windows Python CI results](https://open.cdash.org/viewTest.php?onlyfailed&buildid=7672621).

Seems to have started after the recent commit [4bf1434](https://github.com/InsightSoftwareConsortium/ITK/commit/4bf1434852743edb885efa9f1e6237c7a703b555) added the test.

### Steps to Reproduce

1. Build ITK Python wrapping with the same CMake configuration as in [AzurePipelinesWindowsPython.yml](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml)
2. Run `ctest -C Release -R itkConnectedRegionsMeshFilterPythonTest`

### Expected behavior

Test passes

### Actual behavior

```
2022-01-11T15:44:34.6727167Z 184: Traceback (most recent call last):
2022-01-11T15:44:34.6800473Z 184:   File "D:/a/1/s/Modules/Core/Mesh/wrapping/test/itkConnectedRegionsMeshFilterTest.py", line 28, in <module>
2022-01-11T15:44:34.7029045Z 184:     threshold_filter = itk.BinaryThresholdImageFilter.IUC3IUC3.New()
2022-01-11T15:44:34.7057735Z 184:   File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\lazy.py", line 130, in __getattribute__
2022-01-11T15:44:34.7370988Z 184:     value = types.ModuleType.__getattribute__(self, attr)
2022-01-11T15:44:34.7422543Z 184: AttributeError: module 'itk' has no attribute 'BinaryThresholdImageFilter'
2022-01-11T15:44:34.7721303Z 184: itkTestDriver: Process exited with return value: 1
2022-01-11T15:44:34.9520603Z 58/71 Test #184: itkConnectedRegionsMeshFilterPythonTest .............***Failed    1.47 sec
```

### Reproducibility

100%

### Versions

`master` branch

### Environment

Windows only (passes on macOS and Linux)

### Additional Information

- Short-term resolution is likely the same as #3057, where `Module_ITKThresholding` needs to be explicitly turned `ON` for the module to be appropriately wrapped in Windows CI
- In the bigger picture this seems to be an issue with marking test dependencies; `ITKThresholding` is correctly marked as a test dependency in `itk-module.cmake` and ideally should be picked up for wrapping in CI. It's at best inconvenient for us to have to explicitly update the list of modules to wrap in `AzurePipelinesWindowsPython.yml` every time we add a new Python test.

**Comment by tbirdso** [comment]
@dzenanz @thewtex Would be interested in your thoughts here. Is it expected that CI should pick up and wrap modules required for testing in Python CI? We do explicitly turn off tests with `DISABLE_MODULE_TESTS:BOOL=ON` in Windows Python CI, so maybe this is an expected behavior and we need to be more careful or document this update as a requirement of adding Python tests?

@PranjalSahu Would you be willing / have the bandwidth to patch this issue following #3049? Should just be enabling a dependency in `AzurePipelinesWindowsPython.yml` -- see "Additional Information" in this issue.

**Comment by dzenanz** [comment]
We could try removing `DISABLE_MODULE_TESTS:BOOL=ON`, but I guess that was added there to prevent exceeding time limit.

Maybe we could reorganize the pipelines, to first build C++ with tests and run those tests, then have the second pipeline which builds python and runs python tests. This might be possible now and might not have been possible a few years ago when we switched from Jenkins to Azure.

**Comment by thewtex** [comment]
@PranjalSahu could you please follow-up on this issue?

After 5.3.0 is out, I plan to look into C++ modules, which should help with our build times. Ideally, we will be able to enable the entire Windows build, but we will have to see.

**Comment by PranjalSahu** [comment]
Yes, I can check how to cascade the test pipeline as @dzenanz  mentioned.

**Comment by tbirdso** [comment]
@dzenanz @thewtex Note that CI is now green after @PranjalSahu's successful patch in #3081, should larger-scale Azure pipeline changes be tracked in a separate issue?

**Comment by dzenanz** [comment]
Matt added #3093 to track it.
