### ISSUE TITLE
itkConceptChecking.h build problem

### ISSUE THREAD

**Issue by melrobin** [InsightSoftwareConsortium/ITK#3084]
The build from development sources fails with the following error:
[ 94%] Generating ../../itkCannyEdgeDetectionRecursiveGaussianImageFilter.xml
In file included from /home/melrobin/packages/ITK/build/Wrapping/itkCannyEdgeDetectionRecursiveGaussianImageFilter.cxx:2:
In file included from /home/melrobin/packages/ITK/Modules/Core/Common/include/itkOffset.h:22:
In file included from /home/melrobin/packages/ITK/Modules/Core/Common/include/itkMath.h:33:
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:933:17: error: no viable conversion from 'UniqueType_bool<false>' to 'UniqueType_bool<Self::Integral aka true>'
      IntegralT a = FalseT();
                ^   ~~~~~~~~
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:941:3: note: in instantiation of member function 'itk::Concept::IsFloatingPoint<signed char>::Constraints::constraints' requested here
  itkConceptConstraintsMacro();
  ^
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:63:58: note: expanded from macro 'itkConceptConstraintsMacro'
    using EnforcerInstantiation = Enforcer<&Constraints::constraints>; \
                                                         ^
/home/melrobin/packages/ITK/Modules/Core/Common/include/itkConceptChecking.h:134:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'itk::Concept::IsFloatingPoint::Constraints::FalseT' (aka 'UniqueType_bool<false>') to 'const itk::Concept::Detail::UniqueType_bool<true> &' for 1st argument
struct UniqueType_bool
       ^

The problem occurs with gcc 11.2.1.  There was a small const problem when I reported a similar problem previously, but I do not know how to fix it.  There are several more errors of the type mentioned above.

**Comment by thewtex** [comment]
@melrobin I ran into CastXML build errors with GCC 11.2.0, which are addressed with:

  https://github.com/InsightSoftwareConsortium/ITK/pull/3112

However, I did not run into this error. Are there any non-default CMake configuration options?

**Comment by melrobin** [comment]
I blew the build directory away and the build works.  I am adding modules one by one to try to track down where the problem could be.

**Comment by melrobin** [comment]
Narrowed it down.  The error occurs when adding the LesionSizingToolkit

**Comment by dzenanz** [comment]
LesionSizingToolkit is in need of maintenance. Whoever uses it, should devote some time to it. Please submit this issue [there](https://github.com/InsightSoftwareConsortium/LesionSizingToolkit/issues/) and possibly cross-reference it to this one.

**Comment by melrobin** [comment]
Aaaah  OK.  Thanks for that tip.
