### ISSUE TITLE
Wrap the rest of Registrationv4 methods

### ISSUE THREAD

**Issue by brad-t-moore** [InsightSoftwareConsortium/ITK#3099]
I'd like access to more Registrationv4 methods in Python.  Is there any reason not to wrap any of the classes in the v4 directories (i.e. the ones that haven't been wrapped yet)?  My gut exclusion criteria is anything that is only internally used by other registration classes, i.e., `itk::WindowConvergenceMonitoringFunction`.

If this is a good idea as a PR, my other questions are:

1. It seems that there is existing precedence that if a template is instantiated by a complex class (i.e. not a C++ standard type) that the instantiation happens in the .wrap file of the complex class (not the template).  For example, `itk::RegistrationParameterScalesFromPhysicalShift<itk::EuclideanDistancePointSetToPointSetMetricv4>` happens in .wrap file for `EuclideanDistancePointSetToPointSetMetricv4` not `RegistrationParameterScalesFromPhysicalShift`.  Now that I think about it, it makes sense as the `EuclideanDistancePointSetToPointSetMetricv4` .wrap file is aware of what types it's been instantiated over.  I'm asking this question for the remaining `RegistrationParameterScales*` classes and `CommanderIterationUpdatev4`.

2.  According to the Software Guide, testing is occurring in the CMakeLists.txt under wrapping/tests and is simply a call to .New()?

**Comment by thewtex** [comment]
@brad-t-moore yes, more Registrationv4 methods were wrapped in the last few months, an we should wrap more, moore. :-)

Re 1.: Some classes are wrapped along other classes because their are dependent classes for the class wrapped in the .wrap file. However, they could be broken out into their own .wrap file. Starting fresh, the preference is to add wrapping to a class' self-name .wrap file.

Re 2.: Yes, testing Python instantiation in wrapping/tests is usually sufficient. It is assumed that the C++ tests cover functionality.

**Comment by brad-t-moore** [comment]
So, one thing.  I'm noticing that in the cases of cross-wrapping, or when a template needs to be instantiated for a non-base type (e.g. instantiating `RegistrationParameterScalesFromPhysicalShift` with all the types of `EuclideanDistancePointSetToPointSetMetricv4`), things get a little complex.  For example, this is currently in itkEuclideanDistancePointSetToPointSetMetricv4.wrap:

```
itk_wrap_class("itk::EuclideanDistancePointSetToPointSetMetricv4" POINTER_WITH_2_SUPERCLASSES)
  foreach(d ${ITK_WRAP_IMAGE_DIMS})
    foreach(t ${types})
      itk_wrap_template("PS${ITKM_${t}}${d}" "itk::PointSet< ${ITKT_${t}},${d} >")
    endforeach()
  endforeach()
itk_end_wrap_class()

itk_wrap_class("itk::RegistrationParameterScalesFromPhysicalShift" POINTER_WITH_2_SUPERCLASSES)
  foreach(d ${ITK_WRAP_IMAGE_DIMS})
    foreach(t ${types})
      itk_wrap_template("EDPSTPSMPS${ITKM_${t}}${d}"
        "itk::EuclideanDistancePointSetToPointSetMetricv4< itk::PointSet< ${ITKT_${t}},${d} > >")
    endforeach()
  endforeach()
itk_end_wrap_class()
```
So that is starting to become logic that is iffy to copy-paste.  And oof, if there is anything that needs to be instantiated over the `CastImageFilter` types.

For the v4 classes, I can definitely push through and make it work by copying this instantiation loops.  An alternative, that maybe isn't suitable for this PR, would be to try and put hooks into `itk_wrap_*_all_generators` and have it create like a global instantiation dictionary CMake variable that could be queried.  Unfortunately, with the CMake language quirks for macro parameters, I don't see the possibility of adding like a _dry run only_ parameter to other methods.  Unless I'm completely missing something and this already exists.

**Comment by brad-t-moore** [comment]
To clarify, something like:
```
set(edpstpsmps_types itk_get_instantiated_types_by_key("itk::EuclideanDistancePointSetToPointSetMetricv4"))
# returns something like
# "EDPSTPSMPSD2#itk::EuclideanDistancePointSetToPointSetMetricv4< itk::PointSet< double, 2 > >;EDPSTPSMPSF3#itk::EuclideanDistancePointSetToPointSetMetricv4< itk::PointSet< float, 3 > >"
itk_wrap_class("itk::RegistrationParameterScalesFromPhysicalShift" POINTER_WITH_2_SUPERCLASSES)
foreach(t ${edpstpsmps_types })
  itk_wrap_template(itk_get_first(${t}) itk_get_second(${t}))
endforeach()
itk_end_wrap_class()
```

**Comment by brad-t-moore** [comment]
Also, `itk::PointSetToPointSetMetricv4` and `itk::PointSetToPointSetMetricWithIndexv4` are mangled to just "PS" instead of "PSTPSM".  I think this may be a bug?

**Comment by dzenanz** [comment]
@PranjalSahu might have a comment about that, as he recently used PointSet in wrapping.

**Comment by PranjalSahu** [comment]
I think it was done to reduce complexity in the naming. In the default setting it will be <PointSet, PointSet> so they probably chose to only use PS.  We can change it now (or later if other combinations occur).

There might be other places where the naming convention is not followed strictly. 
For ex. in [itkLabeledPointSetToPointSetMetricv4.wrap](https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/Registration/Metricsv4/wrapping/itkLabeledPointSetToPointSetMetricv4.wrap) only one PS is mentioned 

Also in the console I see that they can be imported as:
```
itk.PointSetToPointSetMetricWithIndexv4.PSD3.New()
itk.PointSetToPointSetMetricv4.PSD3.New()
```

**Comment by brad-t-moore** [comment]
Interesting, lemme see if there is a way to export some of these manglings so we can get a consensus.  I'm building/testing right now, but I think I have got everything remaining in Metricv4, Optimizersv4, Registrationv4.

**Comment by brad-t-moore** [comment]
@thewtex That confusing sample code will make a bit more sense once you see what I had to do (think I have to do) to get the registration parameter scale estimators properly instantiated.  But I'm inkling to get this wrapped up and make that it's own separate issue.

**Comment by brad-t-moore** [comment]
This might be obvious, but also noticed `itk::RegistrationParameterScalesFromIndexShift` can't be used with any of the PointSet-based metrics as it requires a FixedImageType to be defined in the TMetric.

**Comment by brad-t-moore** [comment]
OK, as is, `itk::OnePlusOneEvolutionaryOptimizerv4` can't be instantiated with any metric that uses a float as its internal computation type.  Because of the following call to `m_Metric->GetParameters()`.  If the metric is instantiated with a float that line fails with a type conversion error.  Doesn't seem like as is this class is using the TInternalComputationType template parameter as it should.  If someone thinks this is bug I'm happy to open another issue but in the meantime I'm just going to wrap this for double.

```
  unsigned int       spaceDimension = this->m_Metric->GetNumberOfParameters();
  vnl_matrix<double> A(spaceDimension, spaceDimension);
  vnl_vector<double> parent(this->m_Metric->GetParameters());
  vnl_vector<double> f_norm(spaceDimension);
  vnl_vector<double> child(spaceDimension);
  vnl_vector<double> delta(spaceDimension);
```
[[(https://github.com/InsightSoftwareConsortium/ITK/blob/f53e38ebceb2312a60cc343044a6b231f36772a1/Modules/Numerics/Optimizersv4/include/itkOnePlusOneEvolutionaryOptimizerv4.hxx#L97-L102)
](https://github.com/InsightSoftwareConsortium/ITK/blob/f53e38ebceb2312a60cc343044a6b231f36772a1/Modules/Numerics/Optimizersv4/include/itkOnePlusOneEvolutionaryOptimizerv4.hxx#L97-L102)

**Comment by brad-t-moore** [comment]
> @brad-t-moore Please check this example
> 
> [itkThinShellDemonsTestv4_Affine](https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/main/test/itkThinShellDemonsTestv4_Affine.cxx#L158)
> 
> Here, RegistrationParameterScalesFromPhysicalShift is used which is similar to RegistrationParameterScalesFromIndexShift. We create an image using the points in the pointset. Dimensions etc. are set using the bounding box.

Thanks for the link.  Yes, I can confirm that RegistrationParameterScalesFromPhysicalShift works.  As is, the Index version requires a parameters that the PointSet-based metrics don't have.

**Comment by thewtex** [comment]
> OK, as is, itk::OnePlusOneEvolutionaryOptimizerv4 can't be instantiated with a float. 

Some optimizers only support double.

**Comment by brad-t-moore** [comment]
Well, I have successful compilation but I am getting DLL load errors on the base ITK Python files.  In particular, `_ITKPyBasePython.pyd` seems to be linked to two different version of `python##.dll`.  Trying to figure out what has changed.

**Comment by thewtex** [comment]
Are all python-related variables in *CMakeCache.txt* as expected?

**Comment by brad-t-moore** [comment]
Recompiling now.  Current suspicion is that vcpkg mucked things up.  Will
give details if this works.

**Comment by brad-t-moore** [comment]
Brutal!  So the issue was I had vcpkg installed on this machine a while back.  At least with the version I had, they were implementing their vcpkg linking by simply inserting a `vcpkg/installed/lib/*.lib` in to the configured linker command in Visual Studio BY DEFAULT!  It wasn't even showing up in the command-line display in Visual Studio.  I had to run the build process in Diagnostic mode and then found the vcpkg line in the middle of my desperate grep'ing.  So, vcpkg had python37.lib somewhere and was adding that to the linker on top of the correct linking command coming from ITK.  This was after tracking the import error down to cpython and then using DependencyWalker to find the double python DLL reference in the ITK .pyd files.

https://github.com/microsoft/vcpkg/discussions/19149

I feel like I'm close, got the Python tests to run and 9 of the libraries are throwing errors but I'll be digging in later today.

**Comment by thewtex** [comment]
The Python debugging force is strong! :man_astronaut: :artificial_satellite: I can feel the power and how close you are! Excited for this!

**Comment by brad-t-moore** [comment]
@thewtex I think I'm running into cyclic-dependency issues.  As is, Metricsv4 has Optimizersv4 as a dependency (Metricsv4 <- Optimizersv4).  This is in part due to ObjectToObjectMetricBase being in Optimizersv4.  On the other side, Optimizersv4 has itkRegistrationParameterScalesFromJacobian, itkRegistrationParameterScalesFromPhysicalShift, and itkRegistrationParameterScalesFromIndexShift which while don't have a compile dependency on Metricsv4, are instantiated with Metricsv4.  This is where I think I'm running into a problem.  Currently, we have a handful of Metricsv4 classes including wrapping for itkRegistrationParameterScalesFromJacobian in their .wrap files (not in a itkRegistrationParameterScalesFromJacobian.wrap).  I attempted to move all of that into itkRegistrationParameterScalesFromJacobian.wrap (and .wraps for the other two).  But now, I'm running into errors like this:

```
7: Warning: Unknown parameter 'itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,2>,itk::Image<float,2>>' in template 'itk::RegistrationParameterScalesFromJacobian'
7: Warning: Unknown parameter 'itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,3>,itk::Image<float,3>>' in template 'itk::RegistrationParameterScalesFromJacobian'
7: Warning: template already defined 'itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,3>,itk::Image<float,3>>>'
7: Warning: Unknown parameter 'itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,2>,itk::Image<double,2>>' in template 'itk::RegistrationParameterScalesFromJacobian'
7: Warning: template already defined 'itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,2>,itk::Image<double,2>>>'
7: Warning: Unknown parameter 'itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,3>,itk::Image<double,3>>' in template 'itk::RegistrationParameterScalesFromJacobian'
7: Warning: template already defined 'itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,3>,itk::Image<double,3>>>'
7: Template itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,2>,itk::Image<float,2>>>
7:  already defined as <class 'itk.itkRegistrationParameterScalesFromJacobianPython.itkRegistrationParameterScalesFromJacobianANTSNCITIMF2'>
7:  is redefined as {cl}
7: Warning: template already defined 'itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,2>,itk::Image<float,2>>>'
7: Template itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float,3>,itk::Image<float,3>>>
7:  already defined as <class 'itk.itkRegistrationParameterScalesFromJacobianPython.itkRegistrationParameterScalesFromJacobianANTSNCITIMF3'>
7:  is redefined as {cl}
7: Template itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,2>,itk::Image<double,2>>>
7:  already defined as <class 'itk.itkRegistrationParameterScalesFromJacobianPython.itkRegistrationParameterScalesFromJacobianANTSNCITIMD2'>
7:  is redefined as {cl}
7: Template itk::RegistrationParameterScalesFromJacobian<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double,3>,itk::Image<double,3>>>
7:  already defined as <class 'itk.itkRegistrationParameterScalesFromJacobianPython.itkRegistrationParameterScalesFromJacobianANTSNCITIMD3'>
7:  is redefined as {cl}```

That error is occurring in the test findEmptyClasses.py and I think is due to the itk.force_load.

**Comment by brad-t-moore** [comment]
I'm going to move the .wrap files that have the cyclic dependency into Metricsv4 and report back.

**Comment by thewtex** [comment]
> I'm going to move the .wrap files (e.g. the new itkRegistrationParameterScalesFromJacobian.wrap) that have the cyclic dependency into Metricsv4 and report back.

@brad-t-moore good plan! :+1:

**Comment by brad-t-moore** [comment]
Posed to go but I will rebase and test to handle the merge conflicts.
