### ISSUE TITLE
include error

### ISSUE THREAD

**Issue by Eric-JH** [InsightSoftwareConsortium/ITK#3111]
### Description
once I include itkImageSeriesReader.h、itkImageSeriesWriter、itksys/SystemTools.hxx， there would be errors.
But the quotes of itkImage.h, itkGDCMImageIO.h and itkGDCMSeriesFileNames.h are normal and make no error.

### Steps to Reproduce
C++

#include \<iostream>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <itkImage.h>
#include <itkGDCMImageIO.h>
#include <itkGDCMSeriesFileNames.h>
#include \<vector>

#include <itkImageSeriesReader.h>
#include <itkImageSeriesWriter.h>
#include <itksys/SystemTools.hxx>
int main()
{
return 1;
}

### Expected behavior
No error

### Actual behavior
Error  LNK2019  unresolved external symbol "public: __cdecl itksys::SystemToolsManager::SystemToolsManager(void)" (??0SystemToolsManager@itksys@@QEAA@XZ) referenced in function "void __cdecl itksys::`dynamic initializer for 'SystemToolsManagerInstance''(void)" (??__ESystemToolsManagerInstance@itksys@@YAXXZ)	

### Environment

MSVC2022 
itk[core]:x64-windows -> 5.1.0#7

**Comment by thewtex** [comment]
Please try the latest tag of ITK and include a reproducible CMakeLists.txt and code.

**Comment by dzenanz** [comment]
Is inclusion of OpenCV headers necessary to reproduce?

**Comment by Eric-JH** [comment]
> Is inclusion of OpenCV headers necessary to reproduce?

Nope.

**Comment by Eric-JH** [comment]
> Please try the latest tag of ITK and include a reproducible CMakeLists.txt and code.

I found the problem was caused by my unproper targer_link_directories in CMakeLists.txt. 
[CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/files/7894220/CMakeLists.txt)
And I used vcpkg to manage the inclusion.
By the way, I used the example in [The ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf)
[CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/files/7894236/CMakeLists.txt)
But the error occured and the info was "CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable): Target "HelloWorld" links to target "GTest::GTest" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?"
But if I used target_link_libraries(TestDll ITKFFT ITKVTK ITKznz itksys ITKIOImageBase), the error disappeared.
So my question is can I use ${ITK_LIBS} or some other key words to include ITK so that I don't need to specify module to use in CMakeLists.

**Comment by thewtex** [comment]
`${ITK_LIBRARIES}` provides the libraries found.

**Comment by Eric-JH** [comment]
But I tried the follewed CMakeLists and error was reported. The error info was the same "CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable): Target "HelloWorld" links to target "GTest::GTest" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?"
[CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/files/7898744/CMakeLists.txt)
I don't understand...

**Comment by dzenanz** [comment]
You seem to be forgetting `INCLUDE(${ITK_USE_FILE})`. Take a look at the [Hello Insight](https://itk.org/Wiki/ITK/HelloInsight#Write_the_source_code).

**Comment by Eric-JH** [comment]
No, I test with INCLUDE(${ITK_USE_FILE}) and have tried the example. The same error was reported
[CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/files/7900773/CMakeLists.txt)

**Comment by dzenanz** [comment]
This issue is most likely related to `vcpkg`, so I suggest you focus your attention there.

**Comment by Eric-JH** [comment]
OK, thanks
