### ISSUE TITLE
build itk master branch with ITK_WRAP_rgb_unsigned_short=ON didn't get RGBUS in python wraps itk/support/types.py

### ISSUE THREAD

**Issue by zhusihan-python** [InsightSoftwareConsortium/ITK#3124]
### Description

build itk master branch with cmake, configure ITK_WRAP_rgb_unsigned_short=ON didn't get RGBUS in python wraps itk/support/types.py, it raise "module 'itk' has no attribute 'RGBUS'" error
during configure stage if you add a message("blah") inside this if: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc03/Wrapping/WrapBasicTypes.cmake#L119-L121
it step into the if branch indicate the ITK_WRAP_rgb_unsigned_short is valid.
https://user-images.githubusercontent.com/23504604/149808782-d53b60ae-011c-4ed3-b9b2-75873388b51f.png
### Steps to Reproduce

1. clone itk source code
2. configure cmake, set ITK_WRAP_PYTHON=ON
3. configure again set ITK_WRAP_rgb_unsigned_short=ON and  ITK_WRAP_unsigned_short=ON
4. configure->generate->open project with visual studio
5. select ALL_BUILD, choose Release X64, build
6. copy WrapITK.pth file into site-packages to use local build itk package
### Expected behavior

```
import itk

image = itk.imread(filename, itk.RGBUS)
```
won't raise undefiend Exception

### Actual behavior

module 'itk' has no attribute 'RGBUS'

### Reproducibility

everytime the same results
### Versions
tried 2 branch:
| branch | commit id |
| ---- | ---- |
| master | 6eaa4623e1 |
| python-builds | aec78197f5 |

### Environment

windows 10
cmake 3.22.1
visual studio 2017
python 3.9.10
### Additional Information

backgroud is in this [issue](https://github.com/InsightSoftwareConsortium/ITKMontage/issues/196)
cmake log: [cmake.log](https://github.com/InsightSoftwareConsortium/ITK/files/7886651/cmake.log)
visual studio build log: [visual_studio_build.log](https://github.com/InsightSoftwareConsortium/ITK/files/7886654/visual_studio_build.log)

**Comment by dzenanz** [comment]
@Leengit can you look into this?

**Comment by thewtex** [comment]
This:

```
image = itk.imread(filename, itk.RGBUS)
```

should be:

```
image = itk.imread(filename, itk.RGBPixel[itk.US])
```

**Comment by zhusihan-python** [comment]
> itk.RGBPixel[itk.US]
ide get a hint Cannot find reference 'RGBPixel' in '__init__.py' 
when i run
```
python .\SimpleMontage.py D:\projects\ITKMontage\examples\SampleData_Micro\ D:\projects\ITKMontage\examples\output_new\ mont
age.png
```
got exception
```
Traceback (most recent call last):
  File "D:\softwares\miniconda\envs\qt5\lib\site-packages\itk\support\template_class.py", line 525, in __getitem__
    this_item = self.__template__[key]
KeyError: (<class 'itk.itkRGBPixelPython.itkRGBPixelUS'>, 2)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\projects\ITKMontage\examples\SimpleMontage.py", line 45, in <module>
    image = itk.imread(filename, itk.RGBPixel[itk.US])
  File "D:\softwares\miniconda\envs\qt5\lib\site-packages\itk\support\extras.py", line 962, in imread
    ImageType = itk.Image[pixel_type, dimension]
  File "D:\softwares\miniconda\envs\qt5\lib\site-packages\itk\support\template_class.py", line 529, in __getitem__
    raise itk.TemplateTypeError(self, key)
itk.support.extras.TemplateTypeError: itk.Image is not wrapped for input type `itk.RGBPixel[itk.US], int`.
```

to get image = itk.imread(filename, itk.RGBPixel[itk.US]) work, should i set ITK_WRAP_IMAGE_DIMS=2,3,4,5 and rebuid itk?

**Comment by dzenanz** [comment]
Is there a complete list of wrapped types in that exception message? Can you copy-paste it here?

**Comment by zhusihan-python** [comment]
> Is there a complete list of wrapped types in that exception message? Can you copy-paste it here?
Supported input types:

itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,2]
itk.FixedArray[itk.D,2]
itk.Offset[2]
itk.SymmetricSecondRankTensor[itk.D,2]
itk.SymmetricSecondRankTensor[itk.F,2]
itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,3]
itk.FixedArray[itk.D,3]
itk.Offset[3]
itk.SymmetricSecondRankTensor[itk.D,3]
itk.SymmetricSecondRankTensor[itk.F,3]
itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,4]
itk.FixedArray[itk.D,4]
itk.Offset[4]
itk.SymmetricSecondRankTensor[itk.D,4]
itk.SymmetricSecondRankTensor[itk.F,4]
itk.Vector[itk.F,1]
itk.Vector[itk.F,1]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.CovariantVector[itk.D,2]
itk.CovariantVector[itk.D,3]
itk.CovariantVector[itk.D,4]
itk.NormalBandNode[itk.Image[itk.F,2]]
itk.NormalBandNode[itk.Image[itk.D,2]]
itk.NormalBandNode[itk.Image[itk.F,3]]
itk.NormalBandNode[itk.Image[itk.D,3]]
itk.NormalBandNode[itk.Image[itk.F,4]]
itk.NormalBandNode[itk.Image[itk.D,4]]

**Comment by zhusihan-python** [comment]
> Is there a complete list of wrapped types in that exception message? Can you copy-paste it here?

sor the logs post above is the itk installed by pip, i activated a wrong conda env, this is the local itk exception
```
Traceback (most recent call last):
  File "D:\projects\ITKMontage\examples\SimpleMontage.py", line 37, in <module>
    stage_tiles = itk.TileConfiguration[dimension]()
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\lazy.py", line 137, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\base.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\base.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\base.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\base.py", line 110, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\base.py", line 259, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\projects\build\Wrapping\Generators\Python\itk\support\..\ITKCommonPython.py", line 71, in <module>
    from itk.itkVectorPython import *
  File "D:\projects\build\Wrapping\Generators\Python\itk\itkVectorPython.py", line 830, in <module>
    class itkVectorSC1(itk.itkFixedArrayPython.itkFixedArraySC1):
  File "D:\projects\build\Wrapping\Generators\Python\itk\itkVectorPython.py", line 834, in itkVectorSC1
    GetVectorDimension = _swig_new_static_method(_itkVectorPython.itkVectorSC1_GetVectorDimension)
AttributeError: module '_itkVectorPython' has no attribute 'itkVectorSC1_GetVectorDimension'
```

**Comment by dzenanz** [comment]
Maybe `ITK_WRAP_VECTOR_COMPONENTS` needs to include 1?

**Comment by zhusihan-python** [comment]
> Maybe `ITK_WRAP_VECTOR_COMPONENTS` needs to include 1?

with ITK_WRAP_VECTOR_COMPONENTS 1 include rebuid,
![image](https://user-images.githubusercontent.com/23504604/150180440-96a0a96c-a021-4edc-bdc3-5be8480d59df.png)
now get AttributeError: module 'itk' has no attribute 'TileConfiguration'
```
Traceback (most recent call last):
  File "D:\projects\ITKMontage\examples\SimpleMontage.py", line 37, in <module>
    stage_tiles = itk.TileConfiguration[dimension]()
  File "D:\projects\build_python\Wrapping\Generators\Python\itk\support\lazy.py", line 130, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'TileConfiguration'
```
kind of weird, 3 days ago it can get to itk.imread, i will try the build verion on another pc tommorrow and update the result here

**Comment by dzenanz** [comment]
If you build ITK yourself, you need to enable `Module_Montage`. Otherwise it will not be built.

**Comment by zhusihan-python** [comment]
> If you build ITK yourself, you need to enable `Module_Montage`. Otherwise it will not be built.

my fault. the old version i compiled can work well, and i found the original itk can work well too with
```
image = itk.imread(filename, itk.RGBPixel[itk.US])
```
when save the output, use this to get RGB picture correctly
```
cast_image = resampleF.GetOutput().astype(itk.RGBPixel[itk.UC])
itk.imwrite(cast_image, str(out_file))
```
the output image
![image](https://user-images.githubusercontent.com/23504604/150289062-676de63a-c802-4c58-a881-4fc44366ff5a.png)
i think this issue can be closed, its not a bug, thanks for all your help
there is one more question, if output saved to tiff, its size is 1.5Gb while jpg is only 100Mb, is there any way to optimize the tiff file size?（as i know tiff is multi-level so its resonable to be bigger, i mean that if it can be shrink for a bit）

**Comment by thewtex** [comment]
@zhusihan-python well done with your persistence, and great to see your success!

The JPG has lossy compression, which explains the size difference. In the future, you could use the NGFF-OME-Zarr support we are working on, which will provide better lossless compression.
