### ISSUE TITLE
Intermittent Segfault in python DisplacementFieldTransform + resample_image_filter

### ISSUE THREAD

**Issue by HastingsGreer** [InsightSoftwareConsortium/ITK#3130]
### Description

When a resample_image_filter tries to interpolate a DisplacementFieldTransform that is not aligned with it, it usually extrapolates, but sometimes segfaults.

### Steps to Reproduce

1): Download this self contained [gist](https://gist.github.com/HastingsGreer/5d21606b4fa56f90f8521d6ac79210ed)
2): Run python DisplacementFieldSegault.py with numpy and itk installed

```
pip install itk numpy
wget https://gist.githubusercontent.com/HastingsGreer/5d21606b4fa56f90f8521d6ac79210ed/raw/d5449aab1492ccc345216a8265345cde5874ede0/DisplacementFieldSegfault.py
python DisplacementFieldSegfault.py
```

### Expected behavior

Either an error message stating that extrapolation is not supported by DisplacementFieldTransform, or the displacement always defaults to zero outside the defined region.

### Actual behavior

Displacement field transform sometimes defaults to zero displacement outside the defined region, and other times segfaults.

When run in a loop as in the submitted reproduction code, it always eventually segfaults.
```
$ python DisplacementFieldTransform.py
pre segfault
post_segfault
pre segfault
post_segfault
pre segfault
Segmentation fault (core dumped)
```

### Reproducibility

The submitted gist runs the offending code over and over until it segfaults: this usually takes 3 iterations, but sometimes only one. I have never seen it loop indefinitely without segfaulting.

### Environment 1
python 3.9
itk 5.3.0
numpy 1.21.2

In this environment, the segfault is usually after three iterations

### Environment 2
python 3.9
itk 5.2.1
numpy 1.21.3

In this environment, the segfault is always on the first iteration

**Comment by HastingsGreer** [comment]
My method of creating itk arrays of vectors was bad: caused underlying memory to get garbage collected.

**Comment by thewtex** [comment]
Hey @HastingsGreer !

Thanks for the awesome example and report! Your talent to find the corner cases is strong on this one :-)

> itk arrays of vectors was bad: caused underlying memory to get garbage collected.

I looked into the issue and found this was the source of the segfault, too.

```
    tr.SetDisplacementField(itk_disp_field)
        
    return tr
```

here we lose a reference count to the underlying NumPy array `itk_disp_field` is viewing. 

```
    return itk.PyBuffer[ImageType].GetImageViewFromArray(array)
```

Changing this to

```
      return itk.PyBuffer[ImageType].GetImageFromArray(array)
```

resolves the reference counting, but I found that it needs an `itk.ImageDuplicate` wrapped for double Vector images, which is not currently available in the `itk` package binaries. I will see if we add this without increasing the package size too much.

**Comment by HastingsGreer** [comment]
There seem to be two kinds of vector images in the python wrapping:
```
type1 = itk.VectorImage[itk.D, 3]
type2 = itk.Image[itk.Vector[itk.D, 3], 3]
```
and while `itk.image_from_array(..., vector=True)` creates type 1, `d = itk.DisplacementFieldTransform[itk.D, 3].New(); d.SetDisplacementField(...)` appears to only support type 2. 

Would allowing SetDisplacementField to receive and argument of type itk.VectorImage[itk.D, 3] be possible?

**Comment by dzenanz** [comment]
I don't see a problem with this. Adding VectorImage to DisplacementFieldTransform's [wrapping](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc03/Modules/Filtering/DisplacementField/wrapping/itkDisplacementFieldTransform.wrap) should not be hard.
