### ISSUE TITLE
BUG: KWStyle mishandles `template<unsigned>`

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITK#3143]
### Description

If
```c++
   template <unsigned int>
   struct Dispatch : public DispatchBase
   {};
```
is replaced with
```c++
   template <unsigned>
   struct Dispatch : public DispatchBase
   {};
```
then KWStyle gives the error:
```text
Modules/Core/Common/include/itkBSplineDerivativeKernelFunction.h:93: error: Template definition (unsigned) doesn't match regular expression
```

### Expected behavior

KWStyle should permit `unsigned` in this context of an unsigned template parameter that is unnamed.

### Actual behavior

KWStyle gives the error:
```text
Modules/Core/Common/include/itkBSplineDerivativeKernelFunction.h:93: error: Template definition (unsigned) doesn't match regular expression
```

### Reproducibility

100%

### Versions

Commit ae8cd2588968b1f9680fd3f981a3139e433babc9

### Environment

- Linux 5.13.0-27-generic <span>#</span>29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
- clang-format version 8.0.0 (tags/RELEASE_800/final)
- Python 3.8.10

**Comment by dzenanz** [comment]
This might be in https://github.com/Kitware/KWStyle/issues. Even if not, the fix should go there.

**Comment by Leengit** [comment]
Closing this issue in favor of https://github.com/Kitware/KWStyle/issues/106.
