### ISSUE TITLE
"unknown warning group '-Wimplicit-int-float-conversion'" = Apple Clang 10.0.1.10010046

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#3148]
The following compilation warning is occurring:
```
ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/util/DisableStupidWarnings.h:49:38: warning: unknown warning group '-Wimplicit-int-float-conversion', ignored [-Wunknown-warning-option]
```

This is occurring os Apple OS X, Xcode 10.30 with reported compiler version:
```
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
```

**Comment by seanm** [comment]
Where do you see it?  Have a cdash link?  You using newest master?

**Comment by blowekamp** [comment]
I'm seeing it on the SimpleITK Dashboard: https://open.cdash.org/viewBuildError.php?type=1&buildid=7704947

It is using the newish 5.3.rc03 tag.

**Comment by seanm** [comment]
I'd guess that predates https://github.com/InsightSoftwareConsortium/ITK/commit/ae8cd2588968b1f9680fd3f981a3139e433babc9

**Comment by blowekamp** [comment]
Awesome! Thank you!
