### ISSUE TITLE
Build error for wasm

### ISSUE THREAD

**Issue by engineer1109** [InsightSoftwareConsortium/ITK#3163]
### Description

Build error for wasm when -s USE_PTHREADS=1

Tells:

In file included from /home/wjl/github/ITK/Modules/Core/Common/src/itkPlatformMultiThreader.cxx:40:
/home/wjl/github/ITK/Modules/Core/Common/src/itkPlatformMultiThreaderSingle.cxx:42:29: error: use of undeclared identifier 'm_GlobalMaximumNumberOfThreads'; did you mean 'm_MaximumNumberOfThreads'?

I changed  m_GlobalMaximumNumberOfThreads  to MultiThreaderBase::GetGlobalMaximumNumberOfThreads() will be ok.

### Actual behavior

```none
```

### Versions

Master , the lastest

### Environment

Linux 

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.17
clang version 13.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 3b677b81cec7b3c5132aee8fccc30252d87deb69)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by thewtex** [comment]
To use wasm, use [itk-wasm](http://insightsoftwareconsortium.github.io/itk-wasm). For parallelism, use the WebWorkerPool:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/12eb34db0fb1a2efdd71c1e5a60bf9808e6d2310/test/browser/core/WebWorkerPoolTest.js#L23-L56
