### ISSUE TITLE
Dicom reading

### ISSUE THREAD

**Issue by Eric-JH** [InsightSoftwareConsortium/ITK#3202]
### Description
I tried my code and the error was reported. I couldn't unstander the error info.

### code
`
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkRescaleIntensityImageFilter.h"
#include "itkGDCMImageIO.h"
#include "itkJPEGImageIOFactory.h"

int main(int argc, char* argv[])
{

    using InputPixelType = signed short;
    const unsigned int InputDimension = 2;
    using InputImageType = itk::Image<InputPixelType, InputDimension>;
    using ReaderType = itk::ImageFileReader<InputImageType>;
    ReaderType::Pointer reader = ReaderType::New();
    reader->SetFileName("C:\\Users\\26327\\Desktop\\dll4sw\\data\\SE3\\IM100.dcm");
    using ImageIOType = itk::GDCMImageIO;
    ImageIOType::Pointer gdcmImageIO = ImageIOType::New();
    reader->SetImageIO(gdcmImageIO);
    try
    {
        reader->Update();
    }
    catch (itk::ExceptionObject& e)
    {
        std::cerr << "exception in file reader" << std::endl;
        std::cerr << e << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
`

### Environment
windows 10
MSVC2022 

### Error info 
Warning: In D:\vcpkg\buildtrees\gdcm\src\8c1c28481dfbbf6b12dd.clean\Source\MediaStorageAndFileFormat\gdcmDataSetHelper.cxx, line 107, function gdcm::DataSetHelper::ComputeVR
Please report. Missing dict entry for: [ELSCINT1] de is: (07a1,10a7)    SH      4       Loaded:4

**Comment by dzenanz** [comment]
Maybe all that is needed is updated GDCM (#3042). Could you try building against that branch?

**Comment by dzenanz** [comment]
The error message says that the DICOM dictionary which comes with GDCM does not contain something used in the image you are trying to read. The expectation is that a newer version of GDCM might have it. Otherwise report it to the maintainer, @malaterre. CC: @seanm.

**Comment by issakomi** [comment]
There is no entry for that private tag in GDCM master. This warning should not prevent image from loading. If the file fails to load it may have private transfer syntax and _PMSCT_RLE1_ or _LOSSLESS RICE_ compression. To identify it you could post dump (gdcmdump or dcmdump), sensible attributes like name, maybe SOP Instance UID, study and series UIDs, can be deleted. For _PMSCT_RLE1_ there is an example _rle2img.cxx_ in GDCM Examples folder.

![el](https://user-images.githubusercontent.com/1494580/154372614-8e92e1bd-bf20-444a-83b6-cdf39736aa8b.png)

**Comment by malaterre** [comment]
@Eric-JH As pointed out by @issakomi there is no relation in between the warning reported and your description of an "error". Please either submit the original DICOM dataset, or provide a clearer error description. I am going to incorporate the new dict entry so that the warning disapear in next release of gdcm.

Closing as incomplete, feel free to re-open.

**Comment by malaterre** [comment]
For reference: 450b3d342a5866ff13275801686c18386d083de5

**Comment by Eric-JH** [comment]
@malaterre How can I send the dicom file to you

**Comment by malaterre** [comment]
@Eric-JH Just use the email: `git log | grep malaterre`. As mentionned on the gdcm-developers mailing list, you can use gdcmanon to remove any PHI.
