### ISSUE TITLE
Upgrade Google double-conversion library as "REQUIRED" (at least to version 3.1.6)

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#3204]
With pull request #3160  commit https://github.com/InsightSoftwareConsortium/ITK/commit/701c8c25ea998cc5defdd3457241c518a7b8b65b ("COMP: Add minimum version for double-conversion" by @RafaelPalomar), ITK requires _at least_ version 3.1.6 of the double-conversion library: https://github.com/InsightSoftwareConsortium/ITK/blob/701c8c25ea998cc5defdd3457241c518a7b8b65b/Modules/ThirdParty/DoubleConversion/CMakeLists.txt#L10

At least, when `ITK_USE_SYSTEM_DOUBLECONVERSION` is enabled.

Would it be possible to also upgrade the "embedded" (non-system) version of that library, at https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/DoubleConversion/src ? As I suggested at https://github.com/InsightSoftwareConsortium/ITK/pull/3160#issuecomment-1036156664

Related issue: #3193 "Refactor UpdateDoubleConversionFromGoogle.sh" by @dzenanz

**Comment by N-Dekker** [comment]
@dzenanz Would you possibly still have time to upgrade the double-conversion library? ITK requires _at least_ version 3.1.6 now (commit https://github.com/InsightSoftwareConsortium/ITK/commit/701c8c25ea998cc5defdd3457241c518a7b8b65b), but still has an older versions at [ITK/Modules/ThirdParty/DoubleConversion](https://github.com/InsightSoftwareConsortium/ITK/tree/88e1100ce2ca82212590353b0c4172ca689de9f1/Modules/ThirdParty/DoubleConversion) 

The newer double-conversion library has an extra feature I would like to use  😃: `StringToDoubleConverter::StringTo<T>` , https://github.com/google/double-conversion/commit/eee1a4544fda1fd70f93412ad7a210d40693ef1c added with https://github.com/google/double-conversion/pull/158

**Comment by dzenanz** [comment]
I made some progress in #3533.
