### ISSUE TITLE
Doxygen tarballs are no longer available

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#3207]
### Description

The three links provided in the doxygen footer
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/Doxygen/DoxygenFooter.html#L18-L20
are broken. This breaks the generation of Module documentation which relied on the tag file, e.g., [RTK](https://github.com/SimonRit/RTK/blob/master/documentation/Doxygen/CMakeLists.txt#L14).

### Expected information

Tarball links

### Actual information

Nothing

**Comment by thewtex** [comment]
public.kitware.com was migrated to a new system -- working on the updated URLs.
