### ISSUE TITLE
MaxObjectKiB was obsoleted by hooks-max-size

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#3229]
`MaxObjectKiB` was obsoleted by `hooks-max-size`, so ITK's pre-commit hook should stop checking the former and look at the latter instead. From: https://github.com/InsightSoftwareConsortium/ITK/pull/3215#discussion_r813059233.

**Comment by tbirdso** [comment]
Wanted to note that this caused an entirely separate branch to fail merging in master:
```
$ git commit
pre-commit hook failure
-----------------------

At least one file is staged for commit with size larger than its limit.
We prefer to keep large files out of the main source tree, especially
binary files that do not compress well.  This hook disallows large files
by default but can be configured.  A limit for specific files or patterns
may be set in ".gitattributes" with the "hooks.MaxObjectKiB" attribute.
For example, the line

  *.c              hooks.MaxObjectKiB=2048

sets a limit of 2048 KiB for C source files.  See "git help attributes"
for details on the .gitattributes format.  If no attribute has been set
for a given file then its size is limited by the local default.  Run

  git config hooks.MaxObjectKiB $KiB

to set the local default limit (0 to disable).

The path 'Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/gdcmDefaultDicts.cxx' has size 1167 KiB, greater than allowed 1024 KiB.
The path 'Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition/Part3.xml' has size 2282 KiB, greater than allowed 1024 KiB.
```

Is the preferred workaround for now to increase the local `hooks.MaxObjectKiB` default limit per the error output?

**Comment by dzenanz** [comment]
> workaround for now to increase the local hooks.MaxObjectKiB

Yes. Or you could ignore the warning.

**Comment by tbirdso** [comment]
The error prevented the commit from proceeding. Increasing `MaxObjectKB` allowed the commit to proceed.

**Comment by thewtex** [comment]
@dzenanz could you please submit a patch?

**Comment by dzenanz** [comment]
It turns out there is just one instance of `hooks.MaxObjectKiB` now, and it is in https://github.com/InsightSoftwareConsortium/ITK/blob/e82f200edc902b2b9cf090c9b32631a7e665f855/Modules/ThirdParty/Eigen3/src/itkeigen/.gitattributes#L3

Further search led me to this: [pre-commit hook from the hooks branch](https://github.com/InsightSoftwareConsortium/ITK/blob/hooks/pre-commit) is used, not the one in https://github.com/InsightSoftwareConsortium/ITK/tree/master/Utilities/Hooks. This is governed by https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/GitSetup/setup-hooks.

**Comment by dzenanz** [comment]
The relevant code is at https://github.com/InsightSoftwareConsortium/ITK/blob/d033ed351804e8dfaa2a96e1bc358cc77e63ef90/pre-commit#L164-L210
This is a hard to comprehend git+bash script. Could @mathstuf or @bradking take over this issue?

It would be good if abandoned use of a separate branch just for git hooks, and kept the [hooks in master](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Utilities/Hooks?rgh-link-date=2022-03-07T21%3A50%3A48Z) up to date. The code which uses the special `hooks` branch is in https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/GitSetup/setup-hooks

**Comment by bradking** [comment]
> It would be good if abandoned use of a separate branch just for git hooks

We can't because the hooks branch needs to be checked out inside the `.git/hooks` directory.  Git specifically does not run hooks from the project's checkout.  All the hooks we have in `master` are launched by the separate hooks branch.

I've updated ITK's `hooks` branch to add support for the `hooks-max-size` attribute.  Run `git fetch` to get it, and then run `Utilities/SetupForDevelopment.sh` again to update the `.git/hooks` directory.

**Comment by dzenanz** [comment]
Thank you Brad.
