### ISSUE TITLE
STYLE: `size_t` vs. `std::size_t`

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITK#3248]
### Description
We use both `size_t` and `std::size_t`.  Which is the preferred style?

### Actual coding style
As of cef0b6511c27b486cd3469493fa6fcc774f97f53, the count of occurrences with and without the prefix `std::` are as follows.  
```
     22 int8_t
     41 int16_t
    123 int32_t
     88 int64_t
      6 intmax_t
      4 intptr_t
      2 int_fast8_t
      2 int_fast16_t
      2 int_fast32_t
      2 int_fast64_t
      2 int_least8_t
      2 int_least16_t
      2 int_least32_t
      2 int_least64_t
     21 int_t
     17 ptrdiff_t
   1333 size_t
    156 uint8_t
     84 uint16_t
    495 uint32_t
     49 uint64_t
      6 uintmax_t
      2 uintptr_t
      2 uint_fast8_t
      2 uint_fast16_t
      2 uint_fast32_t
      2 uint_fast64_t
      2 uint_least8_t
      2 uint_least16_t
      2 uint_least32_t
      2 uint_least64_t

      3 std::int8_t
      2 std::int16_t
      1 std::int32_t
      3 std::int64_t
      1 std::intmax_t
      1 std::intptr_t
      1 std::int_fast8_t
      1 std::int_fast16_t
      1 std::int_fast32_t
      1 std::int_fast64_t
      1 std::int_least8_t
      1 std::int_least16_t
      1 std::int_least32_t
      1 std::int_least64_t
     11 std::nullptr_t
     19 std::ptrdiff_t
    144 std::size_t
      4 std::uint8_t
      3 std::uint16_t
      3 std::uint32_t
      1 std::uint64_t
     26 std::uintmax_t
      1 std::uintptr_t
      1 std::uint_fast8_t
      1 std::uint_fast16_t
      1 std::uint_fast32_t
      1 std::uint_fast64_t
      1 std::uint_least8_t
      1 std::uint_least16_t
      1 std::uint_least32_t
      1 std::uint_least64_t
```
This list was generated from
```shell
cd git/ITK
find * -type f | egrep '\.[hc](xx|pp)?$' | fgrep -v ThirdParty |
  xargs egrep -o '(std::)?(size|ptrdiff|nullptr|max_align|u?int(_fast|_least|max|ptr)?[0-9]*|float[0-9]*)_t' |
  cut -d : -f 2- | sort -V | uniq -c
```

**Comment by seanm** [comment]
IMHO prefixing something as rudimentary as `int32_t` just hurts readability for no real gain, likewise for all those others.  It's not like they exist in any other namespace, that would break so much code.

**Comment by hjmjohnson** [comment]
It seems like dropping the prefix has the least effect.  I would recommend adding a maintenance script to ITK that can automatically make these substitutions.  They will inevitably creep back in.

It could also be added to an existing substitution script for the vxl name substitutions.

**Comment by dzenanz** [comment]
I guess sometimes people think that `std::` prefix is required for those, too. Otherwise I doubt there would have been any instances of those. I vote in favor of shorter form. It helps readability.

**Comment by Leengit** [comment]
I will submit a pull request to remove `std::` in these cases.  If any of you know how to put this in as a commit hook, KWStyle check, or wherever is best then please do.  In case it is helpful more generally ... the `bash` `sed` command that I use is:

```sh
sed -i -r \
  -e 's/std::((size|ptrdiff|nullptr|max_align|u?int(_fast|_least|max|ptr)?[0-9]*|float[0-9]*)_t)/\1/g' \
  file1 file2 ...
```

NB: Don't apply it to `Modules/Core/Common/include/itkIntTypes.h`.

**Comment by Leengit** [comment]
NB: If as a commit hook, etc. please apply the `sed` command somewhere before the application of the `clang-format` command.

**Comment by dzenanz** [comment]
Lee, can you self-assign this issue to yourself?

**Comment by Leengit** [comment]
> Lee, can you self-assign this issue to yourself?

It seems that I cannot.

**Comment by dzenanz** [comment]
Then I guess you would need write access for that. I assigned you.
