### ISSUE TITLE
LZW compression in TIFFimageIO.

### ISSUE THREAD

**Issue by HaaPut** [InsightSoftwareConsortium/ITK#3277]
### Description

Based on a quick online search, it appears that the patent on LZW has expired (but don't quote me on the this). So [lzw patent](https://github.com/InsightSoftwareConsortium/ITK/blob/1d68414c4ec026c0086122569301a9576839873a/Modules/IO/TIFF/src/itkTIFFImageIO.cxx#L696) is perhaps not an issue for tiff images anymore. However, if using it is still not possible, what is the point of exposing LZW compression? Why not just remove the option from TiffImageIO? 

### Expected coding style

Remove LZW comrpression option from TiffImageIO.

**Comment by thewtex** [comment]
@HaaPut since the patent has expired, we could enabled it. Would you like to create a patch?
