### ISSUE TITLE
ITK failed to build with many error with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [InsightSoftwareConsortium/ITK#3343]
ITK failed to build with many error with MSVC on windows. It can reproduces on version https://github.com/InsightSoftwareConsortium/ITK/commit/e00bad0359abb15393732b629df3a8c60b3249a9. Could you please help look at this issue? Thank you very much

Environment
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

Steps to reproduce:

1. open VS2019 x64 tools command
2. git clone https://github.com/InsightSoftwareConsortium/ITK F:\gitP\InsightSoftwareConsortium\ITK
3. cd F:\gitP\InsightSoftwareConsortium\ITK
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. mkdir build_arm64a & cd build_arm64a
6. cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_SHARED_LIBS=OFF  -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="F:\gitP\InsightSoftwareConsortium\ITK" ..
7. set _CL_=/D_CRT_DECLARE_NONSTDC_NAMES
8. msbuild /m /p:Platform=arm64 /p:Configuration=Release ITK.sln /t:Rebuild

Build.log:
[ITK_msbuild.log](https://github.com/InsightSoftwareConsortium/ITK/files/8367736/ITK_msbuild.log)

Error info:
![image](https://user-images.githubusercontent.com/86757616/160524466-a2c296cb-4e94-4b55-858e-7a14fd63f89a.png)
![image](https://user-images.githubusercontent.com/86757616/160524548-3beb492f-52dc-4cc0-98a0-adb2f681d2c8.png)
328>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9317,68): error C2664: 'unsigned int gdcm::_InterlockedIncrement(volatile unsigned int *)': cannot convert argument 1 from 'volatile long *' to 'volatile unsigned int *' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9317,62): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9313,1): message : see declaration of 'gdcm::_InterlockedIncrement' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
   328>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9326,73): error C2665: 'gdcm::_InterlockedIncrement': none of the 2 overloads could convert all the argument types [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9322,1): message : could be 'unsigned long gdcm::_InterlockedIncrement(volatile unsigned long *)' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9313,1): message : or       'unsigned int gdcm::_InterlockedIncrement(volatile unsigned int *)' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9326,73): message : while trying to match the argument list '(volatile long *)' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
   328>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9349,73): error C2664: 'unsigned int gdcm::_InterlockedDecrement(volatile unsigned int *)': cannot convert argument 1 from 'volatile long *' to 'volatile unsigned int *' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9349,67): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9345,1): message : see declaration of 'gdcm::_InterlockedDecrement' [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
   328>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9358,73): error C2665: 'gdcm::_InterlockedDecrement': none of the 2 overloads could convert all the argument types [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmCommon.vcxproj]
261>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "setlocal [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: cd F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: F: [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\bin\Release\H5detect.exe H5Tinit.c [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E touch gen_SRCS.stamp1 [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1 [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 216. [F:\gitP\InsightSoftwareConsortium\ITK\build_arm64a\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5detect.vcxproj]

**Comment by dzenanz** [comment]
I assume you have closed the issue because you have seen the [forum post](https://discourse.itk.org/t/cross-compile-problem-itk-bld-internal-h5make-libsettings/2162) or [blog post](https://www.kitware.com/cross-compiling-itk-for-raspbery-pi/)?
