### ISSUE TITLE
`PrintSelf` methods are getting the wrong documentation

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#3401]
### Description

Some `PrintSelf` methods are getting the wrong documentation, e.g.
https://itk.org/Doxygen/html/classitk_1_1DemonsImageToImageMetricv4.html#aadc94300c4c450bce2be16537ffaa89d
https://itk.org/Doxygen/html/classitk_1_1SphereSpatialFunction.html#a92b3d53d4c74be128644a8df65d62c2e

### Expected information

The `PrintSelf` methods should all have the same documentation, i.e. that of the base class, as it is a method that performs the basic same operation in all child classes.

### Actual information

For the above cases, the `PrintSelf` method is getting the documentation of the immediate next method member, which in the above cases happen to be two `private` ivars:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/Metricsv4/include/itkDemonsImageToImageMetricv4.h#L146
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkSphereSpatialFunction.h#L77

### Versions

ITK 5.3.0

Very likely `master` as well.

### Additional Information

This is likely to be happening for many other methods.

**Comment by blowekamp** [comment]
@jhlegarreta The linked itk.org documentation hasn't been updated since Jan 22.

You can see a discussion about some changes to Doxygen here: 
https://discourse.itk.org/t/doxygen-with-github-actions-and-pages/4790

The doxygen for the PrintSelf method looks correct here:
https://insightsoftwareconsortium.github.io/ITKDoxygen/classitk_1_1DemonsImageToImageMetricv4.html#aadc94300c4c450bce2be16537ffaa89d

**Comment by jhlegarreta** [comment]
@blowekamp OK, I see that both are fixed in the linked documentation. Thanks for doing this.

I was pointing to the "official" documentation, but looks like we have nightly documentation now, which is wonderful.

It'd be good to be able to see the documentation of previous releases, and the nightly to be marked with the appropriate "post-" or commit version.

Closing this issue.
