### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by Kodemannen** [InsightSoftwareConsortium/ITK#3483]
### Description
I am Having an issue when reading scans:

What I really am trying to do, is to run image registration with [Elastix](https://github.com/SuperElastix/elastix), which is built upon ITK. I made an issue [there](https://github.com/SuperElastix/elastix/issues/680), but concluded that the problem was with ITK.

### Steps to Reproduce
In Python:
```
import itk  
image = itk.imread("scan.svs")
```
### Expected behavior
Being able to read the image.

### Actual behavior
This
```
(image-registration) samuel@samuelpc:~/repos/ImageRegistration$ python itktest.py
Traceback (most recent call last):
  File "/home/samuel/repos/ImageRegistration/itktest.py", line 8, in <module>
    image = itk.imread(input_fln)
  File "/home/samuel/anaconda3/envs/image-registration/lib/python3.9/site-packages/itk/support/extras.py", line 958, in imread
    reader.Update()
RuntimeError: /work/ITK-source/ITK/Modules/Core/Common/include/itkImportImageContainer.hxx:192:
Failed to allocate memory for image.
```

### Reproducibility
100%

### Versions
Itk version 5.2.0

### Environment
- Installed with `pip install itk`
- Running on Ubuntu 22.04 LTS

### Additional Information
- I have two images that I am trying to test running registration on, one `.svs` and one `.ndpi`
- Both images are about 1gb in size.
- Both images produce the same error when read by ITK
- Both images are successfully read by both [OpenSlide](https://github.com/openslide/openslide) and [SlideIO](https://github.com/Booritas/slideio).
- The machine I am working on has 32 gb RAM

**Comment by Kodemannen** [comment]
I tried opening in 3D Slicer, which gave the following error:

> 
> Slice has caught an application error, please save your work and restart.
> 
> The application has run out of memory. Increasing swap size in system settings or adding more RAM may fix the issue.
> 
> If you have a repeatable sequence of steps that causes this message, please report the issue following instructions available at https://slicer.org
> 
> The message detail ist:
> 
> Exception thrown in event: std::bad_alloc

Regarding zeroing out pixels for better compression: Do you have a suggestion for a tool that I could use for this?

Thanks again.

**Comment by dzenanz** [comment]
I use this [Hex Editor](https://mh-nexus.de/en/hxd/).

**Comment by Kodemannen** [comment]
Hey again @dzenanz,

This turned out to be very non-trivial for me to do. Tried both with the hex editor you suggested, and using Python (made a [thread on stackoverflow](https://stackoverflow.com/questions/73310234/zeroing-blacking-out-pixels-in-a-tiff-like-file-svs-or-ndpi?noredirect=1#comment129473025_73310234)), but I have not been able to figure out how to identify the bytes that correspond to the pixels.

Would it be possible to send it to you as is? Feels a bit weird to spend weeks trying to save 15 minutes, if you know what I mean.

Also, a colleague of mine suggested that the scans (of 1gb, compressed) may be too big, or that the ITK module may not handle .svs and .ndpi? Is he correct on that?

**Comment by dzenanz** [comment]
OK, can you provide a link to the file on some file sharing service? Google Drive, Dropbox or something similar?

**Comment by Kodemannen** [comment]
It looks like this problem was generally avoided by downsampling. Seems like the size of the uncompressed scan was indeed the issue.
