### ISSUE TITLE
Local installation of ITK with `cmake`

### ISSUE THREAD

**Issue by 14thibea** [InsightSoftwareConsortium/ITK#3491]
Dear ITK team,

I need to install ITK with `cmake` to install another package https://github.com/UCL/PETPVC.
However, I don't have `sudo` rights on the machine I would like to use.
I tried `make install/local` but it tries to install everything in `/usr/local` where I don't have writing rights.
Could you please help me? Is there a way to compile ITK and then set an environment variable so it can be found by the other software?

More precisely, this is a traceback:
```
CMake Error at CMakeLists.txt:51 (FIND_PACKAGE):
  By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ITK", but
  CMake did not find one.

  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

  Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
  to a directory containing one of the above files.  If "ITK" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

Best regards,

**Comment by Leengit** [comment]
If you can build `ITK` in a directory called `ITK-build` (e.g., via `mkdir ITK-build; cd ITK-build ; cmake your_flags_here ../ITK; cmake --build .` then when you build the software that depends upon `ITK` you can used the `cmake` flag `-DITK_DIR:PATH="path/to/ITK-build"`.

**Comment by 14thibea** [comment]
The first solution worked, thanks a lot!
