### ISSUE TITLE
Integrate upstream NIFTI fix

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#3492]
https://github.com/NIFTI-Imaging/nifti_clib/pull/150

Creating issue to make sure we include it in 5.3.0 final. If it does not get merged upstream soon, we should apply the fix directly to our bundled copy.

**Comment by jamesobutler** [comment]
@dzenanz https://github.com/NIFTI-Imaging/nifti_clib/pull/150 was merged. So updating this third party in ITK can be done now.
