### ISSUE TITLE
imwrite does ignore nifti intent_code and intent_name

### ISSUE THREAD

**Issue by ch-n** [InsightSoftwareConsortium/ITK#3504]
### Description
When saving images using `itk.imwrite()` in nifti format the writer does ignore nifti `intent_code` and nifti `intent_name`.

### Steps to Reproduce
1. Load image with `intent_code` / `intent_name` or set them on loaded image
2. Save the image with `itk.imwrite(image, some_place.nii)`
3. Load the saved image and check `new_img['intent_code']` and `new_img['intent_code']`

### Expected behavior
`itk.imwrite()` respects `intent_code` and `intent_name`

### Actual behavior
`intent_code` is set to 0 and `intent_name` to `""`

### Reproducibility
Every time

### Versions
itk-io 5.2.1.post1
and higher

### Environment
Python 3.8, 3.9, 3.10

**Comment by hjmjohnson** [comment]
@ch-n   The intent_code and intent_name are specific to the nifti file format.  They are not part of the ITK data model and therefore are not managed by ITK.

As an application developer, you could potentially use the metadata dictionary functionality to privately manage those values in your application.

The code currently works as expected and is documented according to the designed ITK behavior.
