### ISSUE TITLE
*.pyi files not installed

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#3558]
### Description

The Python interface files (*.pyi) are not installed into the install tree. As a result, they are missing from the `5.3rc4.post2` wheels.

### Steps to Reproduce

1. Enable `ITK_WRAP_PYTHON`
2. `ninja`
3. `DESTDIR=/tmp/itk-install ninja install`
4. `find /tmp/itk-install -name '*.pyi'`

### Expected behavior

The .pyi files are installed alongside the .py files.

### Actual behavior

.pyi files are not installed.

### Reproducibility

Always

### Versions

ITK Git `master`, i.e.`58ce6e84f2`

### Environment

Tested on Linux.

**Comment by hjmjohnson** [comment]
This is necessary to start getting the python system to be more consistent with remote modules:  https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/394

**Comment by hjmjohnson** [comment]
@thewtex I think I know how to manipulate the itk-stub files for installing, but I am not sure what is supposed to be done.

There is a variable called "PY_SITE_PACKAGES_PATH". That is sometimes set to CMAKE_INSTALL_PREFIX, and other times to the site-packages directory of the python interpreter.

Currently, the python stuff is installed to the python interpreter site-packages in the "itk" and "itk-stubs" directories, and I have confirmed that the type hints work in the PyCharm interpreter (after waiting for the indexing to complete).

I am not sure if this will allow for the stub files to be included in wheel packages, or if each wheel package will include duplicate copies of the itk-stub directories.

Please review the PR #3560 for the starting effort to make typehints more universally available.

Hans

**Comment by thewtex** [comment]
@hjmjohnson to be included in the wheels, the `*.pyi` files need to be installed into `PY_SITE_PACKAGES_PATH` -- I would think the `PY_SITE_PACKAGES_PATH/itk` path. How does the interpreter understand that it needs to look into `PY_SITE_PACKAGES_PATH/itk-stubs`?

**Comment by hjmjohnson** [comment]
@thewtex   I followed the convention that would allow for making a separate type-hint package:  https://peps.python.org/pep-0561/#stub-only-packages by putting the .pyi files in a separate directory.

This was "doing it the hardest way" initially, knowing that if we wanted to collapse it later, it would be relatively easy to identify and change "itk-stubs" -> "itk"


I'll make a PR to review tonight.  It should be pretty easy.
