### ISSUE TITLE
ITKImageIO and ITKTransformIO not accessible within ITK

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#359]
[`ITKImageIO` and `ITKTransformIO`](https://discourse.itk.org/t/itk-4-13-has-been-released/549) can be used by remote modules' examples only when the remote modules are being built externally. The remote modules cannot use `ITKImageIO` and `ITKTransformIO` when they are being built as part of ITK by enabling e.g. `Module_Montage`. This is a consequence of `ITKImageIO` and `ITKTransformIO` not being defined during module configuration step in ITK.

When this issue is fixed, the [module template](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate) should be updated.

**Comment by thewtex** [comment]
@dzenanz @jhlegarreta @fbudin69500 perhaps `ITKImageIO`, etc. should be defined here:

  https://github.com/InsightSoftwareConsortium/ITK/blob/4cf99119f03510018d222bdb729ca3a97222224d/CMake/ITKModuleMacros.cmake#L340-L343

What do you think?

**Comment by fbudin69500** [comment]
This would work for examples, but if we make the improvement to allow usage of `ITKImageIO` and `ITKTransformIO` inside the ITK build tree, wouldn't it make sense to allow it everywhere (especially for tests)?

**Comment by dzenanz** [comment]
Having it working for examples, but not tests is better than not working for either, which is the case now.

When writing a test the author knows which format is needed  for IO, and can list that format explicitly. And that might be a better way too?

**Comment by jhlegarreta** [comment]
While the solution seems fair to me, @fbudin69500 's comment seems to be fair also. However, I ignore whether we are willing to list *all* components for every test and example, or whether that has bearings in the configuration time. That said, I ignore whether a better solution exists.

**Comment by thewtex** [comment]
> wouldn't it make sense to allow it everywhere (especially for tests)?

Implementation is a Catch 22 -- when processing the modules, the set constituting the ImageIO modules is not known until all the modules are processed.

**Comment by fbudin69500** [comment]
Good call. But in that case, wouldn't it be the same problem for examples? Are remote modules always processed last? What happens if a remote module implements a new IO?

**Comment by thewtex** [comment]
Since the `itk_module_examples()` call comes after the module has been processed (it is placed at the end of the *CMakeLists.txt* after `itk_module_impl()`, the current module will have been processed.

In the case of building the module externally, all ITK IOs are already built.

In the case of a remote module build, if the module depends on `ITKTestKernel` (which most / all do or should), the image IO will already be there:

  https://github.com/InsightSoftwareConsortium/ITK/blob/2cb0896d51bf0dc53f23023a49b54a30a062ee7e/Modules/Core/TestKernel/itk-module.cmake#L11-L21

Transform IO will not necessarily, though.

**Comment by dzenanz** [comment]
Here is an example solution:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/v0.8.2/examples/CMakeLists.txt#L4-L22
