### ISSUE TITLE
Limited use of multithreading in BSplineSyN registration in ANTs

### ISSUE THREAD

**Issue by chrisadamsonmcri** [InsightSoftwareConsortium/ITK#3673]
Apologies for cross-posting but activity on this thread in the ants github has stalled.
https://github.com/ANTsX/ANTs/issues/1017

When using bsplinesyn registration in ANTs, which uses bspline code in ITK, multithreading is very limited with CPU utilisation being around 100% regardless of number of threads used. The utilisation gets worse as the number of control points in the bspline transformation increases, so as downsampling of the image decreases.

My suspicion is that something compute-intense in the bspline code somewhere is running with only one thread. Any thoughts on how to deal with this? Thanks in advance.

**Comment by chrisadamsonmcri** [comment]
Seems to be an issue with ```DisplacementFieldToBSplineImageFilter``` seemingly not being mutlithreaded.

https://github.com/ANTsX/ANTs/issues/1017#issuecomment-1265338784

**Comment by dzenanz** [comment]
Narrowing it down like this would be helpful to anyone willing to tackle this limitation.

**Comment by jhlegarreta** [comment]
@chrisadamsonmcri If I understand correctly PR #3681 fixed this issue, right? If yes, can you please close it?
