### ISSUE TITLE
itk.Matrix.GetVnlMatrix() returns a copy in python instead of a reference

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#3683]
### Description

`GetVnlMatrix()` was retuning a reference before 5.0, now it returns a copy.
Not sure how we modify a matrix now.
It was reported here: https://discourse.itk.org/t/modify-an-element-in-a-matrix/5398/5
This was introduced as a bug fix here: https://github.com/InsightSoftwareConsortium/ITK/commit/fede4b865d2ea7a4fdde0d81fc496b7054e8cfbd

To avoid problems when using the vnl matrix multiple times in the same line: `m2 = m*m`.

### Steps to Reproduce

```python
In [2]: m = itk.Matrix[itk.D, 3,3]()

In [3]: m
Out[3]: itkMatrixD33 ([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])

In [4]: m.GetVnlMatrix()
Out[4]: <itk.vnl_matrix_fixedPython.vnl_matrix_fixedD_3_3; proxy of <Swig Object of type 'vnl_matrix_fixedD_3_3 *' at 0x7fb3662bdb90> >

In [5]: m.GetVnlMatrix()
Out[5]: <itk.vnl_matrix_fixedPython.vnl_matrix_fixedD_3_3; proxy of <Swig Object of type 'vnl_matrix_fixedD_3_3 *' at 0x7fb423e87240> >

```
We can see that GetVnlMatrix returns a new pointer every time, instead of a reference to the actual vnl_matrix in the itkMatrix.

### Expected behavior

I would expect to get a reference.
Also, how do we modify the matrix if we cannot access the inner vnl matrix? We don't have operators in itk.Matrix.

### Actual behavior

GetVnlMatrix() returns a copy.

### Reproducibility

Always

### Versions

The change was commited to 5.0rc2. here: https://github.com/InsightSoftwareConsortium/ITK/commit/fede4b865d2ea7a4fdde0d81fc496b7054e8cfbd

**Comment by phcerdan** [comment]
I agree, maybe, as a mid-term solution we could add an `array_view_from_matrix` to avoid the extra copy needed right now for the numpy bridge with `itk.array_from_matrix`.

Closing as this is not a bug.

**Comment by hjmjohnson** [comment]
I recommend targeting ITK v8 for eigen. :).

**Comment by dzenanz** [comment]
I thought we agreed during v5 scoping we would target transition to Eigen in v6, which is now not that far into the future :smile:

**Comment by phcerdan** [comment]
And in v12, the open source library having a solid implementation of this: https://www.nature.com/articles/s41586-022-05172-4
