### ISSUE TITLE
pip install errors: 5.1.X and 5.2.X versions cannot be found in pypi

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#3684]
`pip install itk` tries to pull itk-5.0.1, instead of the current stable release.

In fact, `pip install itk==5.2.1` reports error:
```
ERROR: Could not find a version that satisfies the requirement itk==5.2.1 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.3rc2, 5.3rc2.post1, 5.3rc3, 5.3rc4, 5.3rc4.post1, 5.3rc4.post2, 5.3rc4.post3)
ERROR: No matching distribution found for itk==5.2.1
```
@thewtex @jcfr

**Comment by dzenanz** [comment]
[5.2.1](https://pypi.org/project/itk/5.2.1/) does exist. Are you trying this in a regular Python distribution, or conda? But I have seen (at least once) the error message you provide.

**Comment by phcerdan** [comment]
Ok, then maybe is a `pip` hiccup. Closing.
