### ISSUE TITLE
git clone operations for remote submodules fail with Operation timed out

### ISSUE THREAD

**Issue by yurivict** [InsightSoftwareConsortium/ITK#3753]
### Description

```
$ git  clone git://github.com/InsightSoftwareConsortium/ITKSimpleITKFilters.git
Cloning into 'ITKSimpleITKFilters'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Operation timed out
```

This might be because I have ssh keys for github, not sure about the reason.
You should use ```https://``` instead for all remote modules: ```git  clone https://github.com/InsightSoftwareConsortium/ITKSimpleITKFilters.git```

### Steps to Reproduce
regular configure

### Versions

Version: 5.3rc04

**Comment by dzenanz** [comment]
ITK should be using https protocol for git repositories by default, see https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/CMake/ITKDownloadSetup.cmake. If you remove `ITK_USE_GIT_PROTOCOL` from your CMake cache, does the error persist?

**Comment by yurivict** [comment]
cmake cache has ```ITK_USE_GIT_PROTOCOL:BOOL=ON```.
configure fills it in this way.
I build in a clean environment in the FreeBSD ports framework. cache gets deleted every time, and then this values gets in again.

**Comment by dzenanz** [comment]
There is also condition `GIT_VERSION_STRING VERSION_LESS "1.7.10"`. Which version of git do you use?

**Comment by yurivict** [comment]
1.6.6

**Comment by dzenanz** [comment]
I guess that is the reason. A comment in that [file](https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/CMake/ITKDownloadSetup.cmake) says that 1.7.0 is the minimum version for https support.

**Comment by dzenanz** [comment]
A [commit](https://github.com/InsightSoftwareConsortium/ITK/commit/7b9d62f10d7f78228acce04f30375fd392caf188) which added that comment is now 7 years old. You have some very old git.

**Comment by yurivict** [comment]
> You have some very old git.

No, I wrote a git wrapper to prevent downloads during configure, and it was simply reporting the same version that cmake is requiring. I'll correct that.

FreeBSD ports aren't allowed to download amything during configure/build for security reasons. So I would circumvent that with git wrapper supplying pre-downloaded directories.

Thank you for your clarification and help.
