### ISSUE TITLE
No Downloads section for the 5.3.0 release

### ISSUE THREAD

**Issue by yurivict** [InsightSoftwareConsortium/ITK#3794]
[here](https://github.com/InsightSoftwareConsortium/ITK/tags)

**Comment by dzenanz** [comment]
It takes a while to compile all the other things which depend on core ITK, such as remote modules, examples, software guide. The download section should be ready by the time we make the announcement.

**Comment by thewtex** [comment]
Now up: https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.3.0
