### ISSUE TITLE
[MSVC] ITK run test case ”itkNiftiLargeImageRegionReadTest“ failed on Windows x86 mode

### ISSUE THREAD

**Issue by Zhaojun-Liu** [InsightSoftwareConsortium/ITK#3797]
### Description
Hi, the MSVC team update the commit of ITK for RWC testing, and the test case `itkNiftiLargeImageRegionReadTest` failed on Windows x86 mode. Could you please look this issue? Thanks.

### Steps to Reproduce
1. open VS2019 x86 tools command
2. git clone https://github.com/InsightSoftwareConsortium/ITK F:\gitP\InsightSoftwareConsortium\ITK
3. mkdir F:\gitP\InsightSoftwareConsortium\ITK\build_x86 and cd F:\gitP\InsightSoftwareConsortium\ITK\build_x86
4. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..
5. set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING
6. msbuild /m /p:Platform=Win32 /p:Configuration=Release All_BUILD.vcxproj /t:Rebuild
7. ctest --build-config Release --output-on-failure -E "itkStatisticsAlgorithmTest|itkBSplineScatteredDataPointSetToImageFilterTest02|itkGradientDescentOptimizerv4Test|itkLandmarkBasedTransformInitializerTest|itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest|ITKIOTransformMatlabKWStyleTest|itkImageFillBufferTest4.1|itkLargeMetaImageWriteReadTest*|itkLargeTIFFImageWriteReadTest*"

### Expected behavior
No test case failed.

### Actual behavior
```
The following tests FAILED:
	1276 - itkNiftiLargeImageRegionReadTest (Failed)
Errors while running CTest
```
logs:
[test.log](https://github.com/InsightSoftwareConsortium/ITK/files/10225610/test.log)
[test_detail.log](https://github.com/InsightSoftwareConsortium/ITK/files/10225611/test_detail.log)

### Versions
The commit of ITK we are using: 476f31db2a32bf1663e02d5682b8cb5cc20f9e36

### Environment
OS: Windows server 2022
VS: VS2019 16.11.20

### Additional Information
I tried to search the related issue, and I found one: #3771, I'm not sure if it is the same with my issue, and I tried the cmake option `-DALIZA_DISABLE_SIMDMATH:BOOL=ON`, it not work, the test case still failed.

**Comment by dzenanz** [comment]
This test should be disabled on 32-bit architectures, as it is probably not expected to work.

**Comment by dzenanz** [comment]
Judging by [this thread](https://cmake.org/pipermail/cmake/2011-August/046024.html), it is best to add conditionals [inside the test](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/test/itkNiftiLargeImageRegionReadTest.cxx). @yurivict and @issakomi do you agree?

**Comment by issakomi** [comment]
> Judging by [this thread](https://cmake.org/pipermail/cmake/2011-August/046024.html), it is best to add conditionals [inside the test](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/test/itkNiftiLargeImageRegionReadTest.cxx). @yurivict and @issakomi do you agree?

Probably yes. There are also issues with the test on 64-bit platforms (relatively harmless), s #3770. This issue on 32-bit Windows is somewhere in Nifti1, not in the test, IMHO.

**Comment by dzenanz** [comment]
On Windows 32-bit, user processes can allocate up to 2GiB of RAM. I know they later relaxed that a bit, but this test breaks that classic limit. On 32-bit Linux, I assume that 4GiB test would not work in a similar manner.

**Comment by issakomi** [comment]
BTW, for large TIFF test there is also
```cmake
if("${ITK_COMPUTER_MEMORY_SIZE}" GREATER 5)
  ...
endif()
```
Might be not bad for this test too, s. sizes of allocation in the [post](https://github.com/InsightSoftwareConsortium/ITK/pull/3748#issuecomment-1317921285)

**Comment by dzenanz** [comment]
If building on 64-bit computer but targeting 32-bit, what does `ITK_COMPUTER_MEMORY_SIZE` gets initialized to if the user has 32GB? Probably 25 (80% of 32). That probably defeats the purpose.

**Comment by issakomi** [comment]
Yes, you are right
```cmake
set(ITK_COMPUTER_MEMORY_SIZE ${EIGHTY_PERCENT_AVAILABLE_MEMORY_IN_GB} CACHE STRING "Provide here the size of your RAM in gibibytes")
```

**Comment by dzenanz** [comment]
@Zhaojun-Liu does PR #3798 fix the issue?

**Comment by Zhaojun-Liu** [comment]
> @Zhaojun-Liu does PR #3798 fix the issue?

I tried the PR #3798, it worked. Thank you 😃 .
