### ISSUE TITLE
Error on Direction values after DICOMOrient

### ISSUE THREAD

**Issue by plenost** [InsightSoftwareConsortium/ITK#3809]
### Description

DICOMOrient and DICOMOrientFilter don't change the direction properly after processing

### Steps to Reproduce

1. Load an axial image with an orientation LPS (1,0,0,0,1,0,0,0,1)
2. Apply sitk.DICOMOrient(original_volume, "PIL")
3. Output image is correctly oriented but the output value of GetDirection() on the reoriented volume is incorrect (0,0,1,1,0,0,0,-1,0) instead of (0,1,0,0,0,-1,1,0,0)

```
import SimpleITK as sitk

dicom_dir = "C:/test_dirs/DCM/ACQ4_270img"

reader = sitk.ImageSeriesReader()
dicom_files = reader.GetGDCMSeriesFileNames(dicom_dir)
reader.SetFileNames(dicom_files)
original_volume = reader.Execute()
input_direction = original_volume.GetDirection()
input_orientation = sitk.DICOMOrientImageFilter_GetOrientationFromDirectionCosines(input_direction)


target_volume = sitk.DICOMOrient(original_volume, "PIL")

output_actual_direction = target_volume.GetDirection()
output_actual_orientation = sitk.DICOMOrientImageFilter_GetOrientationFromDirectionCosines(output_actual_direction)

output_expected_direction = [0,1,0,0,0,-1,1,0,0]
output_expected_orientation = sitk.DICOMOrientImageFilter_GetOrientationFromDirectionCosines(output_expected_direction)

print(f'Input Direction: {input_direction}')
print(f'Input Orientation: {input_orientation}')

print(f'Actual Output Direction: {output_actual_direction}')
print(f'Actual Output Orientation: {output_actual_orientation}')

print(f'Expected Output Direction: {output_expected_direction}')
print(f'Expected Output Orientation: {output_expected_orientation}')

```

Console Ouput:
```
Input Direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Input Orientation: LPS
Actual Output Direction: (0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, -1.0, 0.0)
Actual Output Orientation: PIL
Expected Output Direction: [0, 1, 0, 0, 0, -1, 1, 0, 0]
Expected Output Orientation: SLA
```

### Expected behavior

From my understanding, DICOM orientation in LPS
Meaning L = [1,0,0], P=[0,1,0] and S=[0,0,1]
Thus, if I ask a PIL orientation, I expect the result to be: [P,I,L] = [0,1,0,0,0,-1,1,0,0]

### Actual behavior

The output is actually (0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, -1.0, 0.0) which, to me, is the equivalent of SLA
Yet the function DICOMOrientImageFilter_GetOrientationFromDirectionCosines gives me the opposite result.

### Reproducibility

100% reproducibility

### Versions

Tested with SimpleITK 2.2.0

### Environment

Using VS Code on Windows 10 with Python 3.10.7 64-bits

**Comment by dzenanz** [comment]
@blowekamp @zivy @dave3d can someone transfer this issue to SimpleITK? I don't have permission to do so.

**Comment by plenost** [comment]
I delete this ticket and re-create it on the proper github if you prefer
Sorry for the inconvenience

**Comment by zivy** [comment]
@dzenanz The "transfer issue" option is only showing repositories in the same organization, so couldn't transfer it to the SimpleITK repo because that is under the SimpleITK organization and not the InsightSoftwareConsortium.

**Comment by dzenanz** [comment]
For posterity: the new ticket is https://github.com/SimpleITK/SimpleITK/issues/1800.
