### ISSUE TITLE
Incorrect dicom reading

### ISSUE THREAD

**Issue by lrunaways** [InsightSoftwareConsortium/ITK#3819]
### Description
Hello! I found dicom that is not loading properly, though some viewers (Weasis) open it correctly. I used SimpleITK, but they [suggested](https://github.com/SimpleITK/SimpleITK/issues/1795) that it is ITK problem. I tried to read with ITK and the problem persisted. Other dicoms read correctly.

### Steps to Reproduce
Sorry for redundant code, I didn't find how to make it easier.
1. Download dicom folder and unzip it
[invalid_reading.zip](https://github.com/InsightSoftwareConsortium/ITK/files/10302326/invalid_reading.zip)

2. change dirName to unzipped folder and run script
```
import itk
import numpy
import nrrd
import matplotlib.pyplot as plt

dirName = ***PATH TO DIR WITH DICOM***
PixelType = itk.F
Dimension = 2

ImageType = itk.Image[PixelType, Dimension]

namesGenerator = itk.GDCMSeriesFileNames.New()
namesGenerator.SetUseSeriesDetails(True)
namesGenerator.SetDirectory(dirName)

seriesUID = namesGenerator.GetSeriesUIDs()
seriesFound = False

seriesIdentifier = seriesUID[0]
print("Reading: " + seriesIdentifier)
fileNames = namesGenerator.GetFileNames(seriesIdentifier)

reader = itk.ImageSeriesReader[ImageType].New()
dicomIO = itk.GDCMImageIO.New()
reader.SetImageIO(dicomIO)
reader.SetFileNames(fileNames)
reader.ForceOrthogonalDirectionOff()

writer = itk.ImageFileWriter[ImageType].New()
outFileName = os.path.join(dirName, seriesIdentifier + ".nrrd")
writer.SetFileName(outFileName)
writer.UseCompressionOn()
writer.SetInput(reader.GetOutput())
print("Writing: " + outFileName)
writer.Update()
readdata, header = nrrd.read(outFileName)

plt.imshow(readdata.T)
plt.show()
```

### Expected behavior

DICOM in Weasis
![image](https://user-images.githubusercontent.com/18750353/209520314-8657a5f9-0657-45d8-843a-dd154d753db5.png)

### Actual behavior

This is how image is plotted. Values are thresholded at 4096
![image](https://user-images.githubusercontent.com/18750353/209520545-10fdf5fd-9e1f-47a2-9501-0cbab283e74e.png)

### Reproducibility

There are few dicom that are loading incorrectly every time

### Versions

ITK version:  5.3.0, installed through pip

### Environment

Operating system: Ubuntu 18.04.6
Python 3.10

**Comment by issakomi** [comment]
Encapsulated stream (lossless JPEG) reports precision 12 bits (cinfo.data_precision), DICOM tag "Bits Stored" is 16. GDCM relies on JPEG header, AFAIK, here the image looks correct with 16 bits stored. Weird.
CC @malaterre

**Comment by issakomi** [comment]
That image opens correctly then the block below is disabled:
https://github.com/InsightSoftwareConsortium/ITK/blob/5d1aa4aced99a920ead67787292c1cbbc08c5285/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmBitmap.cxx#L430-L443

The code assumes that the JPEG header is always correct and sets the _PixelFormat_ accordingly. It is workaround for buggy images with wrong "Bits Stored" DICOM tag. This buggy image has wrong JPEG header and the code harms.

**Comment by lrunaways** [comment]
Thanks for localizing the error! 

Does the image really have the wrong JPEG header? I am bad with ITK and C++ code, so I've tried to find a workaround with pydicom. It has the same thresholding and it is easy to get raw jpeg data with python. I've tried to decompress jpeg data with 'imagecodecs' library and it worked fine.

I don't know if it's appropriate or useful to share code of the other libraries, but this worked fine with just python code:

```
import matplotlib.pyplot as plt
import pydicom
from pydicom.encaps import generate_pixel_data_frame
from imagecodecs import jpegsof3_decode

ds = pydicom.dcmread(*PATH_TO_DICOM*)
dicom_frames_generator = generate_pixel_data_frame(self.dicom_info.PixelData, 1)
im_bytes = list(dicom_frames_generator)[0]
decoded_image = jpegsof3_decode(im_bytes)

plt.imshow(decoded_image, cmap='binary')
```

**Comment by issakomi** [comment]
`dcmdjpeg invalid_reading.dcm out.dcm`
generated decompressed image with

```
(0028,0100) US 16                                       #   2, 1 BitsAllocated
(0028,0101) US 12                                       #   2, 1 BitsStored
(0028,0102) US 11                                       #   2, 1 HighBit
```

The issue may  be similar to 
https://groups.google.com/g/comp.protocols.dicom/c/YawAAvFR6WY
(BTW, _latest_ MicroDicom and Weasis show the image as you expect).

Anyway, it is related to GDCM (3rd party).
CC @malaterre

**Comment by lrunaways** [comment]
Thanks for the detailed answer!
