### ISSUE TITLE
CMake reporting `DOWNLOAD_EXTRACT_TIMESTAMP` option and `CMP0135` policy-related warning for remotes

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITK#3846]
### Description

The CMake configure step is reporting a warning related to the `DOWNLOAD_EXTRACT_TIMESTAMP` option and policy `CMP0135` for the `ITKModuleTemplate`:
https://open.cdash.org/build/8374987/configure

And at least one remote (`ITKTextureFeatures`):
https://open.cdash.org/build/8374782/configure

It is weird that the rest of the remotes are not reporting the warning. This seems worrying. The warning has been observed on Jan 3 2023 for the first time in the module template or the remotes.

### Impact analysis

Unsure.

### Expected behavior

The CMake configuration step should complete without warnings.

### Actual behavior

The CMake configuration step raises a warning related to the `DOWNLOAD_EXTRACT_TIMESTAMP` option and `CMP0135` policy .

### Versions

`main`/`master`.

### Environment

Any OS/compiler. Unsure about CMake.

### Additional Information

A few notes:
- See if it gets fixed once PR https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/pull/100 is merged. Unlikely, since other remotes are also requiring `3.10.2` as the minimum version, e.g.:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/CMakeLists.txt#L1
https://github.com/KitwareMedical/ITKRLEImage/blob/master/CMakeLists.txt#L1
- Requiring `3.10.2` as the CMake minimum version by some remotes without raising a warning is worrying, since MSVC builds, e.g.
https://open.cdash.org/build/8372609
are supposed to raise it:
https://github.com/InsightSoftwareConsortium/ITK/blob/7ba787a2d0df3d99fdbaa5ad343e87506c1045cd/CMake/ITKModuleExternal.cmake#L10
- Although one might be tempted to think that it might be related to [a1cf940d0445ea3ea633a8d03c92cf35b7caae14](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/commit/a1cf940d0445ea3ea633a8d03c92cf35b7caae14) upgrading to the `lukka/get-cmake@v3.24.2` action version, `ITKModuleTemplate` does not yet use that commit.
- Cross-referencing related ITK PRs #3552, #3709, #3763
- If the option/policy needs to be set, it might need to be explicitly set here:
https://github.com/InsightSoftwareConsortium/ITK/blob/7ba787a2d0df3d99fdbaa5ad343e87506c1045cd/CMake/ITKModuleExternal.cmake

A quick look at some of the remotes shows a great diversity in their `CMakeLists.txt` files: they have gone out-of-sync.

**Comment by dzenanz** [comment]
A brand new remote module (https://github.com/thewtex/ANTsWasm) has this problem when configured locally:
```log
The C compiler identification is MSVC 19.38.33134.0
The CXX compiler identification is MSVC 19.38.33134.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found Python3: C:/Program Files/Python311/python.exe (found suitable version "3.11.0", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed 
ITK is setting ANTsWasm's MSVC_RUNTIME_LIBRARY to dynamic
Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1") 
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:3074 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:4184 (_ep_add_download_command)
  C:/Dev/ITK-git/Utilities/ClangFormat/DownloadClangFormat.cmake:47 (ExternalProject_Add)
  C:/Dev/ITK-git/CMake/ITKModuleClangFormat.cmake:17 (include)
  C:/Dev/ITK-git/CMake/ITKModuleMacros.cmake:9 (include)
  C:/Dev/ITK-git/CMake/ITKModuleExternal.cmake:159 (include)
  CMakeLists.txt:7 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

ITK is setting WrapITK's MSVC_RUNTIME_LIBRARY to dynamic
Performing Test ITK_UNDEFINED_SYMBOLS_ALLOWED - Failed
ANTsWasm: Creating module.
ANTsWasm: Creating itkANTSRegistration submodule.
Configuring done
Generating done
```
#4404 fixes it for me.
