### ISSUE TITLE
AttributeError: 'itkN4BiasFieldCorrectionImageFilterIF3IUC3ISS3' object has no attribute 'SetUseCudaOn'

### ISSUE THREAD

**Issue by Agymtcelik** [InsightSoftwareConsortium/ITK#3939]
Hello.

I'm doing research for the N4BiasFieldCorrection method, which I use in the preprocess part of my medical project, to work on the GPU. I compiled and ran my codes to use the N4BiasFieldCorrectionImageFilter function in the ITK library. But it keeps giving me this error. By the way, I'm using Python.

AttributeError: 'itkN4BiasFieldCorrectionImageFilterIF3IUC3ISS3' object has no attribute 'SetUseCudaOn'
AttributeError: 'itkN4BiasFieldCorrectionImageFilterIF3IUC3ISS3' object has no attribute 'SetUseCuda'

Here's my code;

input_images = itk.imread(input_filename)

bfc_filter = itk.N4BiasFieldCorrectionImageFilter.New(input_images)

bfc_filter.SetUseCudaOn(True)

bfc_filter.SetMaximumNumberOfIterations(4)
bfc_filter.SetNumberOfHistogramBins(200)
bfc_filter.SetConvergenceThreshld(0.001)

output_image = bfc_filter.GetOutput()

itk.imwrite(output_image, output_filename)

Am I doing something wrong somewhere? Is there anyone who can help?

Thank you.

**Comment by dzenanz** [comment]
`itk::N4BiasFieldCorrectionImageFilter` is a CPU-only filter. There is no GPU implementation. So there is no `SetUseCudaOn()` method.

**Comment by Agymtcelik** [comment]
Thank you very much for the information. So, can I run the Bias Field Correction method over the GPU using another function with the help of the ITK library?

**Comment by dzenanz** [comment]
No. ITK has more than a 100 image filters. Only a small subset (20-30 or so) have GPU variants. Bias Field Correction is one of those without GPU variant, and making a GPU version is non-trivial. I think that all BSpline related things are missing a GPU variant, and this filter leans heavily on it.
