### ISSUE TITLE
A different directory for GTest cxx files?

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#394]
[ITK\Modules\Core\Common\test](https://github.com/InsightSoftwareConsortium/ITK/tree/v5.0b03/Modules/Core/Common/test) now has more than 200 source files. While I think it's great to have such a large number of tests, I feel it becomes a bit cumbersome to find a specific test file in this directory. It seems to me that it it would be more convenient to place the GTest cxx files of the Core module into their own "gtest" subdirectory:

    ITK\Modules\Core\Common\gtest

Currently, the ITK Core has 11 GTest cxx files. I expect (and hope) that this number will still grow very much, in years to come.

Do you guys agree that it would be useful to move the GTest cxx to such a "gtest" subdirectory?

Of course, this issue could be applicable to other ITK modules as well. But the Core module appears to have the most GTest cxx files, and it also appears to have the most tests in one (almost) flat subdirectory.

**Comment by dzenanz** [comment]
As this is more of a discussion than an issue, perhaps post this question on the [forum](https://discourse.itk.org/)?

**Comment by N-Dekker** [comment]
Please discuss at https://discourse.itk.org/t/a-different-directory-for-gtest-cxx-files/1514
