### ISSUE TITLE
`=itk-5.3.0` fails to build if `-DBUILD_TESTING=ON` (`ninja: build stopped: subcommand failed.`) 

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#3982]
This appears to be analogous to https://github.com/InsightSoftwareConsortium/ITK/issues/1945 but there are no warnings about missing test data, so I'm not sure what's going on.

The error line appears to be:

```
ninja: build stopped: subcommand failed.
```

And this is the full build log → https://ppb.chymera.eu/9147cf.log

Any ideas what's wrong?

**Comment by dzenanz** [comment]
I think that ITK's build system ignores `USE_SYSTEM_FFTW`, and only pays attention to `ITK_USE_SYSTEM_FFTW`. You don't have to enable FFTW. I think It is off by default.

**Comment by TheChymera** [comment]
@dzenanz ok, I tried adding `ITK_USE_SYSTEM_FFTW=ON`, I sadly get the same error :( https://ppb.chymera.eu/fd2830.log

**Comment by TheChymera** [comment]
Ok, I fixed some more things, here is the latest log, still fails with that test: https://ppb.chymera.eu/b1d986.log

Should I be using `ITK_USE_SYSTEM_FFTW:BOOL=ON` on this or any other variable instead of `ITK_USE_SYSTEM_FFTW=ON`?

**Comment by dzenanz** [comment]
I think that ITK_USE_SYSTEM_FFTW:BOOL=ON and ITK_USE_SYSTEM_FFTW=ON are equivalent. And this kind of confirms my suspicion that you were using system FFTW even initially. And there seems to be some version or compilation discrepancy with it.

**Comment by TheChymera** [comment]
@dzenanz does ITK require a specific version of `fftw`?

Or does it maybe require some optional features to be enabled on it? The following features are what Gentoo exposes:

```
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sci-libs/fftw-3.3.10:
 U I
 - - abi_x86_32         : 32-bit (x86) libraries
 - - cpu_flags_x86_avx  : Adds support for Advanced Vector Extensions instructions
 - - cpu_flags_x86_avx2 : Adds support for Advanced Vector Extensions 2 instructions
 - - cpu_flags_x86_fma3 : Use the Fused Multiply Add 3 instruction set ([fma] in cpuinfo)
 - - cpu_flags_x86_fma4 : Use the Fused Multiply Add 4 instruction set
 + + cpu_flags_x86_sse  : Use the SSE instruction set
 + + cpu_flags_x86_sse2 : Use the SSE2 instruction set
 - - doc                : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of globally
 + + fortran            : Add support for fortran
 - - mpi                : Add MPI (Message Passing Interface) layer to the apps that support it
 + + openmp             : Build support for the OpenMP (support parallel computing), requires >=sys-devel/gcc-4.2 built with USE="openmp"
 - - test               : Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can be
                          toggled independently)
 - - threads            : Add threads support for various packages. Usually pthreads
 ```

**Comment by TheChymera** [comment]
Ah, looks like it might need the `threads` feature.

**Comment by TheChymera** [comment]
Ok, that was it. Thank you for sharing this journey with me XD
