### ISSUE TITLE
error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter

### ISSUE THREAD

**Issue by federista** [InsightSoftwareConsortium/ITK#3990]
### Description

I am trying to build my catkin workspace that depends on a number of libraries. All of them are installed as per the requirments. I encounter the following error thatr is related to ITK and eigen

`In file included from /usr/local/include/ITK-5.2/itkeigen/Eigen/Eigenvalues:39,
                 from /usr/local/include/ITK-5.2/itkSymmetricEigenAnalysis.h:23,
                 from /usr/local/include/ITK-5.2/itkSymmetricSecondRankTensor.h:29,
                 from /usr/local/include/ITK-5.2/itkImageIOBase.h:30,
                 from /usr/local/include/ITK-5.2/itkImageFileWriter.h:23,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/src/project_main_gui_rceds_v4/include/sar_cfar/CFAR.h:48,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/../../../../src/project_main_gui_rceds_v4/include/gui/cfar_thread.h:56,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/moc_cfar_thread.cpp:9,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/mocs_compilation.cpp:6:
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h: In static member function ‘static void Eigen::internal::direct_selfadjoint_eigenvalues<SolverType, 3, false>::computeRoots(const MatrixType&, Eigen::internal::direct_selfadjoint_eigenvalues<SolverType, 3, false>::VectorType&)’:
**
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:569:5: error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter, so a declaration of ‘EIGEN_USING_STD_MATH’ must be available [-fpermissive]
  569 |     EIGEN_USING_STD_MATH(sqrt)
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:569:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:569:31: error: expected ‘;’ before ‘EIGEN_USING_STD_MATH’
  569 |     EIGEN_USING_STD_MATH(sqrt)
      |                               ^
      |                               ;
  570 |     EIGEN_USING_STD_MATH(atan2)
      |     ~~~~~~~~~~~~~~~~~~~~       
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:585:27: error: ‘s_inv3’ was not declared in this scope
  585 |     Scalar c2_over_3 = c2*s_inv3;
      |                           ^~~~~~
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h: In static member function ‘static bool Eigen::internal::direct_selfadjoint_eigenvalues<SolverType, 3, false>::extract_kernel(Eigen::internal::direct_selfadjoint_eigenvalues<SolverType, 3, false>::MatrixType&, Eigen::Ref<typename SolverType::RealVectorType>, Eigen::Ref<typename SolverType::RealVectorType>)’:
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:608:5: error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter, so a declaration of ‘EIGEN_USING_STD_MATH’ must be available [-fpermissive]
  608 |     EIGEN_USING_STD_MATH(sqrt)
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:608:31: error: expected ‘;’ before ‘EIGEN_USING_STD_MATH’
  608 |     EIGEN_USING_STD_MATH(sqrt)
      |                               ^
      |                               ;
  609 |     EIGEN_USING_STD_MATH(abs)
      |     ~~~~~~~~~~~~~~~~~~~~       
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:612:41: error: ‘i0’ was not declared in this scope; did you mean ‘y0’?
  612 |     mat.diagonal().cwiseAbs().maxCoeff(&i0);
      |                                         ^~
      |                                         y0
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h: In static member function ‘static void Eigen::internal::direct_selfadjoint_eigenvalues<SolverType, 2, false>::run(SolverType&, const MatrixType&, int)’:
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:733:5: error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter, so a declaration of ‘EIGEN_USING_STD_MATH’ must be available [-fpermissive]
  733 |     EIGEN_USING_STD_MATH(sqrt);
      |     ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/ITK-5.2/itkeigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:734:5: error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter, so a declaration of ‘EIGEN_USING_STD_MATH’ must be available [-fpermissive]
  734 |     EIGEN_USING_STD_MATH(abs);
      |     ^~~~~~~~~~~~~~~~~~~~
In file included from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/../../../../src/project_main_gui_rceds_v4/include/gui/main_window.h:62,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/moc_main_window.cpp:9,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/mocs_compilation.cpp:8:
/home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/include/ui_main_window.h: In member function ‘void Ui_MainWindowDesign::setupUi(QMainWindow*)’:
/home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/include/ui_main_window.h:456:53: warning: ‘QVTKWidget::QVTKWidget(QWidget*, Qt::WindowFlags)’ is deprecated [-Wdeprecated-declarations]
  456 |         LIDAR_Widget = new PCLQVTKWidget(groupBox_10);
      |                                                     ^
In file included from /usr/local/include/vtk-8.2/vtkObject.h:46,
                 from /usr/local/include/vtk-8.2/vtkAlgorithm.h:36,
                 from /usr/local/include/vtk-8.2/vtkImageAlgorithm.h:32,
                 from /usr/local/include/vtk-8.2/vtkImageImport.h:36,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/src/project_main_gui_rceds_v4/include/sar_filters/itkImageToVTKImageFilter.h:22,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/src/project_main_gui_rceds_v4/include/sar_filters/TD_postproc.h:36,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/../../../../src/project_main_gui_rceds_v4/include/gui/cfar_thread.h:58,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/BMPI5EA7AM/moc_cfar_thread.cpp:9,
                 from /home/sentech/RCEDS_V4/RCEDS_Project_SW_V4/build/project_main_gui_rceds_v4/project_main_gui_rceds_v4_autogen/mocs_compilation.cpp:6:
/usr/local/include/vtk-8.2/QVTKWidget.h:82:3: note: declared here
   82 |   VTK_LEGACY(QVTKWidget(QWidget *parent = nullptr, Qt::WindowFlags f = 0));
      |   ^~~~~~~~~~
make[2]: *** [project_main_gui_rceds_v4/CMakeFiles/project_main_gui_rceds_v4.dir/build.make:76: project_main_gui_rceds_v4/CMakeFiles/project_main_gui_rceds_v4.dir/project_main_gui_rceds_v4_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3369: project_main_gui_rceds_v4/CMakeFiles/project_main_gui_rceds_v4.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Invoking "make -j12 -l12" failed
**`

**About operating system and libraries**
Ubuntu 20.04
python 3.8
ITK 5.2
VTK 8.2
Opencv 4.5.0
PCL 1.13
cmake version 3.26.0-rc6

Eigen : 

EIGEN_WORLD_VERSION 3
EIGEN_MAJOR_VERSION 3
EIGEN_MINOR_VERSION 7

### Expected behavior

To be build successfuly

### Actual behavior
error: there are no arguments to ‘EIGEN_USING_STD_MATH’ that depend on a template parameter, so a declaration of ‘EIGEN_USING_STD_MATH’ must be available [-fpermissive]
  569 |     EIGEN_USING_STD_MATH(sqrt)
      |     ^~~~~~~~~~~~~~~~~~~~

I would really appreciate if you guys can help me out with it. let me know if something is wrong with building the above libraries from source?

**Comment by phcerdan** [comment]
I don't think this is an ITK related error. You can search in proper Eigen for a related issue with catkin, https://gitlab.com/libeigen/eigen/-/issues/2261

If you have to share Eigen with other libraries, don't use the internal ITK Eigen.
