### ISSUE TITLE
Possible unused variable in itkLaplacianSharpeningImageFilter

### ISSUE THREAD

**Issue by ntustison** [InsightSoftwareConsortium/ITK#4051]
### Description

The [``m_UseImageSpacing``](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.h#L97-L105) does not appear to be used for anything consequential.  The class [checks for non-zero spacing](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx#L98-L101) but otherwise [image spacing is used](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx#L102-L107).  

Multiple runs with switching this variable seems to confirm the above.  My guess is that the [derivative scalings](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx#LL107C33-L107C33) should be set to 1.0 if ``m_UseImageSpacing == false`` but just wanted to confirm.

**Comment by jhlegarreta** [comment]
@ntustison Given that PR #4052 has been merged, may this issue be marked as solved? Thanks.

**Comment by ntustison** [comment]
Yeah, definitely.  Thanks.
