### ISSUE TITLE
ITK failed to build in Visual Studio 2022 due to error C2187, C2938 and C2532

### ISSUE THREAD

**Issue by Eva-An** [InsightSoftwareConsortium/ITK#4071]
[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/11765736/build.log)

### Description

ITK failed to build due to C2187: syntax error: 'attribute specifier' was unexpected here, C2938: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_vectorcall>' : Failed to specialize alias template and 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::operator unknown-type(void) noexcept const': member function already defined or declared

### Steps to Reproduce
1. git clone https://github.com/InsightSoftwareConsortium/ITK F:\gitP\InsightSoftwareConsortium\ITK
2. cd F:\gitP\InsightSoftwareConsortium\ITK
3. git fetch --recurse-submodules=no --force
4. git reset --hard fcc4890
5. git remote prune origin
6. cd F:\gitP\InsightSoftwareConsortium\ITK\build_amd64
7. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..
8. set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING
9. msbuild /m /p:Platform=x64 /p:Configuration=Release All_BUILD.vcxproj /t:Rebuild

### Expected behavior

Build pass

### Actual behavior

Build failed with error C2187: syntax error: 'attribute specifier' was unexpected here [F:\gitP\InsightSoftwareConsortium\ITK\build_amd64\Modules\Core\Common\test\ITKCommonGTestDriver.vcxproj]

error C2938: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_vectorcall>' : Failed to specialize alias template [F:\gitP\InsightSoftwareConsortium\ITK\build_amd64\Modules\Core\Common\test\ITKCommonGTestDriver.vcxproj]

error C2535: 'itk::MakePoint::<lambda_9e775efe5e487be281683759b49e268a>::operator unknown-type(void) noexcept const': member function already defined or declared [F:\gitP\InsightSoftwareConsortium\ITK\build_amd64\Modules\Core\Common\test\ITKCommonGTestDriver.vcxproj]

### Environment

OS: Windows Server 2022 Datacenter 21H2
CMake: 10.0.22621.0
Compiler: MSVC 14.35.32215

**Comment by dzenanz** [comment]
Visual Studio 2017 is no longer a supported compiler. See this [discussion](https://discourse.itk.org/t/c-17-breaks-visual-studio-2017-drop-support/5884).

**Comment by Eva-An** [comment]
@dzenanz We are using Visual Studio 2022, not 2017

**Comment by dzenanz** [comment]
Example build: https://open.cdash.org/build/8783171

**Comment by Eva-An** [comment]
@dzenanz When compiling the itkPointGTest.cxx file, it causes these problems

**Comment by N-Dekker** [comment]
Thanks for reporting this issue, @Eva-An Looks like this is the same problem that Dženan reported last week:
- #4153

It should be addressed now, by commit 89d3c3c0158806ab44a33d3c76b436537864398e, from the following pull request: 
- #4154

It appears that these errors are caused by a recently introduced Visual C++ compiler bug. Please check (and vote for it!): https://developercommunity.visualstudio.com/t/error-C2187-syntax-error:-attribute-sp/10439022

Please close the issue if you agree  😃

**Comment by Eva-An** [comment]
@N-Dekker Thanks for your response, I updated the commit, it passed.

**Comment by N-Dekker** [comment]
Thanks for closing this issue @Eva-An I'm still curious how you could have found this issue already on June 16, while the MSVC compiler bug that caused the issue was only "officially released" on August 8 (with VS2022 version 17.7)!  Did you use some kind of beta or pre-release of VS2022?

**Comment by Eva-An** [comment]
We use the unreleased VS2022.
