### ISSUE TITLE
itkMacros less robust / break external code that also has an itk namespace

### ISSUE THREAD

**Issue by kislinsk** [InsightSoftwareConsortium/ITK#4074]
### Description

In 24e7b452b4d607154e68bb6fdd2ef5bbb5c2d1b4, leading colons for namespaces have been removed with an automated search and replace. Unfortunately this also affected some macros and made them less robust resp. introduced a regression. We have a few projects that also have itk (sub-)namespaces and the lookup for classes like LightObject and ObjectFactory<T> used in macros like itkNewMacro() is now broken in these cases. It is not a compiler-specific issue as it happens on MSVC, gcc, and clang.

### Expected behavior

Macros always should be as robust as possible in particular regarding parenthesis or namespaces.

### Versions

Worked in ITK v5.2.1, broken in ITK v5.3.0.

### Environment

Windows, Ubuntu, macOS, MSVC, GCC, clang.

**Comment by thewtex** [comment]
@kislinsk thanks for the report. Can you please verify that https://github.com/InsightSoftwareConsortium/ITK/pull/4087 addresses your use case?

**Comment by kislinsk** [comment]
@thewtex Thanks, it works!

Not an issue for us but you may want to consider to do the same for the std namespace in macros.

**Comment by thewtex** [comment]
@kislinsk thanks for the verification!

Good idea regarding `std` -- let's add that if it is found that it is needed.
