### ISSUE TITLE
About principles on generating DRR

### ISSUE THREAD

**Issue by fanyigao** [InsightSoftwareConsortium/ITK#4098]
Hello! your work is brilliant! But I am confused about princples on on generating DRRs, could you tell me more about it? I remember a paper in itk website focused on it ,maybe published in 2010, but I cannot find it on itk website now.

**Comment by SimonRit** [comment]
DRR is the discretization of the x-ray transform, i.e., line integrals. There are several solutions to do it, e.g., https://aapm.onlinelibrary.wiley.com/doi/pdf/10.1118/1.595715 or, the implemented version in ITK, https://ieeexplore.ieee.org/document/4307572. I'm not aware of such an ITK article, maybe https://doi.org/10.54294/6f280b? It doesn't seem to contain an article... Maybe youvcan continue the discussion on discourse.itk.org, it does not seem to be a real issue in ITK.

**Comment by fanyigao** [comment]
> Reference in

Thanks for replying，you have already solved the probem for me!

**Comment by fanyigao** [comment]
> DRR is the discretization of the x-ray transform, i.e., line integrals. There are several solutions to do it, e.g., https://aapm.onlinelibrary.wiley.com/doi/pdf/10.1118/1.595715 or, the implemented version in ITK, https://ieeexplore.ieee.org/document/4307572. I'm not aware of such an ITK article, maybe https://doi.org/10.54294/6f280b? It doesn't seem to contain an article... Maybe youvcan continue the discussion on discourse.itk.org, it does not seem to be a real issue in ITK.

Thanks for replying，you have already solved the probem for me!

**Comment by fanyigao** [comment]
> DRR is the discretization of the x-ray transform, i.e., line integrals. There are several solutions to do it, e.g., https://aapm.onlinelibrary.wiley.com/doi/pdf/10.1118/1.595715 or, the implemented version in ITK, https://ieeexplore.ieee.org/document/4307572. I'm not aware of such an ITK article, maybe https://doi.org/10.54294/6f280b? It doesn't seem to contain an article... Maybe youvcan continue the discussion on discourse.itk.org, it does not seem to be a real issue in ITK.

Hello！I want to verify if the example given bellow [https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/Filtering/DigitallyReconstructedRadiograph1.cxx](url) use joseph's method to generate drrs?

**Comment by fanyigao** [comment]
> 

Thanks, I will read the code.
