### ISSUE TITLE
GDCM ignores image geometry in secondary captures

### ISSUE THREAD

**Issue by pieper** [InsightSoftwareConsortium/ITK#4109]
### Description

Secondary capture images can optionally have ImageOrientationPatient and PixelSpacing fields, but GDCM currently forces the orientation to identity and looks for NominalScannedPixelSpacing instead of PixelSpacing, so otherwise valid images are loaded incorrectly.

There is more information in the discussion at this PR:

https://github.com/Slicer/Slicer/pull/7089

### Steps to Reproduce

The data available from the idc-open-data set on aws is the Visible Human Project male dataset converted to dicom by @dclunie.

You can get one file with this command:

`aws s3 cp --no-sign-request s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/fbc89e1c-29c4-48cf-89fd-53b7c1dc1488.dcm .`

Or the whole dataset using this command (about 13 gigabytes).

`s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com cp 's3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/*' .`

### Expected behavior

The index to physical transform should be correctly populated.

### Actual behavior

The direction cosines are explicitly set of identity:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx#L731-L740

The PixelSpacing is ignored, and the NominalScannedPixelSpacing is looked for, but is typically absent.

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx#L1265-L1273

### Reproducibility

Always

### Versions

Tested on current main branch,  but I suspect the code has been around for decades.

### Environment

Any

### Additional Information

I'll probably fix this, although it may not be a high priority if we fix https://github.com/InsightSoftwareConsortium/ITK/issues/4108 instead.

**Comment by issakomi** [comment]
The upstream [PR](https://github.com/malaterre/GDCM/pull/158) was rejected. Unfortunately, since there are many SC data sets with IPP/IOP, I have also seen such RGB fusion (CT/PT) data sets from Osirix and many other. I fact, IPP/IOP is not part of SC, but, AFAIK, GDCM has workarounds for many issues in data sets, these are "extended". _PixelSpacing_ is perfectly legal, the [CP-586](https://github.com/Slicer/Slicer/pull/7089#issuecomment-1636019931) was merged into the standard over 15 years ago.

**Comment by dclunie** [comment]
@issakomi I have asked @malaterre to reopen and implement the referenced [PR](https://github.com/malaterre/GDCM/pull/158), and uploaded to the [PR](https://github.com/malaterre/GDCM/pull/158) a copy of a proposed DICOM CP specifying the behavior.

**Comment by issakomi** [comment]
Thank you very much for your attention to the problem.

**Comment by dclunie** [comment]
Since @malaterre has decided not to be helpful, we will need to work around his recalcitrance in ITK as he suggests.

**Comment by dclunie** [comment]
Your long history of valuable contributions is not undermined by one deviation.

**Comment by thewtex** [comment]
Closed via #4521
