### ISSUE TITLE
Any support for android develeper?

### ISSUE THREAD

**Issue by DavidMGT** [InsightSoftwareConsortium/ITK#4129]
### Description
 have no idea how should I use this on Android platform.

### Expected behavior

Android support

**Comment by jhlegarreta** [comment]
Although the question could be fair, the effort invested in making the issue informative (e.g. what has been tried, or where attemps have failed) is none, and user activity seems suspicious. Closing.

**Comment by DavidMGT** [comment]
> Although the question could be fair, the effort invested in making the issue informative (e.g. what has been tried, or where attemps have failed) is none, and user activity seems suspicious. Closing.

hhh，not get any help from them。like an answer from robot

**Comment by DavidMGT** [comment]
> Thank you for contributing an issue! 🙏
> 
> **Welcome to the ITK community!** 🤗👋☀️
> 
> We are glad you are here and appreciate your contribution. Please keep in mind our [community participation guidelines](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md). 📜 Also, please check [existing open issues](https://github.com/InsightSoftwareConsortium/ITK/issues) and consider discussion on the [ITK Discourse](https://discourse.itk.org). 📖




> and user activity seems suspicious

and what do you mean by" user activity seems suspicious"?

**Comment by DavidMGT** [comment]
> Although the question could be fair, the effort invested in making the issue informative (e.g. what has been tried, or where attemps have failed) is none, and user activity seems suspicious. Closing.

and what do you mean by" user activity seems suspicious"?

**Comment by DavidMGT** [comment]
> Thank you for contributing an issue! 🙏
> 
> **Welcome to the ITK community!** 🤗👋☀️
> 
> We are glad you are here and appreciate your contribution. Please keep in mind our [community participation guidelines](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md). 📜 Also, please check [existing open issues](https://github.com/InsightSoftwareConsortium/ITK/issues) and consider discussion on the [ITK Discourse](https://discourse.itk.org). 📖

That's answer is really useless. just waste of time.please be more professional。I can't find any usefull infomation from the [ITK Discourse](https://discourse.itk.org/). 📖 or [existing open issues](https://github.com/InsightSoftwareConsortium/ITK/issues)

**Comment by dzenanz** [comment]
@brad-t-moore have you tried building ITK on Android?

@DavidMGT if it doesn't build for you, you should write what you tried, and what was the error message. Otherwise we don't have an idea about your problem.
