### ISSUE TITLE
We are looking into building a small app that reads ultrasound cines (basically dicom files)

### ISSUE THREAD

**Issue by DavidMGT** [InsightSoftwareConsortium/ITK#4130]
Thank you for contributing an issue! 🙏

**Welcome to the ITK community!** 🤗👋☀️

We are glad you are here and appreciate your contribution. Please keep in mind our [community participation guidelines](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md). 📜
Also, please check [existing open issues](https://github.com/InsightSoftwareConsortium/ITK/issues) and consider discussion on the [ITK Discourse](https://discourse.itk.org). 📖

_Originally posted by @github-actions[bot] in https://github.com/InsightSoftwareConsortium/ITK/issues/4129#issuecomment-1651332254_

**Comment by DavidMGT** [comment]
That's answer is really useless. just waste of time.please be more professional。I can't find any usefull infomation from the [ITK Discourse](https://discourse.itk.org/). 📖 or [existing open issues](https://github.com/InsightSoftwareConsortium/ITK/issues)

**Comment by thewtex** [comment]
Duplicate of #4129.

**Comment by DavidMGT** [comment]
> Duplicate of #4129.

yes,but didnt get any useful advice
