### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for the ITK

### ISSUE THREAD

**Issue by wangyuliu** [InsightSoftwareConsortium/ITK#4207]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. As part of my dataset, I have collected the ITK project. **I would like to gather community opinions to support my assessment.** I appreciate your help and response! Based on scanning tools, the porting complexity is determined to be moderate, with a moderate amount of code related to the CPU architecture in the project，such as Assembly code,Intrinsic and builtin function. It would require a professional team, but not a large-scale one, to handle this task  (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.
各位好！我在实现一个关于CPU架构的移植工作复杂度评估的工具，主要面向riscv架构移植，我收集ITK项目作为我的数据集之一，需要收集社区的意见作为支撑，期待您的帮助和回答！通过扫描工具得出其移植复杂度为中等，工程中与CPU架构相关的代码量也为中等，例如汇编代码、内建函数等，需要较专业团队但不需要大规模的团队进行，（这里指的是从工程尚未适配某架构到实现某架构的较完整功能的总体工作量）这样的判断是否准确？期待您的帮助与回答

**Comment by dzenanz** [comment]
I don't think it would take a team of people. ITK is meant to be multi-platform, and the bundled third-party libraries too. Which means that a single person should be able to port it to a reasonably popular platform such as RISC-V. Others are welcome to pitch in with their own opinion.

**Comment by jhlegarreta** [comment]
Closing due to lack of follow-up to maintainers' response. Can be re-opened in the future if necessary.

**Comment by wangyuliu** [comment]
> I don't think it would take a team of people. ITK is meant to be multi-platform, and the bundled third-party libraries too. Which means that a single person should be able to port it to a reasonably popular platform such as RISC-V. Others are welcome to pitch in with their own opinion.
https://github.com/InsightSoftwareConsortium/ITK/issues/4207#issuecomment-1708280108

Thank you very much for your comment. Our tool has collected hundreds of lines of assembly code and counted thousands of Intrinsic functions (with duplicates) for ITK. There are also some structures with #if and architecture-related macros, so the tool evaluates it as moderately complexity to transplant. Is this correct? What other comments do you have?

**Comment by dzenanz** [comment]
ITK itself has no assembly code. That comes from bundled third-party libraries, such as `zlib-ng`. In most of those cases, assembly is only a platform-specific optimization for specific popular platforms, with C or C++ fallback for less known platforms. If I remember correctly, most problems related to architecture porting were compiler differences and missing header inclusions.

**Comment by blowekamp** [comment]
> ITK itself has no assembly code.

This is correct, but we do use some cpu intrinsic is a couple places such as here:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkMathDetail.h

And as @dzenanz the code is written as an optimization for common architectures, and has C/C++ fall back code.

**Comment by dzenanz** [comment]
Correct.
