### ISSUE TITLE
Failed to build itk-wasm because ITK does not export ITKModuleExternal.cmake

### ISSUE THREAD

**Issue by gl-yziquel** [InsightSoftwareConsortium/ITK#4211]
### Description

I tried to build `itk-wasm` after having built `ITK`. It fails at the `cmake ..` step since it cannot find `ITKModuleExternal.cmake`. The issue has been reported here:

https://github.com/InsightSoftwareConsortium/itk-wasm/issues/933

### Steps to Reproduce

Build `ITK` on Ubuntu 22 with `cmake .. && make && sudo make install` and then build `itk-wasm` with `cmake ..`. Here are the revisions:

`ITK`: `aaa43159aa5510fd514c71823b6b9c86b1f01212``
`itk-wasm`: `b1289e36d0b2483c8687d9325fb16ed604be4b15`

### Expected behavior

The `itk-wasm` build would pass the `cmake ..`step.

### Actual behavior

It fails to find `ITKModuleExternal.cmake`. Log is here:

https://github.com/InsightSoftwareConsortium/itk-wasm/issues/933

### Reproducibility

Deterministic.

### Versions

Revision SHAs have been given above.

### Environment

Ubuntu 22 on an amd64.

**Comment by gl-yziquel** [comment]
I tried building the `v5.3.0` tag, with `cmake -DITK_WRAP_PYTHON=ON`. Same problem. `ITKModuleExternal.cmake` does not get installed after `sudo make install`.

**Comment by dzenanz** [comment]
https://github.com/InsightSoftwareConsortium/itk-wasm/issues/933 is the right place for this issue. I built ITK yesterday on Ubuntu 22.04 with GCC 11.4 without any issues.

**Comment by gl-yziquel** [comment]
I also ITK fine. Just not itk-wasm.

From what I understand implicitly in your answer, the file ITKModuleExternal.cmake is not supposed to be published from ITK and made available to itk-wasm via the standard location for cmake files.

I find that clumsy. Or, more likely, I fail to understand the underlying issue that prevents from getting ITKModuleExternal.cmake published.
