### ISSUE TITLE
GDCM update fails wih pre-commit hook failure related to MaxObjectKiB

### ISSUE THREAD

**Issue by seanm** [InsightSoftwareConsortium/ITK#4274]
I just tried to update GDCM and it failed with:

```
pre-commit hook failure
-----------------------

At least one file is staged for commit with size larger than its limit.
We prefer to keep large files out of the main source tree, especially
binary files that do not compress well.  This hook disallows large files
by default but can be configured.  A limit for specific files or patterns
may be set in ".gitattributes" with the "hooks.MaxObjectKiB" attribute.
For example, the line

  *.c              hooks.MaxObjectKiB=2048

sets a limit of 2048 KiB for C source files.  See "git help attributes"
for details on the .gitattributes format.  If no attribute has been set
for a given file then its size is limited by the local default.  Run

  git config hooks.MaxObjectKiB $KiB

to set the local default limit (0 to disable).

The path 'Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/privatedicts.xml' has size 1033 KiB, greater than allowed 1024 KiB.
```

Gives me strong deju vu. I found this but it's supposedly fixed: https://github.com/InsightSoftwareConsortium/ITK/issues/3229

The limit in `Modules/ThirdParty/GDCM/src/gdcm/.gitattributes` is already larger:

```
/Source/DataDictionary/privatedicts.xml hooks-max-size=1500000
```

**Comment by dzenanz** [comment]
It is larger in both GDCM and ITK repos:
https://github.com/malaterre/GDCM/blob/master/.gitattributes#L8
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/.gitattributes#L8
@bradking do you have some suggestions?

**Comment by dzenanz** [comment]
I ran the update script on my computer using Git Bash for Windows, and I did not run into any issues. The PR is here: #4275.

**Comment by thewtex** [comment]
@seanm does:

```
cd src/ITK
rm -rf .git/hooks
./Utilities/SetupForDevelopment.sh
```

help?

**Comment by dzenanz** [comment]
I just tried that on Ubuntu 22.04, and I did not run into issues.

**Comment by seanm** [comment]
@thewtex good idea, but alas that didn't help.

@dzenanz thanks for testing, and creating that PR.

I wonder if this could be a Mac-only problem?  Or I guess I could also try to blow away my `ITK` checkout entirely...

**Comment by dzenanz** [comment]
> try to blow away my ITK checkout entirely...

Worth trying. Cruft accumulates over the years.

**Comment by seanm** [comment]
@thewtex @dzenanz looks like nuking my git checkout worked! See https://github.com/InsightSoftwareConsortium/ITK/pull/4293
