### ISSUE TITLE
Please upgrade VXL, for faster access to elements of vnl_sparse_matrix

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#4276]
In the last few months I submitted some pull requests to [VXL](https://github.com/vxl/vxl) to speed up access to the elements of a `vnl_sparse_matrix`:

 - https://github.com/vxl/vxl/pull/926
 - https://github.com/vxl/vxl/pull/928
 - https://github.com/vxl/vxl/pull/932

All of them are merged into the `master` branch now. Daniel Crispell (@decrispell) just merged the last one earlier today, November 1st, 2023). The last commit of those pull request is https://github.com/vxl/vxl/commit/b37c7a22cd0ae5d50fe940f58e2c8e0ebc6ccd24 (October 24).

At the moment these commits are not yet available in a tagged revision of VXL. Looking at https://github.com/vxl/vxl/tags it seems that VXL isn't tagged very frequently, unfortunately. So shall we then just upgrade VXL to a commit at the `master` from after those three pull requests? @dzenanz I see you did so before: 

- https://github.com/InsightSoftwareConsortium/ITK/pull/4100

Can you please do it again?  😃 

This upgrade will be beneficial to [elastix](https://github.com/SuperElastix/elastix), but it may also improve the performance of ITK classes that use `vnl_sparse_matrix`, including `itk::fem::LinearSystemWrapperVNL` and `itk::fem::LinearSystemWrapperDenseVNL`.

**Comment by dzenanz** [comment]
Anyone can do it by running https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/VNL/UpdateFromUpstream.sh, for example in `git bash`. PR: #4277.
