### ISSUE TITLE
ITK Python 3 compatibility issue?

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#428]
### Description

itk Python calls `execfile` in itkBase.py even if ITK is run with Python 3. This should fail as this function does not exist with Python 3, but I haven't found an case in which the piece of code that would create the issue is called.

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkBase.py#L94-L98

The issue would be simple to solve as it has already been solve in other locations in the same file:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkBase.py#L282-L286

Maybe the section of the code calling `execfile` with Python 3 has previously been overlooked.

**Comment by fbudin69500** [comment]
@thewtex Any idea how to call the code that should fail?

**Comment by thewtex** [comment]
@fbudin69500 not sure offhand how to invoke it.

But, we should be should be using the standard library module import functions.

**Comment by thewtex** [comment]
Removed in #1283
