### ISSUE TITLE
Support versioning of "docs.itk.org"

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITK#4300]
### Description

The `docs.itk.org` portal is generated and published on ReadTheDocs each time the `master`[^1] branch is updated.

### Actual vs Expected information

| Actual (ITK) | Expected (Slicer) |
|--|--|
| ![image](https://github.com/InsightSoftwareConsortium/ITK/assets/219043/d9e6ea36-143b-42bb-b777-da2480b6d434) | ![image](https://github.com/InsightSoftwareConsortium/ITK/assets/219043/896f4b27-1d8e-46c8-83e8-911128391f58) |

Similarly to Slicer, documentation for prior releases should be available and maintainable.

To support generating the version of a specific release (copied from Slicer release process[^1]):
* [Activate](https://readthedocs.org/projects/itk/versions/) the build of the `X.Y` maintenance branch in readthedocs.
* If redirects are ever needed, these can be added to [Redirect](https://readthedocs.org/dashboard/itk/redirects/) selecting the type _Exact Redirects_

[^1]: https://github.com/Slicer/Slicer/blob/c2e136fa1addcb64185faba49344d8121100264e/.github/ISSUE_TEMPLATE/release.md#L28

For each release, I suggest to have a permanent "maintenance" branch associated with each release. For example `5.2`, `5.3`, .... To differentiate these branches from the tag, it is important to not have the `v` prefix.

### Versions

NA

### Additional Information

* https://slicer.readthedocs.io/en/latest/

**Comment by thewtex** [comment]
This is now set up for version 5.4:

https://docs.itk.org/en/5.4/

A `release` branch build was also set up for the default / stable value.

Note: I think we may need more builds on the `release` branch for `5.4` to show up in the RTD lower left menu.

The process for future releases is documented in #4306.

**Comment by jcfr** [comment]
> Note: I think we may need more builds on the release branch for 5.4 to show up in the RTD lower left menu.

It is showing up as expected:

<img width=25% src="https://github.com/InsightSoftwareConsortium/ITK/assets/219043/05e5df11-f7a5-461e-b9eb-8ad5c05d6bdb"/>
