### ISSUE TITLE
Revisit versioning of RTD documentation to minimize confusion

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITK#4338]
### Description

After the recent implementation of versioning support via https://github.com/InsightSoftwareConsortium/ITK/pull/4306, there is a need to reassess the versioning strategy for the RTD (Read the Docs) documentation. Currently, the default version of the ITK documentation is set to the latest `release` rather than the `latest` version.

This leads to confusion for few reasons:

1. **URL Structure Misleading:** Upon landing on the documentation portal, the absence of a version number (e.g., `X.Y`) in the URL led me to assume that it represented the latest version. This ambiguity can be misleading for users seeking specific versions.

2. **Expectation of Version-Inclusive URLs:** Users typically expect documentation URLs associated with a specific version to include that version in the URL itself (e.g., `https://docs.itk.org/X.Y`). This ensures that references to a particular documentation page remain valid regardless of the current release, contributing to a more stable and predictable user experience.

### Expected vs Current Behavior

The expected behavior is that the `release` identifier should serve as a convenient redirect, allowing easy reference to the latest release. However, it should not be the default version displayed, as this can lead to confusion. Instead, the `latest` version should be the default, with the option to navigate to the latest release if desired.

### Recommendation

Consider adjusting the default version for the ITK documentation on RTD to be the `latest` version.

### Versions

Issue report based of https://github.com/InsightSoftwareConsortium/ITK/commit/8844ee6549ebdc1294a17d471f8a65311440bd74

### Additional Information

NA

**Comment by thewtex** [comment]
To clarify, as described in https://github.com/InsightSoftwareConsortium/ITK/commit/8844ee6549ebdc1294a17d471f8a65311440bd74, `release` does render the latest released version.

Following ReadTheDocs recommendations,

![image](https://github.com/InsightSoftwareConsortium/ITK/assets/25432/9088d944-0803-475c-b8b9-bceded54d397)

`master`, the default branch of the VCS is used for rendering `latest`.

`release` was used as the default version to avoid confusion regarding differences between the downloaded version of the released version of the package and the latest development version. But there is also potential confusion between the differences in `latest` and `master` -- I agree @jcfr that this outweighs the other path of confusion and follows RTD conventions; the default version has been switched to `latest`.

**Comment by jcfr** [comment]
> I agree @jcfr that this outweighs the other path of confusion and follows RTD conventions; the default version has been switched to latest.

:100: That will really helps and let the user pick which links they want to use.
