### ISSUE TITLE
CMake warning with CMP0135

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#4411]
### Description

PR #4404 has triggered a warning for "old" versions of CMake, e.g.,  3.20.4 (the doc says policy CMP0135 is new in version 3.24, see [here)](https://cmake.org/cmake/help/latest/policy/CMP0135.html#cmp0135).

### Steps to Reproduce

Configure ITK with CMake 3.20.4

### Expected behavior

No warning

### Actual behavior

CMake says
```
CMake Error at Utilities/ClangFormat/DownloadClangFormat.cmake:47 (cmake_policy):
  Policy "CMP0135" is not known to this version of CMake.
Call Stack (most recent call first):
  CMake/ITKModuleClangFormat.cmake:17 (include)
  CMake/ITKModuleMacros.cmake:9 (include)
  CMakeLists.txt:146 (include)
```
see [here](https://my.cdash.org/build/2475044/configure)

### Reproducibility

100%

### Versions, environment

ITK master, CMake 3.20.4, Linux

**Comment by dzenanz** [comment]
Introduction of this was totally my fault. I was testing with 3.25.3 while fixing #3846.
