### ISSUE TITLE
pip install itk failed, file name too long

### ISSUE THREAD

**Issue by ZoroGH** [InsightSoftwareConsortium/ITK#4449]
# Description

I use the command `pip install itk`，the log show it that it didn't have a CMake, then I install the CMake. Then i still fail to install becasue it requires the doxygen, ok i install the doxygen. Finally it show it that the **File Name too Long** error.

I don't know how to fix this, because the pwd is very short already "C:\Users\zorogh\dev\python\BS_origin>"

![image](https://github.com/InsightSoftwareConsortium/ITK/assets/67215466/71fe813d-4098-4005-a92a-cff346436bb3)

### Steps to Reproduce

1. install the CMake, add it to the PATH
2. install the doxygen , add it to the PATH
3. pip install itk

# Environment

- windows11
- Python 3.12.1
- pip 24.0
- cmake version 3.28.2
- doxygen  1.10.0

**Comment by ZoroGH** [comment]
the Cmake error let me change the source directory, but the length is too long...

```shell
      CMake Error at CMakeLists.txt:109 (message):
        ITK source code directory path length is too long (133 > 50).Please move
        the ITK source code directory to a directory with a shorter path.
```

**Comment by dzenanz** [comment]
What processor architecture are you working with? ITK should have [wheels](https://pypi.org/project/itk/#files) for common architectures (amd64 and arm64). Also try [enabling long paths](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).

**Comment by thewtex** [comment]
```
pip install --upgrade pip
pip install --upgrade itk
```

will install the `itk` `5.4.0` wheels. These are 3.11 Stable ABI wheels that work with 3.12.
