### ISSUE TITLE
ITKPhaseSymmetry - inputs do not occupy the same physical space error

### ISSUE THREAD

**Issue by lassoan** [InsightSoftwareConsortium/ITK#445]
### Description

We are trying to use [ITKPhaseSymmetry](https://github.com/KitwareMedical/ITKPhaseSymmetry) filter for pediatric 4D ultrasound image denoising. The filter looks very promising, but we have problems running it: we get "Description: itk::ERROR: MultiplyImageFilter(00000198C6FB7D80): Inputs do not occupy the same physical space!" error.

This report is posted here because bugtracker is disabled in  [ITKPhaseSymmetry](https://github.com/KitwareMedical/ITKPhaseSymmetry) repository.

### Steps to Reproduce

1. Download sample input data file: https://1drv.ms/u/s!Arm_AFxB9yqHtstoJ9wYHMFef6uzbQ
2. Run itkPhaseSymmetryImageFilterTest on it (we used this [CLI module](https://github.com/SlicerHeart/SlicerHeart/blob/master/PhaseSymmetryFilter/PhaseSymmetryFilter.cxx) in Slicer but it should be the same with the tests/examples as well)

```
c:\D\S4R\Slicer-build\Slicer.exe --launch c:\D\SlicerHeartExtension-win64rel\inner-build\lib\Slicer-4.11\cli-modules\Release\PhaseSymmetryFilter.exe --wavelengths 3,3,3,6,6,6,12,12,12 --orientations 1,0,0,0,1,0,0,0,1 --sigma 0.55 --angularBandwidth 3.14 --polarity 0 --noiseThreshold 10 c:\Users\msliv\OneDrive\Share\SlicerBugTrackerAttachment\itk-phase-symmetry-test\input.nrrd c:\Users\msliv\OneDrive\Share\SlicerBugTrackerAttachment\itk-phase-symmetry-test\output.nrrd

itk::ExceptionObject (00000087E433A070)
Location: "unknown"
File: c:\d\s4r\itk\modules\core\common\include\itkImageToImageFilter.hxx
Line: 241
Description: itk::ERROR: MultiplyImageFilter(00000198C6FB7D80): Inputs do not occupy the same physical space!
InputImage Origin: [-1.1590701e-06, -1.1522100e+01, -8.4341402e+00], InputImage_1 Origin: [0.0000000e+00, 0.0000000e+00, 0.0000000e+00]
        Tolerance: 3.3296085e-07
InputImage Spacing: [3.3296085e-01, 4.8425890e-01, 1.7517500e-01], InputImage_1 Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00]
        Tolerance: 3.3296085e-07
```

### Expected behavior

The filter should be able to handle images with any origin, spacing, and orientation.

(the filter should be able to automatically pad the image, too, and remove padding from the output, but this is not a bug but more an enhancement request)

### Actual behavior

Exception is thrown.

### Reproducibility

100%.

### Versions

- ITK in Slicer (4.13.0)
- ITKPhaseSymmetry [here](https://github.com/SlicerHeart/ITKPhaseSymmetry) (had to make a minor change to make it compatible with current Slicer's VTK)

### Environment

Windows 10, VS2015.

**Comment by thewtex** [comment]
Follow-up on Discourse:

https://discourse.itk.org/t/phase-symmetry-filter-fails-with-inputs-do-not-occupy-the-same-physical-space-error/1549/2

If the issue persists, please re-open on the ITKPhaseSymmetry issue tracker.
