### ISSUE TITLE
Create a Citation section for the README

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#456]
Add a *Citation* section to the README. This section should explain how to cite ITK in journal articles.

CC: @bpaniagua

**Comment by jhlegarreta** [comment]
This should be helpful:
https://itk.org/Wiki/ITK/FAQ#How_do_I_cite_the_use_of_ITK_in_a_publication.3F

I guess we still want ITK to be cited as recommended there. The page is outdated, though (third edition is not in press right now: fourth edition is out) :worried:.

**Comment by thewtex** [comment]
Yes, we should reference the original publication, The Software Guide, but also the update emphasizing progress and the project's focus on reproducible research and open science: https://www.frontiersin.org/articles/10.3389/fninf.2014.00013/full.

**Comment by jhlegarreta** [comment]
May be we could use [zenodo](https://zenodo.org/) and add the corresponding file and badge to the `README` file instead of adding a section in the `README` file? Or in addition to?

**Comment by thewtex** [comment]
Good idea. Since Zenodo is version-dependent, we should probably wait until ITK 5.0.0 to create a citation.

**Comment by jhlegarreta** [comment]
Seems reasonable.

A few (possibly useful) thoughts:
* [GitHub Making Your Code Citable guide](https://guides.github.com/activities/citable-code/).
* On second thoughts, even if zenodo is used, adding a *Citing ITK*  section somewhere would still be necessary. The SW Guide could be a good place, but may be the `README` in the ITK repository is better.
* Not sure if it the zenodo citation information could also be used in the PyPI ITK package.
* Generating the zenodo citation every time a release is made should be added to [Release.md](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/Maintenance/Release.md).
* Not sure whether a JSON with the repository/author information ([nibabel script example](https://github.com/nipy/nibabel/blob/master/tools/prep_zenodo.py)) should be generated and uploaded [using a script for example](https://github.com/darvasd/upload-to-zenodo) to zenodo.

We'll figure out.

**Comment by thewtex** [comment]
Zenodo badge added in #1540
