### ISSUE TITLE
Update clang-format version

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#4565]
Current clang-format is version 8, circa 2019. Update to a newer version to support system clang-format executables available in packages and also provide a ARM macOS binary.

- [ ] Update the *ITK/.clang-format* style configuration file
- [ ] Update CMake and shell scripts used for running clang-format: *CMake/*Clang*.cmake**, *Utilities/ClangFormat/DownloadClangFormat.cmake*, *Utilities/Maintenance/clang-format.bash*, *Utilities/Maintenance/git-clang-format*.
- [ ] Re-run on the source tree.
- [ ] Update the [module in ITKSphinxExamples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/master/Superbuild/External-ClangFormat.cmake)

**Comment by blowekamp** [comment]
I have recently been looking into use [pre-commit](https://pre-commit.com) with the [clang-format](https://pre-commit.com/hooks.html) hooks, which pulls clang-format from [pypi](https://pypi.org/project/clang-format/18.1.3/#files)

**Comment by thewtex** [comment]
Yes, possibly we just go to pre-commit. Discussed more in https://github.com/InsightSoftwareConsortium/ITK/issues/4235
