### ISSUE TITLE
itk install error in macOS-latest

### ISSUE THREAD

**Issue by KumoLiu** [InsightSoftwareConsortium/ITK#4614]
Looks itk>=5.2 can be installed successfully yesterday.
https://github.com/Project-MONAI/MONAI/actions/runs/8831347714/job/24246389623#step:10:145
But not today:
```
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.11.4 Requires-Python >=3.9; 1.12.0 Requires-Python >=3.9; 1.12.0rc1 Requires-Python >=3.9; 1.12.0rc2 Requires-Python >=3.9; 1.13.0 Requires-Python >=3.9; 1.13.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement itk>=5.2 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1)
ERROR: No matching distribution found for itk>=5.2
```
https://github.com/Project-MONAI/MONAI/actions/runs/8833587029/job/24282045229#step:10:144

Does it drop support for 3.8?

Thanks

**Comment by KumoLiu** [comment]
Hi @dzenanz, thanks for the quick response. Then it's wired, I try to install it in a fresh conda python=3.8 env, it also throw errors.
```
(base) bash-3.2$ conda activate py3.8
(py3.8) bash-3.2$ pip install itk>=5.2
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      scikit-build is required to build from source.
      Please run:
      
        python -m pip install scikit-build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dzenanz** [comment]
Ah, so you are not installing from wheels but instead building from source. ITK recently switched from `setup.py` to `scikit-build`. Which means there is another requirement now, which you probably need to add to some list of requirements.

**Comment by KumoLiu** [comment]
So do you mean `pip install itk==5.3.0` will try to build from source when python 3.8 but download wheel when python 3.9?
https://github.com/Project-MONAI/MONAI/actions/runs/8849038116/job/24300068122?pr=7719#step:10:146

**Comment by dzenanz** [comment]
Uh-oh, @thewtex and/or @jcfr should be able to answer that, or provide more meaningful help for this issue.

**Comment by dzenanz** [comment]
There are wheels for both ARM and AMD64 for MacOSX for ITK 5.3, for Python 3.9+. Python 3.8 and 3.7 have only AMD64 wheels. Are you trying to `pip install itk==5.3.0` for some configuration which doesn't have [pre-built wheels](https://pypi.org/project/itk/5.3.0/#files)?

**Comment by dzenanz** [comment]
Should this issue be closed now, in light of https://github.com/Project-MONAI/MONAI/issues/7716? Have you figured out the root cause? We have not touched ITK 5.2 in quite a while.

**Comment by KumoLiu** [comment]
Hi @dzenanz, I still didn't find the root cause. We decided to partially drop support for 3.8 as it's reaching end-of-life soon anyhow. Closing this one now.
Thanks.

**Comment by thewtex** [comment]
@KumoLiu I noticed in the linked MONAI CI Action log:

![image](https://github.com/InsightSoftwareConsortium/ITK/assets/25432/4b243864-1e1c-47a7-8a08-3ac43ed7941e)

-- in CI, a good best practice is to upgrade `pip` with `python -m install --upgrade pip` so it can find the latest packages, regardless of project. HTH
