### ISSUE TITLE
Detailed CMake options are not marked as advanced.

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#4629]
### Description

The following CMake options/varaibles are not marked as advanced.
                                 
 - [x] COREFOUNDATION_LIBRARY          */Applications/Xcode_14.2.app/Contents/Develop
 - [x] GDCM_USE_COREFOUNDATION_LIBRAR  *ON                                           
  - [x] Module_FastBilateral            *OFF                                          
 - [x] OPJ_USE_DSYMUTIL                *OFF  

### Steps to Reproduce

The above where included in the `ccmake` GUI on Mac OS X initial configuration

### Expected behavior

These options seem like they should be marked advanced.

**Comment by thewtex** [comment]
xref: https://github.com/malaterre/GDCM/pull/172
