### ISSUE TITLE
Inconsistent conversion of VectorImage to numpy

### ISSUE THREAD

**Issue by ncullen93** [InsightSoftwareConsortium/ITK#4646]
In itk Python, if I have a VectorImage of size (10,10) with 2 channels, then converting it to numpy gives me an array of shape (10,10,2). But if I have a VectorImage with 1 channel, it squeezes that channel and gives me a numpy array of (10,10). Shouldn't the expected behavior be (10,10,1). Or is there a way to ensure this?

```python
import itk
import numpy as np

arr = np.ones((10,10,2))
img = itk.image_from_array(arr, is_vector=True)
arr2 = itk.array_from_image(img)
print(arr2.shape) # (10,10,2)

arr = np.ones((10,10,1))
img = itk.image_from_array(arr, is_vector=True)
arr2 = itk.array_from_image(img)
print(arr2.shape) # (10,10)
```

**Comment by thewtex** [comment]
Hi, thanks for the nice report! Patch is here: #4648
