### ISSUE TITLE
MacOS: the weak symbol cannot be overridden at runtime

### ISSUE THREAD

**Issue by haampie** [InsightSoftwareConsortium/ITK#471]
When building ITK 4.13.1 on MacOS I am getting warnings of the form:

```
ld: warning: direct access in function 
'itk::ThreadPool::GetGlobalDefaultNumberOfThreads()' from file 
'../../../../../lib/libITKCommon-4.13.a(itkThreadPool.cxx.o)' to global weak symbol 
'std::__1::__cxx03_bool::__true_value()' from file '../../../../../lib/libitksys-4.13.a(SystemTools.cxx.o)' 
means the weak symbol cannot be overridden at runtime. This was likely caused by 
different translation units being compiled with different visibility settings. 
```

Is this a known issue?

**Comment by thewtex** [comment]
@haampie  is this warning reproduced with ITK 5 RC 1 or ITK Git `master`?

**Comment by thewtex** [comment]
Also, are you building ITK with static libraries (`BUILD_SHARED_LIBS=OFF`) and integrating it into libraries that are built as shared libraries?

**Comment by haampie** [comment]
Thanks for the quick reply!

I built VTK with BUILD_SHARED_LIBS=OFF and then ITK with BUILD_SHARED_LIBS=OFF.

Let me see what happens on master.

**Comment by haampie** [comment]
I'm not seeing those warnings on ITK 5 RC 1. 

However, unrelatedly, it errors at the very end when compiling `LesionSizingToolkit`:

```
.../ITK-5.0rc01/Modules/Remote/LesionSizingToolkit/Examples/LesionSegmentation.cxx:148:14: error: conversion from 'long' to
      'LesionSegmentationCLI::InputImageType::Pointer' (aka 'SmartPointer<itk::Image<short, 3> >') is ambiguous
      return NULL;
```

**Comment by haampie** [comment]
Following https://discourse.itk.org/t/visibility-settings/596 the issue is that ITK 4.13.1 does not have the c++11 flag on?

**Comment by thewtex** [comment]
:+1: Thanks for the follow-up report @haampie
