### ISSUE TITLE
Cannot use RTK in 5.4rc>1

### ISSUE THREAD

**Issue by brynolf** [InsightSoftwareConsortium/ITK#4723]
### Description
In 5.4rc1 I could use RTK, but in any release after that RTK is not available.

### Steps to Reproduce
a python environment with any of
```
pip install itk==5.4rc2
pip install itk==5.4rc3
pip install itk==5.4rc4
pip install itk==5.4
```
and 
`pip install rtk`

`>>> from itk import RTK as rtk`
will fail after 5.4rc1

### Actual behavior

```none
```

### Versions
python 3.10.9

**Comment by SimonRit** [comment]
Thanks @brynolf. I have been actively working on a new RTK release compatible with ITK 5.4, it should be done in the coming days. Until then, you can download wheels compiled by the actions [here](https://github.com/RTKConsortium/RTK/actions/runs/9384976262) for non-cuda and [here](https://github.com/RTKConsortium/RTK/actions/runs/9413298830) for cuda (see artifacts at the bottom of the page which are visible only if you're logged in GitHub). I had to fix a few things on the RTK packaging (among which, compatibility with Cuda 12.1!), hence the delay after ITK's release (which has not been announced officially yet).

**Comment by PatrikBrynolfsson** [comment]
Thanks for the update! Looking forward to using it.

**Comment by thewtex** [comment]
[`itk-rtk` 2.6.0](https://pypi.org/project/itk-rtk/#history) for `itk-5.4.0` is now available.
