### ISSUE TITLE
Wrapping of member functions that are passed and/or return std:string goes wonky

### ISSUE THREAD

**Issue by aylward** [InsightSoftwareConsortium/ITK#4779]
The issues are demonstrated in https://github.com/InsightSoftwareConsortium/ITK/pull/4776

1) SWIG seems to be converting some member functions that are passed two std::strings as args to new versions of functions that returns a std::string * (rather than returning a void as defined by the C++ code). 

This documentation, though old, might be relevant...
https://www.swig.org/Doc1.3/Arguments.html#Arguments_nn2

That documented feature would cause a function in C++ that returns a void to wrap to a python function that returns a value - hence causing the SetTagValueString to appear to return a value in python.

2) Additionally,  SWIG converts return by value to return by pointer:
https://www.swig.org/Doc1.3/SWIG.html#SWIG_nn23 

So,  that is where the std::string * references are coming from.

**Summary**

I suspect there is a bug in our SWIG wrapping specification for these reasons and because new SWIG should handled std::string fine and these wonkynesses shouldn't be happening.

**Comment by N-Dekker** [comment]
Just wondering, should there be a `%include "std_string.i"` somewhere, that might be missing? Looking at https://www.swig.org/Doc2.0/Library.html#Library_std_string

**Comment by thewtex** [comment]
I think we generally want to avoid the use of `std::string *` in favor of `std::string` and `std::string_view`.

**Comment by N-Dekker** [comment]
I would like to see a minimal example where `f1(const std::string&)` would "swig properly", while `f2(const std::string&, const std::string&)` would go wrong. Actually I would like to try it myself, but not today anymore 🤷

**Comment by blowekamp** [comment]
I tired compiling with wrapping enabled and ran into issue with the precompiled binaries on Mac ARM: 
https://github.com/CastXML/CastXMLSuperbuild/issues/62

**Comment by blowekamp** [comment]
@aylward In itkSpatialObjectProperty.i I see the following:
```
%apply (std::string& INOUT) { std::string & value};
```

Which apply some "funky" input output with then string reference parameter is "value".

This likely is generated from the following code block:
https://github.com/InsightSoftwareConsortium/ITK/blob/e93fa19d909ef06982d8d25b347d575a1911aee9/Wrapping/Generators/SwigInterface/igenerator.py#L1597-L1611

I conjecture the following line is causing this additional "apply" to corrupt the behavior of the other "string" parameter:

```
 GetTagStringValue(const std::string & tag, std::string & value) const;
```

If this signature is needed, name the parameter something like "inout_value".

Additionally I recommend return values be "std::string" and input arguments be "const std::string &".  There is not current wrapping enabled/tested for "string_value".

**Comment by aylward** [comment]
Outstanding!   I will create a PR to start testing this.

Since we're moving towards ITK 6.0, I will break backward compatibility in ITKSpatialObjects, and update its API to use Get/SetMacros and appropriate variable types (e.g., no double * variables).   I'll follow you suggestion of return by value and pass by const reference.

Thanks!!!

**Comment by N-Dekker** [comment]
> In itkSpatialObjectProperty.i I see the following:
> ```
> %apply (std::string& INOUT) { std::string & value};
> ```

I'm glad to see you found the source of this issue, @blowekamp This commit appears to have introduced this behavior: 32df266d631b5def4e9dc5baca468c7d98ed4acb _"ENH: Allow to use methods which pass std::string by reference from python"_, Michka Popoff (@iMichka), Jun 28, 2014.  Saying:


> See ITK-3285.
> 
> Adding the following line for each argument in the .i files lets swig know what to do
with std::string when passed by reference:
%apply (std::string& INOUT) { std::string & variableName )
>
> See the test for the syntax in python.

Is the old bug report ITK-3285 still available somewhere? Given that the bug report (ITK-3285) and the commit are both more than 10 years old, is this `%apply` thing still necessary nowadays?

**Comment by dzenanz** [comment]
@hjmjohnson @thewtex is the old ITK JIRA still available somewhere?
