### ISSUE TITLE
FEM tests failing due to missing parameters

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#4782]
Multiple tests are failing due to missing parameters. Example:
```log
Missing parameters.
Usage: itkFEMElement3DTest inputFileName
```

### Description

Failing tests:

- itkFEMC0HexahedralElement-GravityLoad-BCs
- itkFEMC0HexahedralElement-NodalLoads-BCs
- itkFEMC0HexahedralElement-NoLoads
- itkFEMC0TetrahedralElement-GravityLoad-BCs
- itkFEMC0TetrahedralElement-NodalLoads-BCs
- itkFEMC0TetrahedralElement-NoLoads
- itkImageToRectilinearFEMObjectFilter2DTest
- itkImageToRectilinearFEMObjectFilter3DTest

More details here: https://open.cdash.org/viewTest.php?onlyfailed&buildid=9768301. This link will go stale within a few months, but it comes from Build Name: Windows11-VS22x64-RelWithDebInfo-Favorite-Remotes.

This was probably caused by some test refactoring, because FEM modules are disabled by default.

**Comment by jhlegarreta** [comment]
Issue #4417 is slightly related to this.

**Comment by jhlegarreta** [comment]
PR #4787 fixed:
- [x] itkFEMC0HexahedralElement-GravityLoad-BCs
- [x] itkFEMC0HexahedralElement-NodalLoads-BCs
- [x] itkFEMC0HexahedralElement-NoLoads
- [x] itkFEMC0TetrahedralElement-GravityLoad-BCs
- [x] itkFEMC0TetrahedralElement-NodalLoads-BCs
- [x] itkFEMC0TetrahedralElement-NoLoads

Remaining:
- [ ] itkImageToRectilinearFEMObjectFilter2DTest
- [ ] itkImageToRectilinearFEMObjectFilter3DTest

https://open.cdash.org/viewTest.php?buildid=9782964&onlyfailed
