### ISSUE TITLE
Error building version 5.4rc04 universal libraries on macOS

### ISSUE THREAD

**Issue by bettar** [InsightSoftwareConsortium/ITK#4880]
### Description

Error building ITK version 5.4rc04 universal libraries on macOS
I am building on a mac mini with an arm64 CPU (Apple Silicon)

The same make command

- works for version 5.2.1 universal
- works for version 5.4rc04 arm64
- fails for version 5.4rc04 universal

it's configured with the parameters:

```
-D CMAKE_OSX_ARCHITECTURES="x86_64;arm64"
-D Module_ITKZLIB=OFF
```

### Steps to Reproduce

1. configure on an arm64 machine, with

`cmake '-GUnix Makefiles' -D CMAKE_INSTALL_PREFIX=~/Documents/projects/install/InsightToolkit-5.4rc04 -D 'CMAKE_OSX_ARCHITECTURES=x86_64;arm64' -D CMAKE_BUILD_TYPE=Release -D CMAKE_OSX_DEPLOYMENT_TARGET=10.14 -D BUILD_SHARED_LIBS=OFF -D BUILD_TESTING=OFF -D BUILD_EXAMPLES=OFF -D Module_ITKOpenJPEG=OFF -D Module_ITKZLIB=OFF -D ZLIBNG_ENABLE_TESTS=OFF -D Module_ITKVtkGlue=ON -D VTK_DIR=~/Documents/projects/install/VTK-9.3.1/lib/cmake/vtk-9.3 -D 'CMAKE_CXX_FLAGS= -stdlib=libc++ -std=gnu++17' ~/Downloads/source/InsightToolkit-5.4rc04`

2. run `make`

### Expected behavior

`make` should complete without errors

### Actual behavior

the error message is about ZLIB (which I am setting to OFF anyway)

```none
[ 35%] Building C object Modules/ThirdParty/ZLIB/src/itkzlib-ng/CMakeFiles/zlib.dir/arch/x86/x86_features.c.o
cd ~/Documents/temp/build/InsightToolkit-5.4rc04-mk/Release/Modules/ThirdParty/ZLIB/src/itkzlib-ng && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DHAVE_ALIGNED_ALLOC -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DHAVE_POSIX_MEMALIGN -DHAVE_SYS_SDT_H -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DWITH_GZFILEOP -DX86_FEATURES -DZLIB_COMPAT -I~/Documents/temp/build/InsightToolkit-5.4rc04-mk/Release/Modules/ThirdParty/ZLIB/src -I~/Documents/temp/build/InsightToolkit-5.4rc04-mk/Release/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I~/Downloads/source/InsightToolkit-5.4rc04/Modules/ThirdParty/ZLIB/src -I~/Downloads/source/InsightToolkit-5.4rc04/Modules/ThirdParty/ZLIB/src/itkzlib-ng -Wno-uninitialized -Wno-unused-parameter -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -Wno-strict-overflow  -w -O2 -DNDEBUG -std=c11 -arch x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -mmacosx-version-min=10.14 -fPIC -Wall -MD -MT Modules/ThirdParty/ZLIB/src/itkzlib-ng/CMakeFiles/zlib.dir/arch/x86/x86_features.c.o -MF CMakeFiles/zlib.dir/arch/x86/x86_features.c.o.d -o CMakeFiles/zlib.dir/arch/x86/x86_features.c.o -c ~/Downloads/source/InsightToolkit-5.4rc04/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/x86_features.c
In file included from ~/Downloads/source/InsightToolkit-5.4rc04/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/x86_features.c:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include/cpuid.h:14:2: error: this header is for x86 only
   14 | #error this header is for x86 only
```

### Reproducibility

100%

### Versions

```
ITK_VERSION_MAJOR 5
ITK_VERSION_MINOR 4
ITK_VERSION_PATCH 0
```

### Environment

CPU Apple M2 Pro
macOS Sequoia 15.0.1
Xcode 16.0
CMake 3.30.5

### Additional

Is there any way of specifying my own custom built ZLIB?

**Comment by dzenanz** [comment]
Turn on CMake option `ITK_USE_SYSTEM_ZLIB`?

**Comment by bettar** [comment]
> Turn on CMake option `ITK_USE_SYSTEM_ZLIB`?

Yes, that's what I did, but that only is not enough, I also needed to specify CMake options `ZLIB_INCLUDE_DIR` and `ZLIB_LIBRARY_RELEASE` with my own custom locations, and finally I could build ITK successfully as universal libraries.

**Comment by seanm** [comment]
You can point to the macOS-provided zlib with something like:

```
ITK_USE_SYSTEM_ZLIB=1
ZLIB_INCLUDE_DIR="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include")
ZLIB_LIBRARY_DEBUG="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libz.tbd"
ZLIB_LIBRARY_RELEASE="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libz.tbd"
```
