### ISSUE TITLE
Generate panoramic view

### ISSUE THREAD

**Issue by jiaomei222** [InsightSoftwareConsortium/ITK#4947]
I have a curve including sample points, how to generate a panorama from CBCT based on that curve?

**Comment by dzenanz** [comment]
I am not sure whether there is an ITK implementation of it, but it [can be done in Slicer](https://discourse.slicer.org/t/generating-panoramic-radiograph-from-ct-data/10124), and [this repo](https://github.com/Heegu94/CT2Pano/blob/master/10_arc_slice.ipynb) is top google code result.

**Comment by hjmjohnson** [comment]
Thanks @dzenanz  for giving the Slicer reference.
