### ISSUE TITLE
Update libtiff v4.7.0

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#4953]
The third-party libtiff is rather old and out dated.

**Comment by blowekamp** [comment]
@dzenanz  The current `ITK/Modules/ThirdParty/TIFF` does not have a sub-tree. How does one initialize using sub-trees and the UpdateFromUpstream infrastructure?

**Comment by dzenanz** [comment]
For vanilla initializing subtrees: add a remote of the library you want to add (libtiff), fetch, then merge with main repository.

For starting a new subtree using UpdateFromUpstream infrastructure: I don't know, I have never done that. I have only made changes to existing third-party libaries and their update scripts.

@bradking should be able to advise, or maybe even get it started for us?

**Comment by blowekamp** [comment]
For reference this was the last update to the library:
54c790a509c33b3ee176ae5bfef7292d959c3c30

There are a lot of upstream changes, and not many local changes. So starting with a fresh upstream is reasonable IMHO.

**Comment by bradking** [comment]
I'll take a look at importing a new tiff.

**Comment by dzenanz** [comment]
Linking some related and possibly related issues:
#4777
#2959
#4102

**Comment by bradking** [comment]
As a first step, #4957 rebuilds the existing tiff 4.0.3 import with our modern history structure.  That will make the update to a newer tiff version much easier.

**Comment by hjmjohnson** [comment]
FYI:  Initial 10-minute attempt to update to v4.7.0.    I don't have time to continue working on this at the moment.

Some file names have changed, so we need to update the updater script.

[0001-ENH-Update-to-latest-v4.7.0-libtiff-codebase.patch](https://github.com/user-attachments/files/17802399/0001-ENH-Update-to-latest-v4.7.0-libtiff-codebase.patch)

**Comment by blowekamp** [comment]
> FYI: Initial 10-minute attempt to update to v4.7.0. I don't have time to continue working on this at the moment.
> 
> Some file names have changed, so we need to update the updater script.
> 
> [0001-ENH-Update-to-latest-v4.7.0-libtiff-codebase.patch](https://github.com/user-attachments/files/17802399/0001-ENH-Update-to-latest-v4.7.0-libtiff-codebase.patch)

Yes, lots of changes have happened in the last 10 year. They also add CMake instrastructure. I had not had the change to determine if it was usable or not yet.

**Comment by bradking** [comment]
For reference, VTK has imported tiff 4.6.0 and uses the upstream's CMake code with some patches.

**Comment by blowekamp** [comment]
These look like the changes VTK made:
https://gitlab.kitware.com/third-party/tiff/-/compare/v4.6.0...for%2Fvtk-20231025-4.6.0?page=2&straight=true

It appears VTK make their third party changes in a separate repository,  then form the sub-tree via a script which is then merged into the main-line of the VTK repo.

**Comment by blowekamp** [comment]
> Yes, VTK's approach has the advantage that the changes from upstream are recorded independently from VTK. It has the disadvantage that an extra repository is needed with VTK-specific tags.
> 
> With the tiff 4.0.3 re-import done, I'll move on to an actual update in ITK.

Awesome, I just started to make changes in to libtiff library to get it to configure, but I'll leave it to you!

**Comment by bradking** [comment]
@blowekamp I don't know how soon I'll be able to get to it, so if you've made progress, go ahead and continue.  I can help structure the history once you have something working.

**Comment by blowekamp** [comment]
After merge of #4961, there are some build issues when DCMTK in enabled that I am investigating.

**Comment by blowekamp** [comment]
itktiff has been updated to 4.7.0.
