### ISSUE TITLE
release-4.13: Windows Python test  module 'itk' has no attribute 'FlatStructuringElement'

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#496]
As [discussed on Discourse](https://discourse.itk.org/t/patches-for-itk-4-13-2/1582/3):

Windows Python tests on the `release-4.13` branch are failing with:

```
Loading ITKPyBase... done
Loading ITKCommon... done
Loading ITKIOImageBase... done
Loading ITKPyUtils... done
Traceback (most recent call last):
  File "BoxGrayscaleDilateImageFilter.py", line 32, in <module>
    kernel = itk.FlatStructuringElement[dim].Box(5)
  File "D:\a\1\s-build\Wrapping\Generators\Python\itkLazy.py", line 40, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'FlatStructuringElement'
itkTestDriver: Process exited with return value: 1
```

https://open.cdash.org/buildSummary.php?buildid=5742715

https://open.cdash.org/testDetails.php?test=697259646&build=5742715

**Comment by fbudin69500** [comment]
I cannot reproduce that locally. I compiled ITK release-4.13 on Windows, with VS2017, MinSizeRel, with Python ON and all the Python tests passed.
