### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'itkjpeg12.lib' in user projects

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#5021]
This happens when another project is building against ITK.

### Steps to Reproduce

1. Configure and build ITK
2. Configure a project using ITK (a remote module such as https://github.com/InsightSoftwareConsortium/ITKFPFH will do)
3. Try to build it - it runs into `LINK : fatal error LNK1104: cannot open file 'itkjpeg12.lib'`

### Reproducibility

100% on my Windows machine. I first noticed it in an incremental build, and confirmed it in a clean build.

### Versions

It started with PR #4979. Latest good commit is 6a704aaadef717113aa80e7e021c408c086b3677.

### Environment

Fully updated Windows 11 x64 version 24H2, with fully updated Visual Studio 2022, and CMake 3.31.1.

**Comment by blowekamp** [comment]
The problem is likely related to these lines:
https://github.com/InsightSoftwareConsortium/ITK/blob/948e77ae7da6395aaa42ed274b1c5eb8dde22c68/Modules/ThirdParty/JPEG/src/itkjpeg-turbo/CMakeLists.txt#L131-L143

Perhaps the commented out lines are needed.

**Comment by dzenanz** [comment]
Uncommenting [lines 134 and 135](https://github.com/InsightSoftwareConsortium/ITK/blob/948e77ae7da6395aaa42ed274b1c5eb8dde22c68/Modules/ThirdParty/JPEG/src/itkjpeg-turbo/CMakeLists.txt#L134-L135) unfortunately does not help.

**Comment by dzenanz** [comment]
I just confirmed this happens with Ubuntu 22.04, cmake version 3.30.2, gcc 11.4.0.

**Comment by blowekamp** [comment]
I am looking into it. The itklibjpeg12 and itklibjpeg16 are created as "OBJECT" libraries. I am looking into the implications of that noq.

**Comment by dzenanz** [comment]
Fixed by 261b5054e03373c99abdd1452ce9170243587741 from #5029.
