### ISSUE TITLE
Create a 5.4.1 patch tag

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#5051]
Can we please consider doing a 4.5.1 patch tag?

I am encountering the [libtiff duplicate](https://github.com/InsightSoftwareConsortium/ITK/pull/4958) symbol issues in a few builds. This has been patched in the release branch. Additionally it fixes some race conditions and other build issues. Additionally there are some typedefs for forwards compatibility.

This would allow an official SimpleITK release against a tag and to update the conda-forge version of ITK to a tag that is more robustly building.

**Comment by dzenanz** [comment]
I second this. It is also useful for remote modules which want to build with legacy off, e.g. https://github.com/InsightSoftwareConsortium/ITKMontage/pull/234.

**Comment by dzenanz** [comment]
Of course, we should consider whether we want to add any other patches to release branch before tagging it.

**Comment by thewtex** [comment]
Yes. I will work on a v5.4.1 tag tomorrow.

@InsightSoftwareConsortium/community please create PR's for any patches for ITK 5.4.1 to the `release-5.4` branch today, and for 5.4.2 over the coming weeks.

**Comment by thewtex** [comment]
@N-Dekker thanks for the note!

Done: https://github.com/InsightSoftwareConsortium/ITK/commit/ef7521d2bd9e17839a54c88fb394241e4c37e749

**Comment by dzenanz** [comment]
@blowekamp should 6336380f3253b7e60ecee7f50957ee3ae25a489c be included?

**Comment by blowekamp** [comment]
> @blowekamp should [6336380](https://github.com/InsightSoftwareConsortium/ITK/commit/6336380f3253b7e60ecee7f50957ee3ae25a489c) be included?

No, that was after the libtiff update.

**Comment by dzenanz** [comment]
I don't have anything else to nominate.

**Comment by blowekamp** [comment]
We already have a patch to suppress some TIFF warnings in the release branch. That patch that remove the DICOM monochrome warnings should also be considered:
d29cca5b2e6421181c27e84051bb9a2cf813a024

While training with large datasets I have seen this warnings 100k of times.

**Comment by thewtex** [comment]
@blowekamp :+1: added.

**Comment by thewtex** [comment]
Tag: https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.4.1

**Comment by jamesobutler** [comment]
Looks like the tag unfortunately is a commit title detailing 5.3.1(https://github.com/InsightSoftwareConsortium/ITK/commit/016fd31396836319285cf86389f7e330767b2b65) although the code defines the version as 5.4.1. Unclear if that is something that can be fixed.
![{3CDE1D67-AF37-4F2C-A1A5-52EDC2FEA7EE}](https://github.com/user-attachments/assets/6a7d39ea-800c-4e6a-8d2b-a2995be31666)

**Comment by thewtex** [comment]
@jamesobutler Yes, there is an error in that commit message, but the tag is correct. We cannot change the content of a commit after it mas been merged.

**Comment by thewtex** [comment]
I will follow-up in a different issue on the other release items.

**Comment by blowekamp** [comment]
@thewtex Should we do a complete 5.3.2 tag with the other critical bug fixes added right after the 5.3.1 tag?

**Comment by thewtex** [comment]
@blowekamp yes, done: https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.4.2

**Comment by N-Dekker** [comment]
@thewtex Can you please also make a v6.0a02 tag that includes those critical bug fixes? The first v6.0 alpha ([v6.0a01](https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v6.0a01)) basically appears unusable because it does not yet have the fix for those TIFF link errors (issue #4820).

**Comment by thewtex** [comment]
@N-Dekker yes :+1: tag: https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v6.0a02

**Comment by N-Dekker** [comment]
Thanks Matt! I'm now trying out elastix + ITK v6.0a02 at the SuperElastix CI: https://github.com/SuperElastix/elastix/tree/Require-ITK-6
