### ISSUE TITLE
ITK build failed due to error C2244 on MSVC + permissive- on windows

### ISSUE THREAD

**Issue by QuellaZhang** [InsightSoftwareConsortium/ITK#506]
ITK failed when build with /permissive- by msvc on Windows, I use latset version 4773ca0 on master branch. Could you please help look at this?

**You can repro this issue as the steps below:**
1. git clone http://itk.org/ITK.git D:\ITK\src
2. open VS2017 x86 command prompt as admin and browse to D:\ITK
3. set CL=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /permissive- /Zc:twoPhase-
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

**Failures:**
```
ITKCommonHeaderTest1.cxx
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): error C2244: 'itk::VectorContainer<TElementIdentifier,TElement>::ElementAt': unable to match function definition to an existing declaration
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(37): note: see declaration of 'itk::VectorContainer<TElementIdentifier,TElement>::ElementAt'
::ElementAt(ElementIdentifier id)
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): note: definition
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): note: 'VectorContainer<TElementIdentifier,TElement>::reference itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier)'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): note: existing declarations
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): note: 'const _Ty &itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier) const'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(38,1): note: '_Ty &itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier)'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): error C2244: 'itk::VectorContainer<TElementIdentifier,TElement>::ElementAt': unable to match function definition to an existing declaration
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(52): note: see declaration of 'itk::VectorContainer<TElementIdentifier,TElement>::ElementAt'
::ElementAt(ElementIdentifier id) const
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): note: definition
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): note: 'VectorContainer<TElementIdentifier,TElement>::const_reference itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier) const'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): note: existing declarations
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): note: 'const _Ty &itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier) const'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(53,1): note: '_Ty &itk::VectorContainer<TElementIdentifier,TElement>::ElementAt(TElementIdentifier)'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(69,1): error C2244: 'itk::VectorContainer<TElementIdentifier,TElement>::CreateElementAt': unable to match function definition to an existing declaration
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(68): note: see declaration of 'itk::VectorContainer<TElementIdentifier,TElement>::CreateElementAt'
::CreateElementAt(ElementIdentifier id)
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(69,1): note: definition
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(69,1): note: 'VectorContainer<TElementIdentifier,TElement>::reference itk::VectorContainer<TElementIdentifier,TElement>::CreateElementAt(TElementIdentifier)'
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(69,1): note: existing declarations
{
^
D:\ITK\src\Modules\Core\Common\include\itkVectorContainer.hxx(69,1): note: '_Ty &itk::VectorContainer<TElementIdentifier,TElement>::CreateElementAt(TElementIdentifier)'
{
^
```

**Comment by N-Dekker** [comment]
Thanks @QuellaZhang I'm preparing a possible fix now  `:-)`

**Comment by N-Dekker** [comment]
@QuellaZhang Please check my proposed fix: https://github.com/InsightSoftwareConsortium/ITK/pull/507

**Comment by QuellaZhang** [comment]
@N-Dekker Thank you. Verified that your fix works, ITK passed under /permissive- mode when building on MSVC.

**Comment by N-Dekker** [comment]
Thanks for verifying, @QuellaZhang 

@phcerdan asked at https://github.com/InsightSoftwareConsortium/ITK/pull/507#issuecomment-463851297

> is there any difference on the type with this? Or is just a "workaround" for keeping happy MSVC?

Do you possibly have an answer?

**Comment by N-Dekker** [comment]
Looks like this is a minimal example:

    template <typename T>
    struct Vector
    {
      using NestedType = int;
    };

    template <typename T>
    class Container: public Vector<T>
    {
        using typename Vector<T>::NestedType;
        NestedType Get();
    };

    template <typename T>
    typename Container<T>::NestedType Container<T>::Get()
    {
        return 42;
    }

    int main() { }

VS2017 compiler output:

> F:\X\Src\MyProject>cl c.cpp /permissive-
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
>
> c.cpp
> c.cpp(18): error C2244: 'Container<T>::Get': unable to match function definition to an existing declaration
> c.cpp(17): note: see declaration of 'Container<T>::Get'
> c.cpp(18): note: definition
> c.cpp(18): note: 'Container<T>::NestedType Container<T>::Get(void)'
> c.cpp(18): note: existing declarations
> c.cpp(18): note: 'int Container<T>::Get(void)'
>

**Comment by QuellaZhang** [comment]
I am confirming with relevant personnel now.

**Comment by QuellaZhang** [comment]
@N-Dekker. Sorry for misleading, this is a problem with MSVC. Can you go back to the original source code? Sorry again.

**Comment by dzenanz** [comment]
Going back to original source code is extra effort, and the change @N-Dekker made might have silenced another warning on Red Hat. Is it a problem if source code stays as it is?

**Comment by QuellaZhang** [comment]
Hi, @dzenanz, I verified whether it's the latest or the original source code, we can get a clean build of ITK.
