### ISSUE TITLE
ITK Python with MSVC++ in debug

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#508]
ITK compiles fine with MSVC++ in Debug mode, but the Python tests are failing.

One line of code that can be improved to help with this issue is [this one](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/CMakeLists.txt#L531) since currently at link time, it always uses the Release Python library. CMake Generator Expressions could be used to correct this. However, this is not enough to make the Python tests successfully pass.

**Comment by fbudin69500** [comment]
The CMake file linked above could be improve by using the following code:

itk_target_link_libraries_with_dynamic_lookup(${lib} LINK_PUBLIC $<$<CONFIG:Debug>:${PYTHON_DEBUG_LIBRARY}>$<$<CONFIG:Release>:${PYTHON_LIBRARY}>)

**Comment by blowekamp** [comment]
PYTHONG_DEBUG_LIBRARY is deprecated. Consider this more modern signature:
```
target_link_libraries(<target> LINK_INTERFACE_LIBRARIES [[debug|optimized|general] <lib>] ...)
```
and the following:
https://github.com/Kitware/CMake/blob/master/Modules/FindPythonLibs.cmake#L215-L217
