### ISSUE TITLE
snake case functions are erased when re-running cmake

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#515]
When a developer configures ITK with cmake, the Python Config files for each modules are created. During compilation, these files are appended with the list of snake case functions that the module contains. However, if the developer runs cmake again, the module files are re-generated, and the list of snake_case functions are erased. When trying to recompile ITK with `make` or `ninja` to recreate the complete Config files including the list of snake_case functions, nothing happens.

The current work around is to manually erase some files such as deleting the `Wrapping` folder in the build tree.

**Comment by hjmjohnson** [comment]
This problem seems to still persist, and it makes debugging or improving the python code extremely difficult.

**Comment by hjmjohnson** [comment]
Files in ITK-bld/Wrapping/Generators/Python/Configuration/*Config.py are not written correctly after some reruns of cmake.

![Uploading image.png…]()

**Comment by hjmjohnson** [comment]
![image](https://user-images.githubusercontent.com/313970/95804493-6dcbd700-0cc8-11eb-9ad5-106b7fe70408.png)
