### ISSUE TITLE
Investigate "Mesh: Compacting Memory Management for C/C++ Applications"

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#518]
https://arxiv.org/abs/1902.04738v1

**Comment by gdevenyi** [comment]
https://github.com/plasma-umass/mesh

**Comment by phcerdan** [comment]
This article was mentioned in cpp reddit channel too: https://www.reddit.com/r/cpp/comments/arhfnw/mesh_compacting_memory_management_for_cc/

**Comment by gdevenyi** [comment]
Found via hackernews thread :)
https://news.ycombinator.com/item?id=19182779
