### ISSUE TITLE
Example to use VectorImage in python

### ISSUE THREAD

**Issue by juanprietob** [InsightSoftwareConsortium/ITK#548]
### Description

An example of how to read and write an Image with an unknown number of Components will be great. The VectorImage is wrapped in itk python and it works great but there is no usage example. 

### Expected behavior

An example at the ITKExamples would be great. 

### Actual behavior

There is no example of this feature. 

### Additional Information

```
Dimension = 3
ComponentType = itk.ctype('float')
OutputImageType = itk.VectorImage[ComponentType, Dimension]

out_img = OutputImageType.New()
out_img.SetNumberOfComponentsPerPixel(40)

size = itk.Size[Dimension]()
size.Fill(64)

index = itk.Index[Dimension]()
index.Fill(0)

RegionType = itk.ImageRegion[Dimension]
region = RegionType()
region.SetIndex(index)
region.SetSize(size)

out_img.SetRegions(region)
out_img.SetDirection(img.GetDirection())
out_img.SetOrigin(img.GetOrigin())
out_img.SetSpacing(img.GetSpacing())
out_img.Allocate()
```

**Comment by thewtex** [comment]
Transferred to https://github.com/InsightSoftwareConsortium/ITKExamples/issues/121
