### ISSUE TITLE
Eigen3_DIR_INSTALL path

### ISSUE THREAD

**Issue by adigherman** [InsightSoftwareConsortium/ITK#566]
### Description
Issue manifests when trying to build/test the [ANTsRCore](https://github.com/ANTsX/ANTsRCore) package in a Travis CI environment using a binary version of [ITKR](https://github.com/stnava/ITKR).  During the ITKR build, ITK is built using `R CMD check` in a temporary folder used to check the package and build the binary, and `Eigen3_DIR_INSTALL` in the `ITKEigen3.cmake` file will point to that temp folder. 
Subsequent Travis CI ITKR binary installs will place the package into `/home/travis/R/Library/ITKR` folder so the correct path to the `Eigen3_DIR_INSTALL` should be 
- `/home/travis/R/Library/ITKR/libs/lib/cmake/ITK-5.0/Modules/` 

and not 
- `/home/travis/build/neuroconductor-devel/ITKR/ITKR.Rcheck/00_pkg_src/ITKR/src/itkb/lib/cmake/ITK-5.0/Modules`

### Steps to Reproduce

1. Create ITKR binary
2. Start ANTsRcore testing on Travis CI using the ITKR binary from step 1

Fail log example: https://travis-ci.com/neuroconductor-devel/ANTsRCore/jobs/182411570

The EIGEN3 issue is also referenced here: https://github.com/InsightSoftwareConsortium/ITK/pull/562

@muschellij2 @stnava

**Comment by phcerdan** [comment]
Thanks for reporting, the fix provided in #562 should deal with this.

**Comment by phcerdan** [comment]
PR opened just targeting the Eigen3 fix here: #567
