### ISSUE TITLE
Feature Request: Integrate Intel TBB download/build into Module_ITKTBB

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#575]
Currently, Module_ITKTBB is configured to support the binary distribution of TBB, however, on many HPC, they do not want to use binaries and would rather support custom compiled packages optimized for the architectures and special compilers.

Unfortunately, the current TBB source releases don't provide a canned method to compile the package and generate the required TBBConfig.cmake file.

If ITK were to switch to using this method:
https://github.com/01org/tbb/tree/tbb_2019/cmake#source-code-integration-of-intel-tbb-to-the-sub-string-finder-sample-linux-os

Then, when enabled Module_ITKBB would build TBB using the same configuration that ITK is using.

**Comment by gdevenyi** [comment]
This would of course require a submodule or similar configuration so that Module_ITKBB also downloads the package first.

**Comment by dzenanz** [comment]
I was under the impression that you could download TBB sources, configure and build using CMake, and then point ITK's `TBB_DIR` to your custom compiled TBB. Is this not so?

Also, @blowekamp started a [patch](https://review.source.kitware.com/%23/c/23436/) to download TBB binaries during ITK configure/build process. That might be of interest to you.

**Comment by hjmjohnson** [comment]
> `TBB_DIR` to your custom compiled TBB. Is this not so?

NO!  Not even close.  TBB build system is a raw makefile, wrapped in python, with a cmake cleanup post-processing nightmare.  I have begged them to improve the processes, and have made a little progress.

see: https://github.com/BRAINSia/BRAINSTools/blob/fix-tbb-bld/SuperBuild/build_tbb.sh

for details that only works with changes that have recently been worked on, and hopefully incorporated in the next release of TBB.
