### ISSUE TITLE
Investigate Interprocedural Optimization / Link Time Code Generation for Python binaries

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#58]
### Description

Investigate enabling Interprocedural Optimization / Link Time Code Generation for the Python binaries / C-extensions.

There is a CMake `CheckIPOSupported` module to help with this.

See the discussion here:

  https://gitlab.kitware.com/cmake/cmake/issues/17720

CC: @N-Dekker

**Comment by thewtex** [comment]
xref #531

**Comment by thewtex** [comment]
ping

**Comment by N-Dekker** [comment]
Just double-checked: CMake 3.x has always supported the flag `INTERPROCEDURAL_OPTIMIZATION` (IPO) for various compilers, but MSVC support was just introduced by CMake 3.13 (my CMake merge request https://gitlab.kitware.com/cmake/cmake/merge_requests/2363 )

I would suggest to only enable IPO for release builds:

    set_property(TARGET <target> PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)

**Comment by thewtex** [comment]
poke
