### ISSUE TITLE
Update Azure ITK.Coverage yaml path

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#581]
The Azure build "ITK.Coverage" needs to e updated to the changed yaml file name: `AzurePipelinesBatch.yml`. The file was renamed to reflect that the job(s) are done in batch mode on a rolling build basis. Other rolling builds could be added here.

**Comment by blowekamp** [comment]
@thewtex Can you please look at this, and change the file name in azure pipelines. 

Thanks!

**Comment by thewtex** [comment]
I will take a look at this tomorrow.

**Comment by thewtex** [comment]
All set: https://dev.azure.com/itkrobotbatch/ITK.Coverage/_build/results?buildId=1
