### ISSUE TITLE
itkThresholdImageFilter result differs when employing streaming

### ISSUE THREAD

**Issue by romangrothausmann** [InsightSoftwareConsortium/ITK#586]
### Description

Results of `itkThresholdImageFilter` differ significantly with and without streaming for same input.

### Steps to Reproduce

Tested with https://github.com/romangrothausmann/ITK-CLIs/blob/556423bf4c04c4bcd60a3bd420bb3df0c7d2fe65/thresh-erase.cxx
and
https://github.com/romangrothausmann/ITK-CLIs/blob/556423bf4c04c4bcd60a3bd420bb3df0c7d2fe65/.gitlab-ci.yml#L81-L89

### Expected behavior

Independent of streaming, both version `thresh-erase` and `thresh-erase_SDI` should lead to the same result if the same input file is used.

### Actual behavior

Result of `thresh-erase` is correct (Min: -0.499998 Max: 0.499997): https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/177668140
Result of  `thresh-erase_SDI` is wrong (Min: 0 Max: 255): https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/177668142

### Reproducibility

100%

### Versions

ITK master (b2884129bf6db53c) (https://github.com/romangrothausmann/ITK-CLIs/blob/556423bf4c04c4bcd60a3bd420bb3df0c7d2fe65/Dockerfile#L23)

### Environment

ubuntu:16.04: https://github.com/romangrothausmann/ITK-CLIs/blob/556423bf4c04c4bcd60a3bd420bb3df0c7d2fe65/Dockerfile

**Comment by maekclena** [comment]
In your [`CMakeLists.txt`](https://github.com/romangrothausmann/ITK-CLIs/blob/master/CMakeLists.txt#L338), you use `thresh-glob.cxx` as the source for the `thresh-erase_SDI` executable, which I imagine is a copy-paste mistake. Since it uses a `BinaryThresholdImageFilter` it explains why the output is binary.

**Comment by romangrothausmann** [comment]
Many thanks @maekclena for taking this close look, it was a copy-paste mistake, output as expected now:
https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/180281298
