### ISSUE TITLE
Latest release Tag

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#589]
On Github, the tag marked as latest release is v4.13.1. When looking at the README in the ITK Github repo, the badge indicates that the latest releasee is v4.13.1. I guess this should be changed to v4.13.2.

**Comment by gdevenyi** [comment]
v4.13.2 on releases page is lacking changelog and assets as well.

**Comment by thewtex** [comment]
v4.13.2 release is still in progress -- these will be addressed once the release is finalized.
