### ISSUE TITLE
GetImageFromArray bug with vector array input

### ISSUE THREAD

**Issue by zivy** [InsightSoftwareConsortium/ITK#592]
### Description

The isVector flag in the GetImageFromArray method seems to be ignored. 
The provided MWE reads an image, gets the numpy array and creates an image with the array. The created image should be the same as the one read from file.

### Steps to Reproduce
```
import itk

in_file_name = 'color_image.jpg'

img_itk = itk.imread(in_file_name)
print('Original number of components per pixel: ' + str(img_itk.GetNumberOfComponentsPerPixel()))

img_arr = itk.GetArrayFromImage(img_itk)
print('Numpy array shape: ' + str(img_arr.shape))

img_itk2 = itk.GetImageFromArray(img_arr, isVector=img_itk.GetNumberOfComponentsPerPixel()>1)
print('New number of components per pixel: ' + str(img_itk2.GetNumberOfComponentsPerPixel()))

```

### Reproducibility

Always

### Versions
ITK Python 4.13.2

### Environment
OSX, installed using pip though in an anaconda environment, python 3.7.

**Comment by thewtex** [comment]
@fbudin69500 has this been fixed in ITK 5?

**Comment by maekclena** [comment]
It works for me on master. Note that the parameter was renamed `is_vector`.

**Comment by fbudin69500** [comment]
I'll add a test to ensure that this does not get broken again. Thanks for testing!

**Comment by fbudin69500** [comment]
The bug was corrected in [this PR](https://github.com/InsightSoftwareConsortium/ITK/commit/93919369633d94cd4acbbd1040cbe8f3e6ccbca9) and a test was added then. Closing this PR. If you are still experiencing this issue with a recent version of ITK (past the commit I linked), please reopen the issue.
