### ISSUE TITLE
Is itk_compiler_detection.h still needed?

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#595]
I wonder about the usage of this file in ITK nowadays, seems more like a role for CMake to detect the compiler right?

I faced some issues running clang-tidy because this file, and made me wonder
```
 error: Unsupported compiler [clang-diagnostic-error]
#    error Unsupported compiler
```

I haven't look where or how this file is used really, just putting the thought out there for discussion. Pinging @hjmjohnson @thewtex

**Comment by hjmjohnson** [comment]
My guess is that you are compiling ITK with a compiler that is different than the one used by clang tidy.

For example, you use AppleClang for compiling ITK, then try to use llvm-clang (from clang-tidy) to build it a second time, the problem is that it assumes the two are not compatible.

**Comment by thewtex** [comment]
To discuss with CMake developers:

- Can / should be better error message?
- Do we need an exception for tools like clang-tidy?

**Comment by hjmjohnson** [comment]
@phcerdan Can you please confirm that if you build ITK with the clang associated with clang-tidy that this error does not happen.

The contents of "compile_commands.json" that clang-tidy is driven off of must be created with a compiler (from cmake ) that is compatible with clang-tidy.

Can you please close if this issue is corrected.

**Comment by mathstuf** [comment]
clang-tidy works just fine with gcc as a backing compiler. I'm seeing this error with this combination. Can this combination not be detected as an unknown compiler?

**Comment by mathstuf** [comment]
Note, this is with the `CMAKE_C_CLANG_TIDY` and `CMAKE_CXX_CLANG_TIDY` variables in CMake, not the method which uses `compile_commands.json`.

**Comment by mathstuf** [comment]
Ping @thewtex @hjmjohnson

**Comment by thewtex** [comment]
> clang-tidy works just fine with gcc as a backing compiler. I'm seeing this error with this combination. Can this combination not be detected as an unknown compiler?

:+1: sounds reasonable.
