### ISSUE TITLE
vcl_msvc_warnings.h is not installed with ITK 5.0 RC1

### ISSUE THREAD

**Issue by Siron777** [InsightSoftwareConsortium/ITK#602]
I have built ITK 5.0 RC 1 on visual studio 2017 15.9.7. When I build a project against the installation of this build, it does not find vcl_msvc_warnings.h. The header is present in the source of ITK, but not in the installation folder. It is the same with master of ITK.

Version 
5.0rc1, with RTK 2.0

Environment

Windows 10
Visual studio 2017 15.9.7
Compilation in 64 bits
Ninja
cmake command: cmake "D:/dev/library/source/ITK-5.0rc01" -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH=D:/dev/library/x86-64_msvc2017/itk/5.0_rc1 -DModule_RTK=ON -DRTK_BUILD_APPLICATIONS=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCUDA_TOOLKIT_ROOT_DIR=D:/dev/conan_c/Cuda/10.0/AI/extern/package/479e5c321685f6e20cbbf93c38ae334c54ade580

**Comment by Siron777** [comment]
It seems equally that MetaIO is not installed. I am missing all the headers for this library.  On one of the cmake file associated with metaIO, I can find itk_module_target(ITKMetaIO NO_INSTALL). Is it normal ?

**Comment by thewtex** [comment]
@Siron777 what is the header that depends on `vcl_msvc_warnings.h`? It may have been removed intentionally.

CC @hjmjohnson @dzenanz

**Comment by Siron777** [comment]
This is vnl_vector.h, which is installed:
```
#ifdef _MSC_VER
#  include <vcl_msvc_warnings.h>
#endif
```

**Comment by dzenanz** [comment]
Maybe `vnl_vector.h` needs an update? @hjmjohnson touched it last, I think.
