### ISSUE TITLE
Migrate the release notes from the Wiki to the repository

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#61]
Archive the release notes that were previously maintained on the Wiki:

https://itk.org/Wiki/ITK/Releases

in the folder `ITK/Documentation/ReleaseNotes`.  Convert these notes to Markdown.

In the future, we can add the notes as Markdown to the repository via pull request. Then, copy the notes to GitHub Releases, Discourse, and the ITK landing pages.

**Comment by thewtex** [comment]
@jcfr do you have any tips an conversion of the MediaWiki pages to Markdown?

**Comment by blowekamp** [comment]
Have you looked into [pandoc](https://pandoc.org)? That was use to migrant many wiki pages for SimpleITK to Sphinx or markdown.

**Comment by thewtex** [comment]
> Have you looked into pandoc?

Cool -- I will try that.

**Comment by jcfr** [comment]
Use of pandoc combined with https://github.com/jcfr/mwdoc allows to convert all release pages to markdown. Here is a notebook describing how to proceed: https://nbviewer.jupyter.org/github/jcfr/jupyter-notebooks/blob/master/19_ITK_Wiki_Release_notes.ipynb
