### ISSUE TITLE
ITK 5.0_rc1 fails to build with `multilib-strict check failed`

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#618]
This is a follow-up on my effort to version bump the available ITK version for Gentoo Linux, of which [the first issue was successfully solved by updating hdf5](https://github.com/InsightSoftwareConsortium/ITK/issues/572).

### Description
ITK fails to build

### Steps to Reproduce

`cmake --no-warn-unused-cli -C /var/tmp/portage/sci-libs/itk-5.0_rc1/work/itk-5.0_rc1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DITK_USE_SYSTEM_DCMTK=ON -DITK_USE_SYSTEM_DOUBLECONVERSION=ON -DITK_USE_SYSTEM_GCCXML=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SWIG=ON -DITK_USE_SYSTEM_TIFF=ON -DITK_USE_SYSTEM_ZLIB=ON -DITK_BUILD_DEFAULT_MODULES=ON -DITK_COMPUTER_MEMORY_SIZE=1 -DWRAP_ITK_JAVA=OFF -DWRAP_ITK_TCL=OFF -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DITK_USE_REVIEW=OFF -DITKV3_COMPATIBILITY=OFF -DITK_WRAP_PYTHON=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/itk-5.0_rc1/work/itk-5.0_rc1_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/itk-5.0_rc1/work/ITK-5.0rc01`

### Actual behavior

[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/2994966/build.log)

**Comment by thewtex** [comment]
@TheChymera thanks for the report.

**Comment by thewtex** [comment]
@TheChymera , if I interpret *build.log* correctly, if we change the installation from *usr/lib/libITKSpatialObjects-5.0.so.1* to *usr/lib64/libITKSpatialObjects-5.0.so.1*, e.g., the test will pass.

Is there a Gentoo Docker image and set of commands I can use to reproduce your build locally?

Side note, with ITK 5, a few updates to the CMake build options can be made:

- `-DITK_USE_SYSTEM_GCCXML=ON` -> `-DITK_USE_SYSTEM_CASTXML=ON` and install [CastXML](https://github.com/CastXML/CastXML).
- `-DITKV3_COMPATIBILITY=OFF` can be removed.
- `-G Unix Makefiles` -> `"-GUnix Makefiles"`
- `-DITK_USE_REVIEW=OFF` can be removed

**Comment by TheChymera** [comment]
If you can send me an ssh public key I can give you temporary access to one of our testing servers.

Are the itkv3 compatibility and review oprions fully disabled? i.e. will `=ON` also be meaningless?

**Comment by dzenanz** [comment]
ITKv3 compatibility is meaningless. `Review` module still exists, but most stuff has been taken out of it and put into other modules.

**Comment by thewtex** [comment]
@TheChymera here is my public key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXBMhWVWJDdkhquiKQmdIUZGs03ypSIx0REHypXBcVjtDdaE5EuNEfWXCT3hx3VtZSYTmDNt5g5xIUGuwFIy5bkxQJ+A3Wn2i1IDKDY5HwqTV74mNQa7917VLofh1q/T49QpKyy5yfejkDkLH5eYjKaTF2eWPOsPBz4dDatQ3lGYU2kyaP9ubLFlFs2ltJRER+T3jH+JRjOMFW4Zg9IrDRhcN3EBkbjqLIRQZYuOck8q4vijvmJBsayF84HG3Zh8s1otTBiXauYocPHJRkXn28wYR44GQCfcgRQMHfZT0P+HAdSI16ODMh4wdleVMxaPhhEke9b6bcEDqeVtnOml0D matt@ethan
```

I can also be reached to follow-up at matt.mccormick@kitware.com. Thanks!

**Comment by TheChymera** [comment]
@thewtex Hi, I set up the testing server for you but accidentally ended up fixing the issue while I was at it :D The solution was to set `ITK_INSTALL_LIBRARY_DIR`. Thank you all for your help.

There's still some other issues, but maybe best handled in a separate report.

**Comment by TheChymera** [comment]
if you would like to further help me with this, the next issue is here https://github.com/InsightSoftwareConsortium/ITK/issues/635
