### ISSUE TITLE
MetaIO headers are not installed by ITK 5.0 rc1

### ISSUE THREAD

**Issue by Siron777** [InsightSoftwareConsortium/ITK#619]
I have built ITK 5.0 RC 1 on visual studio 2017 15.9.7. When I build a project against the installation of this build, it does not find some headers related to MetaIO. The headers are present in the source of ITK, but not in the installation folder. Example of headers missing are metaObject.h and metaImage.h included in itkMetaImageIO.h.

Version
5.0rc1, with RTK 2.0

Environment

Windows 10
Visual studio 2017 15.9.7
Compilation in 64 bits
Ninja
cmake command: cmake "D:/dev/library/source/ITK-5.0rc01" -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH=D:/dev/library/x86-64_msvc2017/itk/5.0_rc1 -DModule_RTK=ON -DRTK_BUILD_APPLICATIONS=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCUDA_TOOLKIT_ROOT_DIR=D:/dev/conan_c/Cuda/10.0/AI/extern/package/479e5c321685f6e20cbbf93c38ae334c54ade580

**Comment by thewtex** [comment]
@Siron777 thanks for the report.
