### ISSUE TITLE
Feature Request: Add MD5/SHA* hashes for assets attached to releases

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#621]
My understanding is assets attached to a release are uploaded by the releasing party. It would beneficial for the release announcement if hashes of those files were also supplied.

**Comment by thewtex** [comment]
@gdevenyi Good idea. We will add this to the process for the next release.

**Comment by thewtex** [comment]
The process for generating the hashes is documented in #768
