### ISSUE TITLE
Clean up CMake options

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#622]
Some CMake settings are not marked as advanced, when they should be. And many of them are coming from third party libraries.

**Comment by issakomi** [comment]
Good idea. BTW, several a little bit confusing options are coming from GDCM's openjpeg cmake file, there are usually on top of cmake-gui (e.g. BUILD_VIEWER, BUILD_JAVA). User can assume it is a kind of ITK's viewer or ITK's whatever java thingy.
