### ISSUE TITLE
Wrapping/Generators ignore ${MyModule}Targets.cmake

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITK#650]
I faced this with the module Eigen3 and now with [ITKTotalVariation](https://github.com/InsightSoftwareConsortium/ITKTotalVariation).

I export the dependencies into the `./lib/cmake/ITK-5.0/Modules/Targets/TotalVariationTargets.cmake` with a call of `itk_module_target(${third_party_lib})` in the external module.

That target file is used by apps using the module, however, the python wrappings are ignoring it.

I haven't found any reference to the targets file in the CMake related to wrapping. It would be extremely helpful to have it!

The targets file is referenced in the module info file (i.e. ` lib/cmake/ITK-5.0/Modules/TotalVariation.cmake `), so it would be a matter of reading it from there in the wrapping/generator module.

**Comment by phcerdan** [comment]
@thewtex @fbudin69500 if you have any hint on this would be great. I haven't found yet how/where the wrapping/generators interact with modules.

**Comment by thewtex** [comment]
@phcerdan is this issue still valid?

**Comment by phcerdan** [comment]
It is valid, however, a workaround was merged in #707 . We can close it.
