### ISSUE TITLE
Improve consistency of ResampleImageFilter output when streaming

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#655]
Expand the requested input region by the required interpolator domain. Suggested-by: @blowekamp 

CC: @romangrothausmann

**Comment by thewtex** [comment]
I have a WIP patch for this to push after we get the dashboard green.

**Comment by romangrothausmann** [comment]
In regard to #668, I could contribute some tests based on those I have for my resample CLI, which currently work for NearestNeighbor, Linear and (surprisingly)  BSpline interpolators but not for Gaussian or WindowedSinc, see e.g. resample.X tests at: https://gitlab.com/romangrothausmann/ITK-CLIs/pipelines/55421017
I am wondering though why the BSpline interpolator already seems to work even though it is part of https://github.com/InsightSoftwareConsortium/ITK/pull/668/commits/96c826e6e7594259046527d12437f99bd1bed249.

**Comment by romangrothausmann** [comment]
While #668 basically resolves this issue, there are still #1011 and #1012 that are missing a solution.
@thewtex any idea on #1011?

**Comment by dzenanz** [comment]
Let's close this issue and continue discussion in #1011 and #1012.
