### ISSUE TITLE
New Spatial Object migration guide needs expanding

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITK#656]
### Description

These changes needed to be made to compile the ANTs package.  It would be nice if the migration guide were improved to indiate that these changes would be necessary.

```
       typename BlobType::PointType centerPoint;
       image->TransformIndexToPhysicalPoint(  cIter.GetIndex(), centerPoint );
       BlobPointer blob = BlobType::New();
-      blob->SetSigma( 1 );
+      blob->SetSigmaInObjectSpace( 1 );
       blob->SetScaleSpaceValue( val );
       blob->SetCenter(  cIter.GetIndex() );
       const typename BlobType::VectorType centerVector = centerPoint - zeroPoint;
-      blob->GetObjectToParentTransform()->SetOffset(centerVector);
-      blob->ComputeBoundingBox();
+      blob->GetModifiableObjectToParentTransform()->SetOffset(centerVector);
+      blob->ComputeMyBoundingBox();
       blobs1.push_back( blob );
       }
     }
     BlobPointer blob = BlobType::New();
-    blob->SetSigma( 1 );
+    blob->SetSigmaInObjectSpace( 1 );
     blob->SetScaleSpaceValue( image2->GetPixel( mIter.GetIndex() ) );
     blob->SetCenter(  mIter.GetIndex() );
     const typename BlobType::VectorType centerVector = centerPoint - zeroPoint;
-    blob->GetObjectToParentTransform()->SetOffset(centerVector);
-    blob->ComputeBoundingBox();
+    blob->GetModifiableObjectToParentTransform()->SetOffset(centerVector);
+    blob->ComputeMyBoundingBox();
     blobs2.push_back( blob );
     }

   {
-    return this->GetSigma() *  itk::Math::sqrt2;
+    return this->GetSigmaInObjectSpace() *  itk::Math::sqrt2;
   }

-    blob->GetObjectToParentTransform()->SetOffset(centerVector);
-    blob->ComputeBoundingBox();
+    blob->GetModifiableObjectToParentTransform()->SetOffset(centerVector);
+    blob->ComputeMyBoundingBox();

-            if( !fixedImageMask || fixedImageMask->IsInside( point ) )
+            if( !fixedImageMask || fixedImageMask->IsInsideInObjectSpace( point ) )
```

Additionally, I think these examples in ITK proper would not compile without changing to "GetModifiableObjectToParentTransform" so they should be removed, or fixed and tested.

```
Examples/RegistrationITKv3/ModelToImageRegistration1.cxx:  ellipse1->GetObjectToParentTransform()->SetOffset(offset);
Examples/RegistrationITKv3/ModelToImageRegistration1.cxx:  ellipse2->GetObjectToParentTransform()->SetOffset(offset);
Examples/RegistrationITKv3/ModelToImageRegistration1.cxx:  ellipse3->GetObjectToParentTransform()->SetOffset(offset);
Modules/Core/SpatialObjects/test/SpatialObjectTest.py:ellipse.GetObjectToParentTransform().SetOffset([20, 20])
Modules/Core/SpatialObjects/test/SpatialObjectTest.py:box.GetObjectToParentTransform().SetOffset([20, 40])
Modules/Core/SpatialObjects/test/SpatialObjectTest.py:gaussian.GetObjectToParentTransform().SetOffset([60, 60])
```

### Steps to Reproduce

Try to compile ANTs with new version of ITK.

### Expected behavior

If building with legacy mode, then the old function names should be available in deprecated mode  issuing warnings.

### Actual behavior

Developers spend a lot of time trying to figure out how to change code to meet the new naming conventions :).

### Reproducibility

Always, until ANTs upgrades all code and requires ITK v5 after March 29th.

### Versions

After update to SpatialObjects.

### Environment

All

**Comment by hjmjohnson** [comment]
See: https://github.com/ANTsX/ANTs/pull/747/commits/21ba53729b47e837a358f63f581ed2c7079fc4b7

**Comment by hjmjohnson** [comment]
I am wondering if the following paradigm would be better:
```
blob->GetModifiableObjectToParentTransform()->SetOffset(centerVector);
```
as
```
blob->SetObjectToParentTransformOffset();
```

**Comment by hjmjohnson** [comment]
Was `Modules/Core/SpatialObjects/include/itkCylinderSpatialObject.h` file intended to be deleted?  If so, that should be documented.

**Comment by hjmjohnson** [comment]
@aylward 
#662 fails (a small test case on top of master)
#663 succeeds( Same as #662, but applied before spatial objects)

**Comment by aylward** [comment]
You need to call update() after calling SetImage() on the
ImageMaskSpatialObject.  This is in the new documentation.  I will add it
to the migration guide as well.

S

---
Sent via phone.

**Comment by hjmjohnson** [comment]
The return value of `ComputeMyBoundingBox` is a boolean, but it is not clear what the return value represents.

In the base class it is hardcoded to return false.  Should ComputeMyBoundingBox return void?  If not the return value meaning should be clarified.

**Comment by hjmjohnson** [comment]
Also related to #642 and #645.

**Comment by aylward** [comment]
Hi

In another thread we're taking about making ComputeMyBoundingBox
protected.  We will have to change the return to throwing an exception.
This happens when the object has an empty bounding box, e.g., if a point
based spatial object had no points.

I will add to the documentation this week.   Need to give much more
emphasis to the importance of calling Update() whenever any parameters of
the Spatial Object are changed.

Thanks for your persistence and patience!!!

Stephen

---
Sent via phone.

**Comment by aylward** [comment]
That is such a common use case, perhaps that is useful.  We would add get
and set methods for offset, scale, and rotation.  Sound right?

**Comment by hjmjohnson** [comment]
@aylward I'm working on a patch right now for making both ComputeMyBoundingBox and ComputeObjectToWorldTransform private and forcing them to use "Update" instead.

**Comment by aylward** [comment]
Outstanding!

I think that is the right thing to do.  It addresses a const issue raised
by Niels.

Thank you!
S

---
Sent via phone.

**Comment by dzenanz** [comment]
I think this was done already. If migration guide needs further expanding, please reopen this issue.
