### ISSUE TITLE
The file ITKConfigVersion.cmake and ITKConfig.cmake of ITK 4.13.1 still indicate the version 4.13.0 

### ISSUE THREAD

**Issue by Siron777** [InsightSoftwareConsortium/ITK#67]
The file ITKConfigVersion.cmake of ITK 4.13.1 still indicate the version 4.13.0. In the CMakeLists.txt file at the root of the source directory, the version number is defined two times.

### Versions
4.13.1 

### Environment
Visual studio 2017
Windows 10

**Comment by thewtex** [comment]
@Siron777 Thanks for the report. This has been fixed in https://github.com/InsightSoftwareConsortium/ITK/commit/dcab5c04e19781b4843bd6eeb7d9ea3a5f77e6a9

It will be released in ITK 4.13.2.
