### ISSUE TITLE
Code Coverage is not being reported by files in CDash

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITK#702]
For the new Azure code coverage builds, only the total number of lines and percentage are begin reported on CDash. On CDash when clicking coverage percentage to drill down to the per file level coverage, there are no files lists.

This may be a CDash issue as this info is not available for CMake either: https://open.cdash.org/viewCoverage.php?buildid=5845858

**Comment by thewtex** [comment]
Per-line coverage is working in VTK:

https://open.cdash.org/viewCoverage.php?buildid=5849102

**Comment by thewtex** [comment]
CC: @zackgalbreath

**Comment by zackgalbreath** [comment]
A few weeks ago we upgraded the database server that hosts CDash. One of the default settings changed and this broke per-file coverage. This situation was fixed back on April 8th.

Let me know if there's anything I can do to help help get ITK coverage data displaying correctly on CDash.

**Comment by blowekamp** [comment]
That follows with what I saw. Thanks!
