### ISSUE TITLE
7 tests failing on MacOS (Azure Pipeline) when build type is `MinSizeRel`

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#713]
### Description

7 tests are failing (Segfault or just failing) when compiling ITK on MacOS, at least on Azure Pipeline CI, when build type is `MinSizeRel`. These failure do not appear when compiling ITK in `Release`.

itkAnisotropicFourthOrderLevelSetImageFilterTest : SEGFAULT
itkGaussianInterpolateImageFunctionTest : Failed
itkImplicitManifoldNormalVectorFilterTest : SEGFAULT
itkIsotropicFourthOrderLevelSetImageFilterTest :SEGFAULT
itkLinearInterpolateImageFunctionTest : Failed
itkSparseFieldFourthOrderLevelSetImageFilterTest : SEGFAULT
itkUnsharpMaskLevelSetImageFilterTest : SEGFAULT

https://open.cdash.org/viewTest.php?onlyfailed&buildid=5848875

### Steps to Reproduce

Compile ITK on MacOS with build type set to MinSizeRel. This can be done on CI by creating a PR in which [this](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Testing/ContinuousIntegration/AzurePipelinesMacOS.yml#L44) is modified.

### Reproducibility

100% of the time, these tests fail.

### Versions

Current master:  7dbfeb6

### Environment

MacOS, Azure CI environment.

**Comment by thewtex** [comment]
@maekclena did your PR's address all of these tests?

**Comment by fbudin69500** [comment]
This could be tested on CI by changing build type in the yaml configuration file :)

**Comment by fbudin69500** [comment]
https://github.com/InsightSoftwareConsortium/ITK/pull/758

**Comment by thewtex** [comment]
> #758

Nice, thanks!

**Comment by fbudin69500** [comment]
All these tests now pass on MacOS when build type is `MinSizeRel` (See [here](https://open.cdash.org/viewTest.php?onlypassed&buildid=5875215&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=))
