### ISSUE TITLE
ITK build failed due to fatal error LNK1181: cannot open input file '..\..\..\..\lib\Release\SharedTestLibraryA.lib' with MSVC on windows 

### ISSUE THREAD

**Issue by spacelg** [InsightSoftwareConsortium/ITK#723]
ITK build failed due to fatal error LNK1181: cannot open input file '..\..\..\..\lib\Release\SharedTestLibraryA.lib' with MSVC on windows. I use version 9b6df44 on master branch can be reproduced this issue. And we looked at the commit record and tried to build with 90eb28e revresion and build pass. It should be an ITK source issue. Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:
1.git clone http://itk.org/ITK.git D:\ITK\src
2.open VS2017 x86 command prompt as admin and browse to D:\ITK
3.set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %_CL_%
4.mkdir build_x86 && pushd build_x86
5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..\src\
6.msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild 

The whole log file please see attachment.
[log_x86_build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3071832/log_x86_build.log)

Acutal result:
82>LINK : fatal error LNK1181: cannot open input file '..\..\..\..\lib\Release\SharedTestLibraryA.lib' [D:\ITK\build_x86\Modules\Core\Common\test\itkObjectFactoryBasePrivateDestructor.vcxproj]
    82>Done Building Project "D:\ITK\build_x86\Modules\Core\Common\test\itkObjectFactoryBasePrivateDestructor.vcxproj" (default targets) -- FAILED.

**Comment by N-Dekker** [comment]
Same issue here!  :frowning:  I have no clue! Anyway, thanks for reporting, @spacelg !

**Comment by fbudin69500** [comment]
I have added an extra test last week. I thought it was passing, but clearly I missed that issue. Thanks for reporting the problem. Could you test #735 which should solve that issue.

**Comment by fbudin69500** [comment]
#735  was merged. Please reopen this topic if the problem reappears.
