### ISSUE TITLE
Deprecate Vector* specializations

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#725]
Deprecate Vector* specializations such as `VectorResampleImageFilter` and `VectorLinearInterpolateImageFunction`. The general versions now work with vector types too.

This is not trivial. See this [comment](https://github.com/InsightSoftwareConsortium/ITK/pull/786#issuecomment-488660335).

**Comment by blowekamp** [comment]
There are some filters or algorithms that are specialized just to deal with vector pixel type, while others are specialized to compute different distance, threshold or gradient metrics. Those that treat the vector components independely are likely not to need a specialized implementation. The following is a list of candidates:
- VectorResampleImageFilter
- VectorExpandImageFilter
- VectorLinearInterpolateImageFunction
- VectorCastImageFilter
- VectorCentralDifferenceImageFunction

**Comment by dzenanz** [comment]
Quite some work was done on this already. Is more work expected, or should we close the issue?

**Comment by blowekamp** [comment]
Much of this work was done in : #1054, #900, #856  and others.

This issue has mostly been accomplished and should be closed.
