### ISSUE TITLE
Fix rendering part of VTK Glue

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITK#739]
### Description

Rendering classes in ITKVtkGlue do not work. [Example failure](https://open.cdash.org/testDetails.php?test=670818933&build=5860842):

**Command Line**
/home/dzenan/Dashboards/Tests/ITK-build/bin/ITKLevelSetsv4VisualizationTestDriver \"itkVTKVisualize2DCellsLevelSetSurfaceTest\" \"/home/dzenan/Dashboards/Tests/ITK-build/ExternalData/Modules/Segmentation/LevelSetsv4Visualization/test/Input/cells.png\" \"60\" \"Dense\" \"/home/dzenan/Dashboards/Tests/ITK-build/Testing/Temporary/itkVTKVisualize2DCellsDenseLevelSetSurfaceTest.png\"

**Test output**
Input image read
Finished converting to sparse format
Heaviside function created
LevelSetContainer created
Chan and Vese internal term created
Chan and Vese external term created
Term container created
Equation container created
Stopping criteria created
Generic Warning: In /home/dzenan/VTK-7.1.1/Rendering/Core/vtkRenderer.cxx, line 52
Error: no override found for 'vtkRenderer'.

### Steps to Reproduce

1. Turn on ITKVtkGlue and ITKLevelSetsv4Visualization modules
2. Configure, build, run tests

### Expected behavior

All tests pass

### Actual behavior

20 or so tests fail:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=5860842

### Reproducibility

100%

### Versions

All recent versions

### Environment

Ubuntu 16.04 and Windows 10.

### Additional Information

Related to #714 and https://github.com/InsightSoftwareConsortium/ITK/pull/731#issuecomment-483660906.

**Comment by thewtex** [comment]
The discussion in #424 suggests that adding

```
vtk_module_autoinit(
  TARGETS ITKVtkGlueTestDriver
MODULES ${VTK_LIBRARIES})
```

to *ITK/Modules/Bridge/VtkGlue/test/CMakeLists.txt* should address the issue.

**Comment by dzenanz** [comment]
Still does not work on Windows:

```bash
Dzenan@Ryzenator MINGW64 /c/Dev/ITK-2k17
$ /c/Dev/ITK-2k17/bin/RelWithDebInfo/ITKLevelSetsv4VisualizationTestDriver.exe "itkVTKVisualizeLevelSetsInteractivePauseTest" "C:/Dev/ITK-2k17/ExternalData/Modules/Segmentation/LevelSetsv4Visualization/test/Input/cells.png" "30"
Input image read
Segmentation fault
```
<img width="436" alt="Screenshot 2019-04-29 19 28 51" src="https://user-images.githubusercontent.com/1792121/56934092-bb468b00-6ab8-11e9-868b-75aa3a52de4b.png">

**Comment by dzenanz** [comment]
Or Linux:
```text
Generic Warning: In /home/dzenan/VTK-7.1.1/Rendering/Core/vtkImageSliceMapper.cxx, line 35
Error: no override found for 'vtkImageSliceMapper'.
```
https://open.cdash.org/testDetails.php?test=670818924&build=5883445

**Comment by thewtex** [comment]
@dzenanz does the `vtk_module_autoinit` code result improve the result?

**Comment by dzenanz** [comment]
Sadly, that does not even configure:
```text
CMake Error at Modules/Bridge/VtkGlue/test/CMakeLists.txt:23 (vtk_module_autoinit):
  Unknown CMake command "vtk_module_autoinit".

-- Configuring incomplete, errors occurred!
```

**Comment by mathstuf** [comment]
Here's a commit which gets the Vis tests passing again: https://github.com/mathstuf/ITK/commit/63e26fa844f9e3c91d1d9a674afe97a5d90b2274. Needs some massaging to also support 8.2. See https://gitlab.kitware.com/vtk/vtk/issues/17604 for getting better autoinit support for header-only libraries (something I didn't think about before since header-only VTK usage wasn't something I had considered).

**Comment by dzenanz** [comment]
In order to avoid separately maintaining `ITKLevelSetsv4Visualization`, we decided to [move](https://github.com/InsightSoftwareConsortium/ITK/pull/906) it to a new remote module [ITKVtkGlue](https://github.com/InsightSoftwareConsortium/ITKVtkGlue/), thus effectively merging it with `ITKVtkGlue`. The new module should become active/buildable after ITKv5.0.0 has been released.
