### ISSUE TITLE
Potential link errors classes of SpatialObjects library

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#743]
With commit 198b5c8f59fdb2b67b443f0455ce61b203c3fddd (Feb 10, 2019), `SpatialObjectProperty` member function implementations were moved to a cxx file. In order to export this functionality, I _think_ the class should have some kind of EXPORT macro. Something like `ITKSpatialObjects_EXPORT`? Possibly here:

https://github.com/InsightSoftwareConsortium/ITK/blob/2e23f710b387e8465dd37d102e245b5365c5831c/Modules/Core/SpatialObjects/include/itkSpatialObjectProperty.h#L36

Can you please check this (and please fix it, if necessary)? Stephen @aylward ? Or Hans @hjmjohnson ?

The issue might also apply to `MetaEvent` and `SpatialObjectFactoryBase`.

Note: This is not a high priority issue for me personally, because I usually link _statically_ to ITK. But it could be of importance to users who link dynamically (`BUILD_SHARED_LIBS`) to ITK.

**Comment by aylward** [comment]
You might be right.   Other ITK experts should give us insight...  @dzenanz ?

**Comment by dzenanz** [comment]
@hjmjohnson made [some attempts](https://github.com/hjmjohnson/ITK/tree/move-ITK_TEMPLATE_EXPORT-to-header) regarding this in December. I don't know what is the status of this.
