### ISSUE TITLE
ImageMaskSpatialObject BoundingBox smaller than before Spatial Object update

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#753]
The bounding box of an `ImageMaskSpatialObject`, as returned by `GetMyBoundingBoxInObjectSpace()` (introduced with the recent Spatial Object update by Stephen @aylward ) appears smaller than the one returned by `GetBoundingBox()`, from [ITK5 RC1](https://github.com/InsightSoftwareConsortium/ITK/tree/v5.0rc01) or previous ITK versions. For example, the following code printed `[4, 6, 4, 6]`, using ITK5 RC1:

    const auto image = itk::Image<unsigned char>::New();
    image->SetRegions(itk::Size<>{8, 8});
    image->Allocate(true);  // Zero as background value.

    // Little 2 x 2 square of non-zero values:
    image->SetPixel({ 4, 4 }, 1);
    image->SetPixel({ 4, 5 }, 1);
    image->SetPixel({ 5, 4 }, 1);
    image->SetPixel({ 5, 5 }, 1);

    const auto spatialObject = itk::ImageMaskSpatialObject<2>::New();
    spatialObject->SetImage(image);
    spatialObject->Update();

    std::cout << spatialObject->GetBoundingBox()->GetBounds(); // [4, 6, 4, 6]

With [the current git master revision of ITK, April 23, 2019](https://github.com/InsightSoftwareConsortium/ITK/tree/b83454ef2b4d2385adddab67d6378fe8c47f8800) (which includes the Spatial Object update), the following prints `[4, 5, 4, 5]`, instead:

    std::cout << spatialObject->GetMyBoundingBoxInObjectSpace()->GetBounds(); // [4, 5, 4, 5]!!!

Was this behavior change intended?

**Comment by N-Dekker** [comment]
Just discussed with @kaspermarstal and @stefanklein at our Elastix/SuperElastix sprint meeting. We would like to see a bounding box of `[3.5, 5.5, 3.5, 5.5]` in this case. So in general, taking the size of the border pixels into account. What do you think?

Somewhat related topic: https://discourse.itk.org/t/imagemaskspatialobject-isinside-less-than-half-a-pixel-away/1807

**Comment by aylward** [comment]
Hi

I think returning a continuous index or an index that has a buffer is
appropriate .

So either the 3.5,5.5 or the 3,6 solutions seem valid.   A bounding box
without a buffer seems more likely to lead to errors.

Very nice detective work!!

S

---
Sent via phone.

**Comment by thewtex** [comment]
@N-Dekker has this issue been addressed?

**Comment by N-Dekker** [comment]
@thewtex Indeed, Matt! Pull request #789 does the job! I'll close the issue!
