### ISSUE TITLE
ITK build failed due to error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [InsightSoftwareConsortium/ITK#766]
ITK build failed due to error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion with MSVC on windows. It can be reproduced on master version 651ee50 and this issue can be first reproduced on master version b9f39dd.It should be an ITK source issue. Could you please help look at this? Thanks a lot!

You can repro this issue as the steps below:
 1.git clone http://itk.org/ITK.git D:\ITK\src
 2.open VS2017 x86 command prompt as admin and browse to D:\ITK
 3.set CL=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %CL%
 4.mkdir build_x86 && pushd build_x86
 5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=OFF ..\src
 6.msbuild /m /p:Configuration=Release;Platform=Win32 All_BUILD.vcxproj /t:Rebuild

The whole log file please see attachment.
[log_x86_build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3115886/log_x86_build.log)

Acutal result:
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397:  conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion 
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397:       image->SetPixel({{i, j}}, i + j);

**Comment by thewtex** [comment]
@spacelg please review #767
