### ISSUE TITLE
Pass image orientation information in ITK / VTK pipelines

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#772]
### Description

Transfer the image orientation *Direction* matrix from ITK to VTK and VTK to ITK in ITKVtkGlue.

VTK Git `master` recently added orientation to *vtkImageData*. :tada: :taco: h/t @agirault 

### Steps to Reproduce

In [itkImageToVTKImageFilterTest](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Bridge/VtkGlue/test/itkImageToVTKImageFilterTest.cxx), set the *Direction* on the input *itk::Image*, and verify that it is correct on the output *vtkImageData*. Verify the fix in [itkVTKImageToImageFilterTest](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Bridge/VtkGlue/test/itkVTKImageToImageFilterTest.cxx) similarly.

To implement *Direction* passing, transfer the information in a similar way to the *Origin* and *Spacing* [in the ITKVTK module](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Bridge/VTK/include).

To build the code and tests, enable the *Module_ITKVtkGlue* CMake option in ITK's build configuration, and point the build to the desired *VTK_DIR*.

### Expected behavior

Image orientation information is passed in ITK/VTK pipelines.

### Actual behavior

Image orientation information is lost.

### Reproducibility

100%.

### Versions

This will require VTK Git `master` (9.X) to be fixed.

CC: @aylward @martinken @lassoan @jcfr

**Comment by agirault** [comment]
Followed your steps, and I get this with [itk/c351787](https://github.com/InsightSoftwareConsortium/ITK/commits/c351787) and [vtk/e2f92f6e](https://gitlab.kitware.com/vtk/vtk/commits/e2f92f6e) :
```ninja
[5481/5508] Building CXX object Modules/Bridge/VtkGlue/src/CMakeFiles/ITKVtkGlue.dir/QuickView.cxx.o
/itk/src/Modules/Bridge/VtkGlue/src/QuickView.cxx:25:10: fatal error: 'vtkVersion.h' file not found
#include "vtkVersion.h"
         ^~~~~~~~~~~~~~
1 error generated.

[5483/5508] Building CXX object Modules/Bridge/VtkGlue/test/CMakeFiles/ITKVtkGlueTestDriver.dir/itkImageToVTKImageFilterTest.cxx.o
In file included from /itk/src/Modules/Bridge/VtkGlue/test/itkImageToVTKImageFilterTest.cxx:19:
/itk/src/Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h:22:10: fatal error: 'vtkImageImport.h' file not found
#include "vtkImageImport.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.

[5484/5508] Building CXX object Modules/Bridge/VtkGlue/test/CMakeFiles/ITKVtkGlueTestDriver.dir/itkImageToVTKImageFilterRGBTest.cxx.o
In file included from /itk/src/Modules/Bridge/VtkGlue/test/itkImageToVTKImageFilterRGBTest.cxx:19:
/itk/src/Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h:22:10: fatal error: 'vtkImageImport.h' file not found
#include "vtkImageImport.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.

[5485/5508] Building CXX object Modules/Bridge/VtkGlue/test/CMakeFiles/ITKVtkGlueTestDriver.dir/itkVTKImageToImageFilterTest.cxx.o
In file included from /itk/src/Modules/Bridge/VtkGlue/test/itkVTKImageToImageFilterTest.cxx:19:
/itk/src/Modules/Bridge/VtkGlue/include/itkVTKImageToImageFilter.h:23:10: fatal error: 'vtkImageExport.h' file not found
#include "vtkImageExport.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by agirault** [comment]
Issue found with the help of @fbudin69500: 
1. `vtk_module_config` sets `ITKVtkGlue_VTK_LIBRARIES` to the required libraries in the format `VTK::LibName`
2. for `VTK_VERSION >= 6.0.0`, `ITKVtkGlue_VTK_LIBRARIES` was then overriden to the required libraries in the format `vtkLibName` instead
3. it seems that for `VTK_VERSION >= 9.0.0` (or earlier?) `ITKVtkGlue_VTK_LIBRARIES` should use the `VTK::LibName` format (probably what is exported in the vtk-config.cmake), so we should bypass the step 2 (or get rid of it entirely?)

Fix draft:

```diff
diff --git a/Modules/Bridge/VtkGlue/CMakeLists.txt b/Modules/Bridge/VtkGlue/CMakeLists.txt
index 0739115d54..5c63bf222c 100644
--- a/Modules/Bridge/VtkGlue/CMakeLists.txt
+++ b/Modules/Bridge/VtkGlue/CMakeLists.txt
@@ -73,7 +73,9 @@ else()
   vtk_module_config(ITKVtkGlue_VTK
     ${_required_vtk_libraries}
     )
-  set(ITKVtkGlue_VTK_LIBRARIES ${_required_vtk_libraries})
+  if( ${VTK_VERSION} VERSION_LESS 9.0.0 )
+    set(ITKVtkGlue_VTK_LIBRARIES ${_required_vtk_libraries})
+  endif()
 endif()
 
 # The VTK DICOMParser and vtkmetaio includes conflict with the ITK
```

**Comment by thewtex** [comment]
@agirault thanks for the info -- please review #778 .

> I don't understand how you said you used VTK 9.x while we are only at VTK 8.90 right now.

I assumed `master` was 9.X.

**Comment by thewtex** [comment]
> ```diff
> +  if( ${VTK_VERSION} VERSION_LESS 8.90.0 )
> +    set(ITKVtkGlue_VTK_LIBRARIES ${_required_vtk_libraries})
> +  endif()
> ```

We want this to be set because it is used later.

**Comment by agirault** [comment]
> We want this to be set because it is used later.

It is already set, but to a different value, in `vtk_module_config`

**Comment by thewtex** [comment]
#790 addresses this issue! :taco: :tada: 

#843 opened to track the `vtk_module_config` issue brought up in discussion.
