### ISSUE TITLE
CannySegmentationLevelSetImageFilter not support 3d medical image

### ISSUE THREAD

**Issue by junqiangchen** [InsightSoftwareConsortium/ITK#782]
hello,
I am tring to do a level set based segmentation using CannySegmentationLevelSetImageFilterr.cxx sample in ITK.
2D image works fine but when I try on 3D data I observed that fast marching filter can not working although I gave seed points and radius. I do not know how much more I should wait but it seems it is not usable，when image dimensions are 512 x 512 x 130.
Are there anyone who could succeed to run those segmentation filters in 3D?
 If anyone could help or point me, please? Thank you in advance.

**Comment by blowekamp** [comment]
Hello junqiangchen,

I have successfully used both the FastMarhingImageFilter, and the CannySegementationLevelSetImageFitler in 3D. I do not believe this is a bug in either of the filters.

It sounds like you are trying to modify an example from 2D to 3D. The [ITK discourse ](https://discourse.itk.org) is the appropriate discussion format for help using ITK.
