### ISSUE TITLE
Investigate pprint to improve printing of complex objects

### ISSUE THREAD

**Issue by gdevenyi** [InsightSoftwareConsortium/ITK#787]
Header file only add-on..

Pprint: Pretty Printer for Modern C++ - https://github.com/p-ranav/pprint

H/t hackernews

**Comment by thewtex** [comment]
Related, @jhlegarreta recently added `itk::print_helper` for use in `::PrintSelf`:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkPrintHelper.h
