### ISSUE TITLE
Ubuntu ccmake issue: "ITK should not be configured & built in the ITK source directory"

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [InsightSoftwareConsortium/ITK#79]
### Unable to run `ccmake ..`, `c` configure and `g` generate
I'm using Ubuntu 18.04 and am trying to build ITK. I'm following the steps here (are these still up to date?): https://itk.org/Wiki/ITK/Getting_Started/Build/Linux. After creating a `/bin` directory and trying `ccmake ..`,and `c` to configure I get: 
![screenshot from 2018-10-12 13-10-52](https://user-images.githubusercontent.com/8392709/46868453-482d3e00-ce20-11e8-9382-b70d60befbcb.png)
i.e. it says: "ITK should not be configured & built in the ITK source directory". So I am unable to proceed. Am I doing something wrong? 

### Steps to Reproduce
I attempted the steps described here: https://itk.org/Wiki/ITK/Getting_Started/Build/Linux

### Expected behavior
The software should be compiled

### Actual behavior
Unable to start with `ccmake`

### Reproducibility
100%

### Versions
ITK 4.13.1

### Environment
Ubuntu 18.04

**Comment by phcerdan** [comment]
Hi @Kevin-Mattheus-Moerman, thanks for reporting, the wiki is outdated (pinging @thewtex).
It is general good practice with any CMake project that the build (or bin) folder shouldn't be inside the source folder, but in a parallel folder. For example, the following will create ITK-src with the code and ITK-build in the same level:
```bash
git clone https://itk.org/ITK.git ITK-src
mkdir ITK-build; cd ITK-build
ccmake ../ITK-src
```

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Thanks that solved it.

**Comment by phcerdan** [comment]
That [note](https://itk.org/Wiki/ITK/Getting_Started/Build/Linux) looks mint!
