### ISSUE TITLE
Broken test `PythonFindEmptyClasses`

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#797]
### Description

The test `PythonFindEmptyClasses` is broken. This is most likely due to [this commit](https://github.com/InsightSoftwareConsortium/ITK/commit/37e0474669a6f68026e718114f584a8f631eec84).

The result of the test can be seen [here](https://open.cdash.org/viewTest.php?onlyfailed&buildid=5885143).

**Comment by thewtex** [comment]
Taking a look...
