### ISSUE TITLE
BridgeOpenCV fails to build with OpenCV 4

### ISSUE THREAD

**Issue by nocnokneo** [InsightSoftwareConsortium/ITK#806]
### Description

For example, when building unit tests:

```
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe 
... .../ITK\Modules\Video\BridgeOpenCV\test\itkOpenCVImageBridgeGrayScaleTest.cxx
.../opencv2/imgcodecs/imgcodecs_c.h(1): fatal error C1189: #error:  "This header with legacy C API declarations has been removed from OpenCV. Legacy contants are available from legacy/constants_c.h file." 
```

### Steps to Reproduce

1. Build ITK against OpenCV4 4.0.1 with `-DBUILD_TESTING:BOOL=ON -DModule_ITKVideoBridgeOpenCV:BOOL=ON`

### Versions

Latest master (b83454ef2b4d2385adddab67d6378fe8c47f8800)

### Environment

Tested on Windows with MSVC 2015 and 2017 and Ubuntu 18.04 gcc-6

**Comment by nocnokneo** [comment]
I'm happy to submit a patch for this. Can OpenCV 2.x support be dropped at this point?

**Comment by dzenanz** [comment]
It can probably be dropped. Let's give a few days to others to possibly raise objections.

**Comment by nocnokneo** [comment]
Sounds good. I'll check back in a few days.

**Comment by thewtex** [comment]
+1 for dropping OpenCV 2.x support.

**Comment by hjmjohnson** [comment]
+100 for dropping OpenCV2.x support.

**Comment by dzenanz** [comment]
I could take a stab at this.

**Comment by gentuity-it** [comment]
Thanks @dzenanz! Sorry that I haven't had time to get around to this.

**Comment by nocnokneo** [comment]
There is an open PR for this issue awaiting review.
