### ISSUE TITLE
SpatialObject IsInsideInObjectSpace PERF penalty GetTypeName().find

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITK#820]
### Description

Looking at the performance of `IsInsideInObjectSpace(point, depth=0,  name="")`, I observed a large performance gain when I locally removed the following line, when using the default argument values (so `name=""`):

    if( this->GetTypeName().find( name ) != std::string::npos )

https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0rc02/Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx#L45

### Impact analysis

For `ImageMaskSpatialObject` it appears that `IsInsideInObjectSpace(point)` will be more than twice as fast, and sometimes even more than 3 X as fast, when the line of code that does the `GetTypeName()` check is removed.

I measured the performance of something like this: 

    for (unsigned i = 0; i < n; ++i)
    {
      typename TImage::PointType point{};
      point[0] = i;
      spatialObject->IsInsideInObjectSpace(point);
    }

### Versions

ITK5 RC2

### Environment

Visual C++ 2017 x64 Release 

### Question

Is there a common use case, calling `IsInsideInObjectSpace(point, depth, name)` with a non-empty `name` argument?

**Comment by hjmjohnson** [comment]
@N-Dekker Could you simply make 2 explicit separate signatures and avoid the default parameter for name removed?

```
IsInsideInObjectSpace(point)
```
```
IsInsideInObjectSpace(point, depth) // Perhaps have depth=0 defaulted and skip the first signature
```

```
IsInsideInObjectSpace(point, depth, name)
{
if( this->GetTypeName().find( name ) != std::string::npos )
{}

return IsInsideInObjectSpace(point, depth)
}
```

This would be backward compatible and have the performance gains.

**Comment by N-Dekker** [comment]
@hjmjohnson Thanks for your suggestion. Surely the PERF issue could be solved by adding an overload without the `name` parameter. However, it isn't entirely as simple as you suggested! When `depth` > 0, the function returns `IsInsideChildrenInObjectSpace(point, depth, name)`, so at that point, the name argument must still be available.

**Comment by N-Dekker** [comment]
In the mean time I did figure out that the performance issue can already be fixed easily, by ensuring that `GetTypeName().find(name)` is _only_ called when the name is non-empty. So by doing:

    if(name.empty() || (this->GetTypeName().find( name ) != std::string::npos) )

That would really be a major performance improvement  `:-)`

I'm still curious about the use case, though! Do users want to specifically look into those spatial objects whose _type-name_ has a certain name as _substring_?

**Comment by N-Dekker** [comment]
@hjmjohnson I'm preparing a pull request now that does actually follow your suggestion (separate signatures, separate overloads for with and without `name` parameter). It's quite a refactoring, as it involves 12 SpatialObject classes. Please wait...  `:-)`
