### ISSUE TITLE
BUG: some DICOM files crash GDCMIO (and Slicer, ITK-Snap, etc)

### ISSUE THREAD

**Issue by issakomi** [InsightSoftwareConsortium/ITK#851]
Particular [DICOM files](https://drive.google.com/file/d/19WeGrPdl3itxAlbViq0qiEgtna8vMy70/view?usp=sharing) crash GDCMIO and related applications. To reproduce crash drag-and-drop a file onto Slicer window or ITK-Snap. Here is trivial [test](https://drive.google.com/file/d/1vRgHM1pH8ox0diYL9lM2CdSJUP7Cqbri/view?usp=sharing).

Particular files has _Bits Allocated 16_ and _Bits Stored  8_. Crash happens because [here](https://github.com/InsightSoftwareConsortium/ITK/blob/9e122664724eb049955c968c054247c00d92eee2/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L415) pixel type is taken from gdcm::Rescaler without check of intercept and slope values ("are they different from 1 / 0?"). And [here](https://github.com/InsightSoftwareConsortium/ITK/blob/9e122664724eb049955c968c054247c00d92eee2/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L327) re-scale is applied only if intercept and slope are different from 1 / 0. gdcm::Rescaler returns UINT8 for the files, even if slope = 1 and intercept = 0. The bug is very old, at least 5 years.

[Here is patch](https://github.com/InsightSoftwareConsortium/ITK/compare/master...issakomi:fix_gdcmio_crash)

Just close the issue if don't want fix, i don't rely on this code. Thanks. 

FYI @malaterre

**Comment by dzenanz** [comment]
Can the linked images be added to a unit test?

**Comment by issakomi** [comment]
They are public, i hope, AFAIK from old DCMTK demo CD, also available here
 https://www.creatis.insa-lyon.fr/~jpr/PUBLIC/gdcm

in _gdcmSampleData/Philips_Medical_Images/Integris_H_3_V_11_ folder, but compressed (.Z)

**Comment by issakomi** [comment]
Obviously no interest, closing

**Comment by dzenanz** [comment]
The automatic "timeout" for no interest is set to warn after 3 months, and close after 6. 13 days is a bit aggressive, in my opinion.
