### ISSUE TITLE
ITK 4.13.2 - NUmerics traits - Error

### ISSUE THREAD

**Issue by pedromorais17** [InsightSoftwareConsortium/ITK#858]
Hi all,

While compiling a simple ITK example from the ITK website, I’m receving a set of error messages related to itk::NumericTraits.

Example:

member “itk::NumericTraits::One” may not be initialized

Although this not influence the program (I can run it), I would like to remove this error from my compilation. Do you have a suggestion?

I'm using Windows 10, Visual Studio 2017, OpenCV4.1, VTK8.1.2. I'm not using cmake to create my project. I'm not sure if similarly to VTK, I need to start a specific factory. 

Thank you in advance.

**Comment by N-Dekker** [comment]
Thanks for your bug report @pedromorais17 Are the error message from IntelliSense? The issue you are describing looks similar to this one, to me:

[Intellisense error: C++11 static constexpr member initialization causes "member may not be initialized"
](https://developercommunity.visualstudio.com/content/problem/245425/intellisense-error-c11-static-constexpr-member-ini.html)

Does that correspond to your issue? If so, I'm afraid ITK can't help it  :open_mouth:

**Comment by pedromorais17** [comment]
Yes, that is the problem. Thank you.
