### ISSUE TITLE
Error while writing DICOM series using an integer as output pixel type

### ISSUE THREAD

**Issue by MaxvandenBoom** [InsightSoftwareConsortium/ITK#867]
The writing of DICOM series fails when the output pixel type is set to integer: 

Assertion failed: slope == (int)slope, file \ITK_5.0rc02_src\Modules\ThirdPart
y\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmRescaler.cxx, line 67

I am currently using the example program 'DicomSeriesReadSeriesWrite' to read and write DICOM data and occurs in both the latest release 4.13.2 and ITK 5.0 rc02. When the output pixel type is set to float it does work.

This has been an issue with the InverseRescaleFunction function from GDCM since 2014 (https://itk.org/pipermail/insight-users/2014-September/050886.html). But I was unsure whether to report it here (for possible workarounds, patches and awareness) or at GDCM to look at.

Best regards,
Max

**Comment by dzenanz** [comment]
I think the correct way it to make a patch to GDCM.

CC: @malaterre @thewtex

**Comment by malaterre** [comment]
@MaxvandenBoom is this still a bug in ITK 5 ?

**Comment by MaxvandenBoom** [comment]
@malaterre yes, the bug is still in the 5.0.0 release.

**Comment by malaterre** [comment]
@MaxvandenBoom Where are the test dataset ?

**Comment by MaxvandenBoom** [comment]
@malaterre I created an anonymized test dataset for you. Can I send you an e-mail?

**Comment by malaterre** [comment]
@MaxvandenBoom of course !

**Comment by MaxvandenBoom** [comment]
Sorry, I am relatively new to using github, it seems like it does not provide a way to send you a private message, and can't find your e-mail address anywhere (also not on your blog or website)...

**Comment by malaterre** [comment]
mathieu.malaterre gmail.com

**Comment by seanm** [comment]
@MaxvandenBoom his email is here: https://github.com/malaterre/GDCM/blob/master/.travis.yml

**Comment by MaxvandenBoom** [comment]
Hi guys, sorry for the bump.

@seanm, I already send a link to the dataset by mail to @malaterre on 3 juli 2019.
I was wondering if you managed to figure out the problem in the meantime? Did the mail ever arrive?

**Comment by seanm** [comment]
@MaxvandenBoom Have you checked if the bug is already filed here https://sourceforge.net/p/gdcm/bugs/ ?  Otherwise, I suggest you create one there, as this looks more like a GDCM bug than an ITK bug.

**Comment by MaxvandenBoom** [comment]
Sure, I will! I was just under the impression that when Mathieu asked for a example set, that he wanted to look at it.

Tnx!

**Comment by malaterre** [comment]
For some reason this fell through the cracks. I can reproduce the issue with ITK 5.x. Please report it as a bug and assign it to me. I'll need to find some time to actually dive into the code. Thx

**Comment by dzenanz** [comment]
Has this been fixed or is it still open?

**Comment by MaxvandenBoom** [comment]
> For some reason this fell through the cracks. I can reproduce the issue with ITK 5.x. Please report it as a bug and assign it to me. I'll need to find some time to actually dive into the code. Thx

I think @malaterre asked me to forward it as a bug at GDCM, but I forgot. However, there is a reference to this bug at GDCM in the meantime: https://sourceforge.net/p/gdcm/bugs/328/
which is marked as "won't fix" because it might have been fixed by another GDCM commit.
Is that GDCM commit/release integrated into the latest ITK yet? If so, I could test whether it is resolved..

**Comment by MaxvandenBoom** [comment]
It would still be quite helpful if ITK is able to write DICOM output with the pixel type set to integer.
Can I do anything to help?

**Comment by dzenanz** [comment]
I guess this needs to be fixed in GDCM by @malaterre before it makes its way into ITK.

**Comment by seanm** [comment]
>Can I do anything to help?

Not sure how he does things, but there is a 'donate' button here https://sourceforge.net/projects/gdcm/support perhaps an arrangement could be made...

**Comment by malaterre** [comment]
@MaxvandenBoom

> It would still be quite helpful if ITK is able to write DICOM output with the pixel type set to integer.

Could you quote the section of the standard you're thinking of ? Simply the IOD or the SOP Class Name is enough.

Thanks

**Comment by MaxvandenBoom** [comment]
> @MaxvandenBoom
> 
> > It would still be quite helpful if ITK is able to write DICOM output with the pixel type set to integer.
> 
> Could you quote the section of the standard you're thinking of ? Simply the IOD or the SOP Class Name is enough.
> 
> Thanks

Hi Mathieu, thanks for taking a look!

I'm unsure of what you are asking. It seems something goes wrong in `gdcmRescaler.cxx, line 67`, not sure how that reflects on a section of the standard. I send you a MRI dataset in which the bug occurs a while ago, does that help?

**Comment by malaterre** [comment]
If we are talking about `MR Image Storage` and `Enhanced MR Image Storage`, then everything works as expected. Neither SOP Classes allow for integer type pixels.

**Comment by MaxvandenBoom** [comment]
Ah ok, the classSOP class UID is `1.2.840.10008.5.1.4.1.1.4`, so I am indeed working with `MR Image Storage`.

I didn't know such a SOP check was handled with an assert evaluation:
```
Assertion failed: slope == (int)slope, file \ITK_5.0rc02_src\Modules\ThirdPart
y\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmRescaler.cxx, line 67
```
And because they are mentioned as bugs [https://itk.org/pipermail/insight-users/2014-September/050886.html](https://itk.org/pipermail/insight-users/2014-September/050886.html) and [https://sourceforge.net/p/gdcm/bugs/328/](https://sourceforge.net/p/gdcm/bugs/328/), I saw them as such.

Regardless, thanks for your time!

**Comment by dzenanz** [comment]
Please reopen with an explanation if you feel this has not been resolved.
