### ISSUE TITLE
Include VNL in build

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#908]
On a related issue it has come up that I have [no VNL built into my ITK](https://github.com/ANTsX/ANTs/issues/612#issuecomment-485294868). I have Looked into `CMakeLists.txt`, and found utterly nothing on VNL. How can I set this to be build, or if it is an external piece of software (it appears to be listed as a third-party module), where do I get it, and how can I signal to ITK to use the system distribution?

Currently I am using this command to build:

```
cmake -C /var/tmp/portage/sci-libs/itk-5.0_rc1/work/itk-5.0_rc1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DITK_USE_SYSTEM_DCMTK=ON -DGDCM_USE_SYSTEM_OPENJPEG=ON -DITK_USE_SYSTEM_DOUBLECONVERSION=ON -DITK_USE_SYSTEM_CASTXML=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SWIG=ON -DITK_USE_SYSTEM_TIFF=ON -DITK_USE_SYSTEM_ZLIB=ON -DITK_USE_KWSTYLE=OFF -DITK_BUILD_DEFAULT_MODULES=ON -DITK_COMPUTER_MEMORY_SIZE=1 -DWRAP_ITK_JAVA=OFF -DWRAP_ITK_TCL=OFF -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -DExternalData_OBJECT_STORES=/var/tmp/portage/sci-libs/itk-5.0_rc1/work/InsightToolkit-5.0rc01/.ExternalData -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DITK_USE_REVIEW=OFF -DITK_INSTALL_LIBRARY_DIR=lib64 -DVNL_CONFIG_ENABLE_SSE2=yes -DITK_WRAP_PYTHON=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/itk-5.0_rc1/work/itk-5.0_rc1_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/itk-5.0_rc1/work/ITK-5.0rc01
```

There actually seem to be quite a few files with names including “vnl” installed by my ITK: [itk_files.txt](https://github.com/InsightSoftwareConsortium/ITK/files/3193576/itk_files.txt).

**Comment by gdevenyi** [comment]
Not a bug with ITK

Mismatched ANTs and ITK versions resulting in incompatibility seem to be the issue, see updated comments on https://github.com/ANTsX/ANTs/issues/612

**Comment by TheChymera** [comment]
I see, thank you.
