### ISSUE TITLE
ITK-4.13.2 fails to build with -ldouble-conversion: No such file or directory

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#912]
### Description

ITK-4.13.2 won't build, with `Kerror: ^[[m^[[K../../../../-ldouble-conversion: No such file or directory`

### Steps to Reproduce

```
cmake --no-warn-unused-cli -C /var/tmp/portage/sci-libs/itk-4.13.2/work/itk-4.13.2_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DITK_USE_SYSTEM_DCMTK=ON -DITK_USE_SYSTEM_DOUBLECONVERSION=ON -DITK_USE_SYSTEM_GCCXML=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SWIG=ON -DITK_USE_SYSTEM_TIFF=ON -DITK_USE_SYSTEM_ZLIB=ON -DITK_BUILD_DEFAULT_MODULES=ON -DITK_COMPUTER_MEMORY_SIZE=1 -DWRAP_ITK_JAVA=OFF -DWRAP_ITK_TCL=OFF -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -Ddouble-conversion_LIBRARIES=-ldouble-conversion -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DITK_USE_REVIEW=OFF -DITKV3_COMPATIBILITY=OFF -DVNL_CONFIG_ENABLE_SSE2=ON -DITK_WRAP_PYTHON=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/itk-4.13.2/work/itk-4.13.2_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/itk-4.13.2/work/ITK-4.13.2
```

### Expected behavior

it should compile

### Actual behavior

[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3194757/build.log)

### Reproducibility

always

### Environment

Gentoo Linux
GCC: x86_64-pc-linux-gnu-9.1.0
Python 2.7.16 and 3.6.8

**Comment by thewtex** [comment]
@dzenanz does this ring a bell?

**Comment by dzenanz** [comment]
The version of `double-conversion` which is bundled with 4.13.2 should work fine. I suppose that trying to use a system version which is newer needs the same [fix](https://github.com/InsightSoftwareConsortium/ITK/pull/366) as applied to 5.0 branch some time ago. So if we wanted to support newer system `double-conversion`s, we would have to resort to `if`s in CMake code, or update bundled version of `double-conversion` in ITKv4.13.x and drop support for older versions of system `double-conversion`. That might be fine, as 4.13.2 supports older versions.

Perhaps even better would be to try to use suggestions in this [issue](https://github.com/InsightSoftwareConsortium/ITK/issues/579).

**Comment by dzenanz** [comment]
We should probably be able to apply this [patch](https://github.com/InsightSoftwareConsortium/ITK/pull/915) to 4.13.x branch, but I think we will need to increase the minimum required version of CMake from [2.8.12](https://github.com/InsightSoftwareConsortium/ITK/blob/1724fc0f25cc6fa77bc60ef56161611333ba09f6/CMakeLists.txt#L1) to 3.0. Is that right @thewtex?

**Comment by TheChymera** [comment]
@dzenanz for what it's worth, I haven't seen a system with cmake-2* for a long time, in fact, for some distributions it's entirely deprecated.

**Comment by dzenanz** [comment]
@TheChymera can you check whether patch in #915 fixes the issue when applied to 4.13.x. The newer CMake is required, and possibly also requiring newer version [within the build system](https://github.com/InsightSoftwareConsortium/ITK/blob/d1650699dece1b220efdcbfc359abf37483b6b5c/CMakeLists.txt#L1).

**Comment by TheChymera** [comment]
@dzenanz how would I apply it to 4.13.x? Can I just test the HEAD of dzenanz:cmakeDoubleConversion ? or would that be based on 5.x and thus not equivalent?

**Comment by dzenanz** [comment]
The [file](https://github.com/InsightSoftwareConsortium/ITK/blob/d1650699dece1b220efdcbfc359abf37483b6b5c/Modules/ThirdParty/DoubleConversion/CMakeLists.txt) affected by my patch is almost exactly the same (between 4.13.x and 5.0), so the patch should be easy to apply to it. Yes, just the latest [commit](https://github.com/dzenanz/ITK/commit/a55a394ffe7d07efa02fcd7326a3b4f05558b6f9) in `dzenanz:cmakeDoubleConversion`.

**Comment by TheChymera** [comment]
@dzenanz sorry for the delay, so, with [this code](https://github.com/TheChymera/ITK/tree/c47b390ac29b639d7934d4e3892967c3a726c189) (applied your patch to the current `release-4.13` branch), I get the following [build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3224679/build.log).

Any ideas what remains to be done?

**Comment by dzenanz** [comment]
The patch did not transfer properly. [Lines 11 and 13](https://github.com/TheChymera/ITK/commit/c47b390ac29b639d7934d4e3892967c3a726c189#diff-f52843c1adf4d3c592f0f9d00a57a732R11) survived, and they should not have. Here is my patch on top of [4.13 release](https://github.com/dzenanz/ITK/tree/release-4.13) branch.

**Comment by dzenanz** [comment]
... and I made a [PR](https://github.com/InsightSoftwareConsortium/ITK/pull/969) to 4.x release branch.

**Comment by TheChymera** [comment]
@dzenanz ok, I do indeed get a different error in the [build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3224895/build.log), but it still seems related.

**Comment by dzenanz** [comment]
OK I will try building my own branch to see if I run into issues.

**Comment by dzenanz** [comment]
I got the same errors as you. After updating #969 to set CMP0045 policy to NEW, it now builds fine.

**Comment by dzenanz** [comment]
@TheChymera have you tried this yet?

**Comment by TheChymera** [comment]
@dzenanz now I have, and with https://github.com/dzenanz/ITK/archive/3fc28f16e84fe726653f660710c8991f6756b755.tar.gz I get this error log: [build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3242658/build.log).

Was that the correct archive? This is the corresponding checksum in “Github view”: https://github.com/dzenanz/ITK/tree/3fc28f16e84fe726653f660710c8991f6756b755

**Comment by dzenanz** [comment]
I think you got the correct archive. It is no longer needed to pass `-Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -Ddouble-conversion_LIBRARIES=-ldouble-conversion`.

What happens if you pass the `double-conversion_DIR` to e.g. `-Ddouble-conversion_DIR:PATH=C:/Misc/double-conversion/install/lib/cmake/double-conversion`? You can also check what was picked up into `double-conversion_DIR` by looking in `CMakeCache.txt`.

If that doesn't help, what happens if you turn [`find_package(double-conversion REQUIRED)`](https://github.com/InsightSoftwareConsortium/ITK/commit/3fc28f16e84fe726653f660710c8991f6756b755#diff-f52843c1adf4d3c592f0f9d00a57a732R10) into find_package(double-conversion **CONFIG** REQUIRED)?

**Comment by TheChymera** [comment]
> I think you got the correct archive. It is no longer needed to pass -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -Ddouble-conversion_LIBRARIES=-ldouble-conversion.

Ok, so removing those did not solve the issue

> What happens if you pass the double-conversion_DIR to e.g. -Ddouble-conversion_DIR:PATH=C:/Misc/double-conversion/install/lib/cmake/double-conversion?

That seems like a windows-specific path. I have looked at the files cmake installs on my system (
[cmakefiles.txt](https://github.com/InsightSoftwareConsortium/ITK/files/3242748/cmakefiles.txt)) and nothing of the sort seems to be available. Another package perhaps? `dev-ros/cmake_modules`?
)

> You can also check what was picked up into double-conversion_DIR by looking in CMakeCache.txt.

Uhm, I don't know what this is supposed to tell me:

```
darkhost /var/tmp/portage/sci-libs/itk-4.13.2 # ag double ./work/itk-4.13.2_build/CMakeCache.txt
648:ITKDoubleConversion_BINARY_DIR:STATIC=/var/tmp/portage/sci-libs/itk-4.13.2/work/itk-4.13.2_build/Modules/ThirdParty/DoubleConversion
651:ITKDoubleConversion_SOURCE_DIR:STATIC=/var/tmp/portage/sci-libs/itk-4.13.2/work/ITK-3fc28f16e84fe726653f660710c8991f6756b755/Modules/ThirdParty/DoubleConversion
1568://Use double precision fftw if found
1599://Use an outside build of double-conversion
1600:ITK_USE_SYSTEM_DOUBLECONVERSION:BOOL=ON
2700://Test CXX_HAS_WARNING-Wno-long-double
2701:CXX_HAS_WARNING-Wno-long-double:INTERNAL=
2732://Test C_HAS_WARNING-Wno-long-double
2733:C_HAS_WARNING-Wno-long-double:INTERNAL=
3195://ADVANCED property for variable: ITK_USE_SYSTEM_DOUBLECONVERSION
3196:ITK_USE_SYSTEM_DOUBLECONVERSION-ADVANCED:INTERNAL=1
3399://ADVANCED property for variable: Module_ITKDoubleConversion
3400:Module_ITKDoubleConversion-ADVANCED:INTERNAL=1
3401://Request building ITKDoubleConversion
3402:Module_ITKDoubleConversion:INTERNAL=OFF
4340:VXL_IEEE_128:INTERNAL=long double
4344:VXL_IEEE_64:INTERNAL=double
```

Seems like it's looking in the build dir or not at all?

> If that doesn't help, what happens if you turn find_package(double-conversion REQUIRED) into find_package(double-conversion CONFIG REQUIRED)?

Heh, ok, so it seems I had already tweaked with this and forgot about it. My build script did: 

```
sed -i \
   -e '/find_package/d' \
   Modules/ThirdParty/DoubleConversion/CMakeLists.txt || die
```
But removing that I get this new error: 
[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3242802/build.log)


 any ideas?

**Comment by dzenanz** [comment]
That is now a build error. [The offending line](https://github.com/InsightSoftwareConsortium/ITK/blob/3fc28f16e84fe726653f660710c8991f6756b755/Modules/Core/Common/src/itkNumberToString.cxx#L20) needs to include "double-conversion/double-conversion.h", as in the current [master](https://github.com/InsightSoftwareConsortium/ITK/blob/726e471ba03d5304d82f9fa7fa865f5f3a4cf122/Modules/Core/Common/src/itkNumberToString.cxx#L20). I will update the patch soon.

**Comment by dzenanz** [comment]
The updated patch is [here](https://github.com/InsightSoftwareConsortium/ITK/pull/969/commits/3ee6f1e5c9a18235ca9ab88f7bba6056c09db56d), and [this](https://github.com/InsightSoftwareConsortium/ITK/compare/3fc28f16e84fe726653f660710c8991f6756b755..3ee6f1e5c9a18235ca9ab88f7bba6056c09db56d) is the addition.

**Comment by TheChymera** [comment]
@dzenanz thanks again, 3ee6f1e5c9a18235ca9ab88f7bba6056c09db56d compiles perfectly fine, there does however, seem to be yet another issue, though now I am less sure it's related to the issue at hand: [build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3244320/build.log).

The doc part is not a problem, but the following part is.
It seems the package is building some files which my package manager does not want to install. I have also inquired with my distribution, but have not got got an answer yet. Do you perhaps know what could be wrong here and how I can fix this?

I can open a new issue if this is wholly unrelated.

**Comment by dzenanz** [comment]
This seems to be whole unrelated. It seems to come from `ITK_INSTALL_DOC_DIR` from [here](https://github.com/InsightSoftwareConsortium/ITK/blob/25d137ba411b00ae2a1fc690afe0e959901e460d/CMakeLists.txt#L96) and/or [here](https://github.com/InsightSoftwareConsortium/ITK/blob/25d137ba411b00ae2a1fc690afe0e959901e460d/CMake/ITKModuleExternal.cmake#L58). Maybe `ITK_INSTALL_PREFIX` was forgotten to be prepended to it somewhere?

**Comment by planetmarshall** [comment]
Hi, I am now seeing this issue on https://github.com/InsightSoftwareConsortium/ITK/commit/ac26e1c55fb7fca2227edfc280eef18311ed65f9:

`tkNumberToString.cxx:20:10: fatal error: 'double-conversion/double-conversion.h' file not found`

[cmake.log](https://github.com/InsightSoftwareConsortium/ITK/files/3265591/cmake.log)
[build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3265594/build.log)

**Comment by dzenanz** [comment]
I forgot to change the non-system double conversion CMake code. #1000 should fix it.
