### ISSUE TITLE
GDCM warnings

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#925]
When compiling ITK with Module_RTK, I have a bunch of warnings which are related to GDCM, see the list in the following dashboard results
[https://my.cdash.org/viewBuildError.php?type=1&buildid=1652539](https://my.cdash.org/viewBuildError.php?type=1&buildid=1652539)
[https://my.cdash.org/viewBuildError.php?type=1&buildid=1652545](https://my.cdash.org/viewBuildError.php?type=1&buildid=1652545)
[https://my.cdash.org/viewBuildError.php?type=1&buildid=1652594](https://my.cdash.org/viewBuildError.php?type=1&buildid=1652594)
Should I (1) submit a patch to fix them in ITK, (2) disable warnings in ITK for GDCM with itk_module_warnings_disable (I'm not sure what to do with the "has no symbols" warnings then) or maybe @malaterre wants to fix them both in GDCM and ITK? Thanks!

**Comment by malaterre** [comment]
@SimonRit If you write a patch I can either git cherry-pick / am in GDCM if needed. Thanks

**Comment by SimonRit** [comment]
Alright, I'll propose something. Can you explain empty files like [gdcmItem.cxx](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmItem.cxx) which generate those "has no symbols" warnings? Are they necessary for some reason or can my patch remove them?

**Comment by malaterre** [comment]
Well really the warning is annoying to me. Anyway I'd prefer you move the gdcm::Item::Clear() definition to the cxx file. This should silence the warning.
