### ISSUE TITLE
ITK v5.0.0 packages - Problem with itkHelpers.py

### ISSUE THREAD

**Issue by SimonRit** [InsightSoftwareConsortium/ITK#954]
Hi,
I guess ITK v5 is here, we are just lacking an annoucement. Great! I'm glad this is happening.
I'm busy compiling RTK python packages but when testing, I encountered an ITK problem with the new packages:
```
>>> import itk
>>> img = itk.imread('sldraw.tif')
>>> itk.MedianImageFilter(img, Radius=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/srit/miniconda3/envs/test500/lib/python2.7/site-packages/itkTemplate.py", line 432, in __call__
    import itkHelpers
ImportError: No module named itkHelpers
>>> 
```
itkHelpers.py is here but not in the site-packages folder. Creating a symbolic link solves the problem. I will learn snake case function as a temporary fix but do you know how to fix the released packages on pypi?
Thanks!
Simon

**Comment by thewtex** [comment]
@SimonRit thanks for the report.

This commit:

  https://github.com/InsightSoftwareConsortium/ITKPythonPackage/commit/c392c52f388bba84702dc1565b0dd28f8d3a9717

was not included in the ITKPythonPackage `release` branch -- my fault :disappointed: .

I added it -- we will create `5.0.0.post1` packages with the fix.

CC: @fbudin69500

**Comment by thewtex** [comment]
`5.0.0.post1` is now published.
