### ISSUE TITLE
Re-enable the `PythonGetNameOfClass` test

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#96]
This test currently crashes unreliably with

```
itkTestDriver: Process exception: Illegal instruction
```

on macOS

or

```
itkTestDriver: Process exception: Segmentation fault
```

on Linux.

**Comment by maekclena** [comment]
The error comes from `ScanlineFilterCommon::New` when trying to register its smart pointer instead executes the overriding version with `m_EnclosingFilter` still null.

It seems to me like this class should inherit `ImageToImageFilter` instead of using composition.

**Comment by thewtex** [comment]
> The error comes from `ScanlineFilterCommon::New` when trying to register its smart pointer instead executes the overriding version with `m_EnclosingFilter` still null.

Good catch! :eagle: :eye: 

> It seems to me like this class should inherit `ImageToImageFilter` instead of using composition.

Makes sense -- want to create a PR?
